import Theme from "@/constants/Theme";
import { METRONIC } from "@/features/network/components/desktop/networkDesktopHub.styles";
import { Platform, StyleSheet } from "react-native";

export { METRONIC };
export { networkDesktopHubStyles as hubStyles } from "@/features/network/components/desktop/networkDesktopHub.styles";

export const clientProfileStyles = StyleSheet.create({
  heroTagRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginTop: 8,
  },
  heroSubline: {
    fontSize: 14,
    fontWeight: "500",
    color: METRONIC.subtle,
    marginTop: 2,
  },
  heroVerifiedBadge: {
    position: "absolute",
    right: 0,
    bottom: 0,
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: METRONIC.link,
    borderWidth: 2,
    borderColor: Theme.cardWhite,
    alignItems: "center",
    justifyContent: "center",
  },
  heroMetaDot: {
    fontSize: 13,
    color: METRONIC.muted,
    fontWeight: "600",
  },
  quickActionsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    paddingHorizontal: 32,
    paddingVertical: 16,
    backgroundColor: Theme.cardWhite,
    borderBottomWidth: 1,
    borderBottomColor: METRONIC.border,
  },
  quickActionBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
  },
  quickActionBtnPrimary: {
    backgroundColor: METRONIC.text,
    borderColor: METRONIC.text,
  },
  quickActionText: {
    fontSize: 11,
    fontWeight: "700",
    color: METRONIC.text,
    letterSpacing: 0.3,
  },
  quickActionTextPrimary: {
    color: Theme.textOnPrimary,
  },
  kycScoreBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 20,
    padding: 20,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
  },
  kycScoreRing: {
    width: 72,
    height: 72,
    borderRadius: 36,
    borderWidth: 4,
    borderColor: "#50CD89",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#E8FFF3",
  },
  kycScoreValue: {
    fontSize: 18,
    fontWeight: "800",
    color: "#50CD89",
  },
  kycScoreMeta: {
    flex: 1,
    minWidth: 0,
    gap: 4,
  },
  kycScoreSub: {
    fontSize: 13,
    fontWeight: "500",
    color: METRONIC.subtle,
  },
  kycMissingText: {
    fontSize: 12,
    fontWeight: "500",
    color: "#F6C000",
    marginTop: 4,
  },
  kycCompleteText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#50CD89",
    marginTop: 4,
  },
  kycDocGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    marginTop: 12,
  },
  kycDocCard: {
    width: "31%",
    minWidth: 220,
    flexGrow: 1,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
    padding: 14,
    gap: 8,
  },
  kycDocCardHead: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  kycDocTitle: {
    flex: 1,
    fontSize: 13,
    fontWeight: "700",
    color: METRONIC.text,
  },
  kycDocStatus: {
    fontSize: 12,
    fontWeight: "500",
    color: METRONIC.subtle,
  },
  kycDocExpiry: {
    fontSize: 11,
    fontWeight: "500",
    color: METRONIC.muted,
  },
  kycUploadBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    marginTop: 4,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: METRONIC.text,
  },
  kycUploadBtnText: {
    fontSize: 11,
    fontWeight: "700",
    color: Theme.buttonDarkText,
    letterSpacing: 0.3,
  },
  dataTable: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
    overflow: "hidden",
  },
  dataTableHead: {
    flexDirection: "row",
    backgroundColor: "#F9FAFB",
    borderBottomWidth: 1,
    borderBottomColor: METRONIC.border,
    paddingVertical: 10,
    paddingHorizontal: 14,
  },
  dataTableHeadCell: {
    flex: 1,
    fontSize: 11,
    fontWeight: "700",
    color: METRONIC.muted,
    letterSpacing: 0.4,
    textTransform: "uppercase",
  },
  dataTableRow: {
    flexDirection: "row",
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderBottomWidth: 1,
    borderBottomColor: METRONIC.border,
    alignItems: "center",
  },
  dataTableCell: {
    flex: 1,
    fontSize: 13,
    fontWeight: "500",
    color: METRONIC.text,
    minWidth: 0,
  },
  emptyState: {
    padding: 32,
    alignItems: "center",
    gap: 8,
  },
  emptyStateText: {
    fontSize: 14,
    fontWeight: "500",
    color: METRONIC.subtle,
    textAlign: "center",
  },
  contractTermsBlock: {
    marginTop: 16,
    padding: 16,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: "#F9FAFB",
    gap: 10,
  },
  contractTermsTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: METRONIC.text,
  },
  contractTermsBody: {
    fontSize: 12,
    fontWeight: "400",
    color: METRONIC.subtle,
    lineHeight: 18,
  },
  backBar: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: Theme.cardWhite,
    borderBottomWidth: 1,
    borderBottomColor: METRONIC.border,
  },
  backBarText: {
    fontSize: 14,
    fontWeight: "600",
    color: METRONIC.text,
  },
  heroBackCorner: {
    position: "absolute",
    top: 16,
    left: 24,
    zIndex: 3,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: "rgba(255, 255, 255, 0.94)",
    ...Platform.select({
      web: { cursor: "pointer" as const },
    }),
  },
  heroBackText: {
    fontSize: 13,
    fontWeight: "600",
    color: METRONIC.text,
  },
  heroCompactCenter: {
    paddingTop: 16,
  },
  metricsWrap: {
    paddingHorizontal: 32,
    paddingTop: 20,
    paddingBottom: 4,
    backgroundColor: Theme.cardWhite,
  },
  statCellCompact: {
    paddingVertical: 14,
  },
  tabBtnInner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  hubChromeTitle: {
    flex: 1,
    fontSize: 16,
    fontWeight: "800",
    color: METRONIC.text,
    letterSpacing: -0.2,
  },
  hubChromePills: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    marginTop: 4,
  },
  hubChromePill: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    backgroundColor: "#F1F1F4",
  },
  hubChromePillText: {
    fontSize: 10,
    fontWeight: "700",
    color: METRONIC.subtle,
    letterSpacing: 0.3,
  },
  laneCard: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
    paddingVertical: 4,
    paddingHorizontal: 4,
    marginBottom: 0,
  },
  laneCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  laneCardRoute: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    minWidth: 0,
  },
  laneCardOrigin: {
    flex: 1,
    fontSize: 13,
    fontWeight: "700",
    color: METRONIC.text,
    minWidth: 0,
  },
  laneCardDest: {
    flex: 1,
    fontSize: 13,
    fontWeight: "700",
    color: METRONIC.text,
    minWidth: 0,
    textAlign: "right",
  },
  laneModelPill: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    backgroundColor: "#EEF6FF",
  },
  laneModelPillText: {
    fontSize: 9,
    fontWeight: "800",
    color: METRONIC.link,
    letterSpacing: 0.4,
  },
  laneCardMetaRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  laneMetaChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    backgroundColor: "#F9FAFB",
    borderWidth: 1,
    borderColor: METRONIC.border,
  },
  laneMetaChipText: {
    fontSize: 11,
    fontWeight: "600",
    color: METRONIC.text,
  },
  laneSpotChip: {
    backgroundColor: "#FFF8DD",
    borderColor: "#F6C000",
  },
  laneSpotChipText: {
    fontSize: 10,
    fontWeight: "800",
    color: "#F6C000",
    letterSpacing: 0.4,
  },
  laneCardDetails: {
    gap: 4,
    paddingTop: 4,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: METRONIC.border,
  },
  laneDetailLine: {
    fontSize: 12,
    fontWeight: "500",
    color: METRONIC.subtle,
    lineHeight: 18,
  },
  laneDetailLabel: {
    fontWeight: "700",
    color: METRONIC.muted,
  },
  laneAddressRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 6,
  },
  laneRateRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "baseline",
    gap: 10,
  },
  laneRatePrimary: {
    fontSize: 15,
    fontWeight: "800",
    color: METRONIC.text,
  },
  laneRateSecondary: {
    fontSize: 12,
    fontWeight: "600",
    color: METRONIC.link,
  },
  laneValidity: {
    fontSize: 11,
    fontWeight: "600",
    color: METRONIC.muted,
  },
  laneCardGrid: {
    gap: 8,
  },
  /** Labeled From | To | Vehicle | Rate | Valid — each field separate. */
  laneDenseRow: {
    flexDirection: "row",
    alignItems: "stretch",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
    paddingVertical: 8,
    paddingHorizontal: 4,
    flexWrap: "wrap",
  },
  laneField: {
    minWidth: 110,
    paddingHorizontal: 10,
    paddingVertical: 2,
    gap: 3,
  },
  laneFieldLabel: {
    fontSize: 9,
    fontWeight: "800",
    color: METRONIC.muted,
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  laneFieldValue: {
    fontSize: 12,
    fontWeight: "700",
    color: METRONIC.text,
    lineHeight: 16,
  },
  laneFieldDivider: {
    width: StyleSheet.hairlineWidth,
    alignSelf: "stretch",
    backgroundColor: METRONIC.border,
    marginVertical: 4,
  },
  laneDenseSpot: {
    alignSelf: "center",
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderRadius: 4,
    backgroundColor: "#FFF8DD",
    marginRight: 8,
  },
  laneDenseSpotText: {
    fontSize: 9,
    fontWeight: "800",
    color: "#F6C000",
  },
  laneTableScroll: {
    flexGrow: 1,
  },
  laneTable: {
    minWidth: 720,
    borderWidth: 1,
    borderColor: METRONIC.border,
    borderRadius: 8,
    overflow: "hidden",
    backgroundColor: Theme.cardWhite,
  },
  laneTableRow: {
    flexDirection: "row",
    alignItems: "center",
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: METRONIC.border,
    paddingVertical: 8,
    paddingHorizontal: 8,
    minHeight: 40,
  },
  laneTableHead: {
    backgroundColor: "#F5F8FA",
    paddingVertical: 7,
  },
  laneTableRowAlt: {
    backgroundColor: "#FAFBFC",
  },
  laneTableHeadCell: {
    fontSize: 9,
    fontWeight: "800",
    color: METRONIC.muted,
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  laneTableCell: {
    fontSize: 12,
    fontWeight: "600",
    color: METRONIC.text,
    paddingRight: 6,
  },
  laneTableRate: {
    fontWeight: "800",
  },
  laneColFrom: { width: 160, flexShrink: 0 },
  laneColTo: { width: 200, flexShrink: 0 },
  laneColVehicle: { width: 100, flexShrink: 0 },
  laneColRate: { width: 130, flexShrink: 0 },
  laneColValid: { width: 130, flexShrink: 0 },
  laneColActions: {
    width: 64,
    flexShrink: 0,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 4,
  },
  laneTableActions: {
    gap: 2,
  },
  laneActionBtn: {
    width: 28,
    height: 28,
    borderRadius: 6,
    alignItems: "center",
    justifyContent: "center",
  },

  // ── Hero stats strip (matches supplierStyles.heroStatsRow pattern) ──────────
  heroStatsRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 16,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: "rgba(255,255,255,0.85)",
    overflow: "hidden",
  },
  heroStatItem: {
    flex: 1,
    alignItems: "center",
    paddingVertical: 10,
    paddingHorizontal: 8,
  },
  heroStatValue: {
    fontSize: 16,
    fontWeight: "800",
    color: METRONIC.text,
    letterSpacing: -0.3,
  },
  heroStatLabel: {
    fontSize: 9,
    fontWeight: "700",
    color: METRONIC.muted,
    letterSpacing: 0.6,
    marginTop: 2,
    textTransform: "uppercase",
  },
  heroStatDivider: {
    width: StyleSheet.hairlineWidth,
    alignSelf: "stretch",
    backgroundColor: METRONIC.border,
  },

  // ── Two-column desktop body layout ─────────────────────────────────────────
  hubBodyRow: {
    flexDirection: "row",
    flex: 1,
    minHeight: 400,
  },
  hubSidebarCol: {
    width: 280,
    borderRightWidth: 1,
    borderRightColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
  },
  hubMainCol: {
    flex: 1,
    minWidth: 0,
  },

  // ── Sidebar atoms ───────────────────────────────────────────────────────────
  sidebarCard: {
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: METRONIC.border,
  },
  sidebarCardTitle: {
    fontSize: 11,
    fontWeight: "700",
    color: METRONIC.muted,
    letterSpacing: 0.8,
    marginBottom: 12,
    textTransform: "uppercase",
  },
  sidebarRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 8,
  },
  sidebarRowText: {
    fontSize: 13,
    color: METRONIC.text,
    fontWeight: "500",
    flex: 1,
    minWidth: 0,
  },
  sidebarActionBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
    marginBottom: 8,
  },
  sidebarActionBtnPrimary: {
    backgroundColor: METRONIC.text,
    borderColor: METRONIC.text,
  },
  sidebarActionBtnText: {
    fontSize: 12,
    fontWeight: "700",
    color: METRONIC.text,
    letterSpacing: 0.2,
  },
  sidebarActionBtnTextPrimary: {
    color: Theme.buttonPrimaryText,
  },
  sidebarBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
  },
  sidebarBadgeText: {
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.3,
  },
  sidebarKvRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 7,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: METRONIC.border,
    gap: 8,
  },
  sidebarKvLabel: {
    fontSize: 12,
    fontWeight: "500",
    color: METRONIC.muted,
    flexShrink: 0,
    minWidth: 72,
  },
  sidebarKvValue: {
    fontSize: 12,
    fontWeight: "600",
    color: METRONIC.text,
    textAlign: "right",
    flex: 1,
  },

  // ── Left nav rail (desktop) ─────────────────────────────────────────────────
  navRoot: {
    flexDirection: "row",
    flex: 1,
    minHeight: 480,
    backgroundColor: Theme.screenBackground,
  },
  navRail: {
    width: 264,
    borderRightWidth: 1,
    borderRightColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
  },
  navRailContent: {
    paddingVertical: 20,
    paddingHorizontal: 16,
    gap: 4,
  },
  navBackBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingVertical: 6,
    marginBottom: 8,
  },
  navBackText: {
    fontSize: 13,
    fontWeight: "700",
    color: METRONIC.subtle,
  },
  navIdentity: {
    alignItems: "center",
    gap: 8,
    paddingBottom: 16,
    marginBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: METRONIC.border,
  },
  navName: {
    fontSize: 15,
    fontWeight: "800",
    color: METRONIC.text,
    letterSpacing: -0.2,
    textAlign: "center",
  },
  navMetaText: {
    fontSize: 11,
    fontWeight: "500",
    color: METRONIC.muted,
    textAlign: "center",
  },
  navPillRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: 5,
    marginTop: 2,
  },
  navPill: {
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 5,
  },
  navPillText: {
    fontSize: 9,
    fontWeight: "800",
    letterSpacing: 0.3,
  },
  // Stat rows in the rail
  navStatsBlock: {
    gap: 2,
    paddingBottom: 12,
    marginBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: METRONIC.border,
  },
  navStatRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 6,
    paddingHorizontal: 4,
  },
  navStatLabel: {
    fontSize: 11,
    fontWeight: "600",
    color: METRONIC.muted,
    letterSpacing: 0.4,
    textTransform: "uppercase",
  },
  navStatValue: {
    fontSize: 14,
    fontWeight: "800",
    color: METRONIC.text,
  },
  // Vertical nav items
  navItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 8,
  },
  navItemActive: {
    backgroundColor: "rgba(79,70,229,0.08)",
  },
  navItemText: {
    fontSize: 13,
    fontWeight: "600",
    color: METRONIC.subtle,
    flex: 1,
  },
  navItemTextActive: {
    color: METRONIC.link,
    fontWeight: "800",
  },
  navMainCol: {
    flex: 1,
    minWidth: 0,
  },
  navMainScroll: {
    flex: 1,
  },
  navMainContent: {
    padding: 24,
  },
});
