import Theme from "@/constants/Theme";
import { METRONIC } from "@/features/network/components/desktop/networkDesktopHub.styles";
import { Platform, StyleSheet } from "react-native";

export { METRONIC };
export { networkDesktopHubStyles as hubStyles } from "@/features/network/components/desktop/networkDesktopHub.styles";

export const clientProfileStyles = StyleSheet.create({
  heroTagRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginTop: 8,
  },
  heroSubline: {
    fontSize: 14,
    fontWeight: "500",
    color: METRONIC.subtle,
    marginTop: 2,
  },
  heroVerifiedBadge: {
    position: "absolute",
    right: 0,
    bottom: 0,
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: METRONIC.link,
    borderWidth: 2,
    borderColor: Theme.cardWhite,
    alignItems: "center",
    justifyContent: "center",
  },
  heroMetaDot: {
    fontSize: 13,
    color: METRONIC.muted,
    fontWeight: "600",
  },
  quickActionsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    paddingHorizontal: 32,
    paddingVertical: 16,
    backgroundColor: Theme.cardWhite,
    borderBottomWidth: 1,
    borderBottomColor: METRONIC.border,
  },
  quickActionBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
  },
  quickActionBtnPrimary: {
    backgroundColor: METRONIC.text,
    borderColor: METRONIC.text,
  },
  quickActionText: {
    fontSize: 11,
    fontWeight: "700",
    color: METRONIC.text,
    letterSpacing: 0.3,
  },
  quickActionTextPrimary: {
    color: Theme.textOnPrimary,
  },
  kycScoreBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 20,
    padding: 20,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
  },
  kycScoreRing: {
    width: 72,
    height: 72,
    borderRadius: 36,
    borderWidth: 4,
    borderColor: "#50CD89",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#E8FFF3",
  },
  kycScoreValue: {
    fontSize: 18,
    fontWeight: "800",
    color: "#50CD89",
  },
  kycScoreMeta: {
    flex: 1,
    minWidth: 0,
    gap: 4,
  },
  kycScoreSub: {
    fontSize: 13,
    fontWeight: "500",
    color: METRONIC.subtle,
  },
  kycMissingText: {
    fontSize: 12,
    fontWeight: "500",
    color: "#F6C000",
    marginTop: 4,
  },
  kycCompleteText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#50CD89",
    marginTop: 4,
  },
  kycDocGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    marginTop: 12,
  },
  kycDocCard: {
    width: "31%",
    minWidth: 220,
    flexGrow: 1,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
    padding: 14,
    gap: 8,
  },
  kycDocCardHead: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  kycDocTitle: {
    flex: 1,
    fontSize: 13,
    fontWeight: "700",
    color: METRONIC.text,
  },
  kycDocStatus: {
    fontSize: 12,
    fontWeight: "500",
    color: METRONIC.subtle,
  },
  kycDocExpiry: {
    fontSize: 11,
    fontWeight: "500",
    color: METRONIC.muted,
  },
  kycUploadBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    marginTop: 4,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: METRONIC.text,
  },
  kycUploadBtnText: {
    fontSize: 11,
    fontWeight: "700",
    color: Theme.textOnPrimary,
    letterSpacing: 0.3,
  },
  dataTable: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
    overflow: "hidden",
  },
  dataTableHead: {
    flexDirection: "row",
    backgroundColor: "#F9FAFB",
    borderBottomWidth: 1,
    borderBottomColor: METRONIC.border,
    paddingVertical: 10,
    paddingHorizontal: 14,
  },
  dataTableHeadCell: {
    flex: 1,
    fontSize: 11,
    fontWeight: "700",
    color: METRONIC.muted,
    letterSpacing: 0.4,
    textTransform: "uppercase",
  },
  dataTableRow: {
    flexDirection: "row",
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderBottomWidth: 1,
    borderBottomColor: METRONIC.border,
    alignItems: "center",
  },
  dataTableCell: {
    flex: 1,
    fontSize: 13,
    fontWeight: "500",
    color: METRONIC.text,
    minWidth: 0,
  },
  emptyState: {
    padding: 32,
    alignItems: "center",
    gap: 8,
  },
  emptyStateText: {
    fontSize: 14,
    fontWeight: "500",
    color: METRONIC.subtle,
    textAlign: "center",
  },
  contractTermsBlock: {
    marginTop: 16,
    padding: 16,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: "#F9FAFB",
    gap: 10,
  },
  contractTermsTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: METRONIC.text,
  },
  contractTermsBody: {
    fontSize: 12,
    fontWeight: "400",
    color: METRONIC.subtle,
    lineHeight: 18,
  },
  backBar: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: Theme.cardWhite,
    borderBottomWidth: 1,
    borderBottomColor: METRONIC.border,
  },
  backBarText: {
    fontSize: 14,
    fontWeight: "600",
    color: METRONIC.text,
  },
  heroBackCorner: {
    position: "absolute",
    top: 16,
    left: 24,
    zIndex: 3,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: "rgba(255, 255, 255, 0.94)",
    ...Platform.select({
      web: { cursor: "pointer" as const },
    }),
  },
  heroBackText: {
    fontSize: 13,
    fontWeight: "600",
    color: METRONIC.text,
  },
  heroCompactCenter: {
    paddingTop: 16,
  },
  metricsWrap: {
    paddingHorizontal: 32,
    paddingTop: 20,
    paddingBottom: 4,
    backgroundColor: Theme.cardWhite,
  },
  statCellCompact: {
    paddingVertical: 14,
  },
  tabBtnInner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
});
