import { FinanceTxnTypography } from "@/constants/FinanceTxnTypography";
import {
  NETWORK_HUB_RADIUS,
  networkHubListCardChromeStyles,
} from "@/features/network/components/networkHubListCardChrome";
import Theme from "@/constants/Theme";
import { StyleSheet } from "react-native";

/** List row chrome aligned with NetworkPartyProfileCard list + FinanceTxnTypography. */
export const hubListCardStyles = StyleSheet.create({
  card: networkHubListCardChromeStyles.card,
  cardCompact: networkHubListCardChromeStyles.cardCompact,
  row: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    minWidth: 0,
  },
  rowCompact: {
    flexDirection: "column",
    alignItems: "stretch",
    gap: 10,
  },
  left: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    minWidth: 0,
  },
  leftCompact: {
    gap: 10,
  },
  avatarCol: {
    width: 48,
    height: 48,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    position: "relative",
  },
  avatarWrap: networkHubListCardChromeStyles.avatarWrap,
  onlineDot: {
    position: "absolute",
    right: 1,
    bottom: 1,
    width: 9,
    height: 9,
    borderRadius: 5,
    backgroundColor: Theme.networkHubListCardOnlineDot,
    borderWidth: 2,
    borderColor: Theme.networkHubListCardBackground,
    zIndex: 2,
  },
  identity: {
    flex: 1,
    minWidth: 0,
    gap: 3,
    justifyContent: "center",
    paddingLeft: 2,
  },
  partyName: {
    ...FinanceTxnTypography.partyTitle,
    lineHeight: 16,
    fontWeight: "700",
    color: Theme.textPrimaryDark,
    letterSpacing: -0.2,
  },
  partyNameCompact: {
    fontSize: 11,
    lineHeight: 14,
  },
  partyNameMobileGrid: {
    fontSize: 9,
    lineHeight: 11,
    fontWeight: "700",
    fontStyle: "italic",
    color: Theme.textPrimaryDark,
    letterSpacing: 0,
    textTransform: "uppercase",
  },
  rowMobileGrid: {
    flexDirection: "column",
    alignItems: "stretch",
    gap: 8,
  },
  leftMobileGrid: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    width: "100%",
  },
  avatarColMobileGrid: {
    width: 40,
    height: 40,
  },
  identityMobileGrid: {
    flex: 1,
    minWidth: 0,
    gap: 2,
    paddingLeft: 0,
    justifyContent: "flex-start",
  },
  badgesRowMobileGrid: {
    flexWrap: "wrap",
    gap: 3,
    marginTop: 0,
  },
  badgeTextMobileGrid: {
    fontSize: 6,
    letterSpacing: 0.2,
  },
  phoneTextMobileGrid: {
    fontSize: 8,
    lineHeight: 10,
  },
  rightMobileGrid: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
    gap: 6,
  },
  actionColMobileGrid: {
    alignItems: "flex-end",
    justifyContent: "center",
    minWidth: 0,
    flexShrink: 0,
    gap: 4,
  },
  connectedBtnMobileGrid: {
    paddingHorizontal: 8,
    paddingVertical: 5,
    minWidth: 0,
    minHeight: 28,
    gap: 4,
  },
  connectedBtnTextMobileGrid: {
    fontSize: 7,
    letterSpacing: 0.4,
  },
  partyNameNativeList: {
    fontSize: 11,
    lineHeight: 14,
    fontWeight: "500",
    fontStyle: "normal",
    color: Theme.textPrimaryDark,
    letterSpacing: 0.15,
    textTransform: "uppercase",
  },
  nativeFooterMetrics: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flexShrink: 0,
  },
  nativeActionWrap: {
    flexShrink: 0,
    alignItems: "flex-end",
  },
  roleChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    flexShrink: 0,
    maxWidth: "52%",
  },
  roleChipText: {
    ...FinanceTxnTypography.routeWhy,
    lineHeight: 11,
    flexShrink: 1,
  },
  badgesRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 6,
    marginTop: 2,
  },
  badge: {
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: NETWORK_HUB_RADIUS.badge,
    overflow: "hidden",
  },
  badgeText: {
    fontSize: 7,
    fontWeight: "700",
    letterSpacing: 0.3,
  },
  phoneRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    minWidth: 0,
    marginTop: 1,
  },
  phoneText: {
    ...FinanceTxnTypography.routeWhy,
    flexShrink: 1,
    lineHeight: 11,
  },
  right: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flexShrink: 0,
  },
  rightCompact: {
    justifyContent: "space-between",
    width: "100%",
  },
  metricsRow: networkHubListCardChromeStyles.metricsRow,
  metricsRowCompact: networkHubListCardChromeStyles.metricsRowCompact,
  mutualsSlot: {
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 2,
    marginRight: 2,
    maxWidth: 56,
    overflow: "hidden",
  },
  actionMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 5,
    width: "100%",
    flexShrink: 0,
  },
  actionCol: {
    alignItems: "flex-end",
    justifyContent: "center",
    gap: 6,
    minWidth: 100,
  },
  connectedBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: NETWORK_HUB_RADIUS.control,
    backgroundColor: Theme.networkHubListCardActionBg,
    borderWidth: 1,
    borderColor: Theme.networkHubListCardBorder,
    minWidth: 100,
    minHeight: 36,
    overflow: "hidden",
  },
  connectedDotOuter: {
    width: 8,
    height: 8,
    borderRadius: 4,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(16, 185, 129, 0.25)",
  },
  connectedDotInner: {
    width: 5,
    height: 5,
    borderRadius: 2.5,
    backgroundColor: Theme.positive,
  },
  connectedBtnText: {
    ...FinanceTxnTypography.chipLabel,
    color: Theme.textSecondary,
    letterSpacing: 0.6,
  },
});
