import { FinanceTxnTypography } from "@/constants/FinanceTxnTypography";
import Theme from "@/constants/Theme";
import {
  NETWORK_PROFILE_CARD_RADIUS,
  NETWORK_PROFILE_GRID_MUTUAL_SLOT_HEIGHT,
} from "@/features/network/constants/networkProfileCardLayout";
import { hubCardSectionDivider } from "@/features/network/components/networkHubListCardChrome";
import { StyleSheet } from "react-native";

export const NETWORK_PARTY_MUTUAL_FACE_GRID = 32;
export const NETWORK_PARTY_MUTUAL_FACE_LIST = 34;
export const NETWORK_PROFILE_CARD_LIST_HEIGHT = 88;
export const NETWORK_PROFILE_CARD_LIST_HEIGHT_MOBILE = 76;

export const networkPartyProfileCardStyles = StyleSheet.create({
  cardGrid: {
    width: "100%",
    height: "100%",
    flex: 1,
    minHeight: 0,
    backgroundColor: Theme.networkCardBackground,
    borderRadius: NETWORK_PROFILE_CARD_RADIUS,
    borderWidth: 1,
    borderColor: Theme.networkCardBorder,
    paddingHorizontal: 8,
    paddingTop: 8,
    paddingBottom: 8,
    overflow: "hidden",
    justifyContent: "space-between",
  },
  cardGridPartyDesktop: {
    paddingLeft: 16,
    paddingRight: 12,
    paddingTop: 10,
  },
  cardGridRecommended: {
    borderColor: Theme.aggregatePillBorder,
  },
  cardList: {
    width: "100%",
    minHeight: NETWORK_PROFILE_CARD_LIST_HEIGHT,
    backgroundColor: Theme.networkCardBackground,
    borderRadius: NETWORK_PROFILE_CARD_RADIUS,
    borderWidth: 1,
    borderColor: Theme.networkCardBorder,
    paddingHorizontal: 14,
    paddingVertical: 10,
    position: "relative",
    overflow: "hidden",
  },
  cardListMobile: {
    minHeight: NETWORK_PROFILE_CARD_LIST_HEIGHT_MOBILE,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  cardListDesktop: {
    minHeight: 92,
    paddingLeft: 18,
    paddingRight: 14,
    paddingVertical: 12,
  },
  listSingleRow: {
    flexDirection: "row",
    alignItems: "center",
    width: "100%",
    gap: 10,
    minHeight: 68,
  },
  listSingleRowMobile: {
    gap: 8,
    minHeight: NETWORK_PROFILE_CARD_LIST_HEIGHT_MOBILE - 16,
  },
  listSingleRowDesktop: {
    gap: 14,
    minHeight: 72,
    alignItems: "center",
  },
  listMidGroupMobile: {
    gap: 4,
  },
  listStatBoxes: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    flexShrink: 0,
  },
  listMutualBox: {
    minWidth: 52,
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 10,
    backgroundColor: Theme.surfaceGray,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
  },
  listMutualBoxMobile: {
    minWidth: 46,
    paddingHorizontal: 6,
    paddingVertical: 5,
  },
  listMutualBoxValue: {
    ...FinanceTxnTypography.amount,
    color: Theme.primary,
    lineHeight: 15,
    textAlign: "center",
  },
  listMutualBoxValueMobile: {
    fontSize: 11,
    lineHeight: 14,
  },
  listMutualBoxLabel: {
    ...FinanceTxnTypography.fieldLabel,
    textAlign: "center",
  },
  listMutualBoxLabelMobile: {
    fontSize: 8,
  },
  listMetricCard: {
    minWidth: 54,
    paddingVertical: 6,
    paddingHorizontal: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    backgroundColor: Theme.networkCardBackground,
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
  },
  listMetricCardMobile: {
    minWidth: 48,
    paddingVertical: 5,
    paddingHorizontal: 6,
    gap: 4,
  },
  listMetricCardRating: {
    minWidth: 58,
  },
  metricIconRing: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
  },
  metricIconRingMobile: {
    width: 28,
    height: 28,
    borderRadius: 14,
  },
  metricIconRingTrips: {
    backgroundColor: Theme.aggregatePillBg,
  },
  metricIconRingRating: {
    backgroundColor: "rgba(245, 158, 11, 0.12)",
  },
  metricValuePill: {
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    backgroundColor: Theme.screenBackground,
    minWidth: 30,
    alignItems: "center",
    justifyContent: "center",
  },
  metricValuePillMobile: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    minWidth: 26,
  },
  metricValuePillText: {
    ...FinanceTxnTypography.amount,
    color: Theme.textPrimaryDark,
    fontSize: 11,
    lineHeight: 14,
    fontWeight: "600",
    textAlign: "center",
  },
  metricValuePillTextMobile: {
    fontSize: 10,
    lineHeight: 13,
  },
  metricStarsRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
  },
  statColMetric: {
    gap: 5,
    paddingVertical: 2,
  },
  listMidGroup: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flexShrink: 0,
  },
  listMutualsWrap: {
    flexShrink: 0,
    alignItems: "flex-start",
    justifyContent: "center",
    minWidth: 80,
    paddingHorizontal: 4,
    alignSelf: "center",
  },
  listMutualsWrapMobile: {
    minWidth: 68,
    paddingHorizontal: 2,
  },
  statColMutualFacepile: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    minWidth: 0,
    paddingHorizontal: 2,
    gap: 4,
  },
  listActionSlot: {
    flexShrink: 0,
    marginLeft: "auto",
    alignItems: "flex-end",
    justifyContent: "center",
    gap: 6,
    minWidth: 0,
    maxWidth: 148,
  },
  listActionSlotMobile: {
    marginLeft: 0,
    maxWidth: 118,
    gap: 5,
  },
  listActionMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 6,
    width: "100%",
    flexShrink: 0,
  },
  listAvatarColMobile: {
    width: 40,
  },
  listAvatarWrapMobile: {
    width: 40,
    height: 40,
    borderRadius: 20,
  },
  listAvatarWrapDesktop: {
    width: 52,
    height: 52,
    borderRadius: 26,
  },
  listNameMobile: {
    ...FinanceTxnTypography.partyTitle,
    flexShrink: 1,
    minWidth: 0,
    lineHeight: 15,
  },
  listMetaTextMobile: {
    ...FinanceTxnTypography.routeWhy,
    lineHeight: 11,
  },
  cardTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
    gap: 4,
    minHeight: 20,
    flexShrink: 0,
  },
  metricsLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    flex: 1,
    minWidth: 0,
  },
  tripPill: {
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 8,
    backgroundColor: Theme.surfaceGray,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    minWidth: 24,
    alignItems: "center",
  },
  tripPillText: {
    fontSize: 9,
    fontWeight: "700",
    color: Theme.textSecondary,
  },
  ratingPill: {
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 8,
    backgroundColor: Theme.surfaceGray,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    minWidth: 26,
    alignItems: "center",
  },
  ratingPillText: {
    fontSize: 9,
    fontWeight: "700",
    color: Theme.textSecondary,
  },
  ratingPillTextEmpty: { color: Theme.textMuted },
  starsRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 1,
    flexShrink: 0,
  },
  fullProfileBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 0,
    paddingHorizontal: 5,
    paddingVertical: 3,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    backgroundColor: Theme.screenBackground,
    flexShrink: 0,
    maxWidth: "44%",
  },
  fullProfileText: {
    fontSize: 6,
    fontWeight: "700",
    letterSpacing: 0.4,
    color: Theme.textMuted,
    textTransform: "uppercase",
    flexShrink: 1,
  },
  gridBody: {
    flex: 1,
    minHeight: 0,
    width: "100%",
    justifyContent: "space-between",
    gap: 6,
    paddingVertical: 2,
  },
  gridIdentityRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    width: "100%",
    flex: 1,
    minHeight: 0,
    gap: 8,
  },
  gridAvatarCol: {
    flexShrink: 0,
    width: 44,
  },
  gridAvatarWrap: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: Theme.surfaceGray,
    alignItems: "center",
    justifyContent: "center",
    overflow: "visible",
  },
  gridInfo: {
    flex: 1,
    minWidth: 0,
    gap: 3,
    justifyContent: "center",
    paddingLeft: 2,
  },
  gridIdentityRowDesktop: {
    alignItems: "center",
    gap: 12,
    paddingRight: 2,
  },
  gridAvatarColDesktop: {
    width: 56,
    alignItems: "center",
    justifyContent: "center",
  },
  gridAvatarWrapDesktop: {
    width: 56,
    height: 56,
    borderRadius: 28,
  },
  gridInfoDesktop: {
    gap: 6,
    justifyContent: "space-between",
    paddingVertical: 1,
  },
  gridNameRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 6,
    minWidth: 0,
    width: "100%",
  },
  gridHeaderTrailing: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    flexShrink: 0,
    maxWidth: "56%",
  },
  gridPartyTypeTrailing: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    flexShrink: 1,
    minWidth: 0,
  },
  gridPartnerMetaPhoneRow: {
    flexDirection: "row",
    alignItems: "center",
    width: "100%",
    minWidth: 0,
    gap: 4,
  },
  gridName: {
    ...FinanceTxnTypography.partyTitle,
    flex: 1,
    minWidth: 0,
    fontSize: 12,
    lineHeight: 15,
    textAlign: "left",
  },
  gridNameDesktop: {
    fontSize: 15,
    lineHeight: 19,
    letterSpacing: 0.35,
  },
  gridMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    width: "100%",
    minWidth: 0,
  },
  gridMetaText: {
    ...FinanceTxnTypography.routeWhy,
    flex: 1,
    minWidth: 0,
    lineHeight: 11,
  },
  gridMetaTextDesktop: {
    fontSize: 12,
    fontWeight: "400",
    lineHeight: 16,
    letterSpacing: 0.12,
  },
  gridPartnerMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    width: "100%",
    minWidth: 0,
    gap: 6,
  },
  gridPartnerMetaRowDesktop: {
    gap: 10,
  },
  gridPartnerMetaSegment: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    flexShrink: 1,
    minWidth: 0,
    maxWidth: "48%",
  },
  gridPartnerMetaSegmentPhone: {
    flex: 1,
    maxWidth: "52%",
  },
  gridPartnerMetaSegmentDesktop: {
    flex: 1,
    gap: 5,
  },
  gridPartnerMetaDivider: {
    width: StyleSheet.hairlineWidth,
    alignSelf: "stretch",
    minHeight: 12,
    backgroundColor: Theme.borderLight,
    flexShrink: 0,
  },
  gridPartnerMetaDividerDesktop: {
    minHeight: 16,
  },
  gridRolePillsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 4,
    width: "100%",
  },
  gridRolePillsRowDesktop: {
    gap: 5,
    marginTop: 1,
  },
  rolePillGridDesktop: {
    paddingHorizontal: 7,
    paddingVertical: 3,
    borderRadius: 7,
  },
  rolePillTextGridDesktop: {
    fontSize: 8,
    letterSpacing: 0.35,
  },
  avatarWrap: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: Theme.surfaceGray,
    alignItems: "center",
    justifyContent: "center",
    overflow: "visible",
  },
  onlineDot: {
    position: "absolute",
    right: 0,
    bottom: 0,
    width: 10,
    height: 10,
    borderRadius: 5,
    borderWidth: 2,
    borderColor: Theme.networkCardBackground,
    backgroundColor: Theme.positive,
  },
  nameRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 3,
    width: "100%",
    paddingHorizontal: 2,
  },
  nameWrap: {
    flex: 1,
    minWidth: 0,
    maxWidth: "100%",
    alignItems: "center",
  },
  name: {
    ...FinanceTxnTypography.partyTitle,
    fontSize: 10,
    lineHeight: 13,
    textAlign: "center",
  },
  metaRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    width: "100%",
    paddingHorizontal: 2,
    minHeight: 13,
  },
  metaText: {
    flexShrink: 1,
    minWidth: 0,
    fontSize: 8,
    fontWeight: "500",
    color: Theme.textSecondary,
    textAlign: "center",
  },
  metaTextMuted: {
    fontStyle: "italic",
    color: Theme.textMuted,
  },
  rolePillsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: 4,
    width: "100%",
    paddingHorizontal: 2,
  },
  rolePill: {
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
  },
  rolePillText: {
    fontSize: 7,
    fontWeight: "700",
    letterSpacing: 0.3,
  },
  teamSection: {
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    paddingTop: 2,
    gap: 2,
  },
  gridMutualSlot: {
    width: "100%",
    height: NETWORK_PROFILE_GRID_MUTUAL_SLOT_HEIGHT,
    minHeight: NETWORK_PROFILE_GRID_MUTUAL_SLOT_HEIGHT,
    maxHeight: NETWORK_PROFILE_GRID_MUTUAL_SLOT_HEIGHT,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    overflow: "hidden",
  },
  sectionLabel: {
    fontSize: 7,
    fontWeight: "600",
    letterSpacing: 0.5,
    color: Theme.textMuted,
    textTransform: "uppercase",
    textAlign: "center",
  },
  statsRow: {
    flexDirection: "row",
    alignItems: "stretch",
    width: "100%",
    minHeight: 36,
    flexShrink: 0,
    marginTop: 2,
  },
  statCol: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    minWidth: 0,
    paddingHorizontal: 2,
    gap: 3,
  },
  statColPressable: {
    flex: 1,
    minWidth: 0,
  },
  statDivider: {
    width: StyleSheet.hairlineWidth,
    backgroundColor: Theme.borderLight,
    marginVertical: 4,
  },
  statValue: {
    ...FinanceTxnTypography.amount,
    color: Theme.textPrimaryDark,
    lineHeight: 15,
    textAlign: "center",
  },
  statLabel: {
    marginTop: 2,
    ...FinanceTxnTypography.fieldLabel,
    textAlign: "center",
  },
  footer: {
    width: "100%",
    flexShrink: 0,
    paddingTop: 0,
  },
  footerDivider: {
    ...hubCardSectionDivider,
    marginTop: 10,
    marginBottom: 8,
  },
  actionBtn: {
    borderRadius: 18,
    paddingVertical: 7,
    minHeight: 32,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 5,
  },
  actionBtnFlex: { flex: 1, minWidth: 0 },
  actionBtnOutline: {
    backgroundColor: Theme.screenBackground,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    width: "100%",
  },
  actionTextPrimary: {
    fontSize: 12,
    fontWeight: "600",
    color: Theme.primary,
    flexShrink: 1,
  },
  actionTextMuted: {
    fontSize: 12,
    fontWeight: "600",
    color: Theme.textSecondary,
    flexShrink: 1,
  },
  connectFooter: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    width: "100%",
  },
  iconBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Theme.screenBackground,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    flexShrink: 0,
  },
  listAvatarCol: {
    width: 48,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  listAvatarColDesktop: {
    width: 56,
    alignSelf: "stretch",
    justifyContent: "center",
  },
  listAvatarWrap: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: Theme.surfaceGray,
    alignItems: "center",
    justifyContent: "center",
    overflow: "visible",
  },
  listInfo: {
    flex: 1,
    minWidth: 0,
    gap: 3,
    justifyContent: "center",
    paddingLeft: 4,
  },
  listHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
    gap: 8,
    minWidth: 0,
  },
  listHeaderTrailing: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    flexShrink: 0,
    maxWidth: "58%",
  },
  listPartyTypeTrailing: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    flexShrink: 1,
    minWidth: 0,
  },
  listNameRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    minWidth: 0,
  },
  listName: {
    ...FinanceTxnTypography.partyTitle,
    flex: 1,
    flexShrink: 1,
    minWidth: 0,
    lineHeight: 15,
  },
  listRolePillsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 4,
    marginTop: 1,
  },
  listMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    minWidth: 0,
  },
  listMetaText: {
    ...FinanceTxnTypography.routeWhy,
    flex: 1,
    minWidth: 0,
    lineHeight: 11,
  },
  listPartnerMetaPhoneRow: {
    flexDirection: "row",
    alignItems: "center",
    width: "100%",
    minWidth: 0,
    gap: 4,
  },
  listPartnerMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    width: "100%",
    minWidth: 0,
    gap: 8,
  },
  listPartnerMetaRowMobile: {
    gap: 6,
  },
  listPartnerMetaSegment: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    flexShrink: 1,
    minWidth: 0,
    maxWidth: "46%",
  },
  listPartnerMetaSegmentPhone: {
    flex: 1,
    maxWidth: "54%",
  },
  listPartnerMetaDivider: {
    width: StyleSheet.hairlineWidth,
    alignSelf: "stretch",
    minHeight: 14,
    backgroundColor: Theme.borderLight,
    flexShrink: 0,
  },
  listPartnerMetaText: {
    ...FinanceTxnTypography.routeWhy,
    flexShrink: 1,
    minWidth: 0,
    lineHeight: 11,
  },
  listPartnerMetaTextMobile: {
    ...FinanceTxnTypography.routeWhy,
    lineHeight: 11,
  },
  listMutuals: {
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
  },
  listActionBtn: {
    borderRadius: 20,
    paddingVertical: 8,
    paddingHorizontal: 12,
    minHeight: 36,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 5,
    backgroundColor: Theme.screenBackground,
    borderWidth: 1,
    borderColor: Theme.borderLight,
  },
  listActionBtnFlex: {
    flex: 1,
    minWidth: 0,
  },
  listConnectRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 6,
    flexShrink: 0,
    width: "100%",
  },
  listActionBtnFullWidth: {
    alignSelf: "stretch",
    width: "100%",
  },
});
