/**
 * Invitation-hub visual language for network / public profile heroes.
 * Mirrors InvitationsView hub card cover + centered identity body.
 */
import Theme from "@/constants/Theme";
import { StyleSheet } from "react-native";

export const networkProfileInviteStyles = StyleSheet.create({
  card: {
    width: "100%",
    backgroundColor: Theme.screenBackground,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    overflow: "hidden",
    shadowColor: Theme.shadow,
    shadowOpacity: 0.055,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 7 },
    elevation: 2,
  },
  inviteCover: {
    height: 82,
    overflow: "hidden",
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Theme.borderLight,
    backgroundColor: Theme.surfaceGray,
  },
  coverOrbLarge: {
    position: "absolute",
    width: 132,
    height: 70,
    borderRadius: 66,
    top: -20,
    left: -28,
    backgroundColor: Theme.borderLight,
    transform: [{ rotate: "-10deg" }],
  },
  coverOrbSmall: {
    position: "absolute",
    width: 92,
    height: 54,
    borderRadius: 46,
    right: -22,
    bottom: -16,
    backgroundColor: Theme.surface,
    transform: [{ rotate: "14deg" }],
  },
  coverPlane: {
    position: "absolute",
    width: 112,
    height: 52,
    borderRadius: 14,
    right: 28,
    top: 10,
    backgroundColor: Theme.screenBackground,
    opacity: 0.55,
    transform: [{ rotate: "-8deg" }],
  },
  coverRatingNode: {
    position: "absolute",
    right: 8,
    bottom: 8,
    minHeight: 23,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 8,
    borderRadius: 11,
    backgroundColor: "rgba(255,255,255,0.86)",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: Theme.borderLight,
  },
  coverRatingNodeEmpty: {
    minHeight: 18,
    paddingHorizontal: 5,
    borderRadius: 9,
    backgroundColor: "rgba(255,255,255,0.72)",
  },
  coverRatingText: {
    fontSize: 10,
    fontWeight: "700",
    fontStyle: "italic",
    color: Theme.textPrimaryDark,
  },
  coverRatingTextEmpty: {
    fontSize: 7,
    fontWeight: "700",
    color: Theme.textMutedDemo,
    letterSpacing: -0.1,
  },
  cardHeader: {
    position: "absolute",
    top: 8,
    left: 8,
    right: 8,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "wrap",
    gap: 6,
  },
  roleBadge: {
    minHeight: 21,
    justifyContent: "center",
    paddingHorizontal: 7,
    borderRadius: 10,
    backgroundColor: Theme.screenBackground,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: Theme.borderLight,
  },
  roleBadgeText: {
    fontSize: 8,
    fontWeight: "600",
    fontStyle: "italic",
    color: Theme.textPrimaryDark,
    letterSpacing: 0.2,
  },
  statusPill: {
    minHeight: 21,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 7,
    borderRadius: 10,
    backgroundColor: Theme.screenBackground,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: Theme.borderLight,
  },
  statusPillLive: {
    backgroundColor: Theme.warningMuted,
    borderColor: Theme.borderLight,
  },
  statusPillText: {
    fontSize: 8,
    fontWeight: "600",
    fontStyle: "italic",
    color: Theme.textPrimaryDark,
    letterSpacing: 0.2,
  },
  inviteBody: {
    flexDirection: "column",
    alignItems: "center",
    minHeight: 132,
    paddingHorizontal: 12,
    paddingTop: 0,
    paddingBottom: 12,
    gap: 6,
  },
  avatarLift: {
    marginTop: -40,
    alignItems: "center",
    justifyContent: "center",
  },
  innerText: {
    width: "100%",
    minWidth: 0,
    alignItems: "center",
    gap: 4,
  },
  name: {
    fontSize: 14,
    fontWeight: "600",
    fontStyle: "italic",
    color: Theme.textPrimaryDark,
    letterSpacing: -0.2,
    textAlign: "center",
    lineHeight: 18,
  },
  subtitle: {
    fontSize: 9,
    fontWeight: "400",
    fontStyle: "italic",
    color: Theme.textMutedDemo,
    lineHeight: 12,
    textAlign: "center",
    maxWidth: "100%",
  },
  metaRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: 6,
    marginTop: 4,
  },
  metaChip: {
    minHeight: 22,
    justifyContent: "center",
    paddingHorizontal: 8,
    borderRadius: 11,
    backgroundColor: Theme.screenBackground,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: Theme.borderLight,
  },
  metaChipText: {
    fontSize: 8,
    fontWeight: "600",
    fontStyle: "italic",
    color: Theme.textSecondary,
  },
  innerBand: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Theme.surfaceForm,
    borderRadius: 14,
    paddingVertical: 10,
    paddingHorizontal: 10,
    gap: 8,
    marginHorizontal: 10,
    marginBottom: 10,
  },
  innerBandPhone: {
    marginTop: -4,
    marginBottom: 6,
  },
  phoneBandIcon: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: Theme.screenBackground,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: Theme.borderLight,
  },
  phoneBandCol: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  phoneBandLabel: {
    fontSize: 8,
    fontWeight: "600",
    fontStyle: "italic",
    color: Theme.textMutedDemo,
    letterSpacing: 0.3,
  },
  phoneBandValue: {
    fontSize: 12,
    fontWeight: "600",
    color: Theme.textPrimaryDark,
    letterSpacing: -0.1,
  },
  statsBand: {
    flexDirection: "row",
    alignItems: "stretch",
    marginHorizontal: 10,
    marginTop: 2,
    marginBottom: 12,
    borderRadius: 14,
    backgroundColor: Theme.surfaceForm,
    overflow: "hidden",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: Theme.borderLight,
  },
  statCell: {
    flex: 1,
    minWidth: 0,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 10,
    paddingHorizontal: 4,
    gap: 3,
  },
  statCellDivider: {
    width: StyleSheet.hairlineWidth,
    backgroundColor: Theme.borderLight,
    alignSelf: "stretch",
    marginVertical: 8,
  },
  statLabel: {
    fontSize: 7,
    fontWeight: "600",
    fontStyle: "italic",
    color: Theme.textMutedDemo,
    letterSpacing: 0.35,
    textAlign: "center",
  },
  statValue: {
    fontSize: 11,
    fontWeight: "700",
    fontStyle: "italic",
    color: Theme.textPrimaryDark,
    textAlign: "center",
  },
  statValueLive: {
    color: Theme.positive,
  },
  verifiedDot: {
    position: "absolute",
    right: 2,
    bottom: 2,
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: Theme.positive,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: Theme.screenBackground,
  },
});
