import Theme from "@/constants/Theme";
import { NETWORK_PROFILE_CARD_RADIUS } from "@/features/network/constants/networkProfileCardLayout";
import { StyleSheet } from "react-native";

export const NETWORK_DISCOVER_MUTUAL_FACE_SIZE = 24;

/** Compact discover tile — fits NETWORK_PROFILE_CARD_HEIGHT (204). */
export const networkDiscoverDossierStyles = StyleSheet.create({
  card: {
    width: "100%",
    height: "100%",
    backgroundColor: Theme.screenBackground,
    borderRadius: NETWORK_PROFILE_CARD_RADIUS,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    paddingHorizontal: 8,
    paddingTop: 8,
    paddingBottom: 8,
    shadowColor: Theme.shadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 2,
    overflow: "hidden",
  },
  cardRecommended: {
    borderColor: Theme.aggregatePillBorder,
  },
  cardTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
    gap: 4,
    minHeight: 20,
    flexShrink: 0,
  },
  metricsLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    flex: 1,
    minWidth: 0,
  },
  tripPill: {
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 8,
    backgroundColor: Theme.surfaceGray,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    minWidth: 24,
    alignItems: "center",
  },
  tripPillText: {
    fontSize: 9,
    fontWeight: "700",
    color: Theme.textSecondary,
  },
  ratingPill: {
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 8,
    backgroundColor: Theme.surfaceGray,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    minWidth: 26,
    alignItems: "center",
  },
  ratingPillText: {
    fontSize: 9,
    fontWeight: "700",
    color: Theme.textSecondary,
  },
  ratingPillTextEmpty: {
    color: Theme.textMuted,
  },
  starsRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 1,
    flexShrink: 0,
  },
  fullProfileBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 0,
    paddingHorizontal: 5,
    paddingVertical: 3,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    backgroundColor: Theme.screenBackground,
    flexShrink: 0,
    maxWidth: "44%",
  },
  fullProfileText: {
    fontSize: 6,
    fontWeight: "700",
    letterSpacing: 0.4,
    color: Theme.textMuted,
    textTransform: "uppercase",
    flexShrink: 1,
  },
  main: {
    flex: 1,
    minHeight: 0,
    width: "100%",
    justifyContent: "space-between",
    paddingVertical: 2,
  },
  profileTap: {
    width: "100%",
    alignItems: "center",
    flexShrink: 0,
    gap: 3,
  },
  avatarWrap: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: Theme.surfaceGray,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  nameWrap: {
    width: "100%",
    minHeight: 28,
    justifyContent: "center",
    paddingHorizontal: 2,
  },
  name: {
    fontSize: 10,
    fontWeight: "700",
    color: Theme.textPrimaryDark,
    textAlign: "center",
    width: "100%",
    lineHeight: 13,
  },
  locationRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 3,
    width: "100%",
    paddingHorizontal: 2,
    minHeight: 13,
    maxHeight: 14,
  },
  locationText: {
    flex: 1,
    minWidth: 0,
    fontSize: 8,
    fontWeight: "500",
    color: Theme.textSecondary,
    textAlign: "center",
  },
  locationTextMuted: {
    fontStyle: "italic",
    color: Theme.textMuted,
  },
  teamSection: {
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    minHeight: 38,
    paddingTop: 2,
    paddingHorizontal: 4,
    gap: 3,
  },
  sectionLabel: {
    fontSize: 7,
    fontWeight: "600",
    letterSpacing: 0.5,
    color: Theme.textMuted,
    textTransform: "uppercase",
    textAlign: "center",
  },
  footer: {
    width: "100%",
    flexShrink: 0,
    paddingTop: 2,
  },
  footerDivider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: Theme.borderLight,
    width: "100%",
    marginBottom: 6,
  },
  actionBtn: {
    borderRadius: 18,
    paddingVertical: 7,
    minHeight: 32,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 5,
  },
  actionBtnFlex: {
    flex: 1,
    minWidth: 0,
  },
  actionBtnOutline: {
    backgroundColor: Theme.screenBackground,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    width: "100%",
  },
  actionTextConnect: {
    fontSize: 11,
    fontWeight: "600",
    color: Theme.primary,
    flexShrink: 1,
  },
  actionTextOutline: {
    fontSize: 11,
    fontWeight: "600",
    color: Theme.textSecondary,
    flexShrink: 1,
  },
  connectFooter: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    width: "100%",
  },
  pendingFooter: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    width: "100%",
  },
  iconBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Theme.screenBackground,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    flexShrink: 0,
  },
});
