import { StyleSheet } from 'react-native';
import Theme from '@/constants/Theme';
import { Layout } from '@/constants/Layout';
import { CUSTOMERS_SUPPLIERS, LEDGER } from '@/features/finance/constants/tableColumns';
import { MIN_FISCAL_TAB_WIDTH } from '../types';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    width: '100%',
    minWidth: 0,
    backgroundColor: Theme.screenBackground,
  },
  centered: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 24,
  },
  message: { fontSize: 16, color: Theme.textSecondary },

  darkBlock: {
    backgroundColor: "#000000",
    width: "100%",
    minWidth: 0,
    alignSelf: "stretch",
    paddingBottom: 4,
    shadowColor: Theme.shadow,
    boxShadow: "0px 2px 8px 0px rgba(0, 0, 0, 0.2)",
    elevation: 4,
  },
  darkBlockContent: {
    paddingHorizontal: 0,
  },
  financeDatePresetWrap: {
    paddingHorizontal: 16,
    paddingTop: 2,
    paddingBottom: 6,
    borderBottomWidth: 1,
    borderBottomColor: Theme.separatorDark,
  },
  financeDatePresetOutsideWrap: {
    backgroundColor: Theme.screenBackground,
    width: "100%",
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 10,
    borderTopWidth: 1,
    borderTopColor: Theme.borderLight,
    borderBottomWidth: 1,
    borderBottomColor: Theme.borderLight,
  },
  financeHeaderMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 6,
  },
  financeHeaderMetaLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    minWidth: 0,
    flex: 1,
  },
  financeHeaderLogoBadge: {
    width: 22,
    height: 22,
    borderRadius: 7,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.08)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.14)",
  },
  financeHeaderTextWrap: {
    minWidth: 0,
    flexShrink: 1,
  },
  financeHeaderBrand: {
    fontSize: 10,
    fontWeight: "900",
    color: Theme.textOnDark,
    textTransform: "uppercase",
    letterSpacing: -0.2,
    fontStyle: "italic",
    marginBottom: 1,
  },
  financeHeaderCaption: {
    fontSize: 7,
    fontWeight: "800",
    color: Theme.textOnDarkMuted,
    textTransform: "uppercase",
    letterSpacing: 1.3,
  },
  financeHeaderTotalWrap: {
    alignItems: "flex-end",
    paddingLeft: 10,
  },
  financeHeaderTotalLabel: {
    fontSize: 7,
    fontWeight: "800",
    color: Theme.textOnDarkMuted,
    textTransform: "uppercase",
    letterSpacing: 1.2,
    marginBottom: 1,
  },
  financeHeaderTotalValue: {
    fontSize: 18,
    fontWeight: "900",
    color: Theme.textOnDark,
    letterSpacing: -0.4,
  },
  fiscalTabScroll: {
    width: "100%",
  },
  fiscalTabRow: {
    flexDirection: "row",
    paddingHorizontal: Layout.screenPaddingHorizontal,
    marginTop: 2,
    marginBottom: 6,
    paddingBottom: 8,
  },
  fiscalTab: {
    flex: 1,
    minWidth: MIN_FISCAL_TAB_WIDTH,
    position: "relative" as const,
    paddingVertical: 6,
    justifyContent: "center",
    alignItems: "center",
  },
  fiscalTabActive: {},
  fiscalTabText: {
    fontSize: 8,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 2,
    color: Theme.textSecondary,
  },
  fiscalTabTextActive: {
    color: Theme.textOnDark,
  },
  fiscalTabUnderline: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: 1.5,
    backgroundColor: Theme.teslaRed,
  },

  ledgerViewModeRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 6,
    marginBottom: 8,
    paddingHorizontal: 14,
  },
  /** Customers tab: icon-only pill for matrix/table/ledger toggle in summary. */
  customerViewModeIconPill: {
    paddingVertical: 5,
    paddingHorizontal: 8,
    borderRadius: 6,
    backgroundColor: "rgba(255,255,255,0.08)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.18)",
    alignItems: "center",
    justifyContent: "center",
  },
  ledgerViewModePill: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 8,
    backgroundColor: "rgba(255,255,255,0.08)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.18)",
  },
  ledgerViewModePillActive: {
    backgroundColor: Theme.teslaRed,
    borderColor: Theme.teslaRed,
  },
  ledgerViewModePillText: {
    fontSize: 11,
    fontWeight: "600",
    color: Theme.textOnDarkMuted,
  },
  ledgerViewModePillTextActive: {
    color: "#fff",
  },

  /** minHeight: 0 lets flex children shrink so inner ScrollView can scroll (web + native). */
  tableScroll: { flex: 1, width: '100%', minWidth: 0, minHeight: 0 },
  tableScrollInner: { flex: 1, minHeight: 0, minWidth: 0 },
  tableContent: {
    paddingHorizontal: 0,
    paddingTop: 0,
    backgroundColor: Theme.screenBackground,
  },
  /** Wraps header + ledger banner/strip + body; full width, no side padding */
  ledgerCardWrap: {
    flex: 1,
    minHeight: 0,
    width: '100%',
    minWidth: 0,
    alignSelf: 'stretch',
    marginHorizontal: 0,
    marginBottom: 8,
  },
  tableBodyWrap: {
    flex: 1,
    minHeight: 0,
    paddingHorizontal: 12,
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderLeftColor: Theme.borderLight,
    borderRightColor: Theme.borderLight,
    borderBottomColor: Theme.borderLight,
    borderBottomLeftRadius: 12,
    borderBottomRightRadius: 12,
    backgroundColor: Theme.screenBackground,
    marginTop: -1,
    shadowColor: "#000",
    boxShadow: "0px 1px 2px 0px rgba(0, 0, 0, 0.02)",
    elevation: 1,
  },
  driverSalaryRequestsBlock: {
    paddingVertical: 16,
    paddingHorizontal: 4,
    borderBottomWidth: 1,
    borderBottomColor: Theme.borderLight,
  },
  driverSalaryRequestsTitle: {
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 0.5,
    textTransform: "uppercase",
    color: Theme.textMuted,
    marginBottom: 4,
  },
  driverSalaryRequestsSubtitle: {
    fontSize: 11,
    fontWeight: "600",
    color: Theme.textMuted,
    marginBottom: 12,
  },
  driverSalaryRequestCard: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
    paddingVertical: 12,
    paddingHorizontal: 12,
    marginBottom: 8,
    backgroundColor: Theme.surface,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    borderRadius: 12,
  },
  driverSalaryRequestCardMain: { flex: 1, minWidth: 0 },
  driverSalaryRequestDriverName: {
    fontSize: 15,
    fontWeight: "800",
    color: Theme.textPrimary,
    marginBottom: 2,
  },
  driverSalaryRequestMeta: {
    fontSize: 12,
    fontWeight: "600",
    color: Theme.textMuted,
    marginBottom: 4,
  },
  driverSalaryRequestNote: {
    fontSize: 11,
    fontWeight: "500",
    color: Theme.textSecondary,
    marginBottom: 6,
    fontStyle: "italic",
  },
  driverSalaryRequestAmountRow: { marginTop: 4 },
  driverSalaryRequestAmount: {
    fontSize: 18,
    fontWeight: "800",
    color: Theme.positive,
  },
  driverSalaryRequestActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  driverSalaryRequestBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 10,
    minWidth: 72,
  },
  driverSalaryRequestBtnPay: {
    backgroundColor: Theme.positive,
  },
  driverSalaryRequestBtnPayText: {
    fontSize: 12,
    fontWeight: "800",
    color: Theme.textOnPrimary,
  },
  driverSalaryRequestBtnReject: {
    backgroundColor: Theme.surface,
    borderWidth: 1,
    borderColor: Theme.borderInput,
  },
  driverSalaryRequestBtnRejectText: {
    fontSize: 12,
    fontWeight: "800",
    color: Theme.textSecondary,
  },
  /* Tesla-style header-like filter & info strips: dark bg, tight uppercase typography */
  ledgerEntityFilterBanner: {
    flexDirection: "row",
    alignItems: "stretch",
    marginHorizontal: 0,
    marginTop: 0,
    marginBottom: 0,
    backgroundColor: Theme.darkBackground,
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderLeftColor: Theme.borderLight,
    borderRightColor: Theme.borderLight,
    borderBottomColor: Theme.separatorDark,
    overflow: "hidden",
  },
  ledgerEntityFilterBannerAccent: {
    width: 3,
    backgroundColor: Theme.teslaRed,
    minHeight: 1,
  },
  ledgerEntityFilterBannerContent: {
    flex: 1,
    marginRight: 8,
    minWidth: 0,
    paddingVertical: 10,
    paddingLeft: 14,
    paddingRight: 8,
  },
  ledgerEntityFilterLabelRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 6,
  },
  ledgerEntityFilterIconWrap: {
    marginRight: 2,
  },
  ledgerEntityFilterLabel: {
    fontSize: 9,
    fontWeight: "600",
    color: Theme.textSecondary,
    letterSpacing: 2,
    textTransform: "uppercase",
  },
  ledgerEntityFilterBadge: {
    backgroundColor: Theme.darkBackground,
    paddingVertical: 3,
    paddingHorizontal: 10,
    borderRadius: 4,
    maxWidth: "100%",
  },
  ledgerEntityFilterText: {
    fontSize: 12,
    fontWeight: "700",
    color: Theme.textOnDark,
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  ledgerEntityFilterStatsRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    marginTop: 6,
  },
  ledgerEntityFilterStat: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  ledgerEntityFilterStatValue: {
    fontSize: 12,
    fontWeight: "700",
    color: Theme.textOnDark,
    letterSpacing: 0.5,
  },
  ledgerEntityFilterStatUnit: {
    fontSize: 9,
    fontWeight: "600",
    color: Theme.textSecondary,
    letterSpacing: 1.2,
    textTransform: "uppercase",
  },
  ledgerEntityFilterStatIn: { gap: 4 },
  ledgerEntityFilterStatOut: { gap: 4 },
  ledgerEntityFilterStatPressed: {
    opacity: 0.75,
  },
  ledgerEntityFilterRatioBarWrap: {
    flexDirection: "row",
    height: 3,
    borderRadius: 2,
    overflow: "hidden",
    marginTop: 8,
    backgroundColor: "rgba(255,255,255,0.08)",
  },
  ledgerEntityFilterRatioBarIn: {
    backgroundColor: Theme.darkGreen,
    minWidth: 0,
  },
  ledgerEntityFilterRatioBarOut: {
    backgroundColor: Theme.teslaRed,
    minWidth: 0,
  },
  ledgerEntityFilterStatAmountGreen: {
    fontSize: 11,
    fontWeight: "700",
    color: Theme.darkGreen,
    letterSpacing: 0.4,
  },
  ledgerEntityFilterStatAmountRed: {
    fontSize: 11,
    fontWeight: "700",
    color: Theme.teslaRed,
    letterSpacing: 0.4,
  },
  ledgerEntityFilterClear: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingVertical: 8,
    paddingHorizontal: 12,
    margin: 8,
    backgroundColor: "transparent",
    borderRadius: 6,
    borderWidth: 1,
    borderColor: Theme.borderOnDark,
  },
  ledgerEntityFilterClearText: {
    fontSize: 9,
    fontWeight: "600",
    color: Theme.textOnDark,
    letterSpacing: 1.2,
    textTransform: "uppercase",
  },
  ledgerEntityFilterClearPressed: {
    opacity: 0.85,
    backgroundColor: "rgba(255,255,255,0.06)",
  },
  entityListBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.4)",
    paddingHorizontal: 24,
  },
  entityListBackdropTouchable: { flex: 1 },
  entityListPanel: {
    backgroundColor: Theme.screenBackground,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: Theme.borderInput,
    paddingVertical: 0,
    paddingHorizontal: 0,
    maxHeight: 360,
    overflow: "hidden",
    shadowColor: Theme.shadow,
    boxShadow: "0px 2px 8px 0px rgba(0, 0, 0, 0.2)",
    elevation: 8,
  },
  entityListPanelHeader: {
    backgroundColor: Theme.darkBackground,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: Theme.separatorDark,
  },
  entityListPanelTitle: {
    fontSize: 11,
    fontWeight: "700",
    color: Theme.textOnDark,
    letterSpacing: 1.2,
    textTransform: "uppercase",
  },
  entityListCategoriesScroll: {
    maxHeight: 320,
  },
  entityListCategories: {
    padding: 12,
    gap: 8,
    paddingBottom: 24,
  },
  entityCategoryCard: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    backgroundColor: Theme.surface,
    gap: 12,
  },
  entityCategoryCardActive: {
    borderColor: Theme.teslaRed,
    borderLeftWidth: 4,
    backgroundColor: Theme.screenBackground,
    shadowColor: Theme.teslaRed,
    boxShadow: "0px 0px 8px 0px rgba(200, 0, 0, 0.12)",
    elevation: 2,
  },
  entityCategoryIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: Theme.surfaceGray,
    alignItems: "center",
    justifyContent: "center",
  },
  entityCategoryIconWrapActive: {
    backgroundColor: Theme.darkBackground,
  },
  entityCategoryLabel: {
    flex: 1,
    fontSize: 14,
    fontWeight: "600",
    color: Theme.textPrimaryDark,
    letterSpacing: 0.3,
  },
  entityCategoryLabelActive: {
    color: Theme.textPrimaryDark,
    fontWeight: "700",
  },
  entityCategoryCount: {
    fontSize: 12,
    fontWeight: "600",
    color: Theme.textMuted,
    minWidth: 28,
    textAlign: "right",
  },
  entityCategoryCountActive: {
    color: Theme.teslaRed,
    fontWeight: "700",
  },
  entityCategoryCheck: {
    marginLeft: 4,
  },
  aiInsightsWrap: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 4,
  },
  tableHeaderWrap: {
    width: "100%",
    backgroundColor: Theme.surface,
    paddingHorizontal: 12,
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderTopWidth: 1,
    borderColor: Theme.borderLight,
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
    shadowColor: Theme.shadow,
    boxShadow: "0px 1px 2px 0px rgba(0, 0, 0, 0.02)",
    elevation: 1,
  },
  tableHeader: {
    flexDirection: "row",
    alignItems: "stretch",
    paddingVertical: 0,
    paddingHorizontal: 0,
    minWidth: 0,
  },
  th: {
    fontSize: 11,
    fontWeight: "600",
    color: Theme.textPrimaryDark,
    letterSpacing: 0.3,
    paddingVertical: 10,
  },
  thNode: {
    flex: LEDGER.node,
    minWidth: 0,
    paddingLeft: 0,
    paddingRight: 8,
    paddingVertical: 10,
    justifyContent: "center",
  },
  thMission: {
    flex: LEDGER.mission,
    minWidth: 0,
    paddingVertical: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  thCredit: { flex: LEDGER.credit, minWidth: 0, paddingVertical: 10 },
  thDebit: { flex: LEDGER.debit, minWidth: 0, paddingVertical: 10 },
  /** Column divider — full-height line, matches row cellBorderLeft (0.5px so columns align) */
  thBorderLeft: {
    borderLeftWidth: 0.5,
    borderLeftColor: Theme.borderLight,
    paddingLeft: 8,
    paddingRight: 6,
    paddingVertical: 10,
    justifyContent: "center",
  },
  /** Ledger: spacer so header columns align with body (chevron column width) */
  thLedgerSpacer: { width: LEDGER.chevronWidth, minWidth: LEDGER.chevronWidth },
  /** Customers tab column widths — source of truth for all 4 entity tabs. First col padding matches row cellNode. */
  thNodeCust: { flex: CUSTOMERS_SUPPLIERS.node, minWidth: 0, paddingLeft: 0, paddingRight: 8 },
  thTripsCust: { flex: CUSTOMERS_SUPPLIERS.trips, minWidth: 0 },
  thMissionCust: { flex: CUSTOMERS_SUPPLIERS.mission, minWidth: 0 },
  thCreditCust: { flex: CUSTOMERS_SUPPLIERS.credit, minWidth: 0 },
  thDebitCust: { flex: CUSTOMERS_SUPPLIERS.debit, minWidth: 0 },
  /** Drivers tab: same 5-column flex as Customers (DRIVER | TRIPS | EARNINGS | PAID | DUE). */
  thDriverNode: { flex: CUSTOMERS_SUPPLIERS.node, minWidth: 0, paddingLeft: 0, paddingRight: 8 },
  thDriverTrips: { flex: CUSTOMERS_SUPPLIERS.trips, minWidth: 0 },
  thDriverEarnings: { flex: CUSTOMERS_SUPPLIERS.mission, minWidth: 0 },
  thDriverPaid: { flex: CUSTOMERS_SUPPLIERS.credit, minWidth: 0 },
  thDriverDue: { flex: CUSTOMERS_SUPPLIERS.debit, minWidth: 0 },
  thCenter: { textAlign: "center" as const },
  thCenterView: { alignItems: "center" as const },
  thRight: { textAlign: "right" as const },
  thCol: {
    flex: LEDGER.credit,
    minWidth: 0,
    alignItems: "flex-end",
    justifyContent: "center",
    paddingVertical: 10,
  },
  /** Ledger: all four columns equal (25% each) */
  thColLedgerAmount: { minWidth: 0 },
  thWithFilter: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    position: "relative" as const,
  },
  thText: {
    fontSize: 11,
    fontWeight: "600",
    color: Theme.textPrimaryDark,
    letterSpacing: 0.3,
  },
  fabContainer: {
    position: "absolute",
    right: Layout.fabRightOffset,
    bottom: 0,
    left: 0,
    alignItems: "flex-end",
    justifyContent: "flex-end",
  },
  /** FAB wrapper: absolute, outside ScrollView; bottom set in screen; renders above content */
  fabAbsoluteWrap: {
    position: "absolute",
    right: 16,
    zIndex: 100,
    elevation: 10,
  },
  fabAnimatedWrap: {
    flexDirection: "column-reverse",
    alignItems: "flex-end",
    gap: 12,
  },
  ledgerLoading: {
    paddingVertical: 32,
    textAlign: "center",
    fontSize: 12,
    fontWeight: "600",
    color: Theme.textMutedDemo,
    letterSpacing: 0.5,
  },
});
