import { Layout } from "@/constants/Layout";
import Theme from "@/constants/Theme";
import {
  CUSTOMERS_SUPPLIERS,
  LEDGER,
} from "@/features/finance/constants/tableColumns";
import { Platform, StyleSheet } from "react-native";
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    width: "100%",
    minWidth: 0,
    minHeight: 0,
    backgroundColor: Theme.screenBackground,
  },
  centered: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 24,
  },
  message: { fontSize: 16, color: Theme.textSecondary },
  financeCardsBlock: {
    backgroundColor: Theme.screenBackground,
    paddingHorizontal: 12,
    paddingTop: 10,
    paddingBottom: 8,
    gap: 10,
    borderBottomWidth: 1,
    borderBottomColor: Theme.borderLight,
  },
  financeCardsGrid: {
    flexDirection: "row",
    gap: 10,
  },
  /** Desktop: dock filter toolbar under hero with same dark shell. */
  financeDesktopToolbarDock: {
    marginTop: 8,
    borderRadius: 16,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: Theme.borderLight,
    backgroundColor: Theme.screenBackground,
  },
  financeDesktopToolbarCard: {
    backgroundColor: Theme.screenBackground,
  },
  financeBalanceCardPressable: {
    flex: 1,
    position: "relative",
  },
  financeBalanceCardInnerWrap: {
    flex: 1,
  },
  financeBalanceCardGlow: {
    position: "absolute",
    left: 18,
    right: 18,
    top: 10,
    height: 24,
    borderRadius: 14,
    backgroundColor: "rgba(99,102,241,0.45)",
    zIndex: 0,
    ...Platform.select({
      web: {
        filter: "blur(22px)",
      } as any,
      default: {},
    }),
  },
  financeBalanceCard: {
    flex: 1,
    minHeight: 170,
    backgroundColor: Theme.financeHeroBg,
    borderRadius: 30,
    paddingHorizontal: 20,
    paddingVertical: 18,
    borderWidth: 1,
    borderColor: Theme.financeHeroBorder,
    justifyContent: "space-between",
    overflow: "hidden",
    position: "relative",
  },
  financeBalanceCardDesktop: {
    ...Platform.select({
      web: {
        minHeight: 236,
        paddingHorizontal: 24,
        paddingVertical: 20,
      } as any,
      default: {},
    }),
  },
  /** Desktop hero: fiscal pills docked at bottom; primary metrics stay visually grouped above. */
  financeBalanceCardHeroIntegrated: {
    ...Platform.select({
      web: {
        minHeight: 252,
      } as any,
      default: {},
    }),
  },
  financeHeroPrimaryBlock: {
    width: "100%",
    zIndex: 1,
    flex: 1,
    justifyContent: "space-between",
  },
  financeHeroPillsDock: {
    width: "100%",
    paddingTop: 18,
    marginTop: 2,
    zIndex: 1,
  },
  financeHeroFooterRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
    gap: 16,
    marginTop: 10,
    minWidth: 0,
  },
  financeHeroPillsDockInline: {
    flexShrink: 0,
    minWidth: 0,
    maxWidth: "52%",
    alignSelf: "flex-end",
    marginLeft: "auto",
  },
  financeBalanceDecorIconWrap: {
    position: "absolute",
    right: -18,
    top: -22,
    opacity: 0.06,
  },
  financeBalanceDecorIcon: {
    transform: [{ rotate: "10deg" }],
  },
  financeBalanceTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  financeBalanceEyebrow: {
    fontSize: 10,
    fontWeight: "900",
    color: Theme.textOnDarkMuted,
    textTransform: "uppercase",
    letterSpacing: 2,
    flexShrink: 1,
  },
  financeBalanceRangeBadge: {
    borderWidth: 1,
    borderColor: Theme.financeHeroRangeBorder,
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 4,
    backgroundColor: Theme.financeHeroRangeBg,
  },
  financeBalanceRangeText: {
    fontSize: 8,
    fontWeight: "800",
    color: Theme.textOnDarkMuted,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  financeRangeBar: {
    marginTop: 8,
    gap: 6,
  },
  financeRangeDesktopWrap: {
    alignItems: "center",
    flexDirection: "row",
    gap: 6,
    marginLeft: 14,
  },
  financeRangeDesktopPillRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  financeRangeLabel: {
    fontSize: 8,
    fontWeight: "800",
    color: Theme.textOnDarkMuted,
    textTransform: "uppercase",
    letterSpacing: 1.1,
  },
  financeRangePill: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: Theme.financeHeroRangeBorder,
    backgroundColor: Theme.financeHeroRangeBg,
    paddingHorizontal: 12,
    paddingVertical: 6,
    minHeight: 30,
    justifyContent: "center",
    alignItems: "center",
  },
  financeRangePillDesktop: {
    minHeight: 28,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  financeRangePillCustom: {
    flexDirection: "row",
    gap: 5,
  },
  financeRangePillActive: {
    backgroundColor: Theme.screenBackground,
    borderColor: Theme.screenBackground,
  },
  financeRangePillText: {
    fontSize: 7,
    fontWeight: "900",
    textTransform: "uppercase",
    letterSpacing: 1,
    color: Theme.textOnDarkMuted,
  },
  financeRangePillTextActive: {
    color: Theme.textPrimaryDark,
  },
  financeBalanceValue: {
    fontSize: 52,
    fontWeight: "800",
    color: Theme.textOnDark,
    letterSpacing: -0.85,
    fontStyle: "italic",
    marginTop: 8,
    paddingLeft: Layout.currencyTextPaddingStartLarge,
    paddingTop: Layout.currencyTextPaddingVertical,
    paddingBottom: Layout.currencyTextPaddingVertical,
    lineHeight: 66,
  },
  financeBalanceStatsRow: {
    flexDirection: "row",
    gap: 20,
    flexWrap: "nowrap",
    alignItems: "center",
    flexShrink: 0,
    paddingBottom: 1,
  },
  financeBalanceStat: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    minWidth: 110,
  },
  financeBalanceStatIconIn: {
    width: 26,
    height: 26,
    borderRadius: 9,
    backgroundColor: Theme.darkGreen,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: Theme.darkGreen,
    shadowOpacity: 0.35,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
  },
  financeBalanceStatIconOut: {
    width: 26,
    height: 26,
    borderRadius: 9,
    backgroundColor: Theme.teslaRed,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: Theme.teslaRed,
    shadowOpacity: 0.35,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
  },
  financeBalanceStatLabel: {
    fontSize: 8,
    fontWeight: "800",
    color: Theme.textOnDarkMuted,
    textTransform: "uppercase",
    letterSpacing: 1,
    fontStyle: "italic",
  },
  financeBalanceStatValue: {
    fontSize: 20,
    fontWeight: "800",
    color: Theme.textOnDark,
    fontStyle: "italic",
    paddingLeft: Layout.currencyTextPaddingStart,
    paddingTop: Layout.currencyTextPaddingVerticalTight,
    lineHeight: 28,
  },
  financeCategoryCardsRow: {
    flexDirection: "row",
    gap: 10,
    flexWrap: "nowrap",
  },
  financeCategoryCardsRowDesktopGrid: {
    ...Platform.select({
      web: {
        flexDirection: "row",
        flexWrap: "nowrap",
        alignItems: "stretch",
        width: "100%",
      } as any,
      default: {},
    }),
  },
  financeCategoryCard: {
    flex: 1,
    minWidth: 0,
    height: 124,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: Theme.financeHeroBorder,
    overflow: "hidden",
  },
  financeCategoryCardActive: {
    borderColor: "rgba(255,255,255,0.9)",
    borderWidth: 2,
    shadowColor: Theme.shadow,
    shadowOpacity: 0.2,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 3 },
  },
  financeCategoryCardDesktop: {
    ...Platform.select({
      web: {
        flex: 1,
        minWidth: 0,
        height: 170,
        borderRadius: 20,
      } as any,
      default: {},
    }),
  },
  financeCategoryAnimatedWrap: {
    flex: 1,
    minHeight: 0,
  },
  financeCategoryCardGradient: {
    flex: 1,
    paddingHorizontal: 14,
    paddingVertical: 12,
    justifyContent: "space-between",
    position: "relative",
  },
  financeCategoryCardGradientDesktop: {
    ...Platform.select({
      web: {
        paddingHorizontal: 18,
        paddingVertical: 16,
      } as any,
      default: {},
    }),
  },
  financeCategoryDecorIcon: {
    position: "absolute",
    right: 10,
    top: 7,
    opacity: 0.17,
  },
  financeCategoryDecorIconDesktop: {
    ...Platform.select({
      web: {
        right: 12,
        top: 10,
      } as any,
      default: {},
    }),
  },
  financeCategoryTop: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    minWidth: 0,
  },
  financeCategoryIconBadge: {
    width: 20,
    height: 20,
    borderRadius: 7,
    backgroundColor: "rgba(255,255,255,0.14)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.24)",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#ffffff",
    shadowOpacity: 0.22,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 1 },
  },
  financeCategoryIconBadgeDesktop: {
    ...Platform.select({
      web: {
        width: 24,
        height: 24,
        borderRadius: 9,
      } as any,
      default: {},
    }),
  },
  financeCategoryTitle: {
    fontSize: 8,
    fontWeight: "800",
    color: Theme.textOnDarkMuted,
    textTransform: "uppercase",
    letterSpacing: 1.25,
    flexShrink: 1,
  },
  financeCategoryTitleDesktop: {
    ...Platform.select({
      web: {
        fontSize: 9,
        letterSpacing: 1.35,
      } as any,
      default: {},
    }),
  },
  financeCategoryValue: {
    fontSize: 36,
    fontWeight: "900",
    color: Theme.textOnDark,
    letterSpacing: -0.5,
    paddingLeft: Layout.currencyTextPaddingStart,
    paddingTop: Layout.currencyTextPaddingVerticalTight,
    paddingBottom: Layout.currencyTextPaddingVerticalTight,
    lineHeight: 44,
  },
  financeCategoryValueDesktop: {
    ...Platform.select({
      web: {
        fontSize: 46,
        letterSpacing: -0.85,
        paddingLeft: Layout.currencyTextPaddingStartLarge,
        paddingTop: Layout.currencyTextPaddingVertical,
        paddingBottom: Layout.currencyTextPaddingVertical,
        lineHeight: 58,
      } as any,
      default: {},
    }),
  },
  financeCategoryCountPill: {
    marginLeft: "auto",
    minWidth: 18,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 999,
    backgroundColor: "rgba(0,0,0,0.28)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.22)",
    alignItems: "center",
    justifyContent: "center",
  },
  financeCategoryCountText: {
    fontSize: 8,
    fontWeight: "900",
    color: Theme.textOnDark,
    letterSpacing: 0.3,
  },
  financeCategoryActivePill: {
    marginLeft: 6,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.2)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.45)",
  },
  financeCategoryActivePillText: {
    fontSize: 7,
    fontWeight: "900",
    color: Theme.textOnDark,
    letterSpacing: 0.6,
    textTransform: "uppercase",
  },
  financeCategorySecondaryRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 4,
  },
  financeCategorySecondaryLabel: {
    fontSize: 8,
    fontWeight: "800",
    color: Theme.textOnDarkMuted,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  financeCategorySecondaryValue: {
    fontSize: 10,
    fontWeight: "800",
    color: Theme.textOnDark,
    letterSpacing: 0.2,
    paddingLeft: Layout.currencyTextPaddingStart,
    paddingTop: Layout.currencyTextPaddingVerticalTight,
    lineHeight: 16,
  },
  financeCategoryCtaRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  financeCategoryCtaText: {
    fontSize: 8,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 1.1,
    color: Theme.textOnDark,
  },
  financeCategoryCtaTextDesktop: {
    ...Platform.select({
      web: {
        fontSize: 9,
      } as any,
      default: {},
    }),
  },

  darkBlock: {
    backgroundColor: "#000000",
    width: "100%",
    minWidth: 0,
    alignSelf: "stretch",
    paddingBottom: 4,
    shadowColor: Theme.shadow,
    boxShadow: "0px 2px 8px 0px rgba(0, 0, 0, 0.2)",
    elevation: 4,
  },
  darkBlockContent: {
    paddingHorizontal: 0,
  },
  financeDatePresetWrap: {
    paddingHorizontal: 16,
    paddingTop: 2,
    paddingBottom: 6,
    borderBottomWidth: 1,
    borderBottomColor: Theme.separatorDark,
  },
  financeDatePresetOutsideWrap: {
    backgroundColor: Theme.screenBackground,
    width: "100%",
    paddingHorizontal: Layout.screenPaddingHorizontal,
    paddingTop: 6,
    paddingBottom: 8,
  },
  financeHeaderMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 6,
  },
  financeHeaderMetaLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    minWidth: 0,
    flex: 1,
  },
  financeHeaderLogoBadge: {
    width: 22,
    height: 22,
    borderRadius: 7,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.08)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.14)",
  },
  financeHeaderTextWrap: {
    minWidth: 0,
    flexShrink: 1,
  },
  financeHeaderBrand: {
    fontSize: 10,
    fontWeight: "900",
    color: Theme.textOnDark,
    textTransform: "uppercase",
    letterSpacing: -0.2,
    fontStyle: "italic",
    marginBottom: 1,
  },
  financeHeaderCaption: {
    fontSize: 7,
    fontWeight: "800",
    color: Theme.textOnDarkMuted,
    textTransform: "uppercase",
    letterSpacing: 1.3,
  },
  financeHeaderTotalWrap: {
    alignItems: "flex-end",
    paddingLeft: 10,
  },
  financeHeaderTotalLabel: {
    fontSize: 7,
    fontWeight: "800",
    color: Theme.textOnDarkMuted,
    textTransform: "uppercase",
    letterSpacing: 1.2,
    marginBottom: 1,
  },
  financeHeaderTotalValue: {
    fontSize: 18,
    fontWeight: "900",
    color: Theme.textOnDark,
    letterSpacing: -0.4,
  },

  financeHeroPillsScroll: {
    width: "100%",
    maxWidth: "100%",
    minWidth: 0,
  },
  financeHeroPillsRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 8,
    paddingVertical: 2,
    paddingLeft: 12,
    paddingRight: 4,
  },
  financeHeroPillsRowTreasuryInset: {
    paddingHorizontal: Layout.screenPaddingHorizontal,
  },
  financeHeroPill: {
    borderRadius: 999,
    borderWidth: 1,
    paddingVertical: 8,
    paddingHorizontal: 12,
    minHeight: 34,
    justifyContent: "center",
    alignItems: "center",
  },
  financeHeroPillInactive: {
    backgroundColor: "rgba(255,255,255,0.05)",
    borderColor: "rgba(255,255,255,0.05)",
  },
  financeHeroPillActive: {
    backgroundColor: Theme.screenBackground,
    borderColor: Theme.screenBackground,
  },
  financeHeroPillText: {
    fontSize: 8,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 1.4,
    color: Theme.textOnDarkMuted,
  },
  financeHeroPillTextActive: {
    color: Theme.textPrimaryDark,
  },

  ledgerViewModeRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 6,
    marginBottom: 8,
    paddingHorizontal: 14,
  },
  /** Customers tab: icon-only pill for matrix/table/ledger toggle in summary. */
  customerViewModeIconPill: {
    paddingVertical: 5,
    paddingHorizontal: 8,
    borderRadius: 6,
    backgroundColor: "rgba(255,255,255,0.08)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.18)",
    alignItems: "center",
    justifyContent: "center",
  },
  ledgerViewModePill: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 8,
    backgroundColor: "rgba(255,255,255,0.08)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.18)",
  },
  ledgerViewModePillActive: {
    backgroundColor: Theme.teslaRed,
    borderColor: Theme.teslaRed,
  },
  ledgerViewModePillText: {
    fontSize: 11,
    fontWeight: "600",
    color: Theme.textOnDarkMuted,
  },
  ledgerViewModePillTextActive: {
    color: "#fff",
  },

  /** minHeight: 0 lets flex children shrink so inner ScrollView can scroll (web + native). */
  mobileUnifiedScroll: {
    flex: 1,
    width: "100%",
    minWidth: 0,
    minHeight: 0,
  },
  /** Pinned Cash / Customers / … pills on mobile finance. */
  mobileFixedTabBar: {
    width: "100%",
    minWidth: 0,
    alignSelf: "stretch",
    flexShrink: 0,
    backgroundColor: "#000000",
    paddingTop: 8,
    paddingBottom: 6,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "rgba(255,255,255,0.12)",
    zIndex: 2,
  },
  mobileUnifiedScrollContent: {
    width: "100%",
    minWidth: 0,
  },
  mobileUnifiedBody: {
    width: "100%",
    minWidth: 0,
    alignSelf: "stretch",
  },
  tableBodyWrapEmbedded: {
    width: "100%",
    minWidth: 0,
    alignSelf: "stretch",
    paddingHorizontal: 12,
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderLeftColor: Theme.borderLight,
    borderRightColor: Theme.borderLight,
    borderBottomColor: Theme.borderLight,
    borderBottomLeftRadius: 12,
    borderBottomRightRadius: 12,
    backgroundColor: Theme.screenBackground,
    marginTop: -1,
  },
  tableScroll: { flex: 1, width: "100%", minWidth: 0, minHeight: 0 },
  tableScrollInner: { flex: 1, minHeight: 0, minWidth: 0 },
  tableContent: {
    paddingHorizontal: 0,
    paddingTop: 0,
    backgroundColor: Theme.screenBackground,
  },
  /** Wraps header + ledger banner/strip + body; full width, no side padding */
  ledgerCardWrap: {
    flex: 1,
    minHeight: 0,
    width: "100%",
    minWidth: 0,
    alignSelf: "stretch",
    marginHorizontal: 0,
    marginBottom: 8,
  },
  financeEmptyBannerWrap: {
    width: "100%",
    alignSelf: "stretch",
    paddingTop: 8,
    paddingBottom: 12,
  },
  tableBodyWrap: {
    flex: 1,
    minHeight: 0,
    paddingHorizontal: 12,
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderLeftColor: Theme.borderLight,
    borderRightColor: Theme.borderLight,
    borderBottomColor: Theme.borderLight,
    borderBottomLeftRadius: 12,
    borderBottomRightRadius: 12,
    backgroundColor: Theme.screenBackground,
    marginTop: -1,
    shadowColor: "#000",
    boxShadow: "0px 1px 2px 0px rgba(0, 0, 0, 0.02)",
    elevation: 1,
  },
  driverSalaryRequestsBlock: {
    paddingVertical: 16,
    paddingHorizontal: 4,
    borderBottomWidth: 1,
    borderBottomColor: Theme.borderLight,
  },
  driverSalaryRequestsTitle: {
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 0.5,
    textTransform: "uppercase",
    color: Theme.textMuted,
    marginBottom: 4,
  },
  driverSalaryRequestsSubtitle: {
    fontSize: 11,
    fontWeight: "600",
    color: Theme.textMuted,
    marginBottom: 12,
  },
  driverSalaryRequestCard: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
    paddingVertical: 12,
    paddingHorizontal: 12,
    marginBottom: 8,
    backgroundColor: Theme.surface,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    borderRadius: 12,
  },
  driverSalaryRequestCardMain: { flex: 1, minWidth: 0 },
  driverSalaryRequestDriverName: {
    fontSize: 15,
    fontWeight: "800",
    color: Theme.textPrimary,
    marginBottom: 2,
  },
  driverSalaryRequestMeta: {
    fontSize: 12,
    fontWeight: "600",
    color: Theme.textMuted,
    marginBottom: 4,
  },
  driverSalaryRequestNote: {
    fontSize: 11,
    fontWeight: "500",
    color: Theme.textSecondary,
    marginBottom: 6,
    fontStyle: "italic",
  },
  driverSalaryRequestAmountRow: { marginTop: 4 },
  driverSalaryRequestAmount: {
    fontSize: 18,
    fontWeight: "800",
    color: Theme.positive,
  },
  driverSalaryRequestActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  driverSalaryRequestBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 10,
    minWidth: 72,
  },
  driverSalaryRequestBtnPay: {
    backgroundColor: Theme.positive,
  },
  driverSalaryRequestBtnPayText: {
    fontSize: 12,
    fontWeight: "800",
    color: Theme.textOnPrimary,
  },
  driverSalaryRequestBtnReject: {
    backgroundColor: Theme.surface,
    borderWidth: 1,
    borderColor: Theme.borderInput,
  },
  driverSalaryRequestBtnRejectText: {
    fontSize: 12,
    fontWeight: "800",
    color: Theme.textSecondary,
  },
  /* Tesla-style header-like filter & info strips: dark bg, tight uppercase typography */
  ledgerEntityFilterBanner: {
    flexDirection: "row",
    alignItems: "stretch",
    marginHorizontal: 0,
    marginTop: 0,
    marginBottom: 0,
    backgroundColor: Theme.darkBackground,
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderLeftColor: Theme.borderLight,
    borderRightColor: Theme.borderLight,
    borderBottomColor: Theme.separatorDark,
    overflow: "hidden",
  },
  ledgerEntityFilterBannerAccent: {
    width: 3,
    backgroundColor: Theme.teslaRed,
    minHeight: 1,
  },
  ledgerEntityFilterBannerContent: {
    flex: 1,
    marginRight: 8,
    minWidth: 0,
    paddingVertical: 10,
    paddingLeft: 14,
    paddingRight: 8,
  },
  ledgerEntityFilterLabelRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 6,
  },
  ledgerEntityFilterIconWrap: {
    marginRight: 2,
  },
  ledgerEntityFilterLabel: {
    fontSize: 9,
    fontWeight: "600",
    color: Theme.textSecondary,
    letterSpacing: 2,
    textTransform: "uppercase",
  },
  ledgerEntityFilterBadge: {
    backgroundColor: Theme.darkBackground,
    paddingVertical: 3,
    paddingHorizontal: 10,
    borderRadius: 4,
    maxWidth: "100%",
  },
  ledgerEntityFilterText: {
    fontSize: 12,
    fontWeight: "700",
    color: Theme.textOnDark,
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  ledgerEntityFilterStatsRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    marginTop: 6,
  },
  ledgerEntityFilterStat: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  ledgerEntityFilterStatValue: {
    fontSize: 12,
    fontWeight: "700",
    color: Theme.textOnDark,
    letterSpacing: 0.5,
  },
  ledgerEntityFilterStatUnit: {
    fontSize: 9,
    fontWeight: "600",
    color: Theme.textSecondary,
    letterSpacing: 1.2,
    textTransform: "uppercase",
  },
  ledgerEntityFilterStatIn: { gap: 4 },
  ledgerEntityFilterStatOut: { gap: 4 },
  ledgerEntityFilterStatPressed: {
    opacity: 0.75,
  },
  ledgerEntityFilterRatioBarWrap: {
    flexDirection: "row",
    height: 3,
    borderRadius: 2,
    overflow: "hidden",
    marginTop: 8,
    backgroundColor: "rgba(255,255,255,0.08)",
  },
  ledgerEntityFilterRatioBarIn: {
    backgroundColor: Theme.darkGreen,
    minWidth: 0,
  },
  ledgerEntityFilterRatioBarOut: {
    backgroundColor: Theme.teslaRed,
    minWidth: 0,
  },
  ledgerEntityFilterStatAmountGreen: {
    fontSize: 11,
    fontWeight: "700",
    color: Theme.darkGreen,
    letterSpacing: 0.4,
  },
  ledgerEntityFilterStatAmountRed: {
    fontSize: 11,
    fontWeight: "700",
    color: Theme.teslaRed,
    letterSpacing: 0.4,
  },
  ledgerEntityFilterClear: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingVertical: 8,
    paddingHorizontal: 12,
    margin: 8,
    backgroundColor: "transparent",
    borderRadius: 6,
    borderWidth: 1,
    borderColor: Theme.borderOnDark,
  },
  ledgerEntityFilterClearText: {
    fontSize: 9,
    fontWeight: "600",
    color: Theme.textOnDark,
    letterSpacing: 1.2,
    textTransform: "uppercase",
  },
  ledgerEntityFilterClearPressed: {
    opacity: 0.85,
    backgroundColor: "rgba(255,255,255,0.06)",
  },
  entityListBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.4)",
    paddingHorizontal: 24,
  },
  entityListBackdropTouchable: { flex: 1 },
  entityListPanel: {
    backgroundColor: Theme.screenBackground,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: Theme.borderInput,
    paddingVertical: 0,
    paddingHorizontal: 0,
    maxHeight: 360,
    overflow: "hidden",
    shadowColor: Theme.shadow,
    boxShadow: "0px 2px 8px 0px rgba(0, 0, 0, 0.2)",
    elevation: 8,
  },
  entityListPanelHeader: {
    backgroundColor: Theme.darkBackground,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: Theme.separatorDark,
  },
  entityListPanelTitle: {
    fontSize: 11,
    fontWeight: "700",
    color: Theme.textOnDark,
    letterSpacing: 1.2,
    textTransform: "uppercase",
  },
  entityListCategoriesScroll: {
    maxHeight: 320,
  },
  entityListCategories: {
    padding: 12,
    gap: 8,
    paddingBottom: 24,
  },
  entityCategoryCard: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    backgroundColor: Theme.surface,
    gap: 12,
  },
  entityCategoryCardActive: {
    borderColor: Theme.teslaRed,
    borderLeftWidth: 4,
    backgroundColor: Theme.screenBackground,
    shadowColor: Theme.teslaRed,
    boxShadow: "0px 0px 8px 0px rgba(200, 0, 0, 0.12)",
    elevation: 2,
  },
  entityCategoryIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: Theme.surfaceGray,
    alignItems: "center",
    justifyContent: "center",
  },
  entityCategoryIconWrapActive: {
    backgroundColor: Theme.darkBackground,
  },
  entityCategoryLabel: {
    flex: 1,
    fontSize: 14,
    fontWeight: "600",
    color: Theme.textPrimaryDark,
    letterSpacing: 0.3,
  },
  entityCategoryLabelActive: {
    color: Theme.textPrimaryDark,
    fontWeight: "700",
  },
  entityCategoryCount: {
    fontSize: 12,
    fontWeight: "600",
    color: Theme.textMuted,
    minWidth: 28,
    textAlign: "right",
  },
  entityCategoryCountActive: {
    color: Theme.teslaRed,
    fontWeight: "700",
  },
  entityCategoryCheck: {
    marginLeft: 4,
  },
  aiInsightsWrap: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 4,
  },
  tableHeaderWrap: {
    width: "100%",
    backgroundColor: Theme.surface,
    paddingHorizontal: 12,
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderTopWidth: 1,
    borderColor: Theme.borderLight,
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
    shadowColor: Theme.shadow,
    boxShadow: "0px 1px 2px 0px rgba(0, 0, 0, 0.02)",
    elevation: 1,
  },
  tableHeader: {
    flexDirection: "row",
    alignItems: "stretch",
    paddingVertical: 0,
    paddingHorizontal: 0,
    minWidth: 0,
  },
  th: {
    fontSize: 11,
    fontWeight: "600",
    color: Theme.textPrimaryDark,
    letterSpacing: 0.3,
    paddingVertical: 10,
  },
  thNode: {
    flex: LEDGER.node,
    minWidth: 0,
    paddingLeft: 0,
    paddingRight: 8,
    paddingVertical: 10,
    justifyContent: "center",
  },
  thMission: {
    flex: LEDGER.mission,
    minWidth: 0,
    paddingVertical: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  thCredit: { flex: LEDGER.credit, minWidth: 0, paddingVertical: 10 },
  thDebit: { flex: LEDGER.debit, minWidth: 0, paddingVertical: 10 },
  /** Column divider — full-height line, matches row cellBorderLeft (0.5px so columns align) */
  thBorderLeft: {
    borderLeftWidth: 0.5,
    borderLeftColor: Theme.borderLight,
    paddingLeft: 8,
    paddingRight: 6,
    paddingVertical: 10,
    justifyContent: "center",
  },
  /** Ledger: spacer so header columns align with body (chevron column width) */
  thLedgerSpacer: { width: LEDGER.chevronWidth, minWidth: LEDGER.chevronWidth },
  /** Customers tab column widths — source of truth for all 4 entity tabs. First col padding matches row cellNode. */
  thNodeCust: {
    flex: CUSTOMERS_SUPPLIERS.node,
    minWidth: 0,
    paddingLeft: 0,
    paddingRight: 8,
  },
  thTripsCust: { flex: CUSTOMERS_SUPPLIERS.trips, minWidth: 0 },
  thMissionCust: { flex: CUSTOMERS_SUPPLIERS.mission, minWidth: 0 },
  thCreditCust: { flex: CUSTOMERS_SUPPLIERS.credit, minWidth: 0 },
  thDebitCust: { flex: CUSTOMERS_SUPPLIERS.debit, minWidth: 0 },
  /** Drivers tab: same 5-column flex as Customers (DRIVER | TRIPS | EARNINGS | PAID | DUE). */
  thDriverNode: {
    flex: CUSTOMERS_SUPPLIERS.node,
    minWidth: 0,
    paddingLeft: 0,
    paddingRight: 8,
  },
  thDriverTrips: { flex: CUSTOMERS_SUPPLIERS.trips, minWidth: 0 },
  thDriverEarnings: { flex: CUSTOMERS_SUPPLIERS.mission, minWidth: 0 },
  thDriverPaid: { flex: CUSTOMERS_SUPPLIERS.credit, minWidth: 0 },
  thDriverDue: { flex: CUSTOMERS_SUPPLIERS.debit, minWidth: 0 },
  thCenter: { textAlign: "center" as const },
  thCenterView: { alignItems: "center" as const },
  thRight: { textAlign: "right" as const },
  thCol: {
    flex: LEDGER.credit,
    minWidth: 0,
    alignItems: "flex-end",
    justifyContent: "center",
    paddingVertical: 10,
  },
  /** Ledger: all four columns equal (25% each) */
  thColLedgerAmount: { minWidth: 0 },
  thWithFilter: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    position: "relative" as const,
  },
  thText: {
    fontSize: 11,
    fontWeight: "600",
    color: Theme.textPrimaryDark,
    letterSpacing: 0.3,
  },
  fabContainer: {
    position: "absolute",
    right: Layout.fabRightOffset,
    bottom: 0,
    left: 0,
    alignItems: "flex-end",
    justifyContent: "flex-end",
  },
  /** FAB wrapper: absolute, outside ScrollView; bottom set in screen; renders above content */
  fabAbsoluteWrap: {
    position: "absolute",
    right: Layout.screenPaddingHorizontal,
    zIndex: 100,
    elevation: 10,
  },
  fabAnimatedWrap: {
    flexDirection: "column-reverse",
    alignItems: "flex-end",
    gap: 12,
  },
  ledgerLoading: {
    paddingVertical: 32,
    textAlign: "center",
    fontSize: 12,
    fontWeight: "600",
    color: Theme.textMutedDemo,
    letterSpacing: 0.5,
  },
});
