import { StyleSheet } from "react-native";
import { Theme } from "@/constants/Theme";

/** Slack desktop — compact type scale aligned with mobile. */
export const SLACK_DESKTOP_TYPE = {
  workspace: 15,
  section: 11,
  navItem: 13,
  search: 13,
  rowName: 12,
  rowPreview: 11.5,
  rowMeta: 11,
  threadTitle: 14,
  threadTab: 11,
  msgName: 13,
  msgTime: 11,
  msgBody: 14,
  composer: 14,
  emptyTitle: 14,
  emptySub: 12,
} as const;

export const SLACK_DESKTOP = {
  sidebarWidth: 418,
  border: "rgba(100, 116, 139, 0.24)",
  sidebarBg: "#FFFFFF",
  mainBg: "#FFFFFF",
  textPrimary: "#1D1C1D",
  textSecondary: "#616061",
  textTertiary: "#8B8B8B",
  rowActiveBg: "rgba(79, 70, 229, 0.12)",
  rowHoverBg: "#F8F8F8",
  searchBg: "#F7F9FC",
  activeBar: Theme.primary,
} as const;

export const SLACK_DESKTOP_AVATAR = {
  sidebar: 24,
  thread: 26,
  message: 32,
} as const;

export const slackDesktopStyles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: SLACK_DESKTOP.mainBg,
  },
  shell: {
    flex: 1,
    flexDirection: "row",
    minHeight: 0,
  },
  sidebar: {
    width: SLACK_DESKTOP.sidebarWidth,
    borderRightWidth: StyleSheet.hairlineWidth,
    borderRightColor: SLACK_DESKTOP.border,
    backgroundColor: SLACK_DESKTOP.sidebarBg,
    minHeight: 0,
  },
  main: {
    flex: 1,
    minWidth: 0,
    backgroundColor: SLACK_DESKTOP.mainBg,
  },
  sidebarHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 11,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "rgba(148, 163, 184, 0.2)",
  },
  sidebarTopBrandRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 14,
    paddingTop: 10,
    paddingBottom: 8,
    backgroundColor: "#13171D",
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "rgba(255, 255, 255, 0.12)",
  },
  sidebarBrandTitleRow: {
    flexDirection: "row",
    alignItems: "baseline",
  },
  sidebarBrandTitle: {
    fontSize: 15,
    fontWeight: "800",
    color: "#E2E8F0",
    letterSpacing: -0.25,
  },
  sidebarBrandDot: {
    fontSize: 15,
    fontWeight: "900",
    color: "#6366F1",
    letterSpacing: -0.25,
  },
  sidebarTopCloseBtn: {
    width: 28,
    height: 28,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 8,
    backgroundColor: "rgba(148, 163, 184, 0.14)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.14)",
  },
  workspaceNameWrap: {
    flex: 1,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  workspaceName: {
    flexShrink: 1,
    fontSize: SLACK_DESKTOP_TYPE.workspace,
    fontWeight: "700",
    color: "#1F2937",
    letterSpacing: -0.15,
  },
  headerActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  headerIconBtn: {
    width: 28,
    height: 28,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 8,
    backgroundColor: "rgba(248, 250, 252, 0.82)",
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.28)",
  },
  searchWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginHorizontal: 12,
    marginTop: 12,
    marginBottom: 9,
    paddingHorizontal: 11,
    minHeight: 38,
    borderRadius: 11,
    backgroundColor: "rgba(255,255,255,0.92)",
    borderWidth: 1,
    borderColor: "rgba(100, 116, 139, 0.22)",
  },
  searchInput: {
    flex: 1,
    fontSize: SLACK_DESKTOP_TYPE.search,
    color: "#334155",
    padding: 0,
    minWidth: 0,
    lineHeight: 16,
  },
  sectionLabel: {
    fontSize: SLACK_DESKTOP_TYPE.section,
    fontWeight: "700",
    color: "rgba(30, 41, 59, 0.92)",
    letterSpacing: 0.7,
    textTransform: "uppercase",
    paddingHorizontal: 14,
    paddingTop: 9,
    paddingBottom: 6,
  },
  streamNav: {
    paddingHorizontal: 8,
    paddingBottom: 4,
    gap: 1,
  },
  streamNavItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 6,
    minHeight: 28,
  },
  streamNavItemActive: {
    backgroundColor: SLACK_DESKTOP.rowActiveBg,
  },
  streamNavLabel: {
    flex: 1,
    fontSize: SLACK_DESKTOP_TYPE.navItem,
    fontWeight: "400",
    color: SLACK_DESKTOP.textSecondary,
  },
  streamNavLabelActive: {
    fontWeight: "600",
    color: SLACK_DESKTOP.textPrimary,
  },
  streamNavBadge: {
    minWidth: 16,
    height: 16,
    borderRadius: 8,
    paddingHorizontal: 4,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Theme.primary,
  },
  streamNavBadgeText: {
    fontSize: 9,
    fontWeight: "700",
    color: "#FFFFFF",
  },
  listScroll: {
    flex: 1,
    minHeight: 0,
    backgroundColor: SLACK_DESKTOP.sidebarBg,
  },
  sidebarCategoriesContent: {
    paddingBottom: 14,
    paddingHorizontal: 10,
  },
  sidebarBottomTabsWrap: {
    paddingHorizontal: 10,
    paddingTop: 8,
    paddingBottom: 10,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: "rgba(100, 116, 139, 0.18)",
    backgroundColor: SLACK_DESKTOP.sidebarBg,
    alignItems: "center",
  },
  sidebarBottomMirrorToggle: {
    backgroundColor: "#EEF2F6",
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.24)",
    minHeight: 46,
    padding: 3,
    width: "86%",
    maxWidth: 304,
    minWidth: 248,
    alignSelf: "center",
  },
  sidebarCategoryWrap: {
    marginTop: 4,
    borderRadius: 10,
    borderWidth: 0,
    backgroundColor: "transparent",
    overflow: "hidden",
  },
  sidebarCategoryHeader: {
    minHeight: 32,
    paddingHorizontal: 2,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "transparent",
  },
  sidebarCategoryHeaderRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  sidebarCategoryTitle: {
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.7,
    textTransform: "uppercase",
    color: "rgba(30, 41, 59, 0.9)",
  },
  sidebarCategoryCount: {
    fontSize: 10,
    fontWeight: "700",
    color: "#64748B",
  },
  sidebarCategoryMoreBtn: {
    minHeight: 30,
    justifyContent: "center",
    paddingHorizontal: 8,
  },
  sidebarCategoryMoreText: {
    fontSize: 11,
    fontWeight: "700",
    color: "#93C5FD",
  },
  sidebarCategoryEmptyText: {
    fontSize: 11,
    color: "rgba(51, 65, 85, 0.7)",
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  sidebarRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 11,
    paddingHorizontal: 12,
    paddingVertical: 11,
    minHeight: 66,
    borderLeftWidth: 2.25,
    borderLeftColor: "transparent",
    backgroundColor: "#FFFFFF",
    borderRadius: 10,
    borderWidth: 0,
    marginBottom: 6,
    shadowColor: "#0F172A",
    shadowOpacity: 0.06,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 1 },
    elevation: 1,
  },
  sidebarRowActive: {
    backgroundColor: "#EEF2FF",
    borderLeftColor: SLACK_DESKTOP.activeBar,
    shadowColor: "rgba(79, 70, 229, 0.45)",
    shadowOpacity: 0.12,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  sidebarRowHover: {
    backgroundColor: "#F7FAFF",
    shadowColor: "rgba(99, 102, 241, 0.2)",
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 1,
  },
  sidebarRowActiveHover: {
    backgroundColor: "#E9EEFF",
    shadowColor: "rgba(79, 70, 229, 0.4)",
    shadowOpacity: 0.14,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 3 },
    elevation: 2,
  },
  sidebarRowPressed: {
    backgroundColor: "#F8FAFC",
  },
  sidebarRowAvatarWrap: {
    marginTop: 2,
  },
  sidebarRowBody: {
    flex: 1,
    minWidth: 0,
    paddingTop: 0,
  },
  sidebarRowTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 6,
  },
  sidebarRowName: {
    flex: 1,
    fontSize: SLACK_DESKTOP_TYPE.rowName,
    fontWeight: "600",
    color: "#0F172A",
  },
  sidebarRowTime: {
    fontSize: SLACK_DESKTOP_TYPE.rowMeta,
    color: "#64748B",
    flexShrink: 0,
    marginTop: 1,
  },
  sidebarRowPreview: {
    fontSize: SLACK_DESKTOP_TYPE.rowPreview,
    color: "#475569",
    lineHeight: 17,
    marginTop: 3,
  },
  sidebarSystemPreviewWrap: {
    marginTop: 4,
    gap: 3,
  },
  sidebarPreviewRichRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
  },
  sidebarPreviewTextWrap: {
    flex: 1,
    minWidth: 0,
  },
  sidebarPreviewThumb: {
    width: 34,
    height: 34,
    borderRadius: 7,
    backgroundColor: "#E5E7EB",
    borderWidth: 1,
    borderColor: "#D1D5DB",
  },
  sidebarPreviewThumbPlaceholder: {
    width: 34,
    height: 34,
    borderRadius: 7,
    backgroundColor: "#F1F5F9",
    borderWidth: 0,
  },
  sidebarPreviewBadge: {
    alignSelf: "flex-start",
    fontSize: 8,
    fontWeight: "800",
    letterSpacing: 0.45,
    textTransform: "uppercase",
    borderWidth: 1,
    paddingHorizontal: 6,
    paddingVertical: 1,
    borderRadius: 999,
  },
  sidebarPreviewBadgeSystem: {
    backgroundColor: "#EEF2FF",
    borderColor: "rgba(91, 94, 244, 0.28)",
  },
  sidebarPreviewBadgeTextSystem: {
    color: SLACK_DESKTOP.activeBar,
  },
  sidebarPreviewBadgeImage: {
    backgroundColor: "rgba(14, 116, 144, 0.12)",
    borderColor: "rgba(14, 116, 144, 0.28)",
  },
  sidebarPreviewBadgeTextImage: {
    color: "#0E7490",
  },
  sidebarPreviewBadgeDocument: {
    backgroundColor: "rgba(180, 83, 9, 0.12)",
    borderColor: "rgba(180, 83, 9, 0.28)",
  },
  sidebarPreviewBadgeTextDocument: {
    color: "#B45309",
  },
  sidebarPreviewBadgeData: {
    backgroundColor: "rgba(3, 105, 161, 0.12)",
    borderColor: "rgba(3, 105, 161, 0.3)",
  },
  sidebarPreviewBadgeTextData: {
    color: "#0369A1",
  },
  sidebarPreviewBadgeHtml: {
    backgroundColor: "rgba(126, 34, 206, 0.12)",
    borderColor: "rgba(126, 34, 206, 0.3)",
  },
  sidebarPreviewBadgeTextHtml: {
    color: "#7E22CE",
  },
  threadHeader: {
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: SLACK_DESKTOP.border,
    backgroundColor: SLACK_DESKTOP.mainBg,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  threadHeaderToggleOnly: {
    paddingVertical: 8,
  },
  threadHeaderTop: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    minWidth: 0,
  },
  threadHeaderTopToggleOnly: {
    alignItems: "flex-start",
  },
  threadTitle: {
    flex: 1,
    fontSize: SLACK_DESKTOP_TYPE.threadTitle,
    fontWeight: "700",
    color: SLACK_DESKTOP.textPrimary,
    letterSpacing: -0.1,
  },
  threadSubtitle: {
    fontSize: SLACK_DESKTOP_TYPE.rowMeta,
    color: SLACK_DESKTOP.textTertiary,
    fontWeight: "400",
    marginTop: 1,
  },
  threadMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 2,
  },
  threadTopPartyTabs: {
    alignSelf: "flex-start",
    flexGrow: 0,
    flexShrink: 0,
  },
  threadPartyToggle: {
    alignSelf: "flex-start",
    width: "auto",
    minWidth: 268,
    maxWidth: 340,
  },
  threadCompactRoleTag: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(91, 94, 244, 0.28)",
    backgroundColor: "#F4F6FF",
  },
  threadCompactRoleTagActive: {
    borderColor: SLACK_DESKTOP.activeBar,
    backgroundColor: "#E7EAFF",
  },
  threadCompactRoleTagText: {
    fontSize: 9,
    fontWeight: "700",
    letterSpacing: 0.35,
    textTransform: "uppercase",
    color: SLACK_DESKTOP.activeBar,
  },
  threadCompactRoleTagTextActive: {
    color: SLACK_DESKTOP.textPrimary,
  },
  threadTabsRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    marginTop: 8,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: SLACK_DESKTOP.border,
    paddingBottom: 0,
  },
  threadTab: {
    paddingBottom: 8,
    borderBottomWidth: 2,
    borderBottomColor: "transparent",
  },
  threadTabActive: {
    borderBottomColor: SLACK_DESKTOP.activeBar,
  },
  threadTabText: {
    fontSize: SLACK_DESKTOP_TYPE.threadTab,
    fontWeight: "500",
    color: SLACK_DESKTOP.textTertiary,
  },
  threadTabTextActive: {
    fontWeight: "600",
    color: SLACK_DESKTOP.textPrimary,
  },
  threadMsgsContent: {
    paddingHorizontal: 16,
    paddingTop: 4,
    paddingBottom: 16,
    gap: 0,
  },
  composerWrap: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: SLACK_DESKTOP.border,
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 12,
    backgroundColor: SLACK_DESKTOP.mainBg,
  },
  composerBox: {
    borderWidth: 1,
    borderColor: SLACK_DESKTOP.border,
    borderRadius: 10,
    minHeight: 88,
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  composerInput: {
    flex: 1,
    fontSize: SLACK_DESKTOP_TYPE.composer,
    lineHeight: 21,
    color: SLACK_DESKTOP.textPrimary,
    minHeight: 44,
    textAlignVertical: "top",
  },
  composerToolbar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 6,
    paddingTop: 6,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: SLACK_DESKTOP.border,
  },
  emptyWrap: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 40,
    gap: 8,
  },
  emptyTitle: {
    fontSize: SLACK_DESKTOP_TYPE.emptyTitle,
    fontWeight: "600",
    color: SLACK_DESKTOP.textPrimary,
  },
  emptySub: {
    fontSize: SLACK_DESKTOP_TYPE.emptySub,
    color: SLACK_DESKTOP.textTertiary,
    textAlign: "center",
    lineHeight: 18,
  },
  scopeRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 10,
    paddingBottom: 6,
  },
  scopePill: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: SLACK_DESKTOP.border,
    backgroundColor: "#FFFFFF",
  },
  scopePillOn: {
    backgroundColor: SLACK_DESKTOP.rowActiveBg,
    borderColor: SLACK_DESKTOP.activeBar,
  },
  scopePillText: {
    fontSize: SLACK_DESKTOP_TYPE.rowMeta,
    fontWeight: "500",
    color: SLACK_DESKTOP.textSecondary,
  },
  scopePillTextOn: {
    fontWeight: "600",
    color: SLACK_DESKTOP.textPrimary,
  },
  threadMsgRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
  },
  threadMsgRowLead: {
    paddingTop: 10,
    paddingBottom: 2,
  },
  threadMsgRowContinuation: {
    paddingTop: 2,
    paddingBottom: 2,
  },
  threadMsgAvatarSpacer: {
    width: SLACK_DESKTOP_AVATAR.message,
    flexShrink: 0,
  },
  threadMsgAvatarCircle: {
    width: SLACK_DESKTOP_AVATAR.message,
    height: SLACK_DESKTOP_AVATAR.message,
    borderRadius: SLACK_DESKTOP_AVATAR.message / 2,
    overflow: "hidden",
    flexShrink: 0,
  },
  threadMsgBody: {
    flex: 1,
    minWidth: 0,
  },
  threadMsgHeader: {
    flexDirection: "row",
    alignItems: "baseline",
    flexWrap: "wrap",
    gap: 6,
    marginBottom: 2,
  },
  threadMsgName: {
    fontSize: 12,
    fontWeight: "800",
    color: "#1E293B",
    flexShrink: 1,
    letterSpacing: -0.1,
  },
  threadMsgTime: {
    fontSize: 10.5,
    fontWeight: "400",
    color: "#94A3B8",
    flexShrink: 0,
  },
  threadMsgText: {
    fontSize: 13,
    fontWeight: "400",
    color: "#64748B",
    lineHeight: 19,
  },
  threadMsgTextContinuation: {
    lineHeight: 21,
  },
  threadMsgTextStacked: {
    marginTop: 1,
  },
  threadSysMsg: {
    paddingVertical: 6,
    alignItems: "center",
  },
  threadSysMsgText: {
    fontSize: SLACK_DESKTOP_TYPE.rowMeta,
    fontWeight: "400",
    color: SLACK_DESKTOP.textTertiary,
    lineHeight: 16,
    textAlign: "center",
    paddingHorizontal: 12,
    paddingVertical: 2,
    borderWidth: 1,
    borderColor: SLACK_DESKTOP.border,
    borderRadius: 12,
    overflow: "hidden",
  },
  threadPartyTab: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: SLACK_DESKTOP.border,
    marginRight: 6,
  },
  threadPartyTabOn: {
    backgroundColor: SLACK_DESKTOP.rowActiveBg,
    borderColor: SLACK_DESKTOP.activeBar,
  },
  threadPartyTabOff: {
    opacity: 0.55,
  },
  threadPartyTabName: {
    fontSize: SLACK_DESKTOP_TYPE.rowMeta,
    fontWeight: "600",
    color: SLACK_DESKTOP.textPrimary,
  },
  threadPartyTabNameOn: {
    color: SLACK_DESKTOP.textPrimary,
  },
  threadPartyTabRole: {
    fontSize: SLACK_DESKTOP_TYPE.rowMeta,
    fontWeight: "400",
    color: SLACK_DESKTOP.textTertiary,
  },
  threadPartyTabRoleOn: {
    color: SLACK_DESKTOP.textSecondary,
  },
});
