import type { FlowStep, PersonaFlow } from '@/lib/flowStep.types';
import { triggerHandleNewUser } from '@/lib/flows/shared/triggerHandleNewUser';

const DRIVER_STEPS: FlowStep[] = [
  {
    id: 'dr-phone',
    order: 1,
    label: 'Phone',
    title: 'Welcome',
    subtitle: 'India mobile number',
    route: '/driver-signup',
    screen: 'driver-signup.tsx',
    phase: 'ui',
    fields: ['phone'],
    reads: ['profiles (checkExistingUserByPhone)'],
  },
  {
    id: 'dr-otp',
    order: 2,
    label: 'OTP',
    title: 'Verify',
    route: '/driver-signup',
    phase: 'ui',
    fields: ['6-digit OTP (UI gate)'],
    notes: ['Mock OTP — no invitation resolver on driver path'],
  },
  {
    id: 'dr-credentials',
    order: 3,
    label: 'Account',
    title: 'Registry',
    subtitle: 'Full name, email, password',
    route: '/driver-signup',
    phase: 'ui',
    fields: ['callsign/full_name', 'email', 'password'],
  },
  {
    id: 'dr-avatar',
    order: 4,
    label: 'Avatar',
    title: 'Choose identity',
    route: '/driver-signup',
    phase: 'ui',
    fields: ['avatar_seed preset or photo pick'],
  },
  {
    id: 'dr-docs',
    order: 5,
    label: 'Documents',
    title: 'KYC uploads',
    subtitle: 'License · Aadhaar · PAN (skippable)',
    route: '/driver-signup',
    phase: 'ui',
    fields: ['license', 'aadhaar', 'pan'],
  },
  {
    id: 'dr-auth',
    order: 6,
    label: 'Sign up',
    title: 'establishLink',
    route: '/driver-signup',
    service: 'auth.service signUp + signIn',
    phase: 'auth',
    authMetadata: ['role=driver', 'operating_model=ASSET_BASED', 'full_name', 'phone'],
    tables: ['auth.users', 'public.users', 'public.profiles'],
    notes: ['profiles: aggregated=false, asset=false · no org'],
  },
  {
    id: 'dr-post',
    order: 7,
    label: 'Post-auth',
    title: 'Profile + documents',
    service: 'updateProfile · uploadDriverDocuments',
    phase: 'post-auth',
    tables: [
      'profiles',
      'driver_profiles',
      'storage:driver-documents',
      'auth metadata driver_documents',
    ],
    notes: ['trg_auto_link_driver_on_signup may link roster drivers row by phone'],
  },
];

export const DRIVER_SIGNUP_FLOW: PersonaFlow = {
  id: 'driver',
  label: 'Driver',
  route: '/driver-signup · /onboarding/driver',
  screen: 'driver-signup.tsx',
  description: 'Driver persona — KYC docs, no organization provisioning.',
  sharedSteps: [],
  branches: [{ id: 'driver-main', label: 'Driver signup', summary: 'Single linear path', steps: DRIVER_STEPS }],
  tailSteps: [triggerHandleNewUser],
};
