import Theme from "@/constants/Theme";
import { CHAT_MOBILE } from "@/features/chat/chatMobileLayout";
import { StyleSheet, Platform } from "react-native";
import { METRONIC } from "@/features/network/components/desktop/networkDesktopHub.styles";

/** Pulse indigo — outgoing bubbles & active chips (not Metronic blue). */
const CHAT_PURPLE = Theme.primary;
const CHAT_PURPLE_SOFT = "rgba(79, 70, 229, 0.1)";
const CHAT_PURPLE_BORDER = "rgba(79, 70, 229, 0.28)";

export const networkDesktopChatStyles = StyleSheet.create({
  flexPane: {
    flex: 1,
    minWidth: 0,
    maxWidth: 440,
    backgroundColor: "#f5f7fb",
    paddingHorizontal: 10,
    paddingVertical: 10,
    alignSelf: "stretch",
    borderLeftWidth: StyleSheet.hairlineWidth,
    borderLeftColor: METRONIC.border,
  },
  drawerShell: {
    flex: 1,
    minHeight: 0,
    width: "100%",
    backgroundColor: Theme.cardWhite,
  },
  mobileCard: {
    width: "100%",
    flex: 1,
    minHeight: 0,
    alignSelf: "stretch",
    backgroundColor: Theme.cardWhite,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: METRONIC.border,
    overflow: "hidden",
    ...Platform.select({
      web: { boxShadow: "0 8px 32px rgba(24, 28, 50, 0.1)" as unknown as undefined },
      default: {
        shadowColor: "#181C32",
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.1,
        shadowRadius: 20,
        elevation: 8,
      },
    }),
  },
  mobileCardEmbedded: {
    flex: 1,
    minHeight: 0,
    borderRadius: 0,
    borderWidth: 0,
    ...Platform.select({
      web: { boxShadow: "none" as unknown as undefined },
      default: { elevation: 0 },
    }),
  },
  nativeBackdrop: {
    backgroundColor: "rgba(15, 23, 42, 0.35)",
  },
  nativeDrawer: {
    position: "absolute",
    backgroundColor: Theme.cardWhite,
    borderRadius: 16,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: METRONIC.border,
    overflow: "hidden",
    ...Platform.select({
      web: {
        boxShadow: "0 12px 40px rgba(24, 28, 50, 0.14)" as unknown as undefined,
      },
      default: {
        shadowColor: "#181C32",
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.12,
        shadowRadius: 24,
        elevation: 16,
      },
    }),
  },
  topBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: CHAT_MOBILE.headerBorder,
  },
  topBarTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: METRONIC.text,
  },
  closeBtn: {
    width: 32,
    height: 32,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F9FAFB",
    borderWidth: 1,
    borderColor: METRONIC.border,
  },
  threadHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: CHAT_MOBILE.headerBorder,
  },
  threadHeaderText: { flex: 1, minWidth: 0, gap: 2 },
  threadTitle: { fontSize: 14, fontWeight: "700", color: METRONIC.text },
  threadSubtitle: { fontSize: 11, fontWeight: "500", color: METRONIC.muted, fontStyle: "italic" },
  memberStack: { flexDirection: "row", alignItems: "center" },
  memberOverflow: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#E8FFF3",
    borderWidth: 2,
    borderColor: Theme.cardWhite,
    alignItems: "center",
    justifyContent: "center",
    marginLeft: -8,
  },
  memberOverflowText: { fontSize: 9, fontWeight: "800", color: "#50CD89" },
  partnerPickerScroll: {
    maxHeight: 200,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: CHAT_MOBILE.headerBorder,
  },
  partnerPickerContent: {
    paddingVertical: 4,
  },
  partnerRecRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: CHAT_MOBILE.headerBorder,
  },
  partnerRecRowActive: {
    backgroundColor: CHAT_PURPLE_SOFT,
  },
  partnerRecRowPressed: {
    backgroundColor: "#F3F4F6",
  },
  partnerRecBody: { flex: 1, minWidth: 0, gap: 2 },
  partnerRecTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  partnerRecName: {
    flex: 1,
    fontSize: 13,
    fontWeight: "600",
    color: METRONIC.text,
  },
  partnerRecNameUnread: {
    fontWeight: "800",
  },
  partnerRecNameActive: {
    color: CHAT_PURPLE,
  },
  partnerRecTime: {
    fontSize: 10,
    fontWeight: "500",
    color: METRONIC.muted,
  },
  partnerRecTimeUnread: {
    color: CHAT_PURPLE,
    fontWeight: "700",
  },
  partnerRecPreview: {
    fontSize: 11,
    fontWeight: "500",
    color: METRONIC.muted,
  },
  partnerRecPreviewUnread: {
    color: METRONIC.text,
    fontWeight: "600",
  },
  partnerRecBadge: {
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    paddingHorizontal: 5,
    backgroundColor: CHAT_PURPLE,
    alignItems: "center",
    justifyContent: "center",
  },
  partnerRecBadgeText: {
    fontSize: 10,
    fontWeight: "800",
    color: Theme.textOnPrimary,
    lineHeight: 12,
  },
  partnerChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: "#FAFAFA",
    maxWidth: 180,
  },
  partnerChipActive: {
    borderColor: CHAT_PURPLE_BORDER,
    backgroundColor: CHAT_PURPLE_SOFT,
  },
  partnerChipText: {
    fontSize: 11,
    fontWeight: "600",
    color: METRONIC.muted,
    flexShrink: 1,
  },
  partnerChipTextActive: {
    color: CHAT_PURPLE,
    fontWeight: "700",
  },
  integratedDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#50CD89",
  },
  threadTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    minWidth: 0,
  },
  integratedTag: {
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    backgroundColor: CHAT_PURPLE,
  },
  integratedTagText: {
    fontSize: 8,
    fontWeight: "800",
    letterSpacing: 0.4,
    color: Theme.textOnPrimary,
  },
  messages: { flex: 1, minHeight: 0 },
  messagesArea: {
    flex: 1,
    minHeight: 0,
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
    gap: 8,
  },
  messagesContent: {
    flexGrow: 1,
    justifyContent: "flex-end",
    paddingHorizontal: 12,
    paddingTop: 8,
    paddingBottom: 10,
    gap: 12,
  },
  messagesContentEmpty: {
    justifyContent: "center",
  },
  channelHint: {
    fontSize: 10,
    fontWeight: "600",
    color: METRONIC.muted,
    textAlign: "center",
    marginBottom: 8,
  },
  bubbleRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 8,
    width: "100%",
  },
  bubbleRowOwn: {
    flexDirection: "row-reverse",
    alignSelf: "flex-end",
    maxWidth: "88%",
  },
  bubbleRowOther: {
    alignSelf: "flex-start",
    maxWidth: "88%",
  },
  bubbleCol: {
    flexShrink: 1,
    minWidth: 0,
    maxWidth: "100%",
  },
  bubble: {
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  bubbleOther: { backgroundColor: "#F1F1F4" },
  bubbleOwn: { backgroundColor: CHAT_PURPLE },
  bubbleText: { fontSize: 12, lineHeight: 17, fontWeight: "500" },
  bubbleTextOther: { color: METRONIC.text },
  bubbleTextOwn: { color: Theme.textOnPrimary },
  bubbleMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginTop: 4,
  },
  bubbleMeta: {
    fontSize: 9,
    fontWeight: "500",
    color: METRONIC.muted,
  },
  bubbleMetaOwn: { justifyContent: "flex-end" },
  joinBar: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginHorizontal: 12,
    marginBottom: 8,
    padding: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: "#FAFAFA",
  },
  joinTextCol: { flex: 1, minWidth: 0, gap: 2 },
  joinTitle: { fontSize: 12, fontWeight: "700", color: METRONIC.text },
  joinMeta: { fontSize: 10, fontWeight: "500", color: METRONIC.muted },
  joinActions: { flexDirection: "row", gap: 6 },
  declineBtn: {
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
  },
  declineText: { fontSize: 11, fontWeight: "600", color: METRONIC.text },
  acceptBtn: {
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 7,
    backgroundColor: CHAT_PURPLE,
  },
  acceptText: { fontSize: 11, fontWeight: "700", color: Theme.textOnPrimary },
  composer: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: CHAT_MOBILE.headerBorder,
    backgroundColor: Theme.cardWhite,
  },
  composerInputWrap: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    minHeight: 40,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: "#FAFAFA",
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  composerInput: {
    flex: 1,
    fontSize: 13,
    fontWeight: "500",
    color: METRONIC.text,
    maxHeight: 96,
    padding: 0,
  },
  sendBtn: {
    minWidth: 64,
    height: 40,
    borderRadius: 8,
    backgroundColor: CHAT_PURPLE,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 14,
  },
  sendBtnDisabled: { opacity: 0.45 },
  sendText: { fontSize: 12, fontWeight: "700", color: Theme.textOnPrimary },
  emptyWrap: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
    gap: 8,
  },
  emptyTitle: { fontSize: 13, fontWeight: "700", color: METRONIC.text },
  emptySub: { fontSize: 12, color: METRONIC.muted, textAlign: "center", lineHeight: 18 },
  retryBtn: {
    marginTop: 10,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: CHAT_PURPLE_SOFT,
    borderWidth: 1,
    borderColor: CHAT_PURPLE_BORDER,
  },
  retryBtnText: {
    fontSize: 12,
    fontWeight: "700",
    color: CHAT_PURPLE,
  },
  tabActionIconBtnActive: {
    backgroundColor: CHAT_PURPLE_SOFT,
    borderColor: CHAT_PURPLE_BORDER,
  },
});
