import Theme from "@/constants/Theme";
import { StyleSheet } from "react-native";

/** Shared Metronic connection / grow profile tile chrome. */
export const connectionCardStyles = StyleSheet.create({
  card: {
    paddingVertical: 16,
    paddingHorizontal: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#EFF2F5",
    backgroundColor: Theme.cardWhite,
    /** Content-sized tile; identity + facts must not be clipped. */
    minHeight: 232,
    gap: 8,
    flex: 1,
    alignSelf: "stretch",
    width: "100%",
    minWidth: 0,
    alignItems: "stretch",
    justifyContent: "space-between",
    ...({
      boxShadow: "0 0 20px 0 rgba(76, 87, 125, 0.05)",
    } as object),
  },
  topLead: {
    alignSelf: "stretch",
    alignItems: "flex-start",
    gap: 6,
    paddingRight: 28,
    marginBottom: 2,
  },
  topLeadRoleRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 4,
  },
  topLeadBadges: {
    justifyContent: "flex-start",
    alignSelf: "stretch",
  },
  cardPressed: {
    opacity: 0.92,
  },
  dismissBtn: {
    position: "absolute",
    top: 8,
    right: 8,
    width: 24,
    height: 24,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2,
  },
  topMetaRow: {
    alignSelf: "stretch",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    marginBottom: 2,
    paddingRight: 20,
  },
  topMetaLeft: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 4,
    flexShrink: 1,
    minWidth: 0,
  },
  roleTag: {
    paddingHorizontal: 7,
    paddingVertical: 3,
    borderRadius: 6,
    borderWidth: 1,
  },
  roleTagText: {
    fontSize: 9,
    fontWeight: "800",
    letterSpacing: 0.35,
  },
  ratingWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    flexShrink: 0,
  },
  ratingText: {
    fontSize: 10,
    fontWeight: "700",
    color: "#181C32",
    minWidth: 22,
    textAlign: "right",
  },
  ratingTextEmpty: {
    color: "#A1A5B7",
  },
  trustBadgesRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    flexWrap: "wrap",
    gap: 4,
    marginTop: 0,
    marginBottom: 0,
  },
  /** Always reserve badge-row space so DRIVER tiles match CLIENT/SUPPLIER height. */
  trustBadgesSlot: {
    minHeight: 22,
    height: 22,
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "stretch",
    overflow: "hidden",
  },
  cardBody: {
    alignItems: "center",
    alignSelf: "stretch",
    gap: 4,
    flexGrow: 1,
    minWidth: 0,
  },
  verifiedTag: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    backgroundColor: "rgba(21, 128, 61, 0.12)",
    borderColor: "rgba(21, 128, 61, 0.28)",
  },
  verifiedTagText: {
    color: Theme.darkGreen,
    fontWeight: "700",
  },
  recommendedTag: {
    backgroundColor: Theme.aggregatePillBg,
    borderColor: Theme.aggregatePillBorder,
  },
  recommendedTagText: {
    color: Theme.aggregatePillText,
    fontWeight: "700",
  },
  avatarWrap: {
    width: 76,
    height: 76,
    position: "relative",
    marginBottom: 4,
  },
  onlineDot: {
    position: "absolute",
    right: 0,
    bottom: 0,
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: "#50CD89",
    borderWidth: 2,
    borderColor: Theme.cardWhite,
  },
  nameRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    maxWidth: "100%",
  },
  name: {
    fontSize: 13,
    fontWeight: "700",
    color: "#181C32",
    flexShrink: 1,
  },
  handle: {
    fontSize: 11,
    fontWeight: "500",
    color: "#A1A5B7",
    maxWidth: "100%",
    textAlign: "center",
  },
  footerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    marginTop: 4,
    maxWidth: "100%",
    flexWrap: "nowrap",
    alignSelf: "stretch",
    flexShrink: 0,
  },
  appTag: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 7,
    paddingVertical: 3,
    borderRadius: 999,
    borderWidth: 1,
  },
  appTagOn: {
    backgroundColor: "rgba(80, 205, 137, 0.1)",
    borderColor: "rgba(80, 205, 137, 0.35)",
  },
  appTagOff: {
    backgroundColor: "#F5F8FA",
    borderColor: "#EFF2F5",
  },
  appTagPending: {
    backgroundColor: "rgba(255, 199, 0, 0.12)",
    borderColor: "rgba(255, 199, 0, 0.35)",
  },
  appTagDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  appTagDotOn: {
    backgroundColor: "#50CD89",
  },
  appTagDotOff: {
    backgroundColor: "#A1A5B7",
  },
  appTagDotPending: {
    backgroundColor: "#FFC700",
  },
  appTagText: {
    fontSize: 9,
    fontWeight: "700",
    letterSpacing: 0.2,
  },
  appTagTextOn: {
    color: "#1B7F4A",
  },
  appTagTextOff: {
    color: "#78829D",
  },
  appTagTextPending: {
    color: "#B78103",
  },
  actionBtn: {
    minHeight: 24,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    alignItems: "center",
    justifyContent: "center",
    minWidth: 52,
  },
  actionBtnInvite: {
    backgroundColor: Theme.buttonPrimary,
    borderWidth: Theme.buttonPrimaryBorderWidth,
    borderColor: Theme.buttonPrimaryBorder,
    borderRadius: Theme.buttonPrimaryRadius,
  },
  actionBtnInviteText: {
    fontSize: 9,
    fontWeight: "700",
    color: Theme.buttonPrimaryText,
    letterSpacing: 0.15,
  },
  actionBtnChat: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "#EEF6FF",
    borderWidth: 1,
    borderColor: "rgba(0, 158, 247, 0.25)",
  },
  actionBtnChatText: {
    fontSize: 9,
    fontWeight: "700",
    color: Theme.primary,
    letterSpacing: 0.15,
  },
  actionBtnConnected: {
    backgroundColor: "#F5F8FA",
    borderWidth: 1,
    borderColor: "#EFF2F5",
  },
  actionBtnConnectedText: {
    fontSize: 9,
    fontWeight: "700",
    color: "#78829D",
    letterSpacing: 0.15,
  },
  actionBtnPending: {
    backgroundColor: "#F5F8FA",
    borderWidth: 1,
    borderColor: "#EFF2F5",
  },
  actionBtnPendingText: {
    fontSize: 9,
    fontWeight: "700",
    color: "#78829D",
    letterSpacing: 0.15,
  },
  actionBtnDisabled: {
    opacity: 0.55,
  },
  actionBtnPressed: {
    opacity: 0.88,
  },
});

/** Refined grow / discover tile — lighter type, softer chrome. */
export const growConnectionCardStyles = StyleSheet.create({
  card: {
    paddingTop: 16,
    paddingBottom: 14,
    paddingHorizontal: 16,
    borderRadius: 16,
    borderColor: Theme.borderMedium,
    gap: 14,
    minHeight: 0,
    flex: 1,
    height: "100%",
    alignSelf: "stretch",
    width: "100%",
    minWidth: 0,
    alignItems: "stretch",
    justifyContent: "space-between",
    overflow: "hidden",
    ...({
      boxShadow: "0 8px 24px 0 rgba(15, 23, 42, 0.04)",
    } as object),
  },
  topLead: {
    alignSelf: "stretch",
    alignItems: "flex-start",
    gap: 6,
    paddingRight: 28,
    marginBottom: 2,
  },
  topLeadBadges: {
    justifyContent: "flex-start",
    alignSelf: "stretch",
  },
  roleTag: {
    paddingHorizontal: 5,
    paddingVertical: 1,
    borderRadius: 4,
  },
  roleTagText: {
    fontSize: 8,
    fontWeight: "500",
    letterSpacing: 0.35,
  },
  verifiedTag: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    backgroundColor: "rgba(21, 128, 61, 0.12)",
    borderColor: "rgba(21, 128, 61, 0.28)",
  },
  verifiedTagText: {
    color: Theme.darkGreen,
    fontWeight: "700",
  },
  recommendedTag: {
    backgroundColor: Theme.aggregatePillBg,
    borderColor: Theme.aggregatePillBorder,
  },
  recommendedTagText: {
    color: Theme.aggregatePillText,
    fontWeight: "700",
  },
  trustBadgesRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    flexWrap: "wrap",
    gap: 4,
    marginTop: 0,
    marginBottom: 0,
  },
  /** Fits Verified + Recommended (possibly wrapped) without changing tile height. */
  trustBadgesSlot: {
    minHeight: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "stretch",
    overflow: "hidden",
  },
  ratingText: {
    fontSize: 10,
    fontWeight: "500",
    color: "#78829D",
  },
  avatarWrap: {
    width: 72,
    height: 72,
    marginBottom: 4,
  },
  name: {
    fontSize: 14,
    fontWeight: "500",
    color: "#3F4254",
    letterSpacing: -0.15,
  },
  handle: {
    fontSize: 11,
    fontWeight: "400",
    color: "#78829D",
    minHeight: 15,
  },
  footerBlock: {
    marginTop: "auto",
    width: "100%",
    alignSelf: "stretch",
    alignItems: "stretch",
    gap: 12,
    flexShrink: 0,
    minWidth: 0,
  },
  footerSeparator: {
    width: "100%",
    height: StyleSheet.hairlineWidth,
    backgroundColor: Theme.borderLight,
    alignSelf: "stretch",
  },
  footerRow: {
    gap: 10,
    width: "100%",
    alignSelf: "stretch",
    paddingTop: 0,
    paddingHorizontal: 0,
    justifyContent: "space-between",
    alignItems: "center",
    flexDirection: "row",
    flexWrap: "nowrap",
    flexShrink: 0,
    minHeight: 32,
    minWidth: 0,
  },
  mutualFacepileSlot: {
    flex: 1,
    flexShrink: 1,
    minWidth: 0,
    minHeight: 24,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: 8,
    paddingRight: 8,
    marginRight: 0,
  },
  mutualFacepileSlotCompact: {
    paddingRight: 4,
    maxWidth: 148,
  },
  mutualsWatermark: {
    fontSize: 11,
    fontWeight: "500",
    letterSpacing: 0.2,
    color: Theme.textRouteCard,
    flexShrink: 1,
    minWidth: 0,
  },
  mutualsViewBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    flexShrink: 1,
    minWidth: 0,
    minHeight: 24,
    paddingVertical: 2,
  },
  appTag: {
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  appTagText: {
    fontSize: 9,
    fontWeight: "600",
    letterSpacing: 0.1,
  },
  actionBtn: {
    minHeight: 32,
    height: 32,
    width: undefined,
    minWidth: 92,
    maxWidth: 120,
    marginLeft: 0,
    paddingHorizontal: 14,
    paddingVertical: 0,
    borderRadius: 8,
    flexGrow: 0,
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
  },
  actionBtnCompact: {
    width: undefined,
    minWidth: 84,
    maxWidth: 108,
    paddingHorizontal: 12,
  },
  actionBtnInvite: {
    backgroundColor: Theme.surface,
    borderWidth: 1,
    borderColor: Theme.primary,
  },
  actionBtnInviteText: {
    fontSize: 12,
    fontWeight: "600",
    color: Theme.primary,
    letterSpacing: 0,
  },
  actionBtnConnected: {
    backgroundColor: Theme.surface,
    borderWidth: 1,
    borderColor: Theme.borderMedium,
  },
  actionBtnConnectedText: {
    fontSize: 12,
    fontWeight: "600",
    color: Theme.darkGreen,
  },
  actionBtnPending: {
    backgroundColor: Theme.surface,
    borderWidth: 1,
    borderColor: Theme.borderLight,
  },
  actionBtnPendingText: {
    fontSize: 11,
    fontWeight: "500",
    color: Theme.textRouteCard,
    letterSpacing: 0,
  },
  bizCard: {
    alignSelf: "stretch",
    width: "100%",
    minWidth: 0,
    minHeight: 220,
    paddingTop: 14,
    paddingBottom: 14,
    paddingHorizontal: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Theme.borderMedium,
    backgroundColor: Theme.cardWhite,
    gap: 12,
    ...({
      boxShadow: "0 1px 12px 0 rgba(76, 87, 125, 0.04)",
    } as object),
  },
  bizHeader: {
    alignSelf: "stretch",
    flexDirection: "row",
    alignItems: "center",
    paddingRight: 28,
  },
  bizBody: {
    alignSelf: "stretch",
    flexGrow: 1,
    gap: 8,
    minWidth: 0,
  },
  bizIdentity: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 20,
    alignSelf: "stretch",
    minWidth: 0,
  },
  bizAvatarCol: {
    width: 64,
    flexShrink: 0,
    alignItems: "center",
    gap: 8,
  },
  bizAvatar: {
    width: 52,
    height: 52,
    position: "relative",
    flexShrink: 0,
  },
  avatarRatingBadge: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    minHeight: 20,
    maxWidth: 64,
    paddingHorizontal: 0,
    paddingVertical: 0,
    backgroundColor: "transparent",
    borderWidth: 0,
  },
  avatarRatingBadgeText: {
    fontSize: 14,
    fontWeight: "800",
    color: Theme.textPrimaryDark,
    fontVariant: ["tabular-nums"],
    letterSpacing: -0.3,
    includeFontPadding: false,
    lineHeight: 16,
    textAlignVertical: "center",
  },
  avatarRatingBadgeStar: {
    marginTop: 0.5,
    flexShrink: 0,
  },
  avatarRatingBadgeTextEmpty: {
    fontSize: 9,
    fontWeight: "400",
    color: Theme.textSecondary,
    fontVariant: [],
    letterSpacing: 0,
  },
  bizIdentityText: {
    flex: 1,
    minWidth: 0,
    gap: 5,
    paddingTop: 2,
    paddingRight: 22,
  },
  bizNameRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    minWidth: 0,
  },
  bizName: {
    flexShrink: 1,
    minWidth: 0,
    fontSize: 15,
    fontWeight: "600",
    color: Theme.textPrimaryDark,
    letterSpacing: -0.25,
  },
  bizLocation: {
    fontSize: 12,
    fontWeight: "400",
    color: Theme.textRouteCard,
    lineHeight: 16,
  },
  bizLocationEmpty: {
    color: Theme.textSecondary,
  },
  bizStatsLine: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 8,
    marginTop: 2,
    minWidth: 0,
  },
  bizStatChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    maxWidth: "100%",
    paddingHorizontal: 0,
    paddingVertical: 0,
    borderRadius: 0,
    backgroundColor: "transparent",
    borderWidth: 0,
  },
  bizStatChipTrips: {
    backgroundColor: "transparent",
    borderColor: "transparent",
  },
  bizStatChipAging: {
    backgroundColor: "transparent",
  },
  bizStatPart: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  bizStatDot: {
    fontSize: 10,
    color: Theme.textMuted,
    lineHeight: 13,
    marginRight: 4,
  },
  bizStatText: {
    fontSize: 10,
    fontWeight: "400",
    color: Theme.textRouteCard,
    fontVariant: ["tabular-nums"],
    includeFontPadding: false,
  },
  bizTrustBadges: {
    justifyContent: "flex-start",
    alignSelf: "flex-start",
    flexGrow: 0,
  },
  bizTrustBadgesSlot: {
    minHeight: 0,
    alignSelf: "stretch",
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: 4,
  },
  bizFooter: {
    alignSelf: "stretch",
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingTop: 4,
  },
  bizPrimaryBtn: {
    minWidth: 128,
    maxWidth: 150,
    minHeight: 36,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: Theme.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  bizPrimaryBtnText: {
    fontSize: 13,
    fontWeight: "600",
    color: Theme.textOnPrimary,
  },
  bizPrimaryBtnQuiet: {
    backgroundColor: Theme.surface,
    borderWidth: 1,
    borderColor: Theme.borderMedium,
  },
  bizPrimaryBtnQuietText: {
    fontSize: 13,
    fontWeight: "600",
    color: Theme.textRouteCard,
  },
  bizSecondaryBtn: {
    minWidth: 128,
    maxWidth: 150,
    minHeight: 36,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: Theme.cardWhite,
    borderWidth: 1,
    borderColor: Theme.borderMedium,
    alignItems: "center",
    justifyContent: "center",
  },
  bizSecondaryBtnText: {
    fontSize: 13,
    fontWeight: "600",
    color: Theme.textPrimaryDark,
  },
});
