import Theme from "@/constants/Theme";
import { Platform, StyleSheet } from "react-native";

export const METRONIC = {
  border: "#EFF2F5",
  muted: "#A1A5B7",
  text: "#181C32",
  subtle: "#78829D",
  accent: Theme.primary,
  heroBg: "#FFFFFF",
  heroHex: "#E1E3EA",
  bodyBg: "#F5F8FA",
  link: "#3E97FF",
  heroRing: "#50CD89",
} as const;

/** KeenThemes-style hex tile pattern (web). */
const HEX_PATTERN_SVG = `<svg xmlns="http://www.w3.org/2000/svg" width="56" height="100" viewBox="0 0 56 100"><path d="M28 0 L56 16 V48 L28 64 L0 48 V16 Z" fill="none" stroke="${METRONIC.heroHex}" stroke-width="1" opacity="0.45"/><path d="M28 36 L56 52 V84 L28 100 L0 84 V52 Z" fill="none" stroke="${METRONIC.heroHex}" stroke-width="1" opacity="0.3"/></svg>`;
export const METRONIC_HEX_BACKGROUND = {
  backgroundImage: `url("data:image/svg+xml,${encodeURIComponent(HEX_PATTERN_SVG)}")`,
  backgroundSize: "56px 100px",
} as object;

export const networkDesktopHubStyles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: METRONIC.bodyBg,
  },
  scrollContent: {
    paddingBottom: 24,
  },
  hero: {
    backgroundColor: METRONIC.heroBg,
    borderBottomWidth: 1,
    borderBottomColor: METRONIC.border,
    paddingTop: 16,
    paddingBottom: 14,
    paddingHorizontal: 20,
    position: "relative",
    overflow: "hidden",
    ...METRONIC_HEX_BACKGROUND,
  },
  heroHexOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    ...Platform.select({
      web: {
        backgroundImage:
          "radial-gradient(ellipse 80% 60% at 50% 0%, rgba(255,255,255,0.92) 0%, rgba(255,255,255,0.55) 55%, rgba(255,255,255,0.2) 100%)",
      },
      default: {
        backgroundColor: "rgba(255, 255, 255, 0.72)",
      },
    }),
  },
  heroInner: {
    width: "100%",
    zIndex: 1,
    position: "relative",
    alignItems: "center",
  },
  heroCenter: {
    width: "100%",
    alignItems: "center",
    gap: 6,
    paddingTop: 20,
  },
  heroWelcomeCorner: {
    position: "absolute",
    top: 0,
    right: 0,
    zIndex: 2,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: "rgba(255, 255, 255, 0.92)",
    ...({
      boxShadow: "0 2px 10px rgba(24, 28, 50, 0.06)",
      cursor: "pointer",
    } as object),
  },
  heroWelcomeTextWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  heroWelcomeText: {
    fontSize: 11,
    fontWeight: "600",
    color: METRONIC.subtle,
  },
  heroWelcomeName: {
    fontWeight: "700",
    color: METRONIC.text,
  },
  heroUserRingSm: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: METRONIC.link,
    backgroundColor: Theme.cardWhite,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  heroUserImageSm: {
    width: 24,
    height: 24,
    borderRadius: 12,
  },
  heroAvatarPressable: {
    position: "relative",
    marginTop: 4,
  },
  heroAvatarRing: {
    width: 68,
    height: 68,
    borderRadius: 34,
    borderWidth: 2,
    borderColor: METRONIC.heroRing,
    backgroundColor: Theme.cardWhite,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    ...({
      boxShadow: "0 4px 12px rgba(24, 28, 50, 0.08)",
    } as object),
  },
  heroAvatarImage: {
    width: 62,
    height: 62,
    borderRadius: 31,
  },
  heroCameraBadge: {
    position: "absolute",
    right: 0,
    bottom: 0,
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: METRONIC.text,
    borderWidth: 2,
    borderColor: Theme.cardWhite,
    alignItems: "center",
    justifyContent: "center",
  },
  heroMetaRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    marginTop: 2,
  },
  heroMetaItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  heroMetaText: {
    fontSize: 11,
    fontWeight: "500",
    color: METRONIC.subtle,
  },
  heroStatsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    marginTop: 2,
    paddingHorizontal: 8,
  },
  heroStatChip: {
    fontSize: 11,
    color: METRONIC.subtle,
  },
  heroStatValue: {
    fontWeight: "700",
    color: METRONIC.text,
  },
  heroStatLabel: {
    fontWeight: "500",
    color: METRONIC.muted,
  },
  heroStatDivider: {
    fontSize: 11,
    color: METRONIC.muted,
    fontWeight: "600",
  },
  heroLogoHint: {
    fontSize: 10,
    fontWeight: "500",
    color: METRONIC.muted,
    marginTop: 1,
  },
  heroNameRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
    marginTop: 2,
  },
  heroName: {
    fontSize: 17,
    fontWeight: "700",
    color: METRONIC.text,
    letterSpacing: -0.3,
  },
  tabBar: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
    borderBottomWidth: 1,
    borderBottomColor: METRONIC.border,
    paddingHorizontal: 16,
    paddingTop: 0,
    backgroundColor: Theme.cardWhite,
    minHeight: 42,
  },
  tabScroll: {
    flexGrow: 0,
    flexShrink: 1,
  },
  tabScrollContent: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 0,
  },
  tabBtn: {
    paddingHorizontal: 11,
    paddingVertical: 10,
    borderRadius: 0,
    borderWidth: 0,
    borderBottomWidth: 2,
    borderBottomColor: "transparent",
    backgroundColor: "transparent",
    marginBottom: -1,
  },
  tabBtnActive: {
    borderBottomColor: METRONIC.accent,
    backgroundColor: "transparent",
  },
  tabText: {
    fontSize: 12,
    fontWeight: "500",
    color: METRONIC.muted,
    letterSpacing: 0,
  },
  tabTextActive: {
    color: METRONIC.text,
    fontWeight: "700",
  },
  tabActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flexShrink: 0,
  },
  tabActionBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
  },
  tabActionBtnPrimary: {
    backgroundColor: "#78829D",
    borderColor: "#78829D",
  },
  tabActionBtnText: {
    fontSize: 11,
    fontWeight: "700",
    color: METRONIC.text,
  },
  tabActionBtnTextOn: {
    color: Theme.buttonDarkText,
  },
  tabActionIconBtn: {
    width: 36,
    height: 36,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: METRONIC.border,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Theme.cardWhite,
  },
  panel: {
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 16,
    gap: 12,
    backgroundColor: Theme.cardWhite,
    borderBottomWidth: 1,
    borderBottomColor: METRONIC.border,
  },
  detailsBody: {
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 16,
    gap: 12,
    backgroundColor: Theme.cardWhite,
    borderBottomWidth: 1,
    borderBottomColor: METRONIC.border,
  },
  statsBar: {
    flexDirection: "row",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
    overflow: "hidden",
    ...({
      boxShadow: "0 0 10px 0 rgba(76, 87, 125, 0.04)",
    } as object),
  },
  statCell: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    gap: 3,
    borderRightWidth: 1,
    borderRightColor: METRONIC.border,
  },
  statCellLast: {
    borderRightWidth: 0,
  },
  statValue: {
    fontSize: 16,
    fontWeight: "700",
    color: METRONIC.text,
    letterSpacing: -0.3,
  },
  statLabel: {
    fontSize: 9,
    fontWeight: "600",
    color: METRONIC.muted,
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  splitRow: {
    flexDirection: "row",
    gap: 12,
    alignItems: "flex-start",
    flexWrap: "wrap",
  },
  sidebar: {
    width: "28%",
    minWidth: 220,
    maxWidth: 300,
    gap: 10,
    flexShrink: 0,
  },
  mainCol: {
    flex: 1,
    minWidth: 260,
    gap: 10,
    ...({
      display: "flex",
      flexDirection: "column",
    } as object),
  },
  card: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
    padding: 14,
    gap: 8,
    ...({
      boxShadow: "0 0 10px 0 rgba(76, 87, 125, 0.03)",
    } as object),
  },
  cardTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: METRONIC.text,
    marginBottom: 2,
  },
  cardTitleInline: {
    marginBottom: 0,
    flex: 1,
    minWidth: 0,
  },
  salesCardTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: METRONIC.text,
    marginBottom: 0,
  },
  kvRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 10,
    paddingVertical: 7,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: METRONIC.border,
  },
  kvRowLast: {
    borderBottomWidth: 0,
    paddingBottom: 0,
  },
  kvLabel: {
    fontSize: 11,
    fontWeight: "500",
    color: METRONIC.muted,
    flexShrink: 0,
  },
  kvValue: {
    fontSize: 11,
    fontWeight: "600",
    color: METRONIC.text,
    flex: 1,
    textAlign: "right",
  },
  kvValueLink: {
    color: METRONIC.link,
  },
  aboutBody: {
    fontSize: 12,
    lineHeight: 18,
    fontWeight: "400",
    color: METRONIC.subtle,
  },
  sectionHeading: {
    fontSize: 12,
    fontWeight: "700",
    color: METRONIC.text,
    marginTop: 1,
  },
  sectionHeadingSpaced: {
    marginTop: 12,
  },
  subscribedPill: {
    alignSelf: "flex-end",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 6,
    backgroundColor: "rgba(80, 205, 137, 0.15)",
  },
  subscribedPillText: {
    fontSize: 10,
    fontWeight: "700",
    color: "#47BE7D",
    textTransform: "uppercase",
    letterSpacing: 0.3,
  },
  headquarterRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    marginTop: 6,
    alignItems: "stretch",
  },
  mapFrame: {
    flex: 1,
    minWidth: 200,
    minHeight: 160,
    height: 160,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: "#F3F6F9",
    overflow: "hidden",
    position: "relative",
  },
  mapStaticImage: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: "100%",
    height: "100%",
  },
  mapPlaceholder: {
    flex: 1,
    minWidth: 200,
    minHeight: 140,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: "#F3F6F9",
    alignItems: "center",
    justifyContent: "center",
    padding: 16,
    position: "relative",
  },
  mapPlaceholderLoading: {
    justifyContent: "center",
  },
  mapPinBubble: {
    position: "absolute",
    top: 12,
    left: 12,
    right: 12,
    zIndex: 2,
    backgroundColor: Theme.cardWhite,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: METRONIC.border,
    paddingHorizontal: 10,
    paddingVertical: 8,
    gap: 2,
    ...({
      boxShadow: "0 4px 12px rgba(24, 28, 50, 0.08)",
    } as object),
  },
  mapPinBubbleText: {
    fontSize: 11,
    fontWeight: "700",
    color: METRONIC.text,
    lineHeight: 15,
  },
  mapPinBubbleSub: {
    fontSize: 10,
    fontWeight: "500",
    color: METRONIC.muted,
    lineHeight: 14,
  },
  contactList: {
    flex: 1,
    minWidth: 180,
    gap: 9,
    justifyContent: "center",
    paddingVertical: 2,
  },
  networkLinkRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    minWidth: 0,
  },
  networkLinkText: {
    flex: 1,
    fontSize: 11,
    fontWeight: "500",
    color: METRONIC.text,
    minWidth: 0,
  },
  openJobRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    paddingVertical: 8,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: METRONIC.border,
  },
  openJobRowLast: {
    borderBottomWidth: 0,
  },
  openJobIcon: {
    width: 30,
    height: 30,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: "#F9FAFB",
    alignItems: "center",
    justifyContent: "center",
  },
  openJobTextCol: {
    flex: 1,
    minWidth: 0,
    gap: 1,
  },
  openJobCategory: {
    fontSize: 10,
    fontWeight: "600",
    color: METRONIC.link,
  },
  openJobTitle: {
    fontSize: 11,
    fontWeight: "700",
    color: METRONIC.text,
  },
  openJobMeta: {
    fontSize: 10,
    fontWeight: "500",
    color: METRONIC.muted,
    marginTop: 1,
  },
  cardFooterLink: {
    alignItems: "center",
    paddingTop: 8,
  },
  cardFooterLinkText: {
    fontSize: 12,
    fontWeight: "600",
    color: METRONIC.link,
    ...({
      textDecorationLine: "underline",
      textDecorationStyle: "dotted",
    } as object),
  },
  tagWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
  },
  tagPill: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 5,
    backgroundColor: "#F1F1F4",
  },
  tagPillText: {
    fontSize: 10,
    fontWeight: "600",
    color: METRONIC.subtle,
  },
  productPill: {
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: 5,
    backgroundColor: "#F1F1F4",
  },
  productPillText: {
    fontSize: 11,
    fontWeight: "600",
    color: METRONIC.text,
  },
  cardHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    marginBottom: 2,
  },
  cardEditBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: "#F9FAFB",
  },
  cardEditBtnText: {
    fontSize: 10,
    fontWeight: "600",
    color: METRONIC.muted,
  },
  offerLocationBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: "#50CD89",
  },
  offerLocationBtnText: {
    fontSize: 11,
    fontWeight: "700",
    color: Theme.buttonPrimaryText,
  },
  locationsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    paddingTop: 8,
    alignItems: "stretch",
  },
  locationCard: {
    flexGrow: 1,
    flexShrink: 0,
    flexBasis: "calc(25% - 9px)",
    minWidth: 140,
    maxWidth: "calc(25% - 9px)",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
    overflow: "hidden",
    paddingBottom: 8,
  },
  locationCardPressable: {
    flex: 1,
  },
  locationsEmpty: {
    paddingVertical: 20,
    alignItems: "center",
    gap: 8,
  },
  locationsEmptyText: {
    fontSize: 12,
    fontWeight: "500",
    color: METRONIC.muted,
    textAlign: "center",
    lineHeight: 18,
  },
  locationImage: {
    height: 80,
    alignItems: "center",
    justifyContent: "center",
  },
  locationTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: METRONIC.text,
    paddingHorizontal: 10,
    paddingTop: 12,
  },
  locationAddress: {
    fontSize: 11,
    fontWeight: "500",
    color: METRONIC.muted,
    lineHeight: 16,
    paddingHorizontal: 10,
    paddingBottom: 4,
  },
  locationLinkHint: {
    fontSize: 10,
    fontWeight: "700",
    color: METRONIC.link,
    paddingHorizontal: 10,
    paddingTop: 6,
  },
  projectsTableHead: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    paddingHorizontal: 4,
    borderBottomWidth: 1,
    borderBottomColor: METRONIC.border,
    marginTop: 4,
  },
  projectsHeadCell: {
    fontSize: 10,
    fontWeight: "700",
    color: METRONIC.muted,
    textTransform: "uppercase",
    letterSpacing: 0.45,
  },
  projectsRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 10,
    paddingHorizontal: 4,
    minHeight: 42,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: METRONIC.border,
  },
  projectsRowLast: {
    borderBottomWidth: 0,
  },
  projectsCell: {
    fontSize: 13,
    fontWeight: "600",
    color: METRONIC.text,
  },
  projectsCellMuted: {
    fontSize: 12,
    fontWeight: "500",
    color: METRONIC.muted,
  },
  projectsColName: {
    flex: 2.4,
    minWidth: 0,
    paddingRight: 16,
  },
  projectsColProgress: {
    flex: 1.5,
    minWidth: 72,
    maxWidth: 140,
  },
  projectsColPeople: {
    flex: 1.1,
    minWidth: 96,
    paddingRight: 8,
  },
  projectsColDue: {
    flex: 0.8,
    minWidth: 64,
  },
  projectsColMenu: {
    width: 24,
    alignItems: "center",
  },
  progressTrackWrap: {
    paddingRight: 8,
  },
  progressTrack: {
    height: 6,
    borderRadius: 3,
    backgroundColor: "#F1F1F4",
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    borderRadius: 3,
    backgroundColor: METRONIC.link,
  },
  peopleMoreFill: {
    backgroundColor: "#50CD89",
    borderColor: Theme.cardWhite,
    alignItems: "center",
    justifyContent: "center",
  },
  peopleMoreText: {
    fontSize: 9,
    fontWeight: "800",
    color: Theme.textOnPrimary,
    letterSpacing: -0.2,
  },
  projectsPeopleEmpty: {
    fontSize: 12,
    fontWeight: "500",
    color: METRONIC.muted,
  },
  cardTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  autoRefreshPill: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: "#F9FAFB",
  },
  autoRefreshText: {
    fontSize: 10,
    fontWeight: "600",
    color: METRONIC.muted,
  },
  activityCard: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
    padding: 14,
    gap: 12,
    ...({
      boxShadow: "0 0 20px 0 rgba(76, 87, 125, 0.04)",
    } as object),
  },
  activityList: {
    gap: 0,
    paddingTop: 4,
  },
  activityItem: {
    flexDirection: "row",
    gap: 14,
    paddingTop: 2,
  },
  activityRail: {
    width: 28,
    alignItems: "center",
  },
  activityDot: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: "#F9FAFB",
    alignItems: "center",
    justifyContent: "center",
  },
  activityLine: {
    flex: 1,
    width: 1,
    backgroundColor: METRONIC.border,
    marginTop: 6,
    minHeight: 28,
  },
  activityBody: {
    flex: 1,
    minWidth: 0,
    paddingBottom: 20,
    gap: 5,
  },
  activityBodyLast: {
    paddingBottom: 4,
  },
  activityTitle: {
    fontSize: 13,
    fontWeight: "600",
    color: METRONIC.text,
    lineHeight: 20,
  },
  activityMeta: {
    fontSize: 11,
    fontWeight: "500",
    color: METRONIC.muted,
  },
  activityNestedCard: {
    marginTop: 10,
    padding: 14,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: "#F9FAFB",
    gap: 6,
  },
  activityNestedTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: METRONIC.text,
  },
  activityNestedBody: {
    fontSize: 12,
    fontWeight: "400",
    color: METRONIC.subtle,
    lineHeight: 18,
  },
  sectionToolbar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 4,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: METRONIC.text,
  },
  sectionSub: {
    fontSize: 12,
    fontWeight: "500",
    color: METRONIC.muted,
    marginTop: 2,
  },
  filterRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
  },
  filterPill: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
  },
  filterPillOn: {
    borderColor: METRONIC.accent,
    backgroundColor: "rgba(79, 70, 229, 0.06)",
  },
  filterPillText: {
    fontSize: 11,
    fontWeight: "600",
    color: METRONIC.subtle,
  },
  filterPillTextOn: {
    color: METRONIC.accent,
  },
  searchBox: {
    flex: 1,
    minWidth: 180,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  searchInput: {
    flex: 1,
    fontSize: 12,
    fontWeight: "500",
    color: METRONIC.text,
    padding: 0,
    minWidth: 0,
  },
  hiddenDataBridge: {
    height: 0,
    overflow: "hidden",
    opacity: 0,
  },
  tableHead: {
    flexDirection: "row",
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: METRONIC.border,
    backgroundColor: "#F9FAFB",
  },
  tableHeadText: {
    flex: 1,
    fontSize: 10,
    fontWeight: "700",
    color: METRONIC.muted,
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  tableRow: {
    flexDirection: "row",
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: METRONIC.border,
    alignItems: "center",
  },
  tableCell: {
    flex: 1,
    fontSize: 12,
    fontWeight: "500",
    color: METRONIC.text,
    minWidth: 0,
  },
  statusPill: {
    alignSelf: "flex-start",
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 5,
    backgroundColor: "rgba(79, 70, 229, 0.1)",
  },
  statusPillText: {
    fontSize: 10,
    fontWeight: "700",
    color: METRONIC.accent,
    textTransform: "uppercase",
  },
  emptyWrap: {
    paddingVertical: 48,
    alignItems: "center",
    gap: 8,
  },
  emptyText: {
    fontSize: 13,
    fontWeight: "500",
    color: METRONIC.muted,
  },
  salesBody: {
    paddingHorizontal: 24,
    paddingTop: 16,
    paddingBottom: 24,
    backgroundColor: Theme.cardWhite,
    borderBottomWidth: 1,
    borderBottomColor: METRONIC.border,
  },
  salesCard: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
    ...({
      boxShadow: "0 0 20px 0 rgba(76, 87, 125, 0.04)",
    } as object),
  },
  salesCardPad: {
    padding: 16,
  },
  salesCardPadTight: {
    paddingHorizontal: 10,
    paddingTop: 12,
    paddingBottom: 10,
  },
  salesFilterHint: {
    fontSize: 11,
    fontWeight: "500",
    color: METRONIC.muted,
    marginTop: -4,
    marginBottom: 8,
  },
  salesFilterGroup: {
    fontSize: 11,
    fontWeight: "700",
    color: METRONIC.muted,
    textTransform: "uppercase",
    letterSpacing: 0.4,
    marginTop: 10,
    marginBottom: 6,
  },
  salesFilterChip: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 6,
    backgroundColor: "#F1F1F4",
    borderWidth: 1,
    borderColor: "transparent",
  },
  salesFilterChipOn: {
    backgroundColor: "rgba(62, 151, 255, 0.12)",
    borderColor: "rgba(62, 151, 255, 0.35)",
  },
  salesFilterChipText: {
    fontSize: 11,
    fontWeight: "600",
    color: METRONIC.subtle,
  },
  salesFilterChipTextOn: {
    color: METRONIC.link,
    fontWeight: "700",
  },
  salesSidebarToggleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 16,
    paddingTop: 14,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: METRONIC.border,
  },
  salesSidebarToggleLabel: {
    fontSize: 12,
    fontWeight: "600",
    color: METRONIC.text,
    flex: 1,
    paddingRight: 8,
  },
  salesClearBtn: {
    marginTop: 12,
    alignItems: "center",
    paddingVertical: 8,
  },
  salesClearBtnText: {
    fontSize: 12,
    fontWeight: "600",
    color: METRONIC.link,
    ...({
      textDecorationLine: "underline",
      textDecorationStyle: "dotted",
    } as object),
  },
  salesContributorRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingVertical: 8,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: METRONIC.border,
  },
  salesContributorRowLast: {
    borderBottomWidth: 0,
  },
  salesContributorDot: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#F1F1F4",
    alignItems: "center",
    justifyContent: "center",
  },
  salesContributorDotText: {
    fontSize: 12,
    fontWeight: "800",
    color: METRONIC.subtle,
  },
  salesContributorTextCol: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  salesContributorName: {
    fontSize: 12,
    fontWeight: "700",
    color: METRONIC.text,
  },
  salesContributorMeta: {
    fontSize: 10,
    fontWeight: "500",
    color: METRONIC.muted,
  },
  salesSidebarPartnerCard: {
    minWidth: 0,
  },
  salesGrowPanel: {
    paddingHorizontal: 0,
    paddingTop: 10,
    paddingBottom: 10,
    overflow: "hidden",
  },
  salesGrowHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    paddingHorizontal: 12,
    paddingBottom: 8,
  },
  salesGrowTitleIcon: {
    width: 22,
    height: 22,
    borderRadius: 6,
    backgroundColor: "rgba(62, 151, 255, 0.1)",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 1,
  },
  salesGrowHeaderText: {
    flex: 1,
    minWidth: 0,
    gap: 1,
  },
  salesGrowTitle: {
    fontSize: 12,
    fontWeight: "700",
    color: METRONIC.text,
    lineHeight: 15,
  },
  salesGrowSub: {
    fontSize: 9,
    fontWeight: "500",
    color: METRONIC.muted,
    lineHeight: 12,
  },
  salesGrowLoading: {
    paddingVertical: 12,
    alignItems: "center",
  },
  salesGrowFeed: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: METRONIC.border,
  },
  salesGrowRow: {
    paddingLeft: 10,
    paddingRight: 12,
    paddingTop: 8,
    paddingBottom: 8,
    gap: 6,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: METRONIC.border,
    borderLeftWidth: 3,
    borderLeftColor: METRONIC.link,
  },
  salesGrowRowStripe: {
    backgroundColor: "#FAFBFC",
  },
  salesGrowRowLast: {
    borderBottomWidth: 0,
  },
  salesGrowRowMain: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    minWidth: 0,
  },
  salesGrowRowHeadPressed: {
    opacity: 0.9,
  },
  salesGrowRowBody: {
    flex: 1,
    minWidth: 0,
    gap: 1,
    paddingTop: 1,
  },
  salesGrowNameRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    minWidth: 0,
  },
  salesGrowRowName: {
    flexShrink: 1,
    fontSize: 11,
    fontWeight: "700",
    color: METRONIC.text,
    lineHeight: 14,
  },
  salesGrowRoleBadge: {
    paddingHorizontal: 5,
    paddingVertical: 1,
    borderRadius: 4,
    backgroundColor: "rgba(114, 57, 234, 0.1)",
    flexShrink: 0,
  },
  salesGrowRoleBadgeText: {
    fontSize: 8,
    fontWeight: "700",
    color: "#7239EA",
    letterSpacing: 0.2,
    textTransform: "uppercase",
  },
  salesGrowMatchLine: {
    fontSize: 9,
    lineHeight: 12,
    minHeight: 12,
  },
  salesGrowMatchMuted: {
    fontWeight: "500",
    color: METRONIC.muted,
  },
  salesGrowMatchHighlight: {
    fontWeight: "600",
  },
  salesGrowRowMeta: {
    fontSize: 9,
    fontWeight: "500",
    color: METRONIC.subtle,
    lineHeight: 12,
    minHeight: 12,
  },
  salesGrowDismissIcon: {
    width: 18,
    height: 18,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 9,
    backgroundColor: "#F1F1F4",
    flexShrink: 0,
    marginTop: 1,
  },
  salesGrowActionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingLeft: 38,
  },
  salesGrowActionGhost: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
  },
  salesGrowActionGhostText: {
    fontSize: 9,
    fontWeight: "600",
    color: METRONIC.subtle,
  },
  salesGrowActionSend: {
    flex: 1,
    minHeight: 26,
    borderRadius: 6,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    paddingHorizontal: 8,
  },
  salesGrowActionSendText: {
    fontSize: 9,
    fontWeight: "700",
    color: Theme.cardWhite,
  },
  salesGrowPendingRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingLeft: 38,
    paddingRight: 2,
    minHeight: 22,
  },
  salesGrowPendingLabel: {
    fontSize: 9,
    fontWeight: "600",
    color: METRONIC.muted,
  },
  salesGrowPendingCancel: {
    fontSize: 9,
    fontWeight: "700",
    color: METRONIC.link,
  },
  salesGrowActionPressed: {
    opacity: 0.88,
  },
  salesGrowFooterBtn: {
    marginTop: 8,
    marginHorizontal: 12,
    minHeight: 28,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 10,
  },
  salesGrowFooterBtnText: {
    fontSize: 10,
    fontWeight: "600",
    color: METRONIC.subtle,
  },
  salesEmptySide: {
    fontSize: 10,
    color: METRONIC.muted,
    paddingVertical: 8,
    paddingHorizontal: 12,
    lineHeight: 14,
  },
  salesPerfViewBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 2,
  },
  salesPerfViewTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: METRONIC.text,
    letterSpacing: -0.2,
  },
  salesPerfViewSub: {
    fontSize: 11,
    fontWeight: "500",
    color: METRONIC.muted,
    marginTop: 2,
  },
  salesPerfViewToggle: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flexShrink: 0,
  },
  salesPerfViewTab: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
  },
  salesPerfViewTabOn: {
    borderColor: METRONIC.accent,
    backgroundColor: "rgba(79, 70, 229, 0.06)",
  },
  salesPerfViewTabText: {
    fontSize: 12,
    fontWeight: "600",
    color: METRONIC.subtle,
  },
  salesPerfViewTabTextOn: {
    color: METRONIC.accent,
    fontWeight: "700",
  },
  salesKpiRow: {
    width: "100%",
    ...({
      display: "grid",
      gridTemplateColumns: "repeat(4, minmax(0, 1fr))",
      gap: 12,
      alignItems: "stretch",
    } as object),
  },
  salesWidgetRowDual: {
    width: "100%",
    ...({
      display: "grid",
      gridTemplateColumns: "minmax(0, 2fr) minmax(0, 1fr)",
      gap: 12,
      alignItems: "stretch",
    } as object),
  },
  salesBarRowDual: {
    width: "100%",
    ...({
      display: "grid",
      gridTemplateColumns: "minmax(0, 1fr) minmax(0, 1fr)",
      gap: 12,
      alignItems: "stretch",
    } as object),
  },
  salesKpiCard: {
    minWidth: 0,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
    paddingHorizontal: 10,
    paddingVertical: 12,
    gap: 2,
    ...({
      boxShadow: "0 0 20px 0 rgba(76, 87, 125, 0.04)",
    } as object),
  },
  salesKpiIcon: {
    width: 28,
    height: 28,
    borderRadius: 7,
    backgroundColor: "#F9FAFB",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 2,
  },
  salesKpiValue: {
    fontSize: 18,
    fontWeight: "800",
    color: METRONIC.text,
    letterSpacing: -0.4,
  },
  salesKpiLabel: {
    fontSize: 10,
    fontWeight: "700",
    color: METRONIC.muted,
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  salesKpiSub: {
    fontSize: 10,
    fontWeight: "500",
    color: METRONIC.subtle,
    marginTop: 2,
  },
  salesWidgetRow: {
    width: "100%",
    ...({
      display: "grid",
      gridTemplateColumns: "minmax(0, 2fr) minmax(0, 1fr) minmax(0, 1fr)",
      gap: 12,
      alignItems: "stretch",
    } as object),
  },
  salesWidgetTrend: {
    minWidth: 0,
    minHeight: 196,
    overflow: "hidden",
    flexDirection: "column",
  },
  salesWidgetDonut: {
    minWidth: 0,
    minHeight: 196,
    overflow: "hidden",
    flexDirection: "column",
  },
  salesBarRow: {
    width: "100%",
    ...({
      display: "grid",
      gridTemplateColumns: "minmax(0, 1.5fr) minmax(0, 1fr) minmax(0, 1fr)",
      gap: 12,
      alignItems: "stretch",
    } as object),
  },
  salesBarRowPartner: {
    width: "100%",
  },
  salesBarLane: {
    minWidth: 0,
  },
  salesBarOrigin: {
    minWidth: 0,
    minHeight: 196,
    overflow: "hidden",
    flexDirection: "column",
  },
  salesBarDest: {
    minWidth: 0,
    minHeight: 196,
    overflow: "hidden",
    flexDirection: "column",
  },
  salesBarPartner: {
    minWidth: 0,
    minHeight: 196,
    flexDirection: "column",
  },
  salesBarRowQuad: {
    width: "100%",
    ...({
      display: "grid",
      gridTemplateColumns:
        "minmax(0, 1.2fr) minmax(0, 1.2fr) minmax(0, 1fr) minmax(0, 1fr)",
      gap: 12,
      alignItems: "stretch",
    } as object),
  },
  salesWidgetHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 2,
  },
  salesWidgetSub: {
    fontSize: 11,
    fontWeight: "500",
    color: METRONIC.muted,
    marginBottom: 6,
  },
  salesWidgetChartBody: {
    width: "100%",
    minWidth: 0,
    marginTop: 2,
    overflow: "hidden",
  },
  salesWidgetDonutBody: {
    flex: 1,
    justifyContent: "center",
    alignItems: "stretch",
    paddingTop: 6,
    paddingBottom: 8,
    minHeight: 118,
    overflow: "visible",
  },
  salesCardMenu: {
    width: 24,
    height: 24,
    alignItems: "center",
    justifyContent: "center",
  },
  salesTableCard: {
    overflow: "hidden",
  },
  salesTableScroll: {
    width: "100%",
    ...({
      overflowX: "auto",
    } as object),
  },
  salesTableGrid: {
    width: "100%",
    minWidth: 960,
    ...({
      display: "grid",
      gridTemplateColumns:
        "28px minmax(200px, 1.55fr) 108px 56px 92px 92px minmax(128px, 1fr) 76px 68px 28px",
      columnGap: 16,
      alignItems: "center",
      boxSizing: "border-box",
    } as object),
  },
  salesAssetTableGrid: {
    width: "100%",
    minWidth: 1120,
    ...({
      display: "grid",
      gridTemplateColumns:
        "28px minmax(180px, 1.4fr) 72px 52px 84px 84px 76px minmax(120px, 1fr) 68px 60px 28px",
      columnGap: 14,
      alignItems: "center",
      boxSizing: "border-box",
    } as object),
  },
  salesTripTableGrid: {
    width: "100%",
    minWidth: 1040,
    ...({
      display: "grid",
      gridTemplateColumns:
        "28px minmax(96px, 0.85fr) minmax(140px, 1.2fr) minmax(108px, 1fr) minmax(108px, 1fr) 76px 76px 76px 68px 72px 28px",
      columnGap: 14,
      alignItems: "center",
      boxSizing: "border-box",
    } as object),
  },
  salesTripTableTitleCol: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  salesTripTableSub: {
    fontSize: 11,
    fontWeight: "500",
    color: METRONIC.muted,
    lineHeight: 14,
  },
  /** Desktop hub — horizontal connection card strip (matches card minHeight). */
  connectionsCardsSection: {
    width: "100%",
    minHeight: 188,
    marginBottom: 4,
    zIndex: 1,
  },
  connectionsPartnersTable: {
    marginTop: 0,
    marginHorizontal: 0,
    width: "100%",
    alignSelf: "stretch",
    zIndex: 0,
  },
  salesColTripRef: {
    minWidth: 0,
  },
  salesColLane: {
    minWidth: 0,
  },
  salesColTripClient: {
    minWidth: 0,
  },
  salesColTripSupplier: {
    minWidth: 0,
  },
  salesColCost: {
    minWidth: 0,
  },
  salesTripRefCell: {
    minWidth: 0,
  },
  salesTripRefText: {
    fontSize: 12,
    fontWeight: "700",
    color: METRONIC.link,
    lineHeight: 16,
    ...({
      overflow: "hidden",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
    } as object),
  },
  salesTripPartyText: {
    fontSize: 12,
    fontWeight: "600",
    color: METRONIC.text,
    lineHeight: 16,
    ...({
      overflow: "hidden",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
    } as object),
  },
  salesTripStatusActive: {
    backgroundColor: "rgba(62, 151, 255, 0.12)",
  },
  salesTripStatusActiveText: {
    color: METRONIC.link,
  },
  salesTripStatusPending: {
    backgroundColor: "rgba(161, 165, 183, 0.15)",
  },
  salesTripStatusPendingText: {
    color: METRONIC.subtle,
  },
  salesColPerformance: {
    minWidth: 0,
  },
  salesColEarnings: {
    minWidth: 0,
  },
  salesAssetPerfCell: {
    gap: 2,
    minWidth: 0,
  },
  salesAssetPerfScore: {
    fontSize: 13,
    fontWeight: "800",
    color: METRONIC.text,
    lineHeight: 16,
  },
  salesAssetPerfMeta: {
    fontSize: 10,
    fontWeight: "500",
    color: METRONIC.muted,
    lineHeight: 13,
  },
  salesAssetVehicleTableGrid: {
    width: "100%",
    minWidth: 1180,
    ...({
      display: "grid",
      gridTemplateColumns:
        "28px minmax(160px, 1.25fr) 72px 48px 80px 80px 56px 64px minmax(110px, 1fr) 72px 68px 60px 28px",
      columnGap: 12,
      alignItems: "center",
      boxSizing: "border-box",
    } as object),
  },
  salesColKm: {
    minWidth: 0,
  },
  salesColUtil: {
    minWidth: 0,
  },
  salesVehicleBadge: {
    alignSelf: "flex-start",
    marginTop: 3,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    backgroundColor: "rgba(62, 151, 255, 0.1)",
  },
  salesVehicleBadgeText: {
    fontSize: 9,
    fontWeight: "700",
    color: METRONIC.link,
    letterSpacing: 0.2,
  },
  salesIntelDimList: {
    gap: 6,
    marginTop: 4,
  },
  salesIntelDimRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  salesIntelDimLabel: {
    width: 72,
    fontSize: 10,
    fontWeight: "600",
    color: METRONIC.muted,
  },
  salesIntelDimTrack: {
    flex: 1,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#EEF0F4",
    overflow: "hidden",
  },
  salesIntelDimFill: {
    height: "100%",
    borderRadius: 3,
    backgroundColor: METRONIC.link,
  },
  salesIntelDimValue: {
    width: 28,
    fontSize: 10,
    fontWeight: "700",
    color: METRONIC.text,
    textAlign: "right",
  },
  salesAssetSectionTitle: {
    fontSize: 13,
    fontWeight: "800",
    color: METRONIC.text,
    letterSpacing: -0.2,
  },
  salesAssetSectionSub: {
    fontSize: 11,
    fontWeight: "500",
    color: METRONIC.muted,
    marginTop: 2,
  },
  salesTableTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 10,
  },
  salesTableToolbar: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 16,
    paddingBottom: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: METRONIC.border,
  },
  salesTableSearch: {
    flex: 1,
    minWidth: 160,
    maxWidth: 360,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  salesTableToolbarMid: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flexShrink: 0,
  },
  salesToolbarLabel: {
    fontSize: 11,
    fontWeight: "600",
    color: METRONIC.subtle,
  },
  salesColumnsBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
    flexShrink: 0,
  },
  salesColumnsBtnText: {
    fontSize: 11,
    fontWeight: "600",
    color: METRONIC.subtle,
  },
  salesTableHead: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: METRONIC.border,
    backgroundColor: "#F9FAFB",
  },
  salesTableHeadCell: {
    fontSize: 10,
    fontWeight: "700",
    color: METRONIC.muted,
    textTransform: "uppercase",
    letterSpacing: 0.45,
  },
  salesTableRow: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    minHeight: 64,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: METRONIC.border,
  },
  salesGridNumHead: {
    ...({
      justifySelf: "end",
      textAlign: "right",
      width: "100%",
    } as object),
  },
  salesGridNumCell: {
    ...({
      justifySelf: "end",
      width: "100%",
    } as object),
  },
  salesTableRowLast: {
    borderBottomWidth: 0,
  },
  salesTableCell: {
    fontSize: 12,
    fontWeight: "500",
    color: METRONIC.text,
  },
  salesTableCellMuted: {
    fontSize: 12,
    fontWeight: "500",
    color: METRONIC.muted,
    ...({
      overflow: "hidden",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
    } as object),
  },
  salesColCheck: {
    alignItems: "flex-start",
    justifyContent: "center",
  },
  salesColPartner: {
    minWidth: 0,
  },
  salesColRating: {
    minWidth: 0,
  },
  salesColTrips: {
    minWidth: 0,
  },
  salesColRevenue: {
    minWidth: 0,
  },
  salesColMargin: {
    minWidth: 0,
  },
  salesPartnerCell: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    minWidth: 0,
  },
  salesPartnerTextCol: {
    flex: 1,
    minWidth: 0,
    gap: 1,
  },
  salesRatingCell: {
    gap: 4,
    minWidth: 0,
  },
  salesRatingTopRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    minWidth: 0,
  },
  salesRatingMeta: {
    fontSize: 11,
    fontWeight: "700",
    color: METRONIC.text,
    lineHeight: 14,
  },
  salesRatingSub: {
    fontSize: 10,
    fontWeight: "500",
    color: METRONIC.muted,
    lineHeight: 13,
  },
  salesMoneyCell: {
    gap: 3,
    minWidth: 0,
    ...({
      justifySelf: "end",
      alignItems: "flex-end",
    } as object),
  },
  salesMoneyValue: {
    fontSize: 12,
    fontWeight: "700",
    color: METRONIC.text,
    lineHeight: 16,
    ...({
      textAlign: "right",
      whiteSpace: "nowrap",
    } as object),
  },
  salesMoneyMeta: {
    fontSize: 10,
    fontWeight: "500",
    color: METRONIC.muted,
    lineHeight: 13,
    ...({
      textAlign: "right",
      whiteSpace: "nowrap",
    } as object),
  },
  salesTripsCell: {
    gap: 3,
    minWidth: 0,
    ...({
      justifySelf: "end",
      alignItems: "flex-end",
    } as object),
  },
  salesTripsSub: {
    fontSize: 10,
    fontWeight: "500",
    color: METRONIC.muted,
    lineHeight: 13,
    textAlign: "right",
  },
  salesColRegion: {
    minWidth: 0,
    paddingRight: 4,
  },
  salesLaneText: {
    fontSize: 11,
    fontWeight: "500",
    color: METRONIC.text,
    lineHeight: 15,
    ...({
      overflow: "hidden",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
    } as object),
  },
  salesColLast: {
    minWidth: 0,
  },
  salesLastActiveText: {
    fontSize: 11,
    fontWeight: "500",
    color: METRONIC.muted,
    lineHeight: 15,
    ...({
      whiteSpace: "nowrap",
    } as object),
  },
  salesColStatus: {
    minWidth: 0,
    alignItems: "flex-start",
  },
  salesColMenu: {
    alignItems: "center",
    justifyContent: "center",
  },
  salesCheckBox: {
    width: 16,
    height: 16,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: "#D1D5DB",
    backgroundColor: Theme.cardWhite,
  },
  salesPartnerName: {
    fontSize: 13,
    fontWeight: "700",
    color: METRONIC.text,
    lineHeight: 17,
    ...({
      overflow: "hidden",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
    } as object),
  },
  salesPartnerSub: {
    fontSize: 11,
    fontWeight: "500",
    color: METRONIC.muted,
    marginTop: 1,
    lineHeight: 15,
  },
  salesTripsValue: {
    fontSize: 13,
    fontWeight: "700",
    color: METRONIC.text,
    textAlign: "right",
    lineHeight: 16,
  },
  salesTableEmpty: {
    paddingVertical: 32,
    alignItems: "center",
  },
  salesStatusLive: {
    backgroundColor: "rgba(80, 205, 137, 0.15)",
  },
  salesStatusLiveText: {
    color: "#47BE7D",
  },
  salesStatusInvite: {
    backgroundColor: "rgba(62, 151, 255, 0.1)",
  },
  salesStatusInviteText: {
    color: METRONIC.link,
  },
  salesPagination: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "wrap",
    gap: 10,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: METRONIC.border,
  },
  salesPageSizeRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    flexWrap: "wrap",
  },
  salesPageSizeLabel: {
    fontSize: 11,
    fontWeight: "600",
    color: METRONIC.muted,
    marginRight: 4,
  },
  salesPageSizeBtn: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
  },
  salesPageSizeBtnOn: {
    borderColor: METRONIC.link,
    backgroundColor: "rgba(62, 151, 255, 0.08)",
  },
  salesPageSizeBtnText: {
    fontSize: 11,
    fontWeight: "600",
    color: METRONIC.subtle,
  },
  salesPageSizeBtnTextOn: {
    color: METRONIC.link,
  },
  salesPageNav: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  salesPageRange: {
    fontSize: 11,
    fontWeight: "500",
    color: METRONIC.muted,
    marginRight: 8,
  },
  salesPageBtn: {
    width: 28,
    height: 28,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: METRONIC.border,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Theme.cardWhite,
  },
  salesPageBtnDisabled: {
    opacity: 0.4,
  },
  salesPageNum: {
    minWidth: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 6,
  },
  salesPageNumOn: {
    backgroundColor: "#F1F1F4",
  },
  salesPageNumText: {
    fontSize: 11,
    fontWeight: "600",
    color: METRONIC.subtle,
  },
  salesPageNumTextOn: {
    color: METRONIC.text,
    fontWeight: "800",
  },
  growInviteBanner: {
    backgroundColor: "rgba(62, 151, 255, 0.06)",
    borderColor: "rgba(62, 151, 255, 0.18)",
  },
  growInviteBannerHead: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 4,
  },
  growInviteBannerTitle: {
    fontSize: 14,
    fontWeight: "800",
    color: METRONIC.text,
  },
  growInviteBannerSub: {
    fontSize: 11,
    fontWeight: "500",
    color: METRONIC.muted,
    marginBottom: 10,
  },
  growInviteProgressTrack: {
    height: 6,
    borderRadius: 3,
    backgroundColor: "#EEF0F4",
    overflow: "hidden",
    marginBottom: 6,
  },
  growInviteProgressFill: {
    height: "100%",
    borderRadius: 3,
    backgroundColor: METRONIC.link,
  },
  growInviteBannerMeta: {
    fontSize: 10,
    fontWeight: "600",
    color: METRONIC.subtle,
  },
  growConnectedRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: METRONIC.border,
  },
  growConnectedRowLast: {
    borderBottomWidth: 0,
  },
  growConnectedMenu: {
    width: 28,
    height: 28,
    alignItems: "center",
    justifyContent: "center",
  },
  growConnectProfileBtn: {
    marginTop: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
  },
  growConnectProfileBtnText: {
    fontSize: 12,
    fontWeight: "700",
    color: METRONIC.text,
  },
  growToolbarCard: {
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 12,
  },
  growToolbarTop: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 12,
  },
  growToolbarTitle: {
    fontSize: 15,
    fontWeight: "800",
    color: METRONIC.text,
  },
  growToolbarSub: {
    fontSize: 11,
    fontWeight: "500",
    color: METRONIC.muted,
    marginTop: 2,
  },
  growToolbarActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flexShrink: 0,
  },
  growToolbarPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
  },
  growToolbarPillText: {
    fontSize: 11,
    fontWeight: "600",
    color: METRONIC.subtle,
  },
  growToolbarFilterBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 8,
    backgroundColor: METRONIC.link,
  },
  growToolbarFilterBtnText: {
    fontSize: 11,
    fontWeight: "700",
    color: Theme.buttonPrimaryText,
  },
  growToolbarBottom: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  growViewToggle: {
    flexDirection: "row",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: METRONIC.border,
    overflow: "hidden",
    flexShrink: 0,
  },
  growViewToggleBtn: {
    width: 36,
    height: 36,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Theme.cardWhite,
  },
  growViewToggleBtnOn: {
    backgroundColor: "rgba(62, 151, 255, 0.1)",
  },
  growCardGrid: {
    width: "100%",
    ...({
      display: "grid",
      gridTemplateColumns: "repeat(4, minmax(0, 1fr))",
      gap: 12,
      alignItems: "stretch",
    } as object),
  },
  growListStack: {
    gap: 12,
  },
  growLoadMoreBtn: {
    alignSelf: "center",
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
  },
  growLoadMoreBtnText: {
    fontSize: 12,
    fontWeight: "700",
    color: METRONIC.link,
  },
  growSectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 8,
    marginBottom: 10,
  },
  growSectionTitle: {
    fontSize: 14,
    fontWeight: "800",
    color: METRONIC.text,
  },
  growSectionSub: {
    fontSize: 11,
    fontWeight: "500",
    color: METRONIC.muted,
  },
  growSentStack: {
    gap: 12,
    marginBottom: 8,
  },
  growTeamsHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 4,
  },
  growTeamsCount: {
    fontSize: 16,
    fontWeight: "600",
    color: METRONIC.text,
    letterSpacing: -0.2,
  },
  growOrgCard: {
    position: "relative",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
    paddingHorizontal: 18,
    paddingTop: 20,
    paddingBottom: 16,
    alignItems: "center",
    ...({
      boxShadow: "0 0 20px 0 rgba(76, 87, 125, 0.04)",
    } as object),
  },
  growOrgCardPressed: {
    opacity: 0.92,
  },
  growOrgCardMenuFloat: {
    position: "absolute",
    top: 10,
    right: 10,
    width: 28,
    height: 28,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2,
  },
  growOrgCardHero: {
    alignItems: "center",
    marginBottom: 12,
  },
  growOrgIconHalo: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: "#F9F9F9",
    borderWidth: 1,
    borderColor: "#EFF2F5",
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  growOrgOnlineDot: {
    position: "absolute",
    right: 2,
    bottom: 2,
    width: 10,
    height: 10,
    borderRadius: 5,
    borderWidth: 2,
    borderColor: Theme.cardWhite,
  },
  growOrgName: {
    fontSize: 15,
    fontWeight: "600",
    color: METRONIC.text,
    textAlign: "center",
    flexShrink: 1,
    letterSpacing: -0.1,
    lineHeight: 20,
    maxWidth: "100%",
    paddingHorizontal: 4,
  },
  growOrgTagline: {
    fontSize: 11,
    fontWeight: "400",
    color: METRONIC.subtle,
    textAlign: "center",
    lineHeight: 16,
    marginTop: 4,
    marginBottom: 10,
    paddingHorizontal: 6,
    maxWidth: "100%",
  },
  growOrgSectionsWrap: {
    width: "100%",
    marginBottom: 4,
  },
  growOrgSection: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    paddingVertical: 11,
    borderTopWidth: 1,
    borderTopColor: "#EEF0F4",
    ...({
      borderStyle: "dashed",
    } as object),
  },
  growOrgSectionList: {
    borderTopWidth: 0,
    paddingVertical: 0,
  },
  growOrgSectionLast: {
    paddingBottom: 2,
  },
  growOrgSectionLabel: {
    fontSize: 9,
    fontWeight: "500",
    color: METRONIC.muted,
    textTransform: "uppercase",
    letterSpacing: 0.6,
    width: 58,
    flexShrink: 0,
  },
  growOrgMembersEmpty: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 4,
  },
  growMutualMembersCol: {
    flex: 1,
    alignItems: "flex-end",
    gap: 6,
    minWidth: 0,
  },
  growMutualMembersColList: {
    alignItems: "flex-start",
    width: "100%",
  },
  growMutualMembersLoading: {
    flex: 1,
    alignItems: "flex-end",
    justifyContent: "center",
    minHeight: 28,
  },
  growMutualMemberRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 8,
    maxWidth: "100%",
    minWidth: 0,
  },
  growMutualMemberRowList: {
    justifyContent: "flex-start",
    width: "100%",
  },
  growMutualMemberRowPressed: {
    opacity: 0.88,
  },
  growMutualMemberName: {
    fontSize: 11,
    fontWeight: "500",
    color: METRONIC.subtle,
    flexShrink: 1,
    maxWidth: 120,
    textAlign: "right",
  },
  growMutualMemberNameList: {
    flex: 1,
    maxWidth: undefined,
    textAlign: "left",
  },
  growMutualMoreBtn: {
    alignSelf: "flex-end",
    paddingVertical: 2,
  },
  growMutualMoreText: {
    fontSize: 10,
    fontWeight: "500",
    color: METRONIC.muted,
  },
  growOrgSectionMuted: {
    fontSize: 10,
    fontWeight: "400",
    color: METRONIC.muted,
    flex: 1,
    textAlign: "right",
  },
  growOrgPillRow: {
    flex: 1,
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "flex-end",
    gap: 5,
  },
  growOrgSkillPill: {
    paddingHorizontal: 9,
    paddingVertical: 4,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: "#E4E6EF",
    backgroundColor: Theme.cardWhite,
  },
  growOrgSkillPillText: {
    fontSize: 10,
    fontWeight: "500",
    color: METRONIC.subtle,
  },
  growOrgFooter: {
    width: "100%",
    paddingTop: 12,
    marginTop: 2,
    borderTopWidth: 1,
    borderTopColor: METRONIC.border,
    alignItems: "center",
  },
  growOrgBtnJoin: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    paddingVertical: 9,
    paddingHorizontal: 10,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
  },
  growOrgBtnJoinCompact: {
    width: "auto",
    minWidth: 100,
    paddingHorizontal: 10,
  },
  growOrgBtnJoinText: {
    fontSize: 12,
    fontWeight: "600",
    color: METRONIC.link,
  },
  growOrgBtnJoined: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    paddingVertical: 9,
    paddingHorizontal: 10,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
  },
  growOrgBtnJoinedCompact: {
    width: "auto",
    minWidth: 100,
    paddingHorizontal: 10,
  },
  growOrgBtnJoinedText: {
    fontSize: 12,
    fontWeight: "600",
    color: METRONIC.subtle,
  },
  growOrgStatusBtn: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 6,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
    overflow: "hidden",
  },
  growOrgStatusBtnCompact: {
    width: "auto",
    minWidth: 148,
  },
  growOrgStatusBtnMain: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    paddingVertical: 9,
    paddingHorizontal: 12,
  },
  growOrgStatusBtnClose: {
    width: 36,
    alignSelf: "stretch",
    alignItems: "center",
    justifyContent: "center",
    borderLeftWidth: 1,
    borderLeftColor: METRONIC.border,
  },
  growOrgListCard: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
    paddingHorizontal: 16,
    paddingVertical: 12,
    ...({
      boxShadow: "0 0 16px 0 rgba(76, 87, 125, 0.03)",
    } as object),
  },
  growOrgListGrid: {
    width: "100%",
    ...({
      display: "grid",
      gridTemplateColumns:
        "minmax(240px, 1.75fr) 88px minmax(108px, 0.85fr) auto",
      columnGap: 24,
      alignItems: "center",
      boxSizing: "border-box",
    } as object),
  },
  growOrgListIdentity: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    minWidth: 0,
  },
  growOrgListTextCol: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  growOrgListName: {
    fontSize: 14,
    fontWeight: "600",
    color: METRONIC.text,
    letterSpacing: -0.1,
  },
  growOrgListTagline: {
    fontSize: 11,
    fontWeight: "400",
    color: METRONIC.subtle,
    lineHeight: 15,
  },
  growOrgListMeta: {
    fontSize: 10,
    fontWeight: "400",
    color: METRONIC.muted,
    marginTop: 2,
  },
  growOrgListCol: {
    minWidth: 0,
    gap: 6,
  },
  growOrgListColLabel: {
    fontSize: 9,
    fontWeight: "500",
    color: METRONIC.muted,
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  growOrgListStarsCol: {
    minWidth: 0,
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
  },
  growOrgListMutualsCol: {
    minWidth: 0,
    alignItems: "flex-start",
    justifyContent: "center",
    alignSelf: "center",
  },
  growOrgListMetricEmpty: {
    fontSize: 12,
    fontWeight: "500",
    color: METRONIC.muted,
    lineHeight: 16,
  },
  growOrgListActionCol: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    justifyContent: "flex-end",
    alignSelf: "center",
  },
  growOrgRolePill: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
  },
  growOrgRolePillText: {
    fontSize: 10,
    fontWeight: "600",
    color: METRONIC.subtle,
    letterSpacing: 0.3,
    textTransform: "uppercase",
  },
  growOrgListMenu: {
    width: 28,
    height: 28,
    alignItems: "center",
    justifyContent: "center",
  },
  growOrgBtnPendingText: {
    fontSize: 12,
    fontWeight: "600",
    color: METRONIC.subtle,
  },
  growOrgBtnPressed: {
    opacity: 0.88,
  },
  growOrgBtnDisabled: {
    opacity: 0.65,
  },
  goalsBalanceRow: {
    flexDirection: "row",
    gap: 16,
    flexWrap: "wrap",
    marginBottom: 4,
  },
  goalsBalanceCard: {
    flex: 1,
    minWidth: 280,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
    paddingHorizontal: 18,
    paddingTop: 16,
    paddingBottom: 14,
    ...({
      boxShadow: "0 0 20px 0 rgba(76, 87, 125, 0.04)",
    } as object),
  },
  goalsBalanceHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingBottom: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: METRONIC.border,
    marginBottom: 10,
  },
  goalsBalanceTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: METRONIC.text,
  },
  goalsBalanceIconRow: {
    marginBottom: 6,
  },
  goalsBalanceLabel: {
    fontSize: 11,
    fontWeight: "500",
    color: METRONIC.muted,
    marginBottom: 4,
  },
  goalsBalanceAmount: {
    fontSize: 26,
    fontWeight: "700",
    color: METRONIC.text,
    letterSpacing: -0.5,
    marginBottom: 4,
  },
  goalsBalanceSub: {
    fontSize: 11,
    fontWeight: "400",
    color: METRONIC.subtle,
    lineHeight: 15,
    marginBottom: 12,
  },
  goalsPeriodRow: {
    flexDirection: "row",
    borderWidth: 1,
    borderColor: METRONIC.border,
    borderRadius: 8,
    overflow: "hidden",
    marginBottom: 12,
  },
  goalsPeriodBtn: {
    flex: 1,
    paddingVertical: 6,
    alignItems: "center",
    backgroundColor: Theme.cardWhite,
  },
  goalsPeriodBtnOn: {
    backgroundColor: "#F1F1F4",
  },
  goalsPeriodBtnText: {
    fontSize: 10,
    fontWeight: "600",
    color: METRONIC.muted,
  },
  goalsPeriodBtnTextOn: {
    color: METRONIC.text,
  },
  goalsProgressTrack: {
    height: 6,
    borderRadius: 3,
    backgroundColor: "#F1F1F4",
    overflow: "hidden",
    marginBottom: 6,
  },
  goalsProgressFill: {
    height: "100%",
    borderRadius: 3,
  },
  goalsProgressMeta: {
    fontSize: 10,
    fontWeight: "500",
    color: METRONIC.muted,
  },
  goalsChartSub: {
    fontSize: 11,
    fontWeight: "400",
    color: METRONIC.muted,
  },
  goalsTargetGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 14,
    marginBottom: 4,
  },
  goalsTargetGridThree: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 14,
    marginBottom: 4,
  },
  goalsCarryForwardBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: "#F1FAFF",
  },
  goalsCarryForwardText: {
    flex: 1,
    fontSize: 11,
    fontWeight: "600",
    color: METRONIC.link,
    lineHeight: 15,
  },
  goalsMonthBanner: {
    marginBottom: 8,
    gap: 2,
  },
  goalsMonthBannerTitle: {
    fontSize: 13,
    fontWeight: "600",
    color: METRONIC.text,
  },
  goalsMonthBannerSub: {
    fontSize: 11,
    fontWeight: "400",
    color: METRONIC.subtle,
    lineHeight: 15,
  },
  goalsTargetCard: {
    flex: 1,
    minWidth: 280,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
    paddingHorizontal: 16,
    paddingVertical: 14,
    gap: 8,
    ...({
      boxShadow: "0 0 16px 0 rgba(76, 87, 125, 0.03)",
    } as object),
  },
  goalsTargetCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  goalsTargetCardTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: METRONIC.text,
  },
  goalsTargetCardHint: {
    fontSize: 11,
    fontWeight: "400",
    color: METRONIC.subtle,
    lineHeight: 15,
  },
  goalsTargetInner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    borderWidth: 1,
    borderColor: METRONIC.border,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 12,
    backgroundColor: "#FAFBFC",
  },
  goalsTargetValueCol: {
    flex: 1,
    minWidth: 0,
    gap: 4,
  },
  goalsTargetActual: {
    fontSize: 22,
    fontWeight: "700",
    color: METRONIC.text,
    letterSpacing: -0.3,
  },
  goalsTargetMeta: {
    fontSize: 11,
    fontWeight: "400",
    color: METRONIC.subtle,
    lineHeight: 15,
  },
  goalsTargetActionBtn: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
  },
  goalsTargetActionText: {
    fontSize: 11,
    fontWeight: "600",
    color: METRONIC.link,
  },
  goalsTargetEditCol: {
    gap: 8,
    minWidth: 120,
  },
  goalsTargetInput: {
    minWidth: 100,
    borderWidth: 1,
    borderColor: METRONIC.border,
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 7,
    fontSize: 13,
    fontWeight: "600",
    color: METRONIC.text,
    backgroundColor: Theme.cardWhite,
  },
  goalsTargetEditActions: {
    flexDirection: "row",
    gap: 6,
  },
  goalsTargetCancelBtn: {
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  goalsTargetCancelText: {
    fontSize: 10,
    fontWeight: "600",
    color: METRONIC.muted,
  },
  goalsTargetSaveBtn: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 6,
    backgroundColor: METRONIC.link,
  },
  goalsTargetSaveText: {
    fontSize: 10,
    fontWeight: "700",
    color: Theme.textOnPrimary,
  },
  goalsTargetSliderTrack: {
    height: 8,
    borderRadius: 4,
    backgroundColor: "#F1F1F4",
    position: "relative",
    overflow: "visible",
  },
  goalsTargetSliderFill: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    borderRadius: 4,
    backgroundColor: "rgba(62, 151, 255, 0.35)",
  },
  goalsTargetSliderThumb: {
    position: "absolute",
    top: -4,
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: METRONIC.link,
    marginLeft: -8,
    borderWidth: 2,
    borderColor: Theme.cardWhite,
  },
  goalsStatusPill: {
    alignSelf: "flex-start",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  goalsStatusOnTrack: {
    backgroundColor: "rgba(80, 205, 137, 0.15)",
  },
  goalsStatusOnTrackText: {
    color: "#47BE7D",
  },
  goalsStatusBehind: {
    backgroundColor: "rgba(241, 65, 108, 0.12)",
  },
  goalsStatusBehindText: {
    color: "#F1416C",
  },
  goalsStatusUnset: {
    backgroundColor: "rgba(161, 165, 183, 0.15)",
  },
  goalsStatusText: {
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.2,
  },
  goalsStatusUnsetText: {
    color: METRONIC.muted,
  },
  goalsSidebarRow: {
    paddingVertical: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: METRONIC.border,
    gap: 6,
  },
  goalsSidebarRowLast: {
    borderBottomWidth: 0,
    paddingBottom: 2,
  },
  goalsSidebarRowTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  goalsSidebarLabel: {
    fontSize: 11,
    fontWeight: "600",
    color: METRONIC.text,
  },
  goalsSidebarPct: {
    fontSize: 11,
    fontWeight: "700",
    color: METRONIC.link,
  },
  goalsSidebarTrack: {
    height: 5,
    borderRadius: 3,
    backgroundColor: "#F1F1F4",
    overflow: "hidden",
  },
  goalsSidebarFill: {
    height: "100%",
    borderRadius: 3,
    backgroundColor: METRONIC.link,
  },
  goalsSidebarMeta: {
    fontSize: 10,
    fontWeight: "500",
    color: METRONIC.muted,
  },
  goalsNetValue: {
    fontSize: 22,
    fontWeight: "700",
    color: METRONIC.text,
    marginTop: 4,
  },
  goalsNetSub: {
    fontSize: 11,
    fontWeight: "400",
    color: METRONIC.subtle,
    marginTop: 6,
    lineHeight: 16,
  },
  goalsEntityTableHead: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: METRONIC.border,
    backgroundColor: "#FAFBFC",
  },
  goalsEntityTableGrid: {
    width: "100%",
    minWidth: 640,
    ...({
      display: "grid",
      gridTemplateColumns: "minmax(180px, 1.6fr) 96px 96px 72px 36px",
      columnGap: 16,
      alignItems: "center",
      boxSizing: "border-box",
    } as object),
  },
  goalsEntityTableGridKam: {
    width: "100%",
    minWidth: 760,
    ...({
      display: "grid",
      gridTemplateColumns: "minmax(200px, 1.5fr) minmax(88px, 0.65fr) 96px 96px 72px 36px",
      columnGap: 16,
      alignItems: "center",
      boxSizing: "border-box",
    } as object),
  },
  goalsEntityHeadCell: {
    fontSize: 10,
    fontWeight: "600",
    color: METRONIC.muted,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    ...({
      whiteSpace: "nowrap",
    } as object),
  },
  goalsEntityHeadNum: {
    textAlign: "right",
    ...({
      justifySelf: "end",
      width: "100%",
    } as object),
  },
  goalsEntityColName: {
    minWidth: 0,
  },
  goalsEntityColKam: {
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    ...({
      justifySelf: "start",
      width: "100%",
    } as object),
  },
  goalsEntityColActual: {
    minWidth: 0,
    ...({
      justifySelf: "end",
      width: "100%",
    } as object),
  },
  goalsEntityColTarget: {
    minWidth: 0,
    ...({
      justifySelf: "end",
      width: "100%",
    } as object),
  },
  goalsEntityColProgress: {
    minWidth: 0,
    ...({
      justifySelf: "end",
      width: "100%",
    } as object),
  },
  goalsEntityColAction: {
    ...({
      justifySelf: "center",
    } as object),
  },
  goalsEntityRow: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: METRONIC.border,
  },
  goalsEntityName: {
    fontSize: 13,
    fontWeight: "600",
    color: METRONIC.text,
  },
  goalsEntityMeta: {
    fontSize: 11,
    fontWeight: "400",
    color: METRONIC.subtle,
  },
  goalsEntityValue: {
    fontSize: 12,
    fontWeight: "700",
    color: METRONIC.text,
    textAlign: "right",
    ...({
      whiteSpace: "nowrap",
    } as object),
  },
  goalsEntityProgressText: {
    fontSize: 12,
    fontWeight: "700",
    color: METRONIC.link,
    textAlign: "right",
    ...({
      whiteSpace: "nowrap",
    } as object),
  },
  goalsEntityEditStack: {
    gap: 6,
    width: "100%",
    alignItems: "stretch",
    ...({
      justifySelf: "end",
    } as object),
  },
  goalsEntityInput: {
    borderWidth: 1,
    borderColor: METRONIC.border,
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 6,
    fontSize: 11,
    fontWeight: "600",
    color: METRONIC.text,
    backgroundColor: Theme.cardWhite,
    textAlign: "right",
  },
  goalsEntitySaveLink: {
    fontSize: 11,
    fontWeight: "700",
    color: METRONIC.link,
  },
  goalsWizardBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.45)",
    justifyContent: "center",
    alignItems: "center",
    padding: 24,
  },
  goalsWizardSheet: {
    width: "100%",
    maxWidth: 560,
    maxHeight: "92%",
    backgroundColor: Theme.cardWhite,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: METRONIC.border,
    overflow: "hidden",
  },
  goalsWizardSheetTall: {
    maxWidth: 600,
    maxHeight: "94%",
  },
  goalsWizardHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
    paddingHorizontal: 20,
    paddingTop: 18,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: METRONIC.border,
  },
  goalsWizardHeaderText: {
    flex: 1,
    minWidth: 0,
    gap: 4,
  },
  goalsWizardTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: METRONIC.text,
  },
  goalsWizardSubtitle: {
    fontSize: 12,
    fontWeight: "500",
    color: METRONIC.muted,
  },
  goalsWizardSteps: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 20,
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: METRONIC.border,
  },
  goalsWizardStepItem: {
    alignItems: "center",
    gap: 6,
    minWidth: 72,
  },
  goalsWizardStepDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#E1E3EA",
  },
  goalsWizardStepDotOn: {
    backgroundColor: METRONIC.link,
  },
  goalsWizardStepLabel: {
    fontSize: 10,
    fontWeight: "600",
    color: METRONIC.muted,
  },
  goalsWizardStepLabelOn: {
    color: METRONIC.link,
    fontWeight: "700",
  },
  goalsWizardBody: {
    flex: 1,
    minHeight: 0,
  },
  goalsWizardBodyContent: {
    padding: 20,
    gap: 4,
  },
  goalsWizardHero: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    marginBottom: 12,
  },
  goalsWizardHeroIcon: {
    width: 48,
    height: 48,
    borderRadius: 10,
    backgroundColor: "#F1FAFF",
    alignItems: "center",
    justifyContent: "center",
  },
  goalsWizardHeroName: {
    fontSize: 15,
    fontWeight: "800",
    color: METRONIC.text,
  },
  goalsWizardHeroMeta: {
    fontSize: 11,
    fontWeight: "500",
    color: METRONIC.muted,
    marginTop: 2,
  },
  goalsWizardDetailGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    marginBottom: 14,
  },
  goalsWizardDetailCell: {
    minWidth: "45%",
    flexGrow: 1,
    gap: 2,
  },
  goalsWizardDetailWide: {
    minWidth: "100%",
  },
  goalsWizardDetailLabel: {
    fontSize: 10,
    fontWeight: "700",
    color: METRONIC.muted,
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  goalsWizardDetailValue: {
    fontSize: 12,
    fontWeight: "600",
    color: METRONIC.text,
    lineHeight: 17,
  },
  goalsWizardKpiRow: {
    flexDirection: "row",
    gap: 10,
  },
  goalsWizardKpi: {
    flex: 1,
    minWidth: 0,
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: "#F9F9F9",
    gap: 4,
  },
  goalsWizardKpiValue: {
    fontSize: 14,
    fontWeight: "800",
    color: METRONIC.text,
  },
  goalsWizardKpiLabel: {
    fontSize: 10,
    fontWeight: "600",
    color: METRONIC.muted,
  },
  goalsWizardSectionTitle: {
    fontSize: 12,
    fontWeight: "800",
    color: METRONIC.text,
    marginTop: 8,
    marginBottom: 10,
  },
  goalsWizardHistoryHead: {
    flexDirection: "row",
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: METRONIC.border,
  },
  goalsWizardHistoryHeadCell: {
    fontSize: 9,
    fontWeight: "700",
    color: METRONIC.muted,
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  goalsWizardHistoryRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: METRONIC.border,
  },
  goalsWizardHistoryCell: {
    fontSize: 11,
    fontWeight: "600",
    color: METRONIC.text,
  },
  goalsWizardHistoryMonth: {
    flex: 1.1,
    minWidth: 0,
  },
  goalsWizardHistoryNum: {
    flex: 1.3,
    minWidth: 0,
    textAlign: "right",
    paddingHorizontal: 4,
  },
  goalsWizardHistoryPct: {
    width: 40,
    textAlign: "right",
    color: METRONIC.link,
    fontWeight: "800",
  },
  goalsWizardEmpty: {
    fontSize: 12,
    fontWeight: "500",
    color: METRONIC.muted,
    lineHeight: 18,
    paddingVertical: 12,
  },
  goalsWizardRecommendCard: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(62, 151, 255, 0.35)",
    backgroundColor: "#F1FAFF",
    padding: 14,
    gap: 8,
    marginBottom: 12,
  },
  goalsWizardRecommendHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  goalsWizardRecommendTitle: {
    fontSize: 12,
    fontWeight: "800",
    color: METRONIC.text,
  },
  goalsWizardRecommendAmount: {
    fontSize: 18,
    fontWeight: "800",
    color: METRONIC.link,
  },
  goalsWizardRecommendBody: {
    fontSize: 11,
    fontWeight: "500",
    color: METRONIC.subtle,
    lineHeight: 16,
  },
  goalsWizardOptionBtn: {
    alignSelf: "flex-start",
    marginTop: 4,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: METRONIC.link,
    backgroundColor: Theme.cardWhite,
  },
  goalsWizardOptionBtnOn: {
    backgroundColor: METRONIC.link,
  },
  goalsWizardOptionBtnText: {
    fontSize: 11,
    fontWeight: "700",
    color: METRONIC.link,
  },
  goalsWizardOptionBtnTextOn: {
    color: Theme.buttonPrimaryText,
  },
  goalsWizardCarryCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    padding: 14,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
    marginBottom: 14,
  },
  goalsWizardCarryCardOn: {
    borderColor: METRONIC.link,
    backgroundColor: "#F1FAFF",
  },
  goalsWizardCarryTitle: {
    fontSize: 12,
    fontWeight: "700",
    color: METRONIC.text,
  },
  goalsWizardCarrySub: {
    fontSize: 11,
    fontWeight: "600",
    color: METRONIC.link,
    marginTop: 2,
  },
  goalsWizardFieldLabel: {
    fontSize: 10,
    fontWeight: "700",
    color: METRONIC.muted,
    marginTop: 8,
    marginBottom: 6,
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  goalsWizardInput: {
    borderWidth: 1,
    borderColor: METRONIC.border,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    fontWeight: "600",
    color: METRONIC.text,
    backgroundColor: "#F9F9F9",
  },
  goalsWizardFooter: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 4,
    borderTopWidth: 1,
    borderTopColor: METRONIC.border,
  },
  goalsWizardFooterActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginLeft: "auto",
  },
  goalsWizardBackBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingVertical: 8,
  },
  goalsWizardBackBtnText: {
    fontSize: 12,
    fontWeight: "700",
    color: METRONIC.text,
  },
  goalsWizardCancelBtn: {
    paddingHorizontal: 10,
    paddingVertical: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: METRONIC.border,
  },
  goalsWizardCancelText: {
    fontSize: 12,
    fontWeight: "700",
    color: METRONIC.text,
  },
  goalsWizardPrimaryBtn: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 8,
    backgroundColor: "rgba(0, 0, 0, 0.85)",
    minWidth: 108,
    alignItems: "center",
  },
  goalsWizardPrimaryText: {
    fontSize: 12,
    fontWeight: "800",
    color: Theme.textOnPrimary,
  },
  goalsViewMore: {
    alignItems: "center",
    paddingVertical: 14,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: METRONIC.border,
  },
  goalsViewMoreText: {
    fontSize: 12,
    fontWeight: "600",
    color: METRONIC.link,
    ...({
      textDecorationLine: "underline",
      textDecorationStyle: "dashed",
    } as object),
  },
  teamPanelTitleCol: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  teamPanelCard: {
    overflow: "hidden",
    paddingTop: 4,
  },
  teamInviteBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 10,
    paddingVertical: 9,
    borderRadius: 8,
    backgroundColor: METRONIC.accent,
    flexShrink: 0,
  },
  teamInviteBtnText: {
    fontSize: 12,
    fontWeight: "700",
    color: Theme.buttonPrimaryText,
  },
  teamInviteCancelBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
    flexShrink: 0,
  },
  teamInviteCancelBtnText: {
    fontSize: 12,
    fontWeight: "600",
    color: METRONIC.text,
  },
  invitationsPanelCard: {
    overflow: "hidden",
    paddingBottom: 0,
  },
  invitationsPanelHead: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
    paddingHorizontal: 20,
    paddingTop: 18,
    paddingBottom: 4,
  },
  invitationsPanelTitleCol: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  invitationsCloseBtn: {
    width: 32,
    height: 32,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
  },
  tabActionBtnInvitesOn: {
    backgroundColor: METRONIC.accent,
    borderColor: METRONIC.accent,
  },
  tabActionBtnTextInvitesOn: {
    color: Theme.buttonDarkText,
  },
  profileSplitRow: {
    flexDirection: "row",
    gap: 16,
    alignItems: "flex-start",
    ...({
      flexWrap: "wrap",
    } as object),
  },
  profileCol: {
    flex: 1,
    minWidth: 280,
    gap: 12,
  },
  profileCardTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: METRONIC.text,
  },
  profileCardSub: {
    fontSize: 12,
    fontWeight: "500",
    color: METRONIC.muted,
    marginTop: 2,
    marginBottom: 14,
  },
  profileAvatarRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    marginBottom: 16,
  },
  profileAvatarRing: {
    width: 72,
    height: 72,
    borderRadius: 36,
    borderWidth: 2,
    borderColor: METRONIC.link,
    backgroundColor: Theme.cardWhite,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  profileAvatarImage: {
    width: 66,
    height: 66,
    borderRadius: 33,
  },
  profileAvatarActions: {
    flex: 1,
    minWidth: 0,
    gap: 8,
  },
  profileActionBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    alignSelf: "flex-start",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
  },
  profileActionBtnText: {
    fontSize: 12,
    fontWeight: "600",
    color: METRONIC.link,
  },
  profileFieldGroup: {
    gap: 6,
    marginBottom: 14,
  },
  profileFieldLabel: {
    fontSize: 11,
    fontWeight: "700",
    color: METRONIC.muted,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  profileFieldInput: {
    borderWidth: 1,
    borderColor: METRONIC.border,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    fontWeight: "500",
    color: METRONIC.text,
    backgroundColor: Theme.cardWhite,
  },
  profileFieldReadonly: {
    borderWidth: 1,
    borderColor: METRONIC.border,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: "#F9FAFB",
  },
  profileFieldReadonlyText: {
    fontSize: 14,
    fontWeight: "500",
    color: METRONIC.subtle,
  },
  profileSaveBtn: {
    alignSelf: "flex-start",
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 8,
    backgroundColor: METRONIC.link,
    minWidth: 120,
    alignItems: "center",
  },
  profileSaveBtnDisabled: {
    opacity: 0.5,
  },
  profileSaveBtnText: {
    fontSize: 13,
    fontWeight: "700",
    color: Theme.buttonPrimaryText,
  },
  profilePresetGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 8,
  },
  profilePresetItem: {
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: 2,
    borderColor: "transparent",
    overflow: "hidden",
  },
  profilePresetItemSelected: {
    borderColor: METRONIC.link,
  },
  profilePresetImage: {
    width: 40,
    height: 40,
    borderRadius: 20,
  },
  profileLogoRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    marginBottom: 16,
  },
  profileLogoThumb: {
    width: 72,
    height: 72,
    borderRadius: 12,
    backgroundColor: "#F3F6F9",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    borderWidth: 1,
    borderColor: METRONIC.border,
  },
  profileLogoImage: {
    width: 72,
    height: 72,
    borderRadius: 12,
  },
  profileLogoInitials: {
    fontSize: 20,
    fontWeight: "800",
    color: METRONIC.subtle,
  },
  profileErrorText: {
    fontSize: 12,
    fontWeight: "600",
    color: Theme.negative,
    marginBottom: 8,
  },
});
