import Theme from "@/constants/Theme";
import { column, createStyles, image, text, view, webView, type ColumnStyle } from "@/lib/styles/createStyles";
import { Platform, StyleSheet, type TextStyle, type ViewStyle } from "react-native";

export const METRONIC = {
  border: "#EFF2F5",
  muted: "#A1A5B7",
  text: "#181C32",
  subtle: "#78829D",
  accent: Theme.primary,
  heroBg: "#FFFFFF",
  heroHex: "#E1E3EA",
  bodyBg: "#F5F8FA",
  link: "#3E97FF",
  heroRing: "#50CD89",
} as const;

/** KeenThemes-style hex tile pattern (web). */
const HEX_PATTERN_SVG = `<svg xmlns="http://www.w3.org/2000/svg" width="56" height="100" viewBox="0 0 56 100"><path d="M28 0 L56 16 V48 L28 64 L0 48 V16 Z" fill="none" stroke="${METRONIC.heroHex}" stroke-width="1" opacity="0.45"/><path d="M28 36 L56 52 V84 L28 100 L0 84 V52 Z" fill="none" stroke="${METRONIC.heroHex}" stroke-width="1" opacity="0.3"/></svg>`;
export const METRONIC_HEX_BACKGROUND = {
  backgroundImage: `url("data:image/svg+xml,${encodeURIComponent(HEX_PATTERN_SVG)}")`,
  backgroundSize: "56px 100px",
} as ViewStyle;

const networkDesktopHubStylesDef = {
  root: view({
    flex: 1,
    backgroundColor: METRONIC.bodyBg,
  }),
  scrollContent: view({
    paddingBottom: 24,
  }),
  hero: view({
    backgroundColor: METRONIC.heroBg,
    borderBottomWidth: 1,
    borderBottomColor: METRONIC.border,
    paddingTop: 16,
    paddingBottom: 14,
    paddingHorizontal: 16,
    position: "relative",
    overflow: "hidden",
    ...METRONIC_HEX_BACKGROUND,
  }),
  heroBackCorner: view({
    position: "absolute",
    top: 0,
    left: 0,
    zIndex: 2,
    width: 34,
    height: 34,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: "rgba(255, 255, 255, 0.92)",
    ...({
      boxShadow: "0 2px 10px rgba(24, 28, 50, 0.06)",
      cursor: "pointer",
    } as unknown as ViewStyle),
  }),
  heroHexOverlay: view({
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    ...Platform.select({
      web: {
        backgroundImage:
          "radial-gradient(ellipse 80% 60% at 50% 0%, rgba(255,255,255,0.92) 0%, rgba(255,255,255,0.55) 55%, rgba(255,255,255,0.2) 100%)",
      },
      default: {
        backgroundColor: "rgba(255, 255, 255, 0.72)",
      },
    }),
  }),
  heroInner: view({
    width: "100%",
    zIndex: 1,
    position: "relative",
    alignItems: "center",
  }),
  heroCenter: view({
    width: "100%",
    alignItems: "center",
    gap: 6,
    paddingTop: 20,
  }),
  heroWelcomeCorner: view({
    position: "absolute",
    top: 0,
    right: 0,
    zIndex: 2,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: "rgba(255, 255, 255, 0.92)",
    ...({
      boxShadow: "0 2px 10px rgba(24, 28, 50, 0.06)",
      cursor: "pointer",
    } as unknown as ViewStyle),
  }),
  heroWelcomeTextWrap: view({
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  }),
  heroWelcomeText: text({
    fontSize: 11,
    fontWeight: "600",
    color: METRONIC.subtle,
  }),
  heroWelcomeName: text({
    fontWeight: "700",
    color: METRONIC.text,
  }),
  heroUserRingSm: view({
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: METRONIC.link,
    backgroundColor: Theme.cardWhite,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  }),
  heroUserImageSm: image({
    width: 24,
    height: 24,
    borderRadius: 12,
  }),
  heroAvatarPressable: view({
    position: "relative",
    marginTop: 4,
  }),
  heroAvatarRing: view({
    width: 68,
    height: 68,
    borderRadius: 34,
    borderWidth: 2,
    borderColor: METRONIC.heroRing,
    backgroundColor: Theme.cardWhite,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    ...({
      boxShadow: "0 4px 12px rgba(24, 28, 50, 0.08)",
    } as unknown as ViewStyle),
  }),
  heroAvatarImage: image({
    width: 62,
    height: 62,
    borderRadius: 31,
  }),
  heroCameraBadge: view({
    position: "absolute",
    right: 0,
    bottom: 0,
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: METRONIC.text,
    borderWidth: 2,
    borderColor: Theme.cardWhite,
    alignItems: "center",
    justifyContent: "center",
  }),
  heroMetaRow: view({
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    marginTop: 2,
  }),
  heroMetaItem: view({
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  }),
  heroMetaText: text({
    fontSize: 11,
    fontWeight: "500",
    color: METRONIC.subtle,
  }),
  heroStatsRow: view({
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    marginTop: 2,
    paddingHorizontal: 8,
  }),
  heroStatChip: text({
    fontSize: 11,
    color: METRONIC.subtle,
  }),
  heroStatValue: text({
    fontWeight: "700",
    color: METRONIC.text,
  }),
  heroStatLabel: text({
    fontWeight: "500",
    color: METRONIC.muted,
  }),
  heroStatDivider: text({
    fontSize: 11,
    color: METRONIC.muted,
    fontWeight: "600",
  }),
  heroLogoHint: text({
    fontSize: 10,
    fontWeight: "500",
    color: METRONIC.muted,
    marginTop: 1,
  }),
  heroNameRow: view({
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
    marginTop: 2,
  }),
  heroName: text({
    fontSize: 17,
    fontWeight: "700",
    color: METRONIC.text,
    letterSpacing: -0.3,
  }),
  tabBar: view({
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
    borderBottomWidth: 1,
    borderBottomColor: METRONIC.border,
    paddingHorizontal: 16,
    paddingTop: 0,
    backgroundColor: Theme.cardWhite,
    minHeight: 42,
  }),
  tabScroll: view({
    flexGrow: 0,
    flexShrink: 1,
  }),
  tabScrollContent: view({
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 0,
  }),
  tabBtn: view({
    paddingHorizontal: 11,
    paddingVertical: 10,
    borderRadius: 0,
    borderWidth: 0,
    borderBottomWidth: 2,
    borderBottomColor: "transparent",
    backgroundColor: "transparent",
    marginBottom: -1,
  }),
  tabBtnActive: view({
    borderBottomColor: METRONIC.accent,
    backgroundColor: "transparent",
  }),
  tabText: text({
    fontSize: 12,
    fontWeight: "500",
    color: METRONIC.muted,
    letterSpacing: 0,
  }),
  tabTextActive: text({
    color: METRONIC.text,
    fontWeight: "700",
  }),
  tabActions: view({
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flexShrink: 0,
  }),
  tabActionBtn: view({
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
  }),
  tabActionBtnPrimary: view({
    backgroundColor: "#78829D",
    borderColor: "#78829D",
  }),
  tabActionBtnText: text({
    fontSize: 11,
    fontWeight: "700",
    color: METRONIC.text,
  }),
  tabActionBtnTextOn: text({
    color: Theme.buttonDarkText,
  }),
  tabActionIconBtn: view({
    width: 36,
    height: 36,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: METRONIC.border,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Theme.cardWhite,
  }),
  panel: view({
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 16,
    gap: 12,
    backgroundColor: Theme.cardWhite,
    borderBottomWidth: 1,
    borderBottomColor: METRONIC.border,
  }),
  detailsBody: view({
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 16,
    gap: 12,
    backgroundColor: Theme.cardWhite,
    borderBottomWidth: 1,
    borderBottomColor: METRONIC.border,
  }),
  statsBar: view({
    flexDirection: "row",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
    overflow: "hidden",
    ...({
      boxShadow: "0 0 10px 0 rgba(76, 87, 125, 0.04)",
    } as unknown as ViewStyle),
  }),
  statCell: view({
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    gap: 3,
    borderRightWidth: 1,
    borderRightColor: METRONIC.border,
  }),
  statCellLast: view({
    borderRightWidth: 0,
  }),
  statValue: text({
    fontSize: 16,
    fontWeight: "700",
    color: METRONIC.text,
    letterSpacing: -0.3,
  }),
  statLabel: text({
    fontSize: 9,
    fontWeight: "600",
    color: METRONIC.muted,
    textTransform: "uppercase",
    letterSpacing: 0.4,
  }),
  splitRow: view({
    flexDirection: "row",
    gap: 12,
    alignItems: "flex-start",
    flexWrap: "wrap",
  }),
  sidebar: view({
    width: "28%",
    minWidth: 220,
    maxWidth: 300,
    gap: 10,
    flexShrink: 0,
  }),
  mainCol: view({
    flex: 1,
    minWidth: 260,
    gap: 10,
    ...({
      display: "flex",
      flexDirection: "column",
    } as unknown as ViewStyle),
  }),
  card: view({
    borderRadius: 10,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
    padding: 14,
    gap: 8,
    ...({
      boxShadow: "0 0 10px 0 rgba(76, 87, 125, 0.03)",
    } as unknown as ViewStyle),
  }),
  cardTitle: text({
    fontSize: 13,
    fontWeight: "700",
    color: METRONIC.text,
    marginBottom: 2,
  }),
  cardTitleInline: text({
    marginBottom: 0,
    flex: 1,
    minWidth: 0,
  }),
  salesCardTitle: text({
    fontSize: 15,
    fontWeight: "700",
    color: METRONIC.text,
    marginBottom: 0,
  }),
  kvRow: view({
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 10,
    paddingVertical: 7,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: METRONIC.border,
  }),
  kvRowLast: view({
    borderBottomWidth: 0,
    paddingBottom: 0,
  }),
  kvLabel: text({
    fontSize: 11,
    fontWeight: "500",
    color: METRONIC.muted,
    flexShrink: 0,
  }),
  kvValue: text({
    fontSize: 11,
    fontWeight: "600",
    color: METRONIC.text,
    flex: 1,
    textAlign: "right",
  }),
  kvValueLink: text({
    color: METRONIC.link,
  }),
  aboutBody: text({
    fontSize: 12,
    lineHeight: 18,
    fontWeight: "400",
    color: METRONIC.subtle,
  }),
  sectionHeading: text({
    fontSize: 12,
    fontWeight: "700",
    color: METRONIC.text,
    marginTop: 1,
  }),
  sectionHeadingSpaced: text({
    marginTop: 12,
  }),
  subscribedPill: view({
    alignSelf: "flex-end",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 6,
    backgroundColor: "rgba(80, 205, 137, 0.15)",
  }),
  subscribedPillText: text({
    fontSize: 10,
    fontWeight: "700",
    color: "#47BE7D",
    textTransform: "uppercase",
    letterSpacing: 0.3,
  }),
  headquarterRow: view({
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    marginTop: 6,
    alignItems: "stretch",
  }),
  mapFrame: view({
    flex: 1,
    minWidth: 200,
    minHeight: 160,
    height: 160,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: "#F3F6F9",
    overflow: "hidden",
    position: "relative",
  }),
  mapStaticImage: image({
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: "100%",
    height: "100%",
  }),
  mapPlaceholder: view({
    flex: 1,
    minWidth: 200,
    minHeight: 140,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: "#F3F6F9",
    alignItems: "center",
    justifyContent: "center",
    padding: 16,
    position: "relative",
  }),
  mapPlaceholderLoading: view({
    justifyContent: "center",
  }),
  mapPinBubble: view({
    position: "absolute",
    top: 12,
    left: 12,
    right: 12,
    zIndex: 2,
    backgroundColor: Theme.cardWhite,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: METRONIC.border,
    paddingHorizontal: 10,
    paddingVertical: 8,
    gap: 2,
    ...({
      boxShadow: "0 4px 12px rgba(24, 28, 50, 0.08)",
    } as unknown as ViewStyle),
  }),
  mapPinBubbleText: text({
    fontSize: 11,
    fontWeight: "700",
    color: METRONIC.text,
    lineHeight: 15,
  }),
  mapPinBubbleSub: text({
    fontSize: 10,
    fontWeight: "500",
    color: METRONIC.muted,
    lineHeight: 14,
  }),
  contactList: view({
    flex: 1,
    minWidth: 180,
    gap: 9,
    justifyContent: "center",
    paddingVertical: 2,
  }),
  networkLinkRow: view({
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    minWidth: 0,
  }),
  networkLinkText: text({
    flex: 1,
    fontSize: 11,
    fontWeight: "500",
    color: METRONIC.text,
    minWidth: 0,
  }),
  openJobRow: view({
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    paddingVertical: 8,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: METRONIC.border,
  }),
  openJobRowLast: view({
    borderBottomWidth: 0,
  }),
  openJobIcon: view({
    width: 30,
    height: 30,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: "#F9FAFB",
    alignItems: "center",
    justifyContent: "center",
  }),
  openJobTextCol: view({
    flex: 1,
    minWidth: 0,
    gap: 1,
  }),
  openJobCategory: text({
    fontSize: 10,
    fontWeight: "600",
    color: METRONIC.link,
  }),
  openJobTitle: text({
    fontSize: 11,
    fontWeight: "700",
    color: METRONIC.text,
  }),
  openJobMeta: text({
    fontSize: 10,
    fontWeight: "500",
    color: METRONIC.muted,
    marginTop: 1,
  }),
  cardFooterLink: view({
    alignItems: "center",
    paddingTop: 8,
  }),
  cardFooterLinkText: text({
    fontSize: 12,
    fontWeight: "600",
    color: METRONIC.link,
    ...({
      textDecorationLine: "underline",
      textDecorationStyle: "dotted",
    } as unknown as TextStyle),
  }),
  tagWrap: view({
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
  }),
  tagPill: view({
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 5,
    backgroundColor: "#F1F1F4",
  }),
  tagPillText: text({
    fontSize: 10,
    fontWeight: "600",
    color: METRONIC.subtle,
  }),
  productPill: view({
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: 5,
    backgroundColor: "#F1F1F4",
  }),
  productPillText: text({
    fontSize: 11,
    fontWeight: "600",
    color: METRONIC.text,
  }),
  cardHeaderRow: view({
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    marginBottom: 2,
  }),
  cardEditBtn: view({
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: "#F9FAFB",
  }),
  cardEditBtnText: text({
    fontSize: 10,
    fontWeight: "600",
    color: METRONIC.muted,
  }),
  offerLocationBtn: view({
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: "#50CD89",
  }),
  offerLocationBtnText: text({
    fontSize: 11,
    fontWeight: "700",
    color: Theme.buttonPrimaryText,
  }),
  locationsGrid: view({
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    paddingTop: 8,
    alignItems: "stretch",
  }),
  locationCard: webView({
    flexGrow: 1,
    flexShrink: 0,
    flexBasis: "calc(25% - 9px)",
    minWidth: 140,
    maxWidth: "calc(25% - 9px)",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
    overflow: "hidden",
    paddingBottom: 8,
  }),
  locationCardPressable: view({
    flex: 1,
  }),
  locationsEmpty: view({
    paddingVertical: 20,
    alignItems: "center",
    gap: 8,
  }),
  locationsEmptyText: text({
    fontSize: 12,
    fontWeight: "500",
    color: METRONIC.muted,
    textAlign: "center",
    lineHeight: 18,
  }),
  locationImage: view({
    height: 80,
    alignItems: "center",
    justifyContent: "center",
  }),
  locationTitle: text({
    fontSize: 13,
    fontWeight: "700",
    color: METRONIC.text,
    paddingHorizontal: 10,
    paddingTop: 12,
  }),
  locationAddress: text({
    fontSize: 11,
    fontWeight: "500",
    color: METRONIC.muted,
    lineHeight: 16,
    paddingHorizontal: 10,
    paddingBottom: 4,
  }),
  locationLinkHint: text({
    fontSize: 10,
    fontWeight: "700",
    color: METRONIC.link,
    paddingHorizontal: 10,
    paddingTop: 6,
  }),
  projectsTableHead: view({
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    paddingHorizontal: 4,
    borderBottomWidth: 1,
    borderBottomColor: METRONIC.border,
    marginTop: 4,
  }),
  projectsHeadCell: text({
    fontSize: 10,
    fontWeight: "700",
    color: METRONIC.muted,
    textTransform: "uppercase",
    letterSpacing: 0.45,
  }),
  projectsRow: view({
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 10,
    paddingHorizontal: 4,
    minHeight: 42,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: METRONIC.border,
  }),
  projectsRowLast: view({
    borderBottomWidth: 0,
  }),
  projectsCell: text({
    fontSize: 13,
    fontWeight: "600",
    color: METRONIC.text,
  }),
  projectsCellMuted: text({
    fontSize: 12,
    fontWeight: "500",
    color: METRONIC.muted,
  }),
  projectsColName: text({
    flex: 2.4,
    minWidth: 0,
    paddingRight: 16,
  }),
  projectsColProgress: column({
    flex: 1.5,
    minWidth: 72,
    maxWidth: 140,
  }),
  projectsColPeople: column({
    flex: 1.1,
    minWidth: 96,
    paddingRight: 8,
  }),
  projectsColDue: text({
    flex: 0.8,
    minWidth: 64,
  }),
  projectsColMenu: view({
    width: 24,
    alignItems: "center",
  }),
  progressTrackWrap: view({
    paddingRight: 8,
  }),
  progressTrack: view({
    height: 6,
    borderRadius: 3,
    backgroundColor: "#F1F1F4",
    overflow: "hidden",
  }),
  progressFill: view({
    height: "100%",
    borderRadius: 3,
    backgroundColor: METRONIC.link,
  }),
  peopleMoreFill: view({
    backgroundColor: "#50CD89",
    borderColor: Theme.cardWhite,
    alignItems: "center",
    justifyContent: "center",
  }),
  peopleMoreText: text({
    fontSize: 9,
    fontWeight: "800",
    color: Theme.textOnPrimary,
    letterSpacing: -0.2,
  }),
  projectsPeopleEmpty: text({
    fontSize: 12,
    fontWeight: "500",
    color: METRONIC.muted,
  }),
  cardTitleRow: view({
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  }),
  autoRefreshPill: view({
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: "#F9FAFB",
  }),
  autoRefreshText: text({
    fontSize: 10,
    fontWeight: "600",
    color: METRONIC.muted,
  }),
  activityCard: view({
    borderRadius: 12,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
    padding: 14,
    gap: 12,
    ...({
      boxShadow: "0 0 20px 0 rgba(76, 87, 125, 0.04)",
    } as unknown as ViewStyle),
  }),
  activityList: view({
    gap: 0,
    paddingTop: 4,
  }),
  activityItem: view({
    flexDirection: "row",
    gap: 14,
    paddingTop: 2,
  }),
  activityRail: view({
    width: 28,
    alignItems: "center",
  }),
  activityDot: view({
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: "#F9FAFB",
    alignItems: "center",
    justifyContent: "center",
  }),
  activityLine: view({
    flex: 1,
    width: 1,
    backgroundColor: METRONIC.border,
    marginTop: 6,
    minHeight: 28,
  }),
  activityBody: view({
    flex: 1,
    minWidth: 0,
    paddingBottom: 20,
    gap: 5,
  }),
  activityBodyLast: view({
    paddingBottom: 4,
  }),
  activityTitle: text({
    fontSize: 13,
    fontWeight: "600",
    color: METRONIC.text,
    lineHeight: 20,
  }),
  activityMeta: text({
    fontSize: 11,
    fontWeight: "500",
    color: METRONIC.muted,
  }),
  activityNestedCard: view({
    marginTop: 10,
    padding: 14,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: "#F9FAFB",
    gap: 6,
  }),
  activityNestedTitle: text({
    fontSize: 13,
    fontWeight: "700",
    color: METRONIC.text,
  }),
  activityNestedBody: text({
    fontSize: 12,
    fontWeight: "400",
    color: METRONIC.subtle,
    lineHeight: 18,
  }),
  sectionToolbar: view({
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 4,
  }),
  sectionTitle: text({
    fontSize: 16,
    fontWeight: "700",
    color: METRONIC.text,
  }),
  sectionSub: text({
    fontSize: 12,
    fontWeight: "500",
    color: METRONIC.muted,
    marginTop: 2,
  }),
  filterRow: view({
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
  }),
  filterPill: view({
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
  }),
  filterPillOn: view({
    borderColor: METRONIC.accent,
    backgroundColor: "rgba(79, 70, 229, 0.06)",
  }),
  filterPillText: text({
    fontSize: 11,
    fontWeight: "600",
    color: METRONIC.subtle,
  }),
  filterPillTextOn: text({
    color: METRONIC.accent,
  }),
  searchBox: view({
    flex: 1,
    minWidth: 180,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
    paddingHorizontal: 12,
    paddingVertical: 8,
  }),
  searchInput: text({
    flex: 1,
    fontSize: 12,
    fontWeight: "500",
    color: METRONIC.text,
    padding: 0,
    minWidth: 0,
  }),
  hiddenDataBridge: view({
    height: 0,
    overflow: "hidden",
    opacity: 0,
  }),
  tableHead: view({
    flexDirection: "row",
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: METRONIC.border,
    backgroundColor: "#F9FAFB",
  }),
  tableHeadText: text({
    flex: 1,
    fontSize: 10,
    fontWeight: "700",
    color: METRONIC.muted,
    textTransform: "uppercase",
    letterSpacing: 0.4,
  }),
  tableRow: view({
    flexDirection: "row",
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: METRONIC.border,
    alignItems: "center",
  }),
  tableCell: text({
    flex: 1,
    fontSize: 12,
    fontWeight: "500",
    color: METRONIC.text,
    minWidth: 0,
  }),
  statusPill: view({
    alignSelf: "flex-start",
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 5,
    backgroundColor: "rgba(79, 70, 229, 0.1)",
  }),
  statusPillText: text({
    fontSize: 10,
    fontWeight: "700",
    color: METRONIC.accent,
    textTransform: "uppercase",
  }),
  emptyWrap: view({
    paddingVertical: 48,
    alignItems: "center",
    gap: 8,
  }),
  emptyText: text({
    fontSize: 13,
    fontWeight: "500",
    color: METRONIC.muted,
  }),
  salesBody: view({
    paddingHorizontal: 24,
    paddingTop: 16,
    paddingBottom: 24,
    backgroundColor: Theme.cardWhite,
    borderBottomWidth: 1,
    borderBottomColor: METRONIC.border,
  }),
  salesCard: view({
    borderRadius: 12,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
    ...({
      boxShadow: "0 0 20px 0 rgba(76, 87, 125, 0.04)",
    } as unknown as ViewStyle),
  }),
  salesCardPad: view({
    padding: 16,
  }),
  salesCardPadTight: view({
    paddingHorizontal: 10,
    paddingTop: 12,
    paddingBottom: 10,
  }),
  salesFilterHint: text({
    fontSize: 11,
    fontWeight: "500",
    color: METRONIC.muted,
    marginTop: -4,
    marginBottom: 8,
  }),
  salesFilterGroup: text({
    fontSize: 11,
    fontWeight: "700",
    color: METRONIC.muted,
    textTransform: "uppercase",
    letterSpacing: 0.4,
    marginTop: 10,
    marginBottom: 6,
  }),
  salesFilterChip: view({
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 6,
    backgroundColor: "#F1F1F4",
    borderWidth: 1,
    borderColor: "transparent",
  }),
  salesFilterChipOn: view({
    backgroundColor: "rgba(62, 151, 255, 0.12)",
    borderColor: "rgba(62, 151, 255, 0.35)",
  }),
  salesFilterChipText: text({
    fontSize: 11,
    fontWeight: "600",
    color: METRONIC.subtle,
  }),
  salesFilterChipTextOn: text({
    color: METRONIC.link,
    fontWeight: "700",
  }),
  salesSidebarToggleRow: view({
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 16,
    paddingTop: 14,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: METRONIC.border,
  }),
  salesSidebarToggleLabel: text({
    fontSize: 12,
    fontWeight: "600",
    color: METRONIC.text,
    flex: 1,
    paddingRight: 8,
  }),
  salesClearBtn: view({
    marginTop: 12,
    alignItems: "center",
    paddingVertical: 8,
  }),
  salesClearBtnText: text({
    fontSize: 12,
    fontWeight: "600",
    color: METRONIC.link,
    ...({
      textDecorationLine: "underline",
      textDecorationStyle: "dotted",
    } as unknown as TextStyle),
  }),
  salesContributorRow: view({
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingVertical: 8,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: METRONIC.border,
  }),
  salesContributorRowLast: view({
    borderBottomWidth: 0,
  }),
  salesContributorDot: view({
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#F1F1F4",
    alignItems: "center",
    justifyContent: "center",
  }),
  salesContributorDotText: text({
    fontSize: 12,
    fontWeight: "800",
    color: METRONIC.subtle,
  }),
  salesContributorTextCol: view({
    flex: 1,
    minWidth: 0,
    gap: 2,
  }),
  salesContributorName: text({
    fontSize: 12,
    fontWeight: "700",
    color: METRONIC.text,
  }),
  salesContributorMeta: text({
    fontSize: 10,
    fontWeight: "500",
    color: METRONIC.muted,
  }),
  salesSidebarPartnerCard: view({
    minWidth: 0,
  }),
  salesGrowPanel: view({
    paddingHorizontal: 0,
    paddingTop: 10,
    paddingBottom: 10,
    overflow: "hidden",
  }),
  salesGrowHeader: view({
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    paddingHorizontal: 12,
    paddingBottom: 8,
  }),
  salesGrowTitleIcon: view({
    width: 22,
    height: 22,
    borderRadius: 6,
    backgroundColor: "rgba(62, 151, 255, 0.1)",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 1,
  }),
  salesGrowHeaderText: view({
    flex: 1,
    minWidth: 0,
    gap: 1,
  }),
  salesGrowTitle: text({
    fontSize: 12,
    fontWeight: "700",
    color: METRONIC.text,
    lineHeight: 15,
  }),
  salesGrowSub: text({
    fontSize: 9,
    fontWeight: "500",
    color: METRONIC.muted,
    lineHeight: 12,
  }),
  salesGrowLoading: view({
    paddingVertical: 12,
    alignItems: "center",
  }),
  salesGrowFeed: view({
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: METRONIC.border,
  }),
  salesGrowRow: view({
    paddingLeft: 12,
    paddingRight: 12,
    paddingTop: 8,
    paddingBottom: 8,
    gap: 8,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: METRONIC.border,
  }),
  salesGrowRowStripe: view({
    backgroundColor: "#FAFBFC",
  }),
  salesGrowRowLast: view({
    borderBottomWidth: 0,
  }),
  salesGrowRowMain: view({
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    minWidth: 0,
  }),
  salesGrowRowHeadPressed: view({
    opacity: 0.9,
  }),
  salesGrowRowBody: view({
    flex: 1,
    minWidth: 0,
    gap: 1,
    paddingTop: 1,
  }),
  salesGrowNameRow: view({
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    minWidth: 0,
  }),
  salesGrowRowName: text({
    flexShrink: 1,
    fontSize: 11,
    fontWeight: "700",
    color: METRONIC.text,
    lineHeight: 14,
  }),
  salesGrowRoleBadge: view({
    paddingHorizontal: 5,
    paddingVertical: 1,
    borderRadius: 4,
    backgroundColor: Theme.networkBadgeSupplierBg,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: Theme.networkBadgeSupplierBorder,
    flexShrink: 0,
  }),
  salesGrowRoleBadgeClient: view({
    backgroundColor: Theme.networkBadgeClientBg,
    borderColor: Theme.networkBadgeClientBorder,
  }),
  salesGrowRoleBadgeText: text({
    fontSize: 8,
    fontWeight: "700",
    color: Theme.networkBadgeSupplierText,
    letterSpacing: 0.2,
    textTransform: "uppercase",
  }),
  salesGrowRoleBadgeTextClient: text({
    color: Theme.networkBadgeClientText,
  }),
  salesGrowMatchLine: text({
    fontSize: 9,
    lineHeight: 12,
    minHeight: 12,
  }),
  salesGrowMatchMuted: text({
    fontWeight: "500",
    color: METRONIC.muted,
  }),
  salesGrowMatchHighlight: text({
    fontWeight: "600",
  }),
  salesGrowRowMeta: text({
    fontSize: 9,
    fontWeight: "500",
    color: METRONIC.subtle,
    lineHeight: 12,
    minHeight: 12,
  }),
  salesGrowDismissIcon: view({
    width: 18,
    height: 18,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 9,
    backgroundColor: "#F1F1F4",
    flexShrink: 0,
    marginTop: 1,
  }),
  salesGrowActionRow: view({
    flexDirection: "row",
    alignItems: "stretch",
    justifyContent: "flex-start",
    gap: 8,
    paddingLeft: 38,
    paddingRight: 2,
    width: "100%",
  }),
  salesGrowActionGhost: view({
    flex: 1,
    minHeight: 32,
    paddingHorizontal: 12,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: Theme.borderMedium,
    backgroundColor: Theme.cardWhite,
    alignItems: "center",
    justifyContent: "center",
  }),
  salesGrowActionGhostText: text({
    fontSize: 11,
    fontWeight: "600",
    color: Theme.textSecondary,
  }),
  salesGrowActionSend: view({
    flex: 1,
    minHeight: 32,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: Theme.loadAddButtonBorder,
    backgroundColor: Theme.loadAddButtonBg,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
    paddingHorizontal: 12,
  }),
  salesGrowActionSendText: text({
    fontSize: 11,
    fontWeight: "700",
    color: Theme.loadAddButtonText,
  }),
  salesGrowPendingRow: view({
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingLeft: 38,
    paddingRight: 2,
    minHeight: 22,
  }),
  salesGrowPendingLabel: text({
    fontSize: 9,
    fontWeight: "600",
    color: METRONIC.muted,
  }),
  salesGrowPendingCancel: text({
    fontSize: 9,
    fontWeight: "700",
    color: METRONIC.link,
  }),
  salesGrowActionPressed: view({
    opacity: 0.88,
  }),
  salesGrowFooterBtn: view({
    marginTop: 6,
    marginHorizontal: 12,
    minHeight: 24,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 8,
    paddingVertical: 4,
  }),
  salesGrowFooterBtnText: text({
    fontSize: 10,
    fontWeight: "600",
    color: METRONIC.link,
  }),
  /** Daily invite quota under suggested partners (e.g. 0/5 invites sent today). */
  salesGrowInviteMeta: view({
    marginTop: 8,
    marginHorizontal: 12,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 8,
    backgroundColor: "#F5F8FA",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: METRONIC.border,
  }),
  salesGrowInviteMetaText: text({
    fontSize: 10,
    fontWeight: "500",
    color: METRONIC.muted,
    letterSpacing: 0.1,
  }),
  salesEmptySide: text({
    fontSize: 10,
    color: METRONIC.muted,
    paddingVertical: 8,
    paddingHorizontal: 12,
    lineHeight: 14,
  }),
  salesPerfViewBar: view({
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 2,
  }),
  salesPerfViewTitle: text({
    fontSize: 16,
    fontWeight: "800",
    color: METRONIC.text,
    letterSpacing: -0.2,
  }),
  salesPerfViewSub: text({
    fontSize: 11,
    fontWeight: "500",
    color: METRONIC.muted,
    marginTop: 2,
  }),
  salesPerfViewToggle: view({
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flexShrink: 0,
  }),
  salesPerfViewTab: view({
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
  }),
  salesPerfViewTabOn: view({
    borderColor: METRONIC.accent,
    backgroundColor: "rgba(79, 70, 229, 0.06)",
  }),
  salesPerfViewTabText: text({
    fontSize: 12,
    fontWeight: "600",
    color: METRONIC.subtle,
  }),
  salesPerfViewTabTextOn: text({
    color: METRONIC.accent,
    fontWeight: "700",
  }),
  salesKpiRow: view({
    width: "100%",
    ...({
      display: "grid",
      gridTemplateColumns: "repeat(4, minmax(0, 1fr))",
      gap: 12,
      alignItems: "stretch",
    } as unknown as ViewStyle),
  }),
  salesWidgetRowDual: view({
    width: "100%",
    ...({
      display: "grid",
      gridTemplateColumns: "minmax(0, 2fr) minmax(0, 1fr)",
      gap: 12,
      alignItems: "stretch",
    } as unknown as ViewStyle),
  }),
  salesBarRowDual: view({
    width: "100%",
    ...({
      display: "grid",
      gridTemplateColumns: "minmax(0, 1fr) minmax(0, 1fr)",
      gap: 12,
      alignItems: "stretch",
    } as unknown as ViewStyle),
  }),
  salesKpiCard: view({
    minWidth: 0,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
    paddingHorizontal: 10,
    paddingVertical: 12,
    gap: 2,
    ...({
      boxShadow: "0 0 20px 0 rgba(76, 87, 125, 0.04)",
    } as unknown as ViewStyle),
  }),
  salesKpiIcon: view({
    width: 28,
    height: 28,
    borderRadius: 7,
    backgroundColor: "#F9FAFB",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 2,
  }),
  salesKpiValue: text({
    fontSize: 18,
    fontWeight: "800",
    color: METRONIC.text,
    letterSpacing: -0.4,
  }),
  salesKpiLabel: text({
    fontSize: 10,
    fontWeight: "700",
    color: METRONIC.muted,
    textTransform: "uppercase",
    letterSpacing: 0.4,
  }),
  salesKpiSub: text({
    fontSize: 10,
    fontWeight: "500",
    color: METRONIC.subtle,
    marginTop: 2,
  }),
  salesWidgetRow: view({
    width: "100%",
    ...({
      display: "grid",
      gridTemplateColumns: "minmax(0, 2fr) minmax(0, 1fr) minmax(0, 1fr)",
      gap: 12,
      alignItems: "stretch",
    } as unknown as ViewStyle),
  }),
  salesWidgetTrend: view({
    minWidth: 0,
    minHeight: 196,
    overflow: "hidden",
    flexDirection: "column",
  }),
  salesWidgetDonut: view({
    minWidth: 0,
    minHeight: 196,
    overflow: "hidden",
    flexDirection: "column",
  }),
  salesBarRow: view({
    width: "100%",
    ...({
      display: "grid",
      gridTemplateColumns: "minmax(0, 1.5fr) minmax(0, 1fr) minmax(0, 1fr)",
      gap: 12,
      alignItems: "stretch",
    } as unknown as ViewStyle),
  }),
  salesBarRowPartner: view({
    width: "100%",
  }),
  salesBarLane: view({
    minWidth: 0,
  }),
  salesBarOrigin: view({
    minWidth: 0,
    minHeight: 196,
    overflow: "hidden",
    flexDirection: "column",
  }),
  salesBarDest: view({
    minWidth: 0,
    minHeight: 196,
    overflow: "hidden",
    flexDirection: "column",
  }),
  salesBarPartner: view({
    minWidth: 0,
    minHeight: 196,
    flexDirection: "column",
  }),
  salesBarRowQuad: view({
    width: "100%",
    ...({
      display: "grid",
      gridTemplateColumns:
        "minmax(0, 1.2fr) minmax(0, 1.2fr) minmax(0, 1fr) minmax(0, 1fr)",
      gap: 12,
      alignItems: "stretch",
    } as unknown as ViewStyle),
  }),
  salesWidgetHeader: view({
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 2,
  }),
  salesWidgetSub: text({
    fontSize: 11,
    fontWeight: "500",
    color: METRONIC.muted,
    marginBottom: 6,
  }),
  salesWidgetChartBody: view({
    width: "100%",
    minWidth: 0,
    marginTop: 2,
    overflow: "hidden",
  }),
  salesWidgetDonutBody: view({
    flex: 1,
    justifyContent: "center",
    alignItems: "stretch",
    paddingTop: 6,
    paddingBottom: 8,
    minHeight: 118,
    overflow: "visible",
  }),
  salesCardMenu: view({
    width: 24,
    height: 24,
    alignItems: "center",
    justifyContent: "center",
  }),
  salesTableCard: view({
    overflow: "hidden",
  }),
  salesTableScroll: view({
    width: "100%",
    ...({
      overflowX: "auto",
    } as unknown as ViewStyle),
  }),
  salesTableGrid: view({
    width: "100%",
    minWidth: 960,
    ...({
      display: "grid",
      gridTemplateColumns:
        "28px minmax(200px, 1.55fr) 108px 56px 92px 92px minmax(128px, 1fr) 76px 68px 28px",
      columnGap: 16,
      alignItems: "center",
      boxSizing: "border-box",
    } as unknown as ViewStyle),
  }),
  /** Partners table without Top lane column. */
  salesPartnersTableGrid: view({
    width: "100%",
    minWidth: 820,
    ...({
      display: "grid",
      gridTemplateColumns:
        "28px minmax(200px, 1.7fr) 108px 56px 92px 92px 76px 100px 28px",
      columnGap: 16,
      alignItems: "center",
      boxSizing: "border-box",
    } as unknown as ViewStyle),
  }),
  salesPartnersTableGridDense: view({
    width: "100%",
    minWidth: 760,
    ...({
      display: "grid",
      gridTemplateColumns:
        "22px minmax(160px, 1.7fr) 92px 48px 80px 80px 68px 96px 22px",
      columnGap: 10,
      alignItems: "center",
      boxSizing: "border-box",
    } as unknown as ViewStyle),
  }),
  salesAssetTableGrid: view({
    width: "100%",
    minWidth: 1120,
    ...({
      display: "grid",
      gridTemplateColumns:
        "28px minmax(180px, 1.4fr) 72px 52px 84px 84px 76px minmax(120px, 1fr) 68px 60px 28px",
      columnGap: 14,
      alignItems: "center",
      boxSizing: "border-box",
    } as unknown as ViewStyle),
  }),
  salesTripTableGrid: view({
    width: "100%",
    minWidth: 1040,
    ...({
      display: "grid",
      gridTemplateColumns:
        "28px minmax(96px, 0.85fr) minmax(140px, 1.2fr) minmax(108px, 1fr) minmax(108px, 1fr) 76px 76px 76px 68px 72px 28px",
      columnGap: 14,
      alignItems: "center",
      boxSizing: "border-box",
    } as unknown as ViewStyle),
  }),
  salesTripTableTitleCol: view({
    flex: 1,
    minWidth: 0,
    gap: 2,
  }),
  salesTripTableSub: text({
    fontSize: 11,
    fontWeight: "500",
    color: METRONIC.muted,
    lineHeight: 14,
  }),
  connectionsCardsSection: view({
    width: "100%",
    minHeight: 188,
    marginBottom: 4,
    zIndex: 1,
  }),
  connectionsPartnersTable: view({
    marginTop: 0,
    marginHorizontal: 0,
    width: "100%",
    alignSelf: "stretch",
    zIndex: 0,
  }),
  salesTableGridDense: view({
    width: "100%",
    minWidth: 880,
    ...({
      display: "grid",
      gridTemplateColumns:
        "22px minmax(160px, 1.55fr) 92px 48px 80px 80px minmax(110px, 1fr) 68px 60px 22px",
      columnGap: 10,
      alignItems: "center",
      boxSizing: "border-box",
    } as unknown as ViewStyle),
  }),
  salesTableHeadDense: view({
    paddingVertical: 7,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: METRONIC.border,
    backgroundColor: "#F9FAFB",
  }),
  salesTableHeadCellDense: text({
    fontSize: 9,
    fontWeight: "700",
    color: METRONIC.muted,
    textTransform: "uppercase",
    letterSpacing: 0.35,
  }),
  salesTableRowDense: view({
    paddingVertical: 7,
    paddingHorizontal: 12,
    minHeight: 44,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: METRONIC.border,
  }),
  salesPartnerCellDense: view({
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    minWidth: 0,
  }),
  salesPartnerNameDense: text({
    fontSize: 11,
    fontWeight: "700",
    color: METRONIC.text,
    lineHeight: 14,
    ...({
      overflow: "hidden",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
    } as unknown as TextStyle),
  }),
  salesPartnerSubDense: text({
    fontSize: 10,
    fontWeight: "500",
    color: METRONIC.muted,
    marginTop: 0,
    lineHeight: 13,
  }),
  salesRatingMetaDense: text({
    fontSize: 10,
    fontWeight: "700",
    color: METRONIC.text,
    lineHeight: 12,
  }),
  salesRatingSubDense: text({
    fontSize: 9,
    fontWeight: "500",
    color: METRONIC.muted,
    lineHeight: 12,
  }),
  salesMoneyValueDense: text({
    fontSize: 11,
    fontWeight: "700",
    color: METRONIC.text,
    lineHeight: 14,
    ...({
      textAlign: "right",
      whiteSpace: "nowrap",
    } as unknown as TextStyle),
  }),
  salesMoneyMetaDense: text({
    fontSize: 9,
    fontWeight: "500",
    color: METRONIC.muted,
    lineHeight: 12,
    ...({
      textAlign: "right",
      whiteSpace: "nowrap",
    } as unknown as TextStyle),
  }),
  salesTripsValueDense: text({
    fontSize: 11,
    fontWeight: "700",
    color: METRONIC.text,
    lineHeight: 14,
    textAlign: "right",
  }),
  salesTripsSubDense: text({
    fontSize: 9,
    fontWeight: "500",
    color: METRONIC.muted,
    lineHeight: 12,
    textAlign: "right",
  }),
  salesLaneTextDense: text({
    fontSize: 10,
    fontWeight: "500",
    color: METRONIC.text,
    lineHeight: 13,
    ...({
      overflow: "hidden",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
    } as unknown as TextStyle),
  }),
  salesLastActiveTextDense: text({
    fontSize: 10,
    fontWeight: "500",
    color: METRONIC.muted,
    lineHeight: 13,
    ...({
      whiteSpace: "nowrap",
    } as unknown as TextStyle),
  }),
  statusPillDense: view({
    alignSelf: "flex-start",
    paddingHorizontal: 6,
    paddingVertical: 1,
    borderRadius: 4,
    backgroundColor: "rgba(79, 70, 229, 0.1)",
  }),
  statusPillTextDense: text({
    fontSize: 9,
    fontWeight: "700",
    color: METRONIC.accent,
    textTransform: "uppercase",
  }),
  salesColTripRef: column({
    minWidth: 0,
  }),
  salesColLane: column({
    minWidth: 0,
  }),
  salesColTripClient: column({
    minWidth: 0,
  }),
  salesColTripSupplier: column({
    minWidth: 0,
  }),
  salesColCost: column({
    minWidth: 0,
  }),
  salesTripRefCell: view({
    minWidth: 0,
  }),
  salesTripRefText: text({
    fontSize: 12,
    fontWeight: "700",
    color: METRONIC.link,
    lineHeight: 16,
    ...({
      overflow: "hidden",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
    } as unknown as TextStyle),
  }),
  salesTripPartyText: text({
    fontSize: 12,
    fontWeight: "600",
    color: METRONIC.text,
    lineHeight: 16,
    ...({
      overflow: "hidden",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
    } as unknown as TextStyle),
  }),
  salesTripStatusActive: view({
    backgroundColor: "rgba(62, 151, 255, 0.12)",
  }),
  salesTripStatusActiveText: text({
    color: METRONIC.link,
  }),
  salesTripStatusPending: view({
    backgroundColor: "rgba(161, 165, 183, 0.15)",
  }),
  salesTripStatusPendingText: text({
    color: METRONIC.subtle,
  }),
  salesColPerformance: column({
    minWidth: 0,
  }),
  salesColEarnings: column({
    minWidth: 0,
  }),
  salesAssetPerfCell: view({
    gap: 2,
    minWidth: 0,
  }),
  salesAssetPerfScore: text({
    fontSize: 13,
    fontWeight: "800",
    color: METRONIC.text,
    lineHeight: 16,
  }),
  salesAssetPerfMeta: text({
    fontSize: 10,
    fontWeight: "500",
    color: METRONIC.muted,
    lineHeight: 13,
  }),
  salesAssetVehicleTableGrid: view({
    width: "100%",
    minWidth: 1180,
    ...({
      display: "grid",
      gridTemplateColumns:
        "28px minmax(160px, 1.25fr) 72px 48px 80px 80px 56px 64px minmax(110px, 1fr) 72px 68px 60px 28px",
      columnGap: 12,
      alignItems: "center",
      boxSizing: "border-box",
    } as unknown as ViewStyle),
  }),
  salesColKm: column({
    minWidth: 0,
  }),
  salesColUtil: column({
    minWidth: 0,
  }),
  salesVehicleBadge: view({
    alignSelf: "flex-start",
    marginTop: 3,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    backgroundColor: "rgba(62, 151, 255, 0.1)",
  }),
  salesVehicleBadgeText: text({
    fontSize: 9,
    fontWeight: "700",
    color: METRONIC.link,
    letterSpacing: 0.2,
  }),
  salesIntelDimList: view({
    gap: 6,
    marginTop: 4,
  }),
  salesIntelDimRow: view({
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  }),
  salesIntelDimLabel: text({
    width: 72,
    fontSize: 10,
    fontWeight: "600",
    color: METRONIC.muted,
  }),
  salesIntelDimTrack: view({
    flex: 1,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#EEF0F4",
    overflow: "hidden",
  }),
  salesIntelDimFill: view({
    height: "100%",
    borderRadius: 3,
    backgroundColor: METRONIC.link,
  }),
  salesIntelDimValue: text({
    width: 28,
    fontSize: 10,
    fontWeight: "700",
    color: METRONIC.text,
    textAlign: "right",
  }),
  salesAssetSectionTitle: text({
    fontSize: 13,
    fontWeight: "800",
    color: METRONIC.text,
    letterSpacing: -0.2,
  }),
  salesAssetSectionSub: text({
    fontSize: 11,
    fontWeight: "500",
    color: METRONIC.muted,
    marginTop: 2,
  }),
  salesTableTitleRow: view({
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 10,
  }),
  salesTableToolbar: view({
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 16,
    paddingBottom: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: METRONIC.border,
  }),
  salesTableSearch: view({
    flex: 1,
    minWidth: 160,
    maxWidth: 360,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
    paddingHorizontal: 10,
    paddingVertical: 7,
  }),
  salesTableToolbarMid: view({
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flexShrink: 0,
  }),
  salesToolbarLabel: text({
    fontSize: 11,
    fontWeight: "600",
    color: METRONIC.subtle,
  }),
  salesColumnsBtn: view({
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
    flexShrink: 0,
  }),
  salesColumnsBtnText: text({
    fontSize: 11,
    fontWeight: "600",
    color: METRONIC.subtle,
  }),
  salesTableHead: view({
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: METRONIC.border,
    backgroundColor: "#F9FAFB",
  }),
  salesTableHeadCell: text({
    fontSize: 10,
    fontWeight: "700",
    color: METRONIC.muted,
    textTransform: "uppercase",
    letterSpacing: 0.45,
  }),
  salesTableRow: view({
    paddingVertical: 12,
    paddingHorizontal: 16,
    minHeight: 64,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: METRONIC.border,
  }),
  salesGridNumHead: text({
    ...({
      justifySelf: "end",
      textAlign: "right",
      width: "100%",
    } as unknown as TextStyle),
  }),
  salesGridNumCell: view({
    ...({
      justifySelf: "end",
      width: "100%",
    } as unknown as ViewStyle),
  }),
  salesTableRowLast: view({
    borderBottomWidth: 0,
  }),
  salesTableCell: text({
    fontSize: 12,
    fontWeight: "500",
    color: METRONIC.text,
  }),
  salesTableCellMuted: text({
    fontSize: 12,
    fontWeight: "500",
    color: METRONIC.muted,
    ...({
      overflow: "hidden",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
    } as unknown as TextStyle),
  }),
  salesColCheck: view({
    alignItems: "flex-start",
    justifyContent: "center",
  }),
  salesColPartner: column({
    minWidth: 0,
  }),
  salesColRating: column({
    minWidth: 0,
  }),
  salesColTrips: column({
    minWidth: 0,
  }),
  salesColRevenue: column({
    minWidth: 0,
  }),
  salesColMargin: column({
    minWidth: 0,
  }),
  salesPartnerCell: view({
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    minWidth: 0,
  }),
  salesPartnerTextCol: view({
    flex: 1,
    minWidth: 0,
    gap: 1,
  }),
  salesRatingCell: view({
    gap: 4,
    minWidth: 0,
  }),
  salesRatingTopRow: view({
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    minWidth: 0,
  }),
  salesRatingMeta: text({
    fontSize: 11,
    fontWeight: "700",
    color: METRONIC.text,
    lineHeight: 14,
  }),
  salesRatingSub: text({
    fontSize: 10,
    fontWeight: "500",
    color: METRONIC.muted,
    lineHeight: 13,
  }),
  salesMoneyCell: view({
    gap: 3,
    minWidth: 0,
    ...({
      justifySelf: "end",
      alignItems: "flex-end",
    } as unknown as ViewStyle),
  }),
  salesMoneyValue: text({
    fontSize: 12,
    fontWeight: "700",
    color: METRONIC.text,
    lineHeight: 16,
    ...({
      textAlign: "right",
      whiteSpace: "nowrap",
    } as unknown as TextStyle),
  }),
  salesMoneyMeta: text({
    fontSize: 10,
    fontWeight: "500",
    color: METRONIC.muted,
    lineHeight: 13,
    ...({
      textAlign: "right",
      whiteSpace: "nowrap",
    } as unknown as TextStyle),
  }),
  salesTripsCell: view({
    gap: 3,
    minWidth: 0,
    ...({
      justifySelf: "end",
      alignItems: "flex-end",
    } as unknown as ViewStyle),
  }),
  salesTripsSub: text({
    fontSize: 10,
    fontWeight: "500",
    color: METRONIC.muted,
    lineHeight: 13,
    textAlign: "right",
  }),
  salesColRegion: column({
    minWidth: 0,
    paddingRight: 4,
  }),
  salesLaneText: text({
    fontSize: 11,
    fontWeight: "500",
    color: METRONIC.text,
    lineHeight: 15,
    ...({
      overflow: "hidden",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
    } as unknown as TextStyle),
  }),
  salesColLast: column({
    minWidth: 0,
  }),
  salesLastActiveText: text({
    fontSize: 11,
    fontWeight: "500",
    color: METRONIC.muted,
    lineHeight: 15,
    ...({
      whiteSpace: "nowrap",
    } as unknown as TextStyle),
  }),
  salesColStatus: column({
    minWidth: 0,
    alignItems: "flex-start",
  }),
  salesColMenu: view({
    alignItems: "center",
    justifyContent: "center",
  }),
  salesCheckBox: view({
    width: 16,
    height: 16,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: "#D1D5DB",
    backgroundColor: Theme.cardWhite,
  }),
  salesPartnerName: text({
    fontSize: 13,
    fontWeight: "700",
    color: METRONIC.text,
    lineHeight: 17,
    ...({
      overflow: "hidden",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
    } as unknown as TextStyle),
  }),
  salesPartnerSub: text({
    fontSize: 11,
    fontWeight: "500",
    color: METRONIC.muted,
    marginTop: 1,
    lineHeight: 15,
  }),
  salesTripsValue: text({
    fontSize: 13,
    fontWeight: "700",
    color: METRONIC.text,
    textAlign: "right",
    lineHeight: 16,
  }),
  salesTableEmpty: view({
    paddingVertical: 32,
    alignItems: "center",
  }),
  salesStatusLive: view({
    backgroundColor: "rgba(80, 205, 137, 0.15)",
  }),
  salesStatusLiveText: text({
    color: "#47BE7D",
  }),
  salesStatusInvite: view({
    backgroundColor: "rgba(62, 151, 255, 0.1)",
  }),
  salesStatusInviteText: text({
    color: METRONIC.link,
  }),
  salesInviteBtn: view({
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "rgba(62, 151, 255, 0.35)",
    ...({ cursor: "pointer" } as unknown as ViewStyle),
  }),
  salesInviteBtnPressed: view({
    opacity: 0.88,
  }),
  salesInviteBtnDisabled: view({
    opacity: 0.55,
  }),
  salesPagination: view({
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "nowrap",
    gap: 10,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: METRONIC.border,
  }),
  salesPageSizeRow: view({
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    flexWrap: "wrap",
    flexShrink: 1,
    minWidth: 0,
  }),
  salesPageSizeLabel: text({
    fontSize: 11,
    fontWeight: "600",
    color: METRONIC.muted,
    marginRight: 4,
  }),
  salesPageSizeBtn: view({
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
  }),
  salesPageSizeBtnOn: view({
    borderColor: METRONIC.link,
    backgroundColor: "rgba(62, 151, 255, 0.08)",
  }),
  salesPageSizeBtnText: text({
    fontSize: 11,
    fontWeight: "600",
    color: METRONIC.subtle,
  }),
  salesPageSizeBtnTextOn: text({
    color: METRONIC.link,
  }),
  salesPageNav: view({
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    flexShrink: 0,
    ...({
      flexWrap: "nowrap",
    } as unknown as ViewStyle),
  }),
  salesPageRange: text({
    fontSize: 11,
    fontWeight: "500",
    color: METRONIC.muted,
    marginRight: 8,
    flexShrink: 0,
  }),
  salesPageBtn: view({
    width: 28,
    height: 28,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: METRONIC.border,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Theme.cardWhite,
    flexShrink: 0,
  }),
  salesPageBtnDisabled: view({
    opacity: 0.4,
  }),
  salesPageNum: view({
    minWidth: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 6,
  }),
  salesPageNumOn: view({
    backgroundColor: "#F1F1F4",
  }),
  salesPageNumText: text({
    fontSize: 11,
    fontWeight: "600",
    color: METRONIC.subtle,
  }),
  salesPageNumTextOn: text({
    color: METRONIC.text,
    fontWeight: "800",
  }),
  growInviteBanner: view({
    backgroundColor: "rgba(62, 151, 255, 0.06)",
    borderColor: "rgba(62, 151, 255, 0.18)",
  }),
  growInviteBannerHead: view({
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 4,
  }),
  growInviteBannerTitle: text({
    fontSize: 14,
    fontWeight: "800",
    color: METRONIC.text,
  }),
  growInviteBannerSub: text({
    fontSize: 11,
    fontWeight: "500",
    color: METRONIC.muted,
    marginBottom: 10,
  }),
  growInviteProgressTrack: view({
    height: 6,
    borderRadius: 3,
    backgroundColor: "#EEF0F4",
    overflow: "hidden",
    marginBottom: 6,
  }),
  growInviteProgressFill: view({
    height: "100%",
    borderRadius: 3,
    backgroundColor: METRONIC.link,
  }),
  growInviteBannerMeta: text({
    fontSize: 10,
    fontWeight: "600",
    color: METRONIC.subtle,
  }),
  growConnectedRow: view({
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: METRONIC.border,
  }),
  growConnectedRowLast: view({
    borderBottomWidth: 0,
  }),
  growConnectedMenu: view({
    width: 28,
    height: 28,
    alignItems: "center",
    justifyContent: "center",
  }),
  growConnectProfileBtn: view({
    marginTop: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
  }),
  growConnectProfileBtnText: text({
    fontSize: 12,
    fontWeight: "700",
    color: METRONIC.text,
  }),
  growToolbarCard: view({
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 12,
  }),
  growToolbarTop: view({
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 12,
  }),
  growToolbarTitle: text({
    fontSize: 15,
    fontWeight: "800",
    color: METRONIC.text,
  }),
  growToolbarSub: text({
    fontSize: 11,
    fontWeight: "500",
    color: METRONIC.muted,
    marginTop: 2,
  }),
  growToolbarActions: view({
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flexShrink: 0,
  }),
  growToolbarPill: view({
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
  }),
  growToolbarPillText: text({
    fontSize: 11,
    fontWeight: "600",
    color: METRONIC.subtle,
  }),
  growToolbarFilterBtn: view({
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 8,
    backgroundColor: METRONIC.link,
  }),
  growToolbarFilterBtnText: text({
    fontSize: 11,
    fontWeight: "700",
    color: Theme.buttonPrimaryText,
  }),
  growToolbarBottom: view({
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  }),
  growViewToggle: view({
    flexDirection: "row",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: METRONIC.border,
    overflow: "hidden",
    flexShrink: 0,
  }),
  growViewToggleBtn: view({
    width: 36,
    height: 36,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Theme.cardWhite,
  }),
  growViewToggleBtnOn: view({
    backgroundColor: "rgba(62, 151, 255, 0.1)",
  }),
  growCardGrid: view({
    width: "100%",
    ...({
      display: "grid",
      gridTemplateColumns: "repeat(4, minmax(0, 1fr))",
      gap: 12,
      alignItems: "stretch",
    } as unknown as ViewStyle),
  }),
  growCardGridCell: view({
    minWidth: 0,
    height: "100%",
    ...({
      display: "flex",
      alignSelf: "stretch",
    } as unknown as ViewStyle),
  }),
  growListStack: view({
    gap: 12,
  }),
  growLoadMoreBtn: view({
    alignSelf: "center",
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
  }),
  growLoadMoreBtnText: text({
    fontSize: 12,
    fontWeight: "700",
    color: METRONIC.link,
  }),
  growSectionHeader: view({
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 8,
    marginBottom: 10,
  }),
  growSectionTitle: text({
    fontSize: 14,
    fontWeight: "800",
    color: METRONIC.text,
  }),
  growSectionSub: text({
    fontSize: 11,
    fontWeight: "500",
    color: METRONIC.muted,
  }),
  growSentStack: view({
    gap: 12,
    marginBottom: 8,
  }),
  growTeamsHeader: view({
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 4,
  }),
  growTeamsCount: text({
    fontSize: 16,
    fontWeight: "600",
    color: METRONIC.text,
    letterSpacing: -0.2,
  }),
  growOrgCard: view({
    position: "relative",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
    paddingHorizontal: 18,
    paddingTop: 20,
    paddingBottom: 16,
    alignItems: "center",
    ...({
      boxShadow: "0 0 20px 0 rgba(76, 87, 125, 0.04)",
    } as unknown as ViewStyle),
  }),
  growOrgCardPressed: view({
    opacity: 0.92,
  }),
  growOrgCardMenuFloat: view({
    position: "absolute",
    top: 10,
    right: 10,
    width: 28,
    height: 28,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2,
  }),
  growOrgCardHero: view({
    alignItems: "center",
    marginBottom: 12,
  }),
  growOrgIconHalo: view({
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: "#F9F9F9",
    borderWidth: 1,
    borderColor: "#EFF2F5",
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  }),
  growOrgOnlineDot: view({
    position: "absolute",
    right: 2,
    bottom: 2,
    width: 10,
    height: 10,
    borderRadius: 5,
    borderWidth: 2,
    borderColor: Theme.cardWhite,
  }),
  growOrgName: text({
    fontSize: 15,
    fontWeight: "600",
    color: METRONIC.text,
    textAlign: "center",
    flexShrink: 1,
    letterSpacing: -0.1,
    lineHeight: 20,
    maxWidth: "100%",
    paddingHorizontal: 4,
  }),
  growOrgTagline: text({
    fontSize: 11,
    fontWeight: "400",
    color: METRONIC.subtle,
    textAlign: "center",
    lineHeight: 16,
    marginTop: 4,
    marginBottom: 10,
    paddingHorizontal: 6,
    maxWidth: "100%",
  }),
  growOrgSectionsWrap: view({
    width: "100%",
    marginBottom: 4,
  }),
  growOrgSection: view({
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    paddingVertical: 11,
    borderTopWidth: 1,
    borderTopColor: "#EEF0F4",
    ...({
      borderStyle: "dashed",
    } as unknown as ViewStyle),
  }),
  growOrgSectionList: view({
    borderTopWidth: 0,
    paddingVertical: 0,
  }),
  growOrgSectionLast: view({
    paddingBottom: 2,
  }),
  growOrgSectionLabel: text({
    fontSize: 9,
    fontWeight: "500",
    color: METRONIC.muted,
    textTransform: "uppercase",
    letterSpacing: 0.6,
    width: 58,
    flexShrink: 0,
  }),
  growOrgMembersEmpty: view({
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 4,
  }),
  growMutualMembersCol: view({
    flex: 1,
    alignItems: "flex-end",
    gap: 6,
    minWidth: 0,
  }),
  growMutualMembersColList: view({
    alignItems: "flex-start",
    width: "100%",
  }),
  growMutualMembersLoading: view({
    flex: 1,
    alignItems: "flex-end",
    justifyContent: "center",
    minHeight: 28,
  }),
  growMutualMemberRow: view({
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 8,
    maxWidth: "100%",
    minWidth: 0,
  }),
  growMutualMemberRowList: view({
    justifyContent: "flex-start",
    width: "100%",
  }),
  growMutualMemberRowPressed: view({
    opacity: 0.88,
  }),
  growMutualMemberName: text({
    fontSize: 11,
    fontWeight: "500",
    color: METRONIC.subtle,
    flexShrink: 1,
    maxWidth: 120,
    textAlign: "right",
  }),
  growMutualMemberNameList: text({
    flex: 1,
    maxWidth: undefined,
    textAlign: "left",
  }),
  growMutualMoreBtn: view({
    alignSelf: "flex-end",
    paddingVertical: 2,
  }),
  growMutualMoreText: text({
    fontSize: 10,
    fontWeight: "500",
    color: METRONIC.muted,
  }),
  growOrgSectionMuted: text({
    fontSize: 10,
    fontWeight: "400",
    color: METRONIC.muted,
    flex: 1,
    textAlign: "right",
  }),
  growOrgPillRow: view({
    flex: 1,
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "flex-end",
    gap: 5,
  }),
  growOrgSkillPill: view({
    paddingHorizontal: 9,
    paddingVertical: 4,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: "#E4E6EF",
    backgroundColor: Theme.cardWhite,
  }),
  growOrgSkillPillText: text({
    fontSize: 10,
    fontWeight: "500",
    color: METRONIC.subtle,
  }),
  growOrgFooter: view({
    width: "100%",
    paddingTop: 12,
    marginTop: 2,
    borderTopWidth: 1,
    borderTopColor: METRONIC.border,
    alignItems: "center",
  }),
  growOrgBtnJoin: view({
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    paddingVertical: 9,
    paddingHorizontal: 10,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
  }),
  growOrgBtnJoinCompact: view({
    width: "auto",
    minWidth: 100,
    paddingHorizontal: 10,
  }),
  growOrgBtnJoinText: text({
    fontSize: 12,
    fontWeight: "600",
    color: METRONIC.link,
  }),
  growOrgBtnJoined: view({
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    paddingVertical: 9,
    paddingHorizontal: 10,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
  }),
  growOrgBtnJoinedCompact: view({
    width: "auto",
    minWidth: 100,
    paddingHorizontal: 10,
  }),
  growOrgBtnJoinedText: text({
    fontSize: 12,
    fontWeight: "600",
    color: METRONIC.subtle,
  }),
  growOrgStatusBtn: view({
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 6,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
    overflow: "hidden",
  }),
  growOrgStatusBtnCompact: view({
    width: "auto",
    minWidth: 148,
  }),
  growOrgStatusBtnMain: view({
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    paddingVertical: 9,
    paddingHorizontal: 12,
  }),
  growOrgStatusBtnClose: view({
    width: 36,
    alignSelf: "stretch",
    alignItems: "center",
    justifyContent: "center",
    borderLeftWidth: 1,
    borderLeftColor: METRONIC.border,
  }),
  growOrgListCard: view({
    borderRadius: 12,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
    paddingHorizontal: 16,
    paddingVertical: 12,
    ...({
      boxShadow: "0 0 16px 0 rgba(76, 87, 125, 0.03)",
    } as unknown as ViewStyle),
  }),
  growOrgListGrid: view({
    width: "100%",
    ...({
      display: "grid",
      gridTemplateColumns:
        "minmax(240px, 1.75fr) 88px minmax(108px, 0.85fr) auto",
      columnGap: 24,
      alignItems: "center",
      boxSizing: "border-box",
    } as unknown as ViewStyle),
  }),
  growOrgListIdentity: view({
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    minWidth: 0,
  }),
  growOrgListTextCol: view({
    flex: 1,
    minWidth: 0,
    gap: 2,
  }),
  growOrgListName: text({
    fontSize: 14,
    fontWeight: "600",
    color: METRONIC.text,
    letterSpacing: -0.1,
  }),
  growOrgListTagline: text({
    fontSize: 11,
    fontWeight: "400",
    color: METRONIC.subtle,
    lineHeight: 15,
  }),
  growOrgListMeta: text({
    fontSize: 10,
    fontWeight: "400",
    color: METRONIC.muted,
    marginTop: 2,
  }),
  growOrgListCol: view({
    minWidth: 0,
    gap: 6,
  }),
  growOrgListColLabel: text({
    fontSize: 9,
    fontWeight: "500",
    color: METRONIC.muted,
    textTransform: "uppercase",
    letterSpacing: 0.6,
  }),
  growOrgListStarsCol: view({
    minWidth: 0,
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
  }),
  growOrgListMutualsCol: view({
    minWidth: 0,
    alignItems: "flex-start",
    justifyContent: "center",
    alignSelf: "center",
  }),
  growOrgListMetricEmpty: text({
    fontSize: 12,
    fontWeight: "500",
    color: METRONIC.muted,
    lineHeight: 16,
  }),
  growOrgListActionCol: view({
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    justifyContent: "flex-end",
    alignSelf: "center",
  }),
  growOrgRolePill: view({
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
  }),
  growOrgRolePillText: text({
    fontSize: 10,
    fontWeight: "600",
    color: METRONIC.subtle,
    letterSpacing: 0.3,
    textTransform: "uppercase",
  }),
  growOrgListMenu: view({
    width: 28,
    height: 28,
    alignItems: "center",
    justifyContent: "center",
  }),
  growOrgBtnPendingText: text({
    fontSize: 12,
    fontWeight: "600",
    color: METRONIC.subtle,
  }),
  growOrgBtnPressed: view({
    opacity: 0.88,
  }),
  growOrgBtnDisabled: view({
    opacity: 0.65,
  }),
  goalsBalanceRow: view({
    flexDirection: "row",
    gap: 16,
    flexWrap: "wrap",
    marginBottom: 4,
  }),
  goalsBalanceCard: view({
    flex: 1,
    minWidth: 280,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
    paddingHorizontal: 18,
    paddingTop: 16,
    paddingBottom: 14,
    ...({
      boxShadow: "0 0 20px 0 rgba(76, 87, 125, 0.04)",
    } as unknown as ViewStyle),
  }),
  goalsBalanceHeader: view({
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingBottom: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: METRONIC.border,
    marginBottom: 10,
  }),
  goalsBalanceTitle: text({
    fontSize: 14,
    fontWeight: "600",
    color: METRONIC.text,
  }),
  goalsBalanceIconRow: view({
    marginBottom: 6,
  }),
  goalsBalanceLabel: text({
    fontSize: 11,
    fontWeight: "500",
    color: METRONIC.muted,
    marginBottom: 4,
  }),
  goalsBalanceAmount: text({
    fontSize: 26,
    fontWeight: "700",
    color: METRONIC.text,
    letterSpacing: -0.5,
    marginBottom: 4,
  }),
  goalsBalanceSub: text({
    fontSize: 11,
    fontWeight: "400",
    color: METRONIC.subtle,
    lineHeight: 15,
    marginBottom: 12,
  }),
  goalsPeriodRow: view({
    flexDirection: "row",
    borderWidth: 1,
    borderColor: METRONIC.border,
    borderRadius: 8,
    overflow: "hidden",
    marginBottom: 12,
  }),
  goalsPeriodBtn: view({
    flex: 1,
    paddingVertical: 6,
    alignItems: "center",
    backgroundColor: Theme.cardWhite,
  }),
  goalsPeriodBtnOn: view({
    backgroundColor: "#F1F1F4",
  }),
  goalsPeriodBtnText: text({
    fontSize: 10,
    fontWeight: "600",
    color: METRONIC.muted,
  }),
  goalsPeriodBtnTextOn: text({
    color: METRONIC.text,
  }),
  goalsProgressTrack: view({
    height: 6,
    borderRadius: 3,
    backgroundColor: "#F1F1F4",
    overflow: "hidden",
    marginBottom: 6,
  }),
  goalsProgressFill: view({
    height: "100%",
    borderRadius: 3,
  }),
  goalsProgressMeta: text({
    fontSize: 10,
    fontWeight: "500",
    color: METRONIC.muted,
  }),
  goalsChartSub: text({
    fontSize: 11,
    fontWeight: "400",
    color: METRONIC.muted,
  }),
  goalsTargetGrid: view({
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 14,
    marginBottom: 4,
  }),
  goalsTargetGridThree: view({
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 14,
    marginBottom: 4,
  }),
  goalsCarryForwardBtn: view({
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: "#F1FAFF",
  }),
  goalsCarryForwardText: text({
    flex: 1,
    fontSize: 11,
    fontWeight: "600",
    color: METRONIC.link,
    lineHeight: 15,
  }),
  goalsMonthBanner: view({
    marginBottom: 8,
    gap: 2,
  }),
  goalsMonthBannerTitle: text({
    fontSize: 13,
    fontWeight: "600",
    color: METRONIC.text,
  }),
  goalsMonthBannerSub: text({
    fontSize: 11,
    fontWeight: "400",
    color: METRONIC.subtle,
    lineHeight: 15,
  }),
  goalsTargetCard: view({
    flex: 1,
    minWidth: 280,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
    paddingHorizontal: 16,
    paddingVertical: 14,
    gap: 8,
    ...({
      boxShadow: "0 0 16px 0 rgba(76, 87, 125, 0.03)",
    } as unknown as ViewStyle),
  }),
  goalsTargetCardHeader: view({
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  }),
  goalsTargetCardTitle: text({
    fontSize: 14,
    fontWeight: "600",
    color: METRONIC.text,
  }),
  goalsTargetCardHint: text({
    fontSize: 11,
    fontWeight: "400",
    color: METRONIC.subtle,
    lineHeight: 15,
  }),
  goalsTargetInner: view({
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    borderWidth: 1,
    borderColor: METRONIC.border,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 12,
    backgroundColor: "#FAFBFC",
  }),
  goalsTargetValueCol: view({
    flex: 1,
    minWidth: 0,
    gap: 4,
  }),
  goalsTargetActual: text({
    fontSize: 22,
    fontWeight: "700",
    color: METRONIC.text,
    letterSpacing: -0.3,
  }),
  goalsTargetMeta: text({
    fontSize: 11,
    fontWeight: "400",
    color: METRONIC.subtle,
    lineHeight: 15,
  }),
  goalsTargetActionBtn: view({
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
  }),
  goalsTargetActionText: text({
    fontSize: 11,
    fontWeight: "600",
    color: METRONIC.link,
  }),
  goalsTargetEditCol: view({
    gap: 8,
    minWidth: 120,
  }),
  goalsTargetInput: text({
    minWidth: 100,
    borderWidth: 1,
    borderColor: METRONIC.border,
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 7,
    fontSize: 13,
    fontWeight: "600",
    color: METRONIC.text,
    backgroundColor: Theme.cardWhite,
  }),
  goalsTargetEditActions: view({
    flexDirection: "row",
    gap: 6,
  }),
  goalsTargetCancelBtn: view({
    paddingHorizontal: 8,
    paddingVertical: 5,
  }),
  goalsTargetCancelText: text({
    fontSize: 10,
    fontWeight: "600",
    color: METRONIC.muted,
  }),
  goalsTargetSaveBtn: view({
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 6,
    backgroundColor: METRONIC.link,
  }),
  goalsTargetSaveText: text({
    fontSize: 10,
    fontWeight: "700",
    color: Theme.textOnPrimary,
  }),
  goalsTargetSliderTrack: view({
    height: 8,
    borderRadius: 4,
    backgroundColor: "#F1F1F4",
    position: "relative",
    overflow: "visible",
  }),
  goalsTargetSliderFill: view({
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    borderRadius: 4,
    backgroundColor: "rgba(62, 151, 255, 0.35)",
  }),
  goalsTargetSliderThumb: view({
    position: "absolute",
    top: -4,
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: METRONIC.link,
    marginLeft: -8,
    borderWidth: 2,
    borderColor: Theme.cardWhite,
  }),
  goalsStatusPill: view({
    alignSelf: "flex-start",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  }),
  goalsStatusOnTrack: view({
    backgroundColor: "rgba(80, 205, 137, 0.15)",
  }),
  goalsStatusOnTrackText: text({
    color: "#47BE7D",
  }),
  goalsStatusBehind: view({
    backgroundColor: "rgba(241, 65, 108, 0.12)",
  }),
  goalsStatusBehindText: text({
    color: "#F1416C",
  }),
  goalsStatusUnset: view({
    backgroundColor: "rgba(161, 165, 183, 0.15)",
  }),
  goalsStatusText: text({
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.2,
  }),
  goalsStatusUnsetText: text({
    color: METRONIC.muted,
  }),
  goalsSidebarRow: view({
    paddingVertical: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: METRONIC.border,
    gap: 6,
  }),
  goalsSidebarRowLast: view({
    borderBottomWidth: 0,
    paddingBottom: 2,
  }),
  goalsSidebarRowTop: view({
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  }),
  goalsSidebarLabel: text({
    fontSize: 11,
    fontWeight: "600",
    color: METRONIC.text,
  }),
  goalsSidebarPct: text({
    fontSize: 11,
    fontWeight: "700",
    color: METRONIC.link,
  }),
  goalsSidebarTrack: view({
    height: 5,
    borderRadius: 3,
    backgroundColor: "#F1F1F4",
    overflow: "hidden",
  }),
  goalsSidebarFill: view({
    height: "100%",
    borderRadius: 3,
    backgroundColor: METRONIC.link,
  }),
  goalsSidebarMeta: text({
    fontSize: 10,
    fontWeight: "500",
    color: METRONIC.muted,
  }),
  goalsNetValue: text({
    fontSize: 22,
    fontWeight: "700",
    color: METRONIC.text,
    marginTop: 4,
  }),
  goalsNetSub: text({
    fontSize: 11,
    fontWeight: "400",
    color: METRONIC.subtle,
    marginTop: 6,
    lineHeight: 16,
  }),
  goalsEntityTableHead: view({
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: METRONIC.border,
    backgroundColor: "#FAFBFC",
  }),
  goalsEntityTableGrid: view({
    width: "100%",
    minWidth: 640,
    ...({
      display: "grid",
      gridTemplateColumns: "minmax(180px, 1.6fr) 96px 96px 72px 36px",
      columnGap: 16,
      alignItems: "center",
      boxSizing: "border-box",
    } as unknown as ViewStyle),
  }),
  goalsEntityTableGridKam: view({
    width: "100%",
    minWidth: 760,
    ...({
      display: "grid",
      gridTemplateColumns: "minmax(200px, 1.5fr) minmax(88px, 0.65fr) 96px 96px 72px 36px",
      columnGap: 16,
      alignItems: "center",
      boxSizing: "border-box",
    } as unknown as ViewStyle),
  }),
  goalsEntityHeadCell: text({
    fontSize: 10,
    fontWeight: "600",
    color: METRONIC.muted,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    ...({
      whiteSpace: "nowrap",
    } as unknown as TextStyle),
  }),
  goalsEntityHeadNum: text({
    textAlign: "right",
    ...({
      justifySelf: "end",
      width: "100%",
    } as unknown as TextStyle),
  }),
  goalsEntityColName: column({
    minWidth: 0,
  }),
  goalsEntityColKam: column({
    minWidth: 0,
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    ...({
      justifySelf: "start",
    } as unknown as ColumnStyle),
  }),
  goalsEntityColActual: column({
    minWidth: 0,
    width: "100%",
    ...({
      justifySelf: "end",
    } as unknown as ColumnStyle),
  }),
  goalsEntityColTarget: column({
    minWidth: 0,
    width: "100%",
    ...({
      justifySelf: "end",
    } as unknown as ColumnStyle),
  }),
  goalsEntityColProgress: column({
    minWidth: 0,
    width: "100%",
    ...({
      justifySelf: "end",
    } as unknown as ColumnStyle),
  }),
  goalsEntityColAction: view({
    ...({
      justifySelf: "center",
    } as unknown as ViewStyle),
  }),
  goalsEntityRow: view({
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: METRONIC.border,
  }),
  goalsEntityName: text({
    fontSize: 13,
    fontWeight: "600",
    color: METRONIC.text,
  }),
  goalsEntityMeta: text({
    fontSize: 11,
    fontWeight: "400",
    color: METRONIC.subtle,
  }),
  goalsEntityValue: text({
    fontSize: 12,
    fontWeight: "700",
    color: METRONIC.text,
    textAlign: "right",
    ...({
      whiteSpace: "nowrap",
    } as unknown as TextStyle),
  }),
  goalsEntityProgressText: text({
    fontSize: 12,
    fontWeight: "700",
    color: METRONIC.link,
    textAlign: "right",
    ...({
      whiteSpace: "nowrap",
    } as unknown as TextStyle),
  }),
  goalsEntityEditStack: view({
    gap: 6,
    width: "100%",
    alignItems: "stretch",
    ...({
      justifySelf: "end",
    } as unknown as ViewStyle),
  }),
  goalsEntityInput: text({
    borderWidth: 1,
    borderColor: METRONIC.border,
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 6,
    fontSize: 11,
    fontWeight: "600",
    color: METRONIC.text,
    backgroundColor: Theme.cardWhite,
    textAlign: "right",
  }),
  goalsEntitySaveLink: text({
    fontSize: 11,
    fontWeight: "700",
    color: METRONIC.link,
  }),
  goalsWizardBackdrop: view({
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.45)",
    justifyContent: "center",
    alignItems: "center",
    padding: 24,
  }),
  goalsWizardSheet: view({
    width: "100%",
    maxWidth: 560,
    maxHeight: "92%",
    backgroundColor: Theme.cardWhite,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: METRONIC.border,
    overflow: "hidden",
  }),
  goalsWizardSheetTall: view({
    maxWidth: 600,
    maxHeight: "94%",
  }),
  goalsWizardHeader: view({
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
    paddingHorizontal: 20,
    paddingTop: 18,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: METRONIC.border,
  }),
  goalsWizardHeaderText: view({
    flex: 1,
    minWidth: 0,
    gap: 4,
  }),
  goalsWizardTitle: text({
    fontSize: 16,
    fontWeight: "800",
    color: METRONIC.text,
  }),
  goalsWizardSubtitle: text({
    fontSize: 12,
    fontWeight: "500",
    color: METRONIC.muted,
  }),
  goalsWizardSteps: view({
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 20,
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: METRONIC.border,
  }),
  goalsWizardStepItem: view({
    alignItems: "center",
    gap: 6,
    minWidth: 72,
  }),
  goalsWizardStepDot: view({
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#E1E3EA",
  }),
  goalsWizardStepDotOn: view({
    backgroundColor: METRONIC.link,
  }),
  goalsWizardStepLabel: text({
    fontSize: 10,
    fontWeight: "600",
    color: METRONIC.muted,
  }),
  goalsWizardStepLabelOn: text({
    color: METRONIC.link,
    fontWeight: "700",
  }),
  goalsWizardBody: view({
    flex: 1,
    minHeight: 0,
  }),
  goalsWizardBodyContent: view({
    padding: 20,
    gap: 4,
  }),
  goalsWizardHero: view({
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    marginBottom: 12,
  }),
  goalsWizardHeroIcon: view({
    width: 48,
    height: 48,
    borderRadius: 10,
    backgroundColor: "#F1FAFF",
    alignItems: "center",
    justifyContent: "center",
  }),
  goalsWizardHeroName: text({
    fontSize: 15,
    fontWeight: "800",
    color: METRONIC.text,
  }),
  goalsWizardHeroMeta: text({
    fontSize: 11,
    fontWeight: "500",
    color: METRONIC.muted,
    marginTop: 2,
  }),
  goalsWizardDetailGrid: view({
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    marginBottom: 14,
  }),
  goalsWizardDetailCell: view({
    minWidth: "45%",
    flexGrow: 1,
    gap: 2,
  }),
  goalsWizardDetailWide: view({
    minWidth: "100%",
  }),
  goalsWizardDetailLabel: text({
    fontSize: 10,
    fontWeight: "700",
    color: METRONIC.muted,
    textTransform: "uppercase",
    letterSpacing: 0.4,
  }),
  goalsWizardDetailValue: text({
    fontSize: 12,
    fontWeight: "600",
    color: METRONIC.text,
    lineHeight: 17,
  }),
  goalsWizardKpiRow: view({
    flexDirection: "row",
    gap: 10,
  }),
  goalsWizardKpi: view({
    flex: 1,
    minWidth: 0,
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: "#F9F9F9",
    gap: 4,
  }),
  goalsWizardKpiValue: text({
    fontSize: 14,
    fontWeight: "800",
    color: METRONIC.text,
  }),
  goalsWizardKpiLabel: text({
    fontSize: 10,
    fontWeight: "600",
    color: METRONIC.muted,
  }),
  goalsWizardSectionTitle: text({
    fontSize: 12,
    fontWeight: "800",
    color: METRONIC.text,
    marginTop: 8,
    marginBottom: 10,
  }),
  goalsWizardHistoryHead: view({
    flexDirection: "row",
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: METRONIC.border,
  }),
  goalsWizardHistoryHeadCell: text({
    fontSize: 9,
    fontWeight: "700",
    color: METRONIC.muted,
    textTransform: "uppercase",
    letterSpacing: 0.4,
  }),
  goalsWizardHistoryRow: view({
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: METRONIC.border,
  }),
  goalsWizardHistoryCell: text({
    fontSize: 11,
    fontWeight: "600",
    color: METRONIC.text,
  }),
  goalsWizardHistoryMonth: text({
    flex: 1.1,
    minWidth: 0,
  }),
  goalsWizardHistoryNum: text({
    flex: 1.3,
    minWidth: 0,
    textAlign: "right",
    paddingHorizontal: 4,
  }),
  goalsWizardHistoryPct: text({
    width: 40,
    textAlign: "right",
    color: METRONIC.link,
    fontWeight: "800",
  }),
  goalsWizardEmpty: text({
    fontSize: 12,
    fontWeight: "500",
    color: METRONIC.muted,
    lineHeight: 18,
    paddingVertical: 12,
  }),
  goalsWizardRecommendCard: view({
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(62, 151, 255, 0.35)",
    backgroundColor: "#F1FAFF",
    padding: 14,
    gap: 8,
    marginBottom: 12,
  }),
  goalsWizardRecommendHeader: view({
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  }),
  goalsWizardRecommendTitle: text({
    fontSize: 12,
    fontWeight: "800",
    color: METRONIC.text,
  }),
  goalsWizardRecommendAmount: text({
    fontSize: 18,
    fontWeight: "800",
    color: METRONIC.link,
  }),
  goalsWizardRecommendBody: text({
    fontSize: 11,
    fontWeight: "500",
    color: METRONIC.subtle,
    lineHeight: 16,
  }),
  goalsWizardOptionBtn: view({
    alignSelf: "flex-start",
    marginTop: 4,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: METRONIC.link,
    backgroundColor: Theme.cardWhite,
  }),
  goalsWizardOptionBtnOn: view({
    backgroundColor: METRONIC.link,
  }),
  goalsWizardOptionBtnText: text({
    fontSize: 11,
    fontWeight: "700",
    color: METRONIC.link,
  }),
  goalsWizardOptionBtnTextOn: text({
    color: Theme.buttonPrimaryText,
  }),
  goalsWizardCarryCard: view({
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    padding: 14,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
    marginBottom: 14,
  }),
  goalsWizardCarryCardOn: view({
    borderColor: METRONIC.link,
    backgroundColor: "#F1FAFF",
  }),
  goalsWizardCarryTitle: text({
    fontSize: 12,
    fontWeight: "700",
    color: METRONIC.text,
  }),
  goalsWizardCarrySub: text({
    fontSize: 11,
    fontWeight: "600",
    color: METRONIC.link,
    marginTop: 2,
  }),
  goalsWizardFieldLabel: text({
    fontSize: 10,
    fontWeight: "700",
    color: METRONIC.muted,
    marginTop: 8,
    marginBottom: 6,
    textTransform: "uppercase",
    letterSpacing: 0.4,
  }),
  goalsWizardInput: text({
    borderWidth: 1,
    borderColor: METRONIC.border,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    fontWeight: "600",
    color: METRONIC.text,
    backgroundColor: "#F9F9F9",
  }),
  goalsWizardFooter: view({
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 4,
    borderTopWidth: 1,
    borderTopColor: METRONIC.border,
  }),
  goalsWizardFooterActions: view({
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginLeft: "auto",
  }),
  goalsWizardBackBtn: view({
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingVertical: 8,
  }),
  goalsWizardBackBtnText: text({
    fontSize: 12,
    fontWeight: "700",
    color: METRONIC.text,
  }),
  goalsWizardCancelBtn: view({
    paddingHorizontal: 10,
    paddingVertical: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: METRONIC.border,
  }),
  goalsWizardCancelText: text({
    fontSize: 12,
    fontWeight: "700",
    color: METRONIC.text,
  }),
  goalsWizardPrimaryBtn: view({
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 8,
    backgroundColor: "rgba(0, 0, 0, 0.85)",
    minWidth: 108,
    alignItems: "center",
  }),
  goalsWizardPrimaryText: text({
    fontSize: 12,
    fontWeight: "800",
    color: Theme.textOnPrimary,
  }),
  goalsViewMore: view({
    alignItems: "center",
    paddingVertical: 14,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: METRONIC.border,
  }),
  goalsViewMoreText: text({
    fontSize: 12,
    fontWeight: "600",
    color: METRONIC.link,
    ...({
      textDecorationLine: "underline",
      textDecorationStyle: "dashed",
    } as unknown as TextStyle),
  }),
  teamPanelTitleCol: view({
    flex: 1,
    minWidth: 0,
    gap: 2,
  }),
  teamPanelCard: view({
    overflow: "hidden",
    paddingTop: 4,
  }),
  teamInviteBtn: view({
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 10,
    paddingVertical: 9,
    borderRadius: 8,
    backgroundColor: METRONIC.accent,
    flexShrink: 0,
  }),
  teamInviteBtnText: text({
    fontSize: 12,
    fontWeight: "700",
    color: Theme.textOnPrimary,
  }),
  teamInviteCancelBtn: view({
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
    flexShrink: 0,
  }),
  teamInviteCancelBtnText: text({
    fontSize: 12,
    fontWeight: "600",
    color: METRONIC.text,
  }),
  invitationsPanelCard: view({
    overflow: "hidden",
    paddingBottom: 0,
  }),
  invitationsPanelHead: view({
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
    paddingHorizontal: 20,
    paddingTop: 18,
    paddingBottom: 4,
  }),
  invitationsPanelTitleCol: view({
    flex: 1,
    minWidth: 0,
    gap: 2,
  }),
  invitationsCloseBtn: view({
    width: 32,
    height: 32,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
  }),
  tabActionBtnInvitesOn: view({
    backgroundColor: METRONIC.accent,
    borderColor: METRONIC.accent,
  }),
  tabActionBtnTextInvitesOn: text({
    color: Theme.buttonDarkText,
  }),
  profileSplitRow: view({
    flexDirection: "row",
    gap: 12,
    alignItems: "stretch",
    ...({
      flexWrap: "wrap",
    } as unknown as ViewStyle),
  }),
  profileCol: view({
    flex: 1,
    minWidth: 300,
    minHeight: 0,
  }),
  profileCard: view({
    flex: 1,
    flexDirection: "column",
    alignSelf: "stretch",
  }),
  profileCardHeader: view({
    paddingBottom: 12,
    marginBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: METRONIC.border,
  }),
  profileCardTitle: text({
    fontSize: 13,
    fontWeight: "600",
    color: METRONIC.text,
    letterSpacing: -0.15,
  }),
  profileCardSub: text({
    fontSize: 11,
    fontWeight: "400",
    color: METRONIC.muted,
    marginTop: 2,
    lineHeight: 15,
  }),
  profileCardBody: view({
    flex: 1,
    gap: 0,
  }),
  profileCardFooter: view({
    marginTop: 4,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: METRONIC.border,
    flexDirection: "row",
    justifyContent: "flex-end",
    alignItems: "center",
  }),
  profileMediaRow: view({
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    marginBottom: 14,
  }),
  profileAvatarRow: view({
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    marginBottom: 14,
  }),
  profileAvatarRing: view({
    width: 56,
    height: 56,
    borderRadius: 28,
    borderWidth: 1.5,
    borderColor: METRONIC.border,
    backgroundColor: "#F9FAFB",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    flexShrink: 0,
  }),
  profileAvatarImage: image({
    width: 52,
    height: 52,
    borderRadius: 26,
  }),
  profileAvatarActions: view({
    flex: 1,
    minWidth: 0,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    alignItems: "center",
    paddingTop: 4,
  }),
  profileActionBtn: view({
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
  }),
  profileActionBtnText: text({
    fontSize: 11,
    fontWeight: "600",
    color: METRONIC.link,
  }),
  profileFieldGroup: view({
    gap: 4,
    marginBottom: 10,
  }),
  profileFieldLabel: text({
    fontSize: 10,
    fontWeight: "600",
    color: METRONIC.muted,
    textTransform: "uppercase",
    letterSpacing: 0.4,
  }),
  profileFieldInput: text({
    borderWidth: 1,
    borderColor: METRONIC.border,
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 7,
    fontSize: 13,
    fontWeight: "400",
    color: METRONIC.text,
    backgroundColor: Theme.cardWhite,
    minHeight: 34,
  }),
  profileFieldReadonly: view({
    borderWidth: 1,
    borderColor: METRONIC.border,
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 7,
    backgroundColor: "#F9FAFB",
    minHeight: 34,
    justifyContent: "center",
  }),
  profileFieldReadonlyText: text({
    fontSize: 13,
    fontWeight: "400",
    color: METRONIC.subtle,
  }),
  profileSaveBtn: view({
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 6,
    backgroundColor: Theme.buttonPrimary,
    borderWidth: 1.5,
    borderColor: Theme.textPrimaryDark,
    minWidth: 108,
    alignItems: "center",
    justifyContent: "center",
    minHeight: 32,
  }),
  profileSaveBtnDisabled: view({
    opacity: 0.72,
  }),
  profileSaveBtnText: text({
    fontSize: 12,
    fontWeight: "700",
    color: Theme.textPrimaryDark,
  }),
  profilePresetGrid: view({
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    marginTop: 6,
    marginBottom: 10,
  }),
  profilePresetItem: view({
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 2,
    borderColor: "transparent",
    overflow: "hidden",
  }),
  profilePresetItemSelected: view({
    borderColor: METRONIC.link,
  }),
  profilePresetImage: image({
    width: 32,
    height: 32,
    borderRadius: 16,
  }),
  profileLogoRow: view({
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    marginBottom: 14,
  }),
  profileLogoThumb: view({
    width: 56,
    height: 56,
    borderRadius: 8,
    backgroundColor: "#F3F6F9",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    borderWidth: 1,
    borderColor: METRONIC.border,
    flexShrink: 0,
  }),
  profileLogoImage: image({
    width: 56,
    height: 56,
    borderRadius: 8,
  }),
  profileLogoInitials: text({
    fontSize: 16,
    fontWeight: "700",
    color: METRONIC.subtle,
  }),
  profileErrorText: text({
    fontSize: 11,
    fontWeight: "500",
    color: Theme.negative,
    marginBottom: 6,
  }),
  profilePageTitle: text({
    fontSize: 14,
    fontWeight: "600",
    color: METRONIC.text,
    letterSpacing: -0.2,
  }),
  profilePageSub: text({
    fontSize: 11,
    fontWeight: "400",
    color: METRONIC.muted,
    marginTop: 1,
    lineHeight: 15,
  }),
  profileCardPad: view({
    padding: 14,
  }),
};

export const networkDesktopHubStyles = createStyles(networkDesktopHubStylesDef);
