/** Shared sizing for business + driver mobile signup (mature, compact). */
export const SIGNUP_MOBILE_TOKENS = {
  padH: 20,
  contentMaxWidth: 400,
  brandSize: 20,
  backFontSize: 14,
  titleSize: 20,
  titleLineHeight: 26,
  subtitleSize: 13,
  subtitleLineHeight: 18,
  fieldLabelSize: 10,
  fieldLabelSpacing: 0.5,
  displayFontSize: 17,
  displayMinHeight: 48,
  inputFontSize: 16,
  inputMinHeight: 48,
  btnFontSize: 15,
  btnPaddingV: 12,
  btnRadius: 12,
  inputRadius: 12,
  googleBtnPaddingV: 11,
  orMarginV: 10,
  altMarginTop: 14,
  altFontSize: 13,
  linkFontSize: 13,
  heroPadBottom: 12,
  displayBlockMarginBottom: 4,
  progressPadTop: 10,
  progressLabelSize: 8,
  otpBoxW: 36,
  otpBoxH: 42,
  otpGap: 7,
  otpDigitSize: 18,
  flagSize: 18,
  dialCodeSize: 15,
} as const;
