import { Platform, StyleSheet } from "react-native";

import Theme from "@/constants/Theme";

export const deployModalStyles = StyleSheet.create({
  backdrop: {
    flex: 1,
    backgroundColor: "rgba(15,23,42,0.75)",
    justifyContent: "flex-end",
  },
  backdropWeb: {
    position: "fixed" as "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 100000,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  sheet: {
    backgroundColor: Theme.cardWhite,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    overflow: "hidden",
    alignSelf: "stretch",
    ...(Platform.OS === "web"
      ? { width: "100%", maxWidth: 440, borderRadius: 28 }
      : {}),
  },
  hero: {
    paddingTop: 16,
    paddingHorizontal: 18,
    paddingBottom: 16,
    gap: 12,
    borderBottomWidth: 1,
    borderBottomColor: Theme.financeHeroBorder,
  },
  heroTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    minHeight: 22,
  },
  heroEyebrowRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  heroEyebrow: {
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 1.2,
    color: Theme.textOnDarkMuted,
    textTransform: "uppercase",
  },
  queueBadge: {
    backgroundColor: "rgba(255,255,255,0.18)",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
  },
  queueText: {
    fontSize: 10,
    fontWeight: "700",
    color: "#fff",
  },
  heroBody: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  heroLogoWrap: {
    width: 56,
    height: 56,
    borderRadius: 16,
    backgroundColor: "#fff",
    overflow: "visible",
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
  },
  heroAvatar: {
    borderRadius: 16,
    borderWidth: 0,
  },
  heroLogoBadge: {
    position: "absolute",
    right: -2,
    bottom: -2,
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: Theme.financeCardSlateTo,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "#fff",
  },
  heroTextBlock: {
    flex: 1,
    minWidth: 0,
    gap: 6,
  },
  heroTitle: {
    fontSize: 20,
    fontWeight: "900",
    color: "#fff",
    letterSpacing: -0.4,
    lineHeight: 24,
  },
  heroShipperName: {
    fontSize: 13,
    fontWeight: "600",
    color: "rgba(255,255,255,0.78)",
    lineHeight: 17,
  },
  heroPillRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    flexWrap: "wrap",
  },
  heroPill: {
    backgroundColor: "rgba(255,255,255,0.18)",
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 999,
  },
  heroPillText: {
    fontSize: 10,
    fontWeight: "700",
    color: "#fff",
  },
  heroDate: {
    fontSize: 10,
    fontWeight: "500",
    color: "rgba(255,255,255,0.78)",
  },
  body: {
    paddingHorizontal: 18,
    paddingTop: 14,
    paddingBottom: 10,
    gap: 10,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    minHeight: 20,
  },
  sectionLabel: {
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 1.2,
    textTransform: "uppercase",
    color: Theme.textMuted,
  },
  offerPill: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
    backgroundColor: "#f1f5f9",
  },
  offerPillText: {
    fontSize: 10,
    fontWeight: "700",
    color: Theme.buttonMatteBlack,
  },
  payGrid: {
    flexDirection: "row",
    alignItems: "stretch",
    gap: 8,
  },
  payTile: {
    flex: 1,
    minWidth: 0,
    borderRadius: 14,
    borderWidth: StyleSheet.hairlineWidth,
    padding: 11,
    gap: 3,
    justifyContent: "flex-start",
  },
  payTileAccent: {
    backgroundColor: "#f1f5f9",
    borderColor: Theme.borderMedium,
  },
  payTileNeutral: {
    backgroundColor: Theme.surface,
    borderColor: Theme.borderLight,
  },
  payTileIconWrap: {
    width: 28,
    height: 28,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 2,
    backgroundColor: Theme.cardWhite,
  },
  payTileIconOnAccent: {
    backgroundColor: "#fff",
  },
  payTileAmount: {
    fontSize: 20,
    fontWeight: "900",
    letterSpacing: -0.4,
    lineHeight: 24,
    color: Theme.textPrimaryDark,
    fontVariant: ["tabular-nums"],
  },
  payTileLabel: {
    fontSize: 9,
    fontWeight: "800",
    letterSpacing: 0.6,
    textTransform: "uppercase",
    color: Theme.buttonMatteBlack,
  },
  payTileHint: {
    fontSize: 10,
    lineHeight: 13,
    fontWeight: "400",
    color: Theme.textMuted,
  },
  routeRow: {
    marginTop: -2,
    marginBottom: -2,
  },
  metaRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    minHeight: 24,
  },
  metaText: {
    flex: 1,
    minWidth: 0,
    fontSize: 10,
    fontWeight: "600",
    color: Theme.textMuted,
    fontVariant: ["tabular-nums"],
  },
  statusPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: "#f1f5f9",
    borderWidth: 1,
    borderColor: Theme.borderMedium,
    flexShrink: 0,
  },
  statusPillText: {
    fontSize: 8,
    fontWeight: "800",
    letterSpacing: 0.35,
    textTransform: "uppercase",
    color: Theme.buttonMatteBlack,
  },
  nextCard: {
    borderRadius: 12,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: Theme.borderLight,
    backgroundColor: Theme.surface,
    padding: 11,
    gap: 6,
  },
  nextTitle: {
    fontSize: 11,
    fontWeight: "700",
    color: Theme.textPrimaryDark,
    marginBottom: 0,
  },
  nextRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 6,
  },
  nextText: {
    flex: 1,
    minWidth: 0,
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "400",
    color: Theme.textMuted,
  },
  footer: {
    paddingHorizontal: 18,
    paddingTop: 10,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: Theme.borderLight,
  },
  actions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  laterBtnOutline: {
    flex: 1,
    height: 46,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    backgroundColor: Theme.surface,
    alignItems: "center",
    justifyContent: "center",
  },
  laterBtnOutlineText: {
    fontSize: 14,
    fontWeight: "600",
    color: Theme.textMuted,
  },
  assignBtn: {
    flex: 1.55,
    height: 46,
    borderRadius: 12,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: Theme.financeHeroBorder,
  },
  assignGradient: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingHorizontal: 10,
    minHeight: 46,
  },
  assignText: {
    fontSize: 14,
    fontWeight: "800",
    color: Theme.textOnDark,
    letterSpacing: -0.2,
  },
  viewLoadBtn: {
    alignItems: "center",
    paddingVertical: 10,
  },
  viewLoadText: {
    fontSize: 13,
    fontWeight: "500",
    color: Theme.textMuted,
  },
});
