/**
 * Ops Agent styles — theme-dependent StyleSheet for the chat UI.
 */
import { Platform, StyleSheet } from "react-native";
import { FONT, SP } from "./constants";
import type { OpsRef } from "./types";

export function getOpsAgentStyles(ref: OpsRef) {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: ref.bg,
    },
    successToast: {
      position: "absolute",
      left: SP.lg,
      right: SP.lg,
      zIndex: 300,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: SP.sm,
      backgroundColor: ref.bg,
      paddingVertical: SP.md,
      paddingHorizontal: SP.xl,
      borderRadius: 24,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: ref.border,
      ...ref.shadow,
    },
    successToastText: {
      fontSize: 13,
      fontFamily: FONT.semiBold,
      color: ref.text,
      letterSpacing: 0.3,
    },
    keyboardView: { flex: 1 },
    messageList: { flex: 1, backgroundColor: ref.bg },
    messageListContent: {
      paddingHorizontal: SP.lg,
      paddingTop: SP.md,
      paddingBottom: SP.md,
      minHeight: 120,
    },
    refHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: SP.lg,
      paddingBottom: SP.md,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: ref.border,
      backgroundColor: ref.bg,
    },
    refHeaderLeft: { flexDirection: "row", alignItems: "center", gap: SP.sm },
    refBackBtn: { padding: SP.xs },
    refStatusDot: {
      width: 6,
      height: 6,
      borderRadius: 3,
      backgroundColor: ref.green,
      ...(Platform.OS === "ios"
        ? { shadowColor: ref.green, shadowOffset: { width: 0, height: 0 }, shadowOpacity: 0.6, shadowRadius: 4 }
        : {}),
    },
    refHeaderTitle: { fontSize: 15, fontFamily: FONT.semiBold, color: ref.text, letterSpacing: 0.2 },
    refHeaderMeta: { fontSize: 11, fontFamily: FONT.regular, color: ref.text2, letterSpacing: 0.3 },
    refHeaderRight: { flexDirection: "row", alignItems: "center", gap: SP.sm },
    refHeaderBtn: {
      paddingVertical: SP.sm,
      paddingHorizontal: SP.md,
      borderRadius: ref.radiusSm,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: ref.border2,
    },
    refAvatar: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: ref.accent,
      alignItems: "center",
      justifyContent: "center",
    },
    refAvatarText: { fontSize: 12, fontFamily: FONT.bold, color: ref.textOnAccent },
    emptyState: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: SP.xxl * 2,
      paddingHorizontal: SP.xl,
    },
    emptyIcon: {
      width: 120,
      height: 144,
      borderRadius: 20,
      backgroundColor: "#000000",
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: ref.border,
      alignItems: "center",
      justifyContent: "center",
      marginBottom: SP.xl,
      ...ref.shadowSm,
    },
    emptyIconEmoji: { fontSize: 28 },
    emptyTitle: {
      fontSize: 20,
      fontFamily: FONT.bold,
      color: ref.text,
      marginBottom: SP.sm,
      textAlign: "center",
      letterSpacing: 0.15,
    },
    emptySub: {
      fontSize: 14,
      fontFamily: FONT.regular,
      color: ref.text2,
      textAlign: "center",
      maxWidth: 340,
      lineHeight: 22,
      marginBottom: SP.xl,
      letterSpacing: 0.1,
    },
    quickPills: {
      flexDirection: "row",
      flexWrap: "wrap",
      justifyContent: "center",
      gap: SP.sm,
      maxWidth: 460,
    },
    quickPill: {
      paddingVertical: SP.sm,
      paddingHorizontal: SP.md,
      borderRadius: 20,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: ref.border,
      backgroundColor: ref.surface2,
      ...ref.shadowSm,
    },
    quickPillText: { fontSize: 13, fontFamily: FONT.medium, color: ref.text2, letterSpacing: 0.1 },
    messageRow: {
      flexDirection: "row",
      alignItems: "flex-start",
      marginBottom: SP.sm,
      gap: SP.sm,
      paddingVertical: 2,
    },
    messageRowUser: { flexDirection: "row-reverse" },
    messageRowSystem: {},
    msgAvatar: {
      width: 28,
      height: 28,
      borderRadius: 10,
      alignItems: "center",
      justifyContent: "center",
      overflow: "hidden",
    },
    msgAvatarAgent: {
      backgroundColor: "#000000",
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: ref.border2,
    },
    msgAvatarUser: { backgroundColor: ref.accent },
    msgAvatarText: { fontSize: 9, fontFamily: FONT.bold, color: ref.accent },
    msgAvatarTextUser: { fontFamily: FONT.bold, color: ref.text, fontSize: 12 },
    msgBody: { flex: 1, minWidth: 0, maxWidth: "85%" },
    msgBodyUser: { alignItems: "flex-end" },
    msgBodySystem: { alignItems: "flex-start" },
    msgMeta: { flexDirection: "row", alignItems: "center", gap: SP.xs, marginBottom: 3 },
    msgMetaEnd: { justifyContent: "flex-end" },
    msgName: {
      fontSize: 9,
      fontFamily: FONT.semiBold,
      color: ref.text3,
      textTransform: "uppercase",
      letterSpacing: 0.5,
    },
    msgTime: { fontSize: 9, fontFamily: FONT.regular, color: ref.text3, letterSpacing: 0.2 },
    msgActionsRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: SP.lg,
      marginTop: 4,
    },
    msgActionsRowEnd: { justifyContent: "flex-end" },
    msgActionBtn: { padding: 4, borderRadius: 6 },
    quBubble: {
      maxWidth: "100%",
      paddingVertical: SP.sm,
      paddingHorizontal: SP.md,
      borderRadius: ref.radius,
      borderWidth: StyleSheet.hairlineWidth,
    },
    quBubbleUser: {
      borderBottomRightRadius: 6,
      ...ref.shadowSm,
    },
    quBubbleBot: {
      backgroundColor: ref.surface,
      borderColor: ref.border,
    },
    quBubbleText: {
      fontSize: 14,
      fontFamily: FONT.regular,
      color: ref.text,
      lineHeight: 20,
      letterSpacing: 0.05,
    },
    quBubbleTextUser: { fontFamily: FONT.regular, color: ref.text },
    quAttachmentImage: {
      marginTop: 12,
      borderRadius: 16,
      overflow: "hidden",
      borderWidth: 1,
      borderColor: ref.border2,
      height: 120,
      width: "100%",
    },
    quAttachmentImageImg: { width: "100%", height: "100%" },
    quAttachmentImagePlaceholder: {
      width: "100%",
      height: "100%",
      backgroundColor: ref.imagePlaceholderOverlay,
      alignItems: "center",
      justifyContent: "center",
    },
    quAttachmentContact: {
      marginTop: 12,
      flexDirection: "row",
      alignItems: "center",
      gap: 16,
      padding: 16,
      backgroundColor: ref.contactCardBg,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: ref.contactCardBorder,
    },
    quAttachmentContactIcon: {
      width: 40,
      height: 40,
      borderRadius: 12,
      backgroundColor: ref.accent,
      alignItems: "center",
      justifyContent: "center",
    },
    quAttachmentContactInfo: { flex: 1 },
    quAttachmentContactName: {
      fontSize: 11,
      fontFamily: FONT.bold,
      fontStyle: "italic",
      color: ref.text,
    },
    quAttachmentContactRole: {
      fontSize: 8,
      fontFamily: FONT.bold,
      color: ref.text2,
      marginTop: 4,
    },
    reportCard: {
      marginTop: SP.md,
      backgroundColor: ref.cardBg,
      borderRadius: ref.radiusLg,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: ref.cardBorder,
      overflow: "hidden",
      maxWidth: 480,
      maxHeight: 320,
      ...ref.shadow,
    },
    reportCardHeader: {
      flexDirection: "row",
      alignItems: "center",
      gap: SP.sm,
      padding: SP.md,
      paddingHorizontal: SP.lg,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: ref.border,
    },
    reportCardTitle: {
      fontSize: 14,
      fontFamily: FONT.semiBold,
      color: ref.text,
      marginBottom: 2,
      letterSpacing: 0.1,
    },
    reportCardDate: {
      fontSize: 11,
      fontFamily: FONT.regular,
      color: ref.text3,
      letterSpacing: 0.2,
    },
    reportIconBox: {
      width: 36,
      height: 36,
      borderRadius: 12,
      backgroundColor: ref.amberSoft,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: ref.border2,
      alignItems: "center",
      justifyContent: "center",
    },
    reportIconEmoji: { fontSize: 14 },
    reportTitleBlock: {},
    reportCardScroll: { maxHeight: 200, marginBottom: 12 },
    reportSection: { marginBottom: 12 },
    reportSectionTitle: {
      fontSize: 10,
      fontFamily: FONT.bold,
      color: ref.text3,
      textTransform: "uppercase",
      letterSpacing: 0.8,
      marginBottom: 6,
    },
    reportSectionBody: {
      fontSize: 13,
      fontFamily: FONT.regular,
      color: ref.text2,
      lineHeight: 20,
    },
    reportTable: {
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: ref.border,
      borderRadius: 6,
      overflow: "hidden",
    },
    reportTableHeaderRow: {
      flexDirection: "row",
      backgroundColor: ref.border2,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: ref.border,
    },
    reportTableHeaderCell: {
      flex: 1,
      fontSize: 10,
      fontFamily: FONT.bold,
      color: ref.text3,
      textTransform: "uppercase",
      letterSpacing: 0.5,
      paddingVertical: 8,
      paddingHorizontal: 10,
    },
    reportTableRow: {
      flexDirection: "row",
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: ref.border,
    },
    reportTableCell: {
      flex: 1,
      fontSize: 12,
      fontFamily: FONT.regular,
      color: ref.text2,
      paddingVertical: 6,
      paddingHorizontal: 10,
    },
    reportTableCellRight: { textAlign: "right" as const },
    reportDownloadBtn: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      paddingVertical: 10,
      paddingHorizontal: 16,
      margin: 10,
      marginHorizontal: 16,
      marginBottom: 14,
      backgroundColor: ref.amberSoft,
      borderWidth: 1,
      borderColor: ref.border2,
      borderRadius: ref.radiusSm,
    },
    reportDownloadBtnText: {
      fontSize: 13,
      fontFamily: FONT.semiBold,
      color: ref.amber,
    },
    previewCard: {
      marginTop: SP.md,
      backgroundColor: ref.cardBg,
      borderRadius: ref.radiusLg,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: ref.cardBorder,
      overflow: "hidden",
      ...ref.shadow,
    },
    previewCardHeader: {
      padding: SP.md,
      paddingHorizontal: SP.lg,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: ref.border,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    previewCardTitle: {
      fontSize: 14,
      fontFamily: FONT.semiBold,
      color: ref.text,
      marginBottom: 2,
      letterSpacing: 0.1,
    },
    previewCardHint: {
      fontSize: 11,
      fontFamily: FONT.regular,
      color: ref.text2,
      lineHeight: 16,
      letterSpacing: 0.1,
    },
    previewSummaryCard: {
      marginTop: 4,
      backgroundColor: ref.surface,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: ref.border,
      overflow: "hidden",
    },
    previewSummaryHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingVertical: 10,
      paddingHorizontal: 14,
      borderBottomWidth: 1,
      borderBottomColor: ref.border,
    },
    previewBadge: {
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 6,
      backgroundColor: ref.accentSoft,
    },
    previewBadgeText: {
      fontSize: 11,
      fontFamily: FONT.bold,
      color: ref.accent,
      textTransform: "uppercase",
      letterSpacing: 0.5,
    },
    previewEditLink: {
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
      paddingVertical: 4,
      paddingHorizontal: 8,
    },
    previewEditLinkText: {
      fontSize: 12,
      fontFamily: FONT.semiBold,
      color: ref.accent,
    },
    previewSummaryBody: { padding: 14, gap: 0 },
    previewSummaryRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingVertical: 8,
      borderBottomWidth: 1,
      borderBottomColor: ref.border,
    },
    previewSummaryRowLast: { borderBottomWidth: 0 },
    previewSummaryLabel: {
      fontSize: 11,
      fontFamily: FONT.semiBold,
      color: ref.text3,
      textTransform: "uppercase",
      letterSpacing: 0.3,
      marginRight: 12,
    },
    previewSummaryValue: {
      flex: 1,
      fontSize: 13,
      fontFamily: FONT.semiBold,
      color: ref.text,
      textAlign: "right",
    },
    quTypingBubble: {
      paddingVertical: SP.lg,
      paddingHorizontal: SP.xl,
      borderRadius: ref.radiusLg,
      borderWidth: StyleSheet.hairlineWidth,
      borderTopLeftRadius: 6,
    },
    quTypingDot: {
      backgroundColor: ref.accent,
      width: 5,
      height: 5,
      borderRadius: 2.5,
    },
    typingDots: { flexDirection: "row", alignItems: "center", gap: 6 },
    typingDot: { width: 6, height: 6, borderRadius: 3, opacity: 0.5 },
    typingDot2: { opacity: 0.75 },
    typingDot3: { opacity: 1 },
    reattemptBubble: { paddingVertical: SP.sm, paddingHorizontal: SP.sm },
    reattemptBtn: {
      flexDirection: "row",
      alignItems: "center",
      gap: SP.sm,
      paddingVertical: SP.sm,
      paddingHorizontal: SP.md,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: ref.accent,
      borderRadius: ref.radiusSm,
      alignSelf: "flex-start",
    },
    reattemptBtnText: { fontSize: 12, fontFamily: FONT.semiBold, color: ref.accent },
    editMessageWrap: { gap: SP.md },
    editMessageInput: {
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: ref.editInputBorder,
      backgroundColor: ref.editInputBg,
      borderRadius: ref.radiusSm,
      paddingHorizontal: SP.md,
      paddingVertical: SP.sm,
      fontSize: 14,
      fontFamily: FONT.regular,
      color: ref.text,
      minHeight: 48,
      maxHeight: 100,
    },
    editMessageActions: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "flex-end",
      gap: SP.sm,
      marginTop: SP.sm,
    },
    editMessageBtnCancel: {
      paddingVertical: SP.sm,
      paddingHorizontal: SP.lg,
      borderRadius: ref.radiusSm,
      backgroundColor: ref.surfaceOverlay,
    },
    editMessageBtnCancelText: {
      fontSize: 13,
      fontFamily: FONT.medium,
      color: ref.surfaceOverlayText,
    },
    editMessageBtnSend: {
      paddingVertical: SP.sm,
      paddingHorizontal: SP.lg,
      borderRadius: ref.radiusSm,
      backgroundColor: ref.bg,
    },
    editMessageBtnSendDisabled: { backgroundColor: ref.surface3, opacity: 0.8 },
    editMessageBtnSendText: { fontSize: 13, fontFamily: FONT.semiBold, color: ref.text },
    errorText: {
      fontSize: 12,
      fontFamily: FONT.regular,
      color: ref.red,
      marginBottom: 8,
      paddingHorizontal: 4,
    },
    quInputWrap: {
      paddingHorizontal: SP.lg,
      paddingTop: SP.sm,
      paddingBottom: SP.sm,
      backgroundColor: ref.bg,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: ref.border,
    },
    quAttachmentStrip: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      backgroundColor: ref.surface2,
      paddingVertical: 8,
      paddingHorizontal: 10,
      borderRadius: 12,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: ref.border,
      marginBottom: 6,
    },
    quAttachmentStripLeft: { flexDirection: "row", alignItems: "center", gap: 8 },
    quAttachmentStripText: {
      fontSize: 10,
      fontFamily: FONT.bold,
      color: ref.accent,
      letterSpacing: 0.5,
    },
    quAttachmentStripRemove: {
      width: 22,
      height: 22,
      borderRadius: 11,
      backgroundColor: "rgba(239,68,68,0.15)",
      alignItems: "center",
      justifyContent: "center",
    },
    quInputRow: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: ref.inputBg,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: ref.border,
      borderRadius: ref.radiusXl,
      paddingLeft: SP.xs,
      paddingRight: SP.xs,
      paddingVertical: SP.xs,
      minHeight: 44,
      ...ref.shadow,
    },
    quInputPlusBtn: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: ref.surface3,
      alignItems: "center",
      justifyContent: "center",
      marginRight: SP.sm,
    },
    quInputPlusBtnActive: { backgroundColor: ref.accentSoft },
    quInput: {
      flex: 1,
      fontSize: 15,
      fontFamily: FONT.regular,
      color: ref.text,
      paddingVertical: SP.sm,
      paddingRight: SP.xs,
      paddingLeft: SP.xs,
      maxHeight: 88,
      letterSpacing: 0.1,
    },
    quInputActionBtn: {
      width: 32,
      height: 32,
      borderRadius: 10,
      backgroundColor: "transparent",
      alignItems: "center",
      justifyContent: "center",
    },
    quSendBtn: {
      width: 40,
      height: 40,
      borderRadius: 20,
      alignItems: "center",
      justifyContent: "center",
      ...ref.shadowSm,
    },
    quSendBtnActive: { backgroundColor: ref.accent },
    quSendBtnDisabled: { backgroundColor: ref.surface3 },
    attachMenu: {
      backgroundColor: ref.surface2,
      borderRadius: ref.radiusLg,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: ref.border,
      marginBottom: SP.sm,
      paddingVertical: SP.xs,
      ...ref.shadow,
    },
    attachMenuItem: {
      flexDirection: "row",
      alignItems: "center",
      gap: SP.md,
      paddingVertical: SP.sm,
      paddingHorizontal: SP.lg,
    },
    attachMenuItemText: {
      fontSize: 14,
      fontFamily: FONT.regular,
      color: ref.text2,
    },
    attachMenuDivider: {
      height: StyleSheet.hairlineWidth,
      backgroundColor: ref.border,
      marginVertical: SP.xs,
      marginHorizontal: SP.lg,
    },
    modalField: { marginBottom: SP.md },
    modalLabel: {
      fontSize: 10,
      fontFamily: FONT.semiBold,
      color: ref.text3,
      marginBottom: SP.xs + 1,
      textTransform: "uppercase",
      letterSpacing: 0.8,
    },
    modalInput: {
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: ref.border2,
      backgroundColor: ref.surface2,
      borderRadius: ref.radiusSm,
      paddingHorizontal: SP.md,
      paddingVertical: SP.sm + 1,
      fontSize: 14,
      fontFamily: FONT.regular,
      color: ref.text,
    },
    modalActions: {
      flexDirection: "row",
      justifyContent: "flex-end",
      alignItems: "center",
      gap: SP.sm,
      paddingVertical: SP.sm,
      paddingHorizontal: SP.lg,
      paddingBottom: SP.md,
    },
    modalBtnCancel: {
      paddingVertical: SP.sm + 1,
      paddingHorizontal: SP.lg,
      backgroundColor: "transparent",
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: ref.border2,
      borderRadius: ref.radiusSm,
    },
    modalBtnCancelText: {
      fontSize: 13,
      fontFamily: FONT.medium,
      color: ref.text2,
    },
    modalBtnConfirm: {
      flex: 1,
      paddingVertical: SP.sm + 1,
      paddingHorizontal: SP.lg,
      backgroundColor: ref.accent,
      borderRadius: ref.radiusSm,
      alignItems: "center",
      justifyContent: "center",
    },
    modalBtnConfirmText: {
      fontSize: 13,
      fontFamily: FONT.semiBold,
      color: ref.textOnAccent,
    },
  });
}

export type OpsAgentStyles = ReturnType<typeof getOpsAgentStyles>;
