import Layout from "@/constants/Layout";
import Theme from "@/constants/Theme";
import { StyleSheet } from "react-native";

const H = Layout.entityHero;

/**
 * Shared shell + typography for the profile column on entity detail screens.
 * Sizes come from Layout.entityHero so all entities stay visually aligned.
 */
export const entityCompanionCardStyles = StyleSheet.create({
  card: {
    flex: H.profileFlex,
    minHeight: H.columnMinHeightDesktop,
    alignSelf: "stretch",
    borderRadius: H.profileRadius,
    backgroundColor: Theme.screenBackground,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    paddingHorizontal: H.profilePaddingHorizontal,
    paddingVertical: H.profilePaddingVertical,
    shadowColor: "rgba(148, 163, 184, 0.35)",
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.45,
    shadowRadius: 20,
    boxShadow:
      "0 20px 25px -5px rgba(226, 232, 240, 0.5), 0 8px 10px -6px rgba(226, 232, 240, 0.4)",
    elevation: 6,
    justifyContent: "flex-start",
    gap: H.profileGap,
  },
  dossierHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    marginBottom: 2,
  },
  dossierIdentity: {
    alignItems: "center",
    paddingTop: 4,
    paddingBottom: 2,
  },
  dossierAvatarWrap: {
    width: 68,
    height: 62,
    borderRadius: 22,
    backgroundColor: Theme.textPrimaryDark,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
    shadowColor: Theme.shadow,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.16,
    shadowRadius: 22,
    elevation: 4,
  },
  dossierAvatarImage: {
    width: "100%",
    height: "100%",
    borderRadius: 22,
  },
  dossierAvatarBadge: {
    position: "absolute",
    right: -5,
    top: -5,
    width: 22,
    height: 22,
    borderRadius: 8,
    backgroundColor: Theme.positive,
    borderWidth: 3,
    borderColor: Theme.screenBackground,
    alignItems: "center",
    justifyContent: "center",
  },
  dossierName: {
    fontSize: 16,
    fontWeight: "900",
    fontStyle: "italic",
    letterSpacing: -0.3,
    color: Theme.textPrimaryDark,
    textTransform: "uppercase",
    textAlign: "center",
  },
  dossierSub: {
    marginTop: 3,
    fontSize: 9,
    fontWeight: "700",
    color: Theme.textMuted,
    textAlign: "center",
  },
  dossierBadgeRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: 5,
    marginTop: 8,
  },
  dossierBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    borderWidth: 1,
  },
  dossierBadgeBlue: {
    backgroundColor: Theme.aggregatePillBg,
    borderColor: Theme.aggregatePillBorder,
  },
  dossierBadgeDark: {
    backgroundColor: Theme.textPrimaryDark,
    borderColor: Theme.textPrimaryDark,
  },
  dossierBadgeMuted: {
    backgroundColor: Theme.surface,
    borderColor: Theme.borderLight,
  },
  dossierBadgeText: {
    fontSize: 7,
    fontWeight: "900",
    letterSpacing: 0.8,
    textTransform: "uppercase",
    color: Theme.aggregatePillText,
  },
  dossierBadgeTextDark: {
    color: Theme.textOnPrimary,
  },
  dossierBadgeTextMuted: {
    color: Theme.textMuted,
  },
  dossierInfoRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: 10,
    width: "100%",
  },
  dossierStatGrid: {
    flexDirection: "row",
    gap: 6,
    width: "100%",
  },
  dossierStatCard: {
    flex: 1,
    minWidth: 0,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    backgroundColor: Theme.surface,
    paddingVertical: 8,
    paddingHorizontal: 6,
    alignItems: "center",
  },
  dossierStatValue: {
    fontSize: 12,
    fontWeight: "900",
    color: Theme.textPrimaryDark,
    letterSpacing: -0.2,
  },
  dossierStatLabel: {
    marginTop: 3,
    fontSize: 6,
    fontWeight: "900",
    color: Theme.textMuted,
    letterSpacing: 0.7,
    textTransform: "uppercase",
    textAlign: "center",
  },
  dossierContactStack: {
    flexDirection: "row",
    gap: 8,
    width: "100%",
  },
  dossierContactRow: {
    flex: 1,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderWidth: 1,
    borderColor: Theme.surfaceBorder,
    backgroundColor: Theme.screenBackground,
    borderRadius: 14,
    paddingHorizontal: 8,
    paddingVertical: 8,
    minHeight: 58,
  },
  dossierContactIcon: {
    width: 26,
    height: 26,
    borderRadius: 9,
    backgroundColor: Theme.surface,
    alignItems: "center",
    justifyContent: "center",
  },
  dossierContactText: {
    flex: 1,
    minWidth: 0,
  },
  dossierContactLabel: {
    fontSize: 6,
    fontWeight: "900",
    color: Theme.textMuted,
    letterSpacing: 0.9,
    textTransform: "uppercase",
    marginBottom: 2,
  },
  dossierContactValue: {
    fontSize: 8,
    fontWeight: "800",
    color: Theme.textPrimaryDark,
  },
  dossierWorkloadBlock: {
    width: "100%",
    paddingHorizontal: 2,
  },
  dossierWorkloadHead: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    marginBottom: 6,
  },
  dossierWorkloadLabel: {
    fontSize: 7,
    fontWeight: "900",
    color: Theme.textMuted,
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  dossierWorkloadStatus: {
    fontSize: 7,
    fontWeight: "900",
    color: Theme.primary,
    letterSpacing: 0.8,
    textTransform: "uppercase",
    fontStyle: "italic",
  },
  dossierWorkloadBars: {
    flexDirection: "row",
    gap: 3,
    height: 5,
  },
  dossierWorkloadBar: {
    flex: 1,
    borderRadius: 999,
    backgroundColor: Theme.surfaceBorder,
  },
  dossierWorkloadBarOn: {
    backgroundColor: Theme.buttonPrimary,
  },
  eyebrow: {
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 2,
    color: Theme.textMuted,
    textTransform: "uppercase",
  },
  identityRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: -2,
  },
  identityAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: Theme.surfaceGray,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    borderWidth: 1,
    borderColor: Theme.borderLight,
  },
  identityAvatarImage: {
    width: "100%",
    height: "100%",
  },
  identityMeta: {
    flex: 1,
    minWidth: 0,
  },
  identityName: {
    fontSize: 10,
    fontWeight: "800",
    color: Theme.textPrimaryDark,
  },
  identitySub: {
    marginTop: 1,
    fontSize: 8,
    fontWeight: "600",
    color: Theme.textMuted,
  },
  ratingRow: {
    flexShrink: 0,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    width: "auto",
    gap: 10,
    marginTop: 0,
  },
  stars: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
  },
  ratingBadge: {
    borderRadius: 8,
    minWidth: 36,
    paddingHorizontal: 8,
    paddingVertical: 3,
    backgroundColor: Theme.surfaceGray,
    alignItems: "center",
    justifyContent: "center",
  },
  ratingBadgeText: {
    fontSize: 11,
    fontWeight: "900",
    color: Theme.textSecondary,
  },
  experienceBlock: {
    marginBottom: 0,
    flex: 1,
    minWidth: 0,
    width: "auto",
    alignItems: "flex-end",
  },
  tripCountOnly: {
    flex: 0,
    minWidth: 38,
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 3,
    backgroundColor: Theme.surfaceGray,
    alignItems: "center",
    justifyContent: "center",
  },
  experienceEyebrow: {
    fontSize: 8,
    fontWeight: "900",
    letterSpacing: 1.6,
    color: Theme.textMuted,
    textTransform: "uppercase",
    marginBottom: 3,
  },
  experienceRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 8,
    width: "auto",
    maxWidth: "100%",
  },
  experienceIconWrap: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Theme.darkBackground,
    borderWidth: 0,
  },
  tripsNumber: {
    fontSize: 16,
    fontWeight: "900",
    color: Theme.textPrimaryDark,
    lineHeight: 18,
    minWidth: 0,
    textAlign: "center",
  },
  experienceLabel: {
    fontSize: 10,
    fontWeight: "800",
    color: Theme.textSecondary,
    letterSpacing: 0.2,
    marginBottom: 0,
    flexShrink: 1,
  },
  details: {
    borderTopWidth: 1,
    borderTopColor: Theme.surfaceBorder,
    borderBottomWidth: 1,
    borderBottomColor: Theme.surfaceBorder,
    paddingVertical: H.profileDetailsPaddingVertical,
    gap: H.profileDetailsGap,
    maxHeight: H.profileDetailsMaxHeight,
    overflow: "hidden",
  },
  detailRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 6,
  },
  detailLabel: {
    fontSize: 8,
    fontWeight: "900",
    letterSpacing: 0.8,
    color: Theme.textMuted,
    textTransform: "uppercase",
  },
  detailValue: {
    flex: 1,
    textAlign: "right",
    fontSize: H.profileDetailValueFontSize,
    fontWeight: "800",
    color: Theme.textPrimaryDark,
  },
  toggle: {
    width: "100%",
    backgroundColor: Theme.surfaceForm,
    borderWidth: 1,
    borderColor: Theme.surfaceBorder,
    borderRadius: 16,
    paddingHorizontal: H.togglePaddingHorizontal,
    paddingVertical: H.togglePaddingVertical,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  toggleTextWrap: {
    flex: 1,
    minWidth: 0,
  },
  toggleDot: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Theme.surfaceGray,
  },
  toggleDotActive: {
    borderColor: Theme.darkGreen,
    backgroundColor: Theme.darkGreen,
  },
  toggleTitle: {
    fontSize: 12,
    fontWeight: "900",
    letterSpacing: 0.5,
    textTransform: "uppercase",
    color: Theme.textPrimaryDark,
  },
  toggleSub: {
    fontSize: 8,
    fontWeight: "800",
    color: Theme.textSecondary,
    marginTop: 2,
  },
  actionBtn: {
    width: "100%",
    borderRadius: 16,
    paddingVertical: H.actionButtonPaddingVertical,
    minHeight: H.actionButtonMinHeight,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
    marginTop: "auto",
  },
  /** Black CTA on all entity profile cards (client / supplier / driver / vehicle) */
  actionBtnPrimary: {
    backgroundColor: Theme.darkBackground,
  },
  actionBtnDisabled: {
    backgroundColor: Theme.textSecondary,
  },
  actionText: {
    fontSize: 10,
    fontWeight: "900",
    textTransform: "uppercase",
    letterSpacing: 1.4,
    color: Theme.textOnPrimary,
  },
});
