import Theme from "@/constants/Theme";
import { StyleSheet } from "react-native";

/** Icon on light-blue outline download buttons — ink for contrast. */
export const entityDetailDownloadIconColor = Theme.buttonPrimaryText;

/**
 * Shared chrome for Client / Supplier entity detail pages (mobile-first compact).
 * Financial hero sizes live in entityHeroScorecard.styles.ts.
 */
export const entityDetailPageChromeStyles = StyleSheet.create({
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 12,
    paddingVertical: 10,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(0,0,0,0.05)",
    backgroundColor: "rgba(255,255,255,0.6)",
  },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: Theme.surfaceGray,
    alignItems: "center",
    justifyContent: "center",
  },
  headerCenter: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 6,
  },
  headerTitle: {
    fontSize: 14,
    fontWeight: "800",
    fontStyle: "italic",
    color: Theme.textPrimaryDark,
    textTransform: "uppercase",
    letterSpacing: -0.35,
  },
  headerSubtitle: {
    fontSize: 7,
    fontWeight: "700",
    color: Theme.textMuted,
    letterSpacing: 1,
    marginTop: 2,
  },
  headerRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  downloadBtn: {
    width: 36,
    height: 36,
    borderRadius: Theme.buttonPrimaryRadius,
    backgroundColor: Theme.buttonPrimary,
    borderWidth: Theme.buttonPrimaryBorderWidth,
    borderColor: Theme.buttonPrimaryBorder,
    alignItems: "center",
    justifyContent: "center",
  },
  profileBtn: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: Theme.surfaceGray,
    alignItems: "center",
    justifyContent: "center",
  },
  scrollContent: {
    paddingTop: 8,
  },
  tabRow: {
    flexDirection: "row",
    backgroundColor: Theme.surfaceGray,
    padding: 3,
    borderRadius: 14,
    marginBottom: 6,
    gap: 3,
  },
  tripDatePillWrap: {
    paddingHorizontal: 2,
    marginBottom: 4,
    marginTop: -2,
  },
  tabItem: {
    flex: 1,
    paddingVertical: 7,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    minHeight: 34,
  },
  tabItemActive: {
    backgroundColor: Theme.screenBackground,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  tabItemText: {
    fontSize: 8,
    fontWeight: "700",
    color: Theme.textMuted,
    letterSpacing: 0.35,
  },
  tabItemTextActive: {
    color: Theme.textPrimaryDark,
  },
  tableCard: {
    backgroundColor: Theme.screenBackground,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    borderRadius: 16,
    overflow: "hidden",
  },
  tableHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 8,
    paddingHorizontal: 10,
    backgroundColor: Theme.surfaceLight,
    borderBottomWidth: 1,
    borderBottomColor: Theme.borderLight,
    gap: 6,
  },
  th: {
    fontSize: 9,
    fontWeight: "600",
    fontStyle: "normal",
    color: Theme.textSecondary,
    letterSpacing: 0.45,
    textTransform: "uppercase",
  },
  headerAmountCol: {
    flexGrow: 0,
    flexShrink: 0,
    width: 80,
    alignItems: "flex-end",
    justifyContent: "center",
  },
  amountCol: {
    flexGrow: 0,
    flexShrink: 0,
    width: 80,
    alignItems: "flex-end",
    justifyContent: "center",
  },
  /** Desktop trip table — proportional columns that fill the row (no maxWidth gaps). */
  tripColDesktop: {
    flexGrow: 1.45,
    flexShrink: 1,
    flexBasis: 0,
    minWidth: 160,
    paddingRight: 12,
    justifyContent: "center",
  },
  tripPartyColDesktop: {
    flexGrow: 1.15,
    flexShrink: 1,
    flexBasis: 0,
    minWidth: 128,
    paddingHorizontal: 12,
    justifyContent: "center",
    borderLeftWidth: StyleSheet.hairlineWidth,
    borderLeftColor: Theme.borderMedium,
  },
  tripDriverColDesktop: {
    flexGrow: 1.05,
    flexShrink: 1,
    flexBasis: 0,
    minWidth: 120,
    paddingHorizontal: 12,
    justifyContent: "center",
    borderLeftWidth: StyleSheet.hairlineWidth,
    borderLeftColor: Theme.borderMedium,
  },
  tripAmountColDesktop: {
    flexGrow: 0.85,
    flexShrink: 1,
    flexBasis: 0,
    minWidth: 92,
    paddingHorizontal: 10,
    alignItems: "flex-end",
    justifyContent: "center",
    borderLeftWidth: StyleSheet.hairlineWidth,
    borderLeftColor: Theme.borderMedium,
  },
  tripCountColDesktop: {
    flexGrow: 0.4,
    flexShrink: 0,
    flexBasis: 0,
    minWidth: 56,
    paddingHorizontal: 6,
    alignItems: "center",
    justifyContent: "center",
    borderLeftWidth: StyleSheet.hairlineWidth,
    borderLeftColor: Theme.borderMedium,
  },
  tripLastTxnColDesktop: {
    flexGrow: 0.55,
    flexShrink: 0,
    flexBasis: 0,
    minWidth: 80,
    paddingHorizontal: 10,
    alignItems: "flex-end",
    justifyContent: "center",
    borderLeftWidth: StyleSheet.hairlineWidth,
    borderLeftColor: Theme.borderMedium,
  },
  thCellRight: {
    width: "100%",
    textAlign: "right",
  },
  thCellCenter: {
    width: "100%",
    textAlign: "center",
  },
  thCellNowrap: {
    flexShrink: 0,
  },
  tdAmountRight: {
    width: "100%",
    textAlign: "right",
    fontVariant: ["tabular-nums"],
  },
  thMission: {
    flex: 1,
    minWidth: 0,
    paddingRight: 8,
  },
  tableRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 10,
    paddingHorizontal: 10,
    borderBottomWidth: 1,
    borderBottomColor: Theme.borderLight,
    gap: 6,
    minHeight: 52,
  },
  tableRowDesktop: {
    width: "100%",
    alignItems: "center",
    gap: 0,
    minHeight: 52,
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  tableHeaderDesktop: {
    width: "100%",
    alignItems: "center",
    gap: 0,
    minHeight: 40,
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  tableScrollDesktop: {
    width: "100%",
  },
  tableGridDesktop: {
    width: "100%",
    minWidth: "100%" as unknown as number,
    flexGrow: 1,
  },
  tableGridInnerDesktop: {
    width: "100%",
    minWidth: 1080,
    alignSelf: "stretch",
  },
  td: {
    fontSize: 11,
    fontWeight: "600",
    fontStyle: "normal",
    color: Theme.textPrimaryDark,
    fontVariant: ["tabular-nums"],
  },
  tdMissionId: {
    fontSize: 11,
    fontWeight: "700",
    fontStyle: "normal",
    color: Theme.textPrimaryDark,
    letterSpacing: -0.15,
  },
  tdMissionIdRow: {
    flexDirection: "row",
    alignItems: "baseline",
    flexWrap: "wrap",
    gap: 4,
    minWidth: 0,
    width: "100%",
  },
  tdMissionIdFlex: {
    flexShrink: 1,
    minWidth: 0,
    maxWidth: "100%",
  },
  tdMissionDateSep: {
    fontSize: 9,
    fontWeight: "500",
    color: Theme.textMuted,
    flexShrink: 0,
    opacity: 0.7,
  },
  tdMissionDate: {
    fontSize: 9,
    fontWeight: "400",
    fontStyle: "normal",
    color: Theme.textMuted,
    letterSpacing: 0.15,
    flexShrink: 0,
  },
  tdRoute: {
    fontSize: 10,
    fontWeight: "400",
    fontStyle: "normal",
    color: Theme.textMuted,
    lineHeight: 14,
    marginTop: 3,
  },
  emptyRow: {
    width: "100%",
    alignSelf: "stretch",
    paddingVertical: 36,
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
  },
  emptyRowText: {
    fontSize: 12,
    fontWeight: "600",
    fontStyle: "italic",
    color: Theme.textMuted,
    textAlign: "center",
  },
});
