import Theme from "@/constants/Theme";
import { StyleSheet } from "react-native";

/** Icon on light-blue outline download buttons — ink for contrast. */
export const entityDetailDownloadIconColor = Theme.buttonPrimaryText;

/**
 * Shared chrome for Client / Supplier entity detail pages (mobile-first compact).
 * Financial hero sizes live in entityHeroScorecard.styles.ts.
 */
export const entityDetailPageChromeStyles = StyleSheet.create({
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 12,
    paddingVertical: 10,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(0,0,0,0.05)",
    backgroundColor: "rgba(255,255,255,0.6)",
  },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: Theme.surfaceGray,
    alignItems: "center",
    justifyContent: "center",
  },
  headerCenter: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 6,
  },
  headerTitle: {
    fontSize: 14,
    fontWeight: "800",
    fontStyle: "italic",
    color: Theme.textPrimaryDark,
    textTransform: "uppercase",
    letterSpacing: -0.35,
  },
  headerSubtitle: {
    fontSize: 7,
    fontWeight: "700",
    color: Theme.textMuted,
    letterSpacing: 1,
    marginTop: 2,
  },
  headerRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  downloadBtn: {
    width: 36,
    height: 36,
    borderRadius: Theme.buttonPrimaryRadius,
    backgroundColor: Theme.buttonPrimary,
    borderWidth: Theme.buttonPrimaryBorderWidth,
    borderColor: Theme.buttonPrimaryBorder,
    alignItems: "center",
    justifyContent: "center",
  },
  profileBtn: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: Theme.surfaceGray,
    alignItems: "center",
    justifyContent: "center",
  },
  scrollContent: {
    paddingTop: 8,
  },
  tabRow: {
    flexDirection: "row",
    backgroundColor: Theme.surfaceGray,
    padding: 3,
    borderRadius: 14,
    marginBottom: 6,
    gap: 3,
  },
  tripDatePillWrap: {
    paddingHorizontal: 2,
    marginBottom: 4,
    marginTop: -2,
  },
  tabItem: {
    flex: 1,
    paddingVertical: 7,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    minHeight: 34,
  },
  tabItemActive: {
    backgroundColor: Theme.screenBackground,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  tabItemText: {
    fontSize: 8,
    fontWeight: "700",
    color: Theme.textMuted,
    letterSpacing: 0.35,
  },
  tabItemTextActive: {
    color: Theme.textPrimaryDark,
  },
  tableCard: {
    backgroundColor: Theme.screenBackground,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    borderRadius: 16,
    overflow: "hidden",
  },
  tableHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 8,
    paddingHorizontal: 10,
    backgroundColor: Theme.surfaceLight,
    borderBottomWidth: 1,
    borderBottomColor: Theme.borderLight,
    gap: 6,
  },
  th: {
    fontSize: 9,
    fontWeight: "600",
    fontStyle: "normal",
    color: Theme.textSecondary,
    letterSpacing: 0.45,
    textTransform: "uppercase",
  },
  headerAmountCol: {
    flexGrow: 0,
    flexShrink: 0,
    width: 80,
    alignItems: "flex-end",
    justifyContent: "center",
  },
  amountCol: {
    flexGrow: 0,
    flexShrink: 0,
    width: 80,
    alignItems: "flex-end",
    justifyContent: "center",
  },
  thMission: {
    flex: 1,
    minWidth: 0,
    paddingRight: 8,
  },
  tableRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 10,
    paddingHorizontal: 10,
    borderBottomWidth: 1,
    borderBottomColor: Theme.borderLight,
    gap: 6,
    minHeight: 52,
  },
  td: {
    fontSize: 11,
    fontWeight: "600",
    fontStyle: "normal",
    color: Theme.textPrimaryDark,
    fontVariant: ["tabular-nums"],
  },
  tdMissionId: {
    fontSize: 11,
    fontWeight: "700",
    fontStyle: "normal",
    color: Theme.textPrimaryDark,
    letterSpacing: -0.15,
  },
  tdMissionIdRow: {
    flexDirection: "row",
    alignItems: "baseline",
    flexWrap: "wrap",
    gap: 4,
    minWidth: 0,
    width: "100%",
  },
  tdMissionIdFlex: {
    flexShrink: 1,
    minWidth: 0,
    maxWidth: "100%",
  },
  tdMissionDateSep: {
    fontSize: 9,
    fontWeight: "500",
    color: Theme.textMuted,
    flexShrink: 0,
    opacity: 0.7,
  },
  tdMissionDate: {
    fontSize: 9,
    fontWeight: "400",
    fontStyle: "normal",
    color: Theme.textMuted,
    letterSpacing: 0.15,
    flexShrink: 0,
  },
  tdRoute: {
    fontSize: 10,
    fontWeight: "400",
    fontStyle: "normal",
    color: Theme.textMuted,
    lineHeight: 14,
    marginTop: 3,
  },
  emptyRow: {
    width: "100%",
    alignSelf: "stretch",
    paddingVertical: 36,
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
  },
  emptyRowText: {
    fontSize: 12,
    fontWeight: "600",
    fontStyle: "italic",
    color: Theme.textMuted,
    textAlign: "center",
  },
});
