/**
 * Shared dashboard chrome for Partner-style profile views (counterparty + driver).
 * Visual parity with CounterpartyProfileSystemCard view mode.
 */
import Theme from "@/constants/Theme";
import { Platform, StyleSheet } from "react-native";

export const partnerProfileDashboardStyles = StyleSheet.create({
  viewRoot: {
    flex: 1,
    backgroundColor: Theme.surface,
  },
  viewStickyHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: Theme.cardWhite,
    borderBottomWidth: 1,
    borderBottomColor: Theme.surfaceBorder,
    ...Platform.select({
      ios: {
        shadowColor: Theme.shadow,
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.06,
        shadowRadius: 6,
      },
      android: { elevation: 2 },
      default: {},
    }),
  },
  viewStickyLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flex: 1,
    minWidth: 0,
  },
  viewStickyTitle: {
    fontSize: 16,
    fontWeight: "900",
    fontStyle: "italic",
    color: Theme.textPrimaryDark,
    textTransform: "uppercase",
    letterSpacing: -0.6,
    flexShrink: 1,
  },
  viewStickyRight: { flexDirection: "row", alignItems: "center", gap: 8 },
  iconBtn: {
    width: 44,
    height: 44,
    borderRadius: 16,
    backgroundColor: Theme.surfaceGray,
    alignItems: "center",
    justifyContent: "center",
  },
  editProfileBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 22,
    backgroundColor: Theme.textPrimaryDark,
    ...Platform.select({
      ios: {
        shadowColor: Theme.shadow,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.12,
        shadowRadius: 10,
      },
      android: { elevation: 3 },
      default: {},
    }),
  },
  editProfileBtnText: {
    color: Theme.buttonDarkText,
    fontSize: 11,
    fontWeight: "900",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  viewScroll: { flex: 1 },
  viewScrollContent: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 32,
    maxWidth: 960,
    width: "100%",
    alignSelf: "center",
  },
  identityCard: {
    backgroundColor: Theme.cardWhite,
    borderRadius: 36,
    paddingVertical: 28,
    paddingHorizontal: 18,
    borderWidth: 1,
    borderColor: Theme.surfaceBorder,
    marginBottom: 20,
    overflow: "hidden",
    alignItems: "center",
    ...Platform.select({
      ios: {
        shadowColor: Theme.shadow,
        shadowOffset: { width: 0, height: 24 },
        shadowOpacity: 0.06,
        shadowRadius: 40,
      },
      android: { elevation: 4 },
      default: {},
    }),
  },
  identityBlob: {
    position: "absolute",
    top: -40,
    right: -40,
    width: 140,
    height: 140,
    borderBottomLeftRadius: 140,
    backgroundColor: Theme.fiscalTabActiveBg,
    opacity: 0.55,
  },
  avatarRing: {
    padding: 6,
    borderRadius: 100,
    backgroundColor: Theme.cardWhite,
    marginBottom: 12,
  },
  avatarCircle: {
    width: 88,
    height: 88,
    borderRadius: 44,
    backgroundColor: Theme.textPrimaryDark,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  avatarImage: {
    width: "100%",
    height: "100%",
    borderRadius: 44,
  },
  avatarInitials: {
    color: Theme.textOnPrimary,
    fontSize: 28,
    fontWeight: "900",
    fontStyle: "italic",
  },
  identityName: {
    fontSize: 22,
    fontWeight: "900",
    fontStyle: "italic",
    color: Theme.textPrimaryDark,
    textTransform: "uppercase",
    textAlign: "center",
    letterSpacing: -1,
    lineHeight: 26,
  },
  identityId: {
    marginTop: 4,
    fontSize: 14,
    fontWeight: "900",
    fontStyle: "italic",
    color: Theme.aggregatePillText,
  },
  identityBadgeRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: 8,
    marginTop: 14,
  },
  pillEmerald: {
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: Theme.positiveMuted,
    borderWidth: 1,
    borderColor: Theme.positive + "33",
  },
  pillEmeraldText: {
    fontSize: 10,
    fontWeight: "900",
    color: Theme.positive,
    textTransform: "uppercase",
  },
  pillIndigo: {
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: Theme.fiscalTabActiveBg,
    borderWidth: 1,
    borderColor: Theme.borderMedium,
  },
  pillIndigoMuted: { backgroundColor: Theme.surfaceGray },
  pillIndigoText: {
    fontSize: 10,
    fontWeight: "900",
    color: Theme.aggregatePillText,
    textTransform: "uppercase",
  },
  pillIndigoTextMuted: { color: Theme.textMuted },
  completionBlock: { width: "100%", maxWidth: 360, marginTop: 18 },
  completionHead: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
    paddingHorizontal: 2,
    marginBottom: 6,
  },
  completionLabel: {
    fontSize: 10,
    fontWeight: "900",
    color: Theme.textMuted,
    textTransform: "uppercase",
    letterSpacing: 1.2,
  },
  completionPct: {
    fontSize: 15,
    fontWeight: "900",
    fontStyle: "italic",
    color: Theme.primary,
  },
  completionTrack: {
    height: 8,
    borderRadius: 999,
    backgroundColor: Theme.surfaceBorder,
    borderWidth: 1,
    borderColor: Theme.borderMedium,
    overflow: "hidden",
  },
  completionFill: { height: "100%", borderRadius: 999 },
  kpiGrid: { flexDirection: "row", gap: 12, marginTop: 22, width: "100%" },
  kpiTile: {
    flex: 1,
    backgroundColor: Theme.surface,
    borderRadius: 28,
    paddingVertical: 16,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: Theme.surfaceBorder,
    alignItems: "center",
  },
  kpiTileLabel: {
    fontSize: 9,
    fontWeight: "900",
    color: Theme.textSection,
    textTransform: "uppercase",
    letterSpacing: 1.4,
    marginBottom: 8,
    textAlign: "center",
  },
  kpiTileValue: {
    fontSize: 20,
    fontWeight: "900",
    fontStyle: "italic",
    color: Theme.textPrimaryDark,
    textAlign: "center",
  },
  twoCol: { flexDirection: "row", gap: 16, marginBottom: 8 },
  twoColStack: { flexDirection: "column" },
  colBlock: { flex: 1, minWidth: 0 },
  sectionHeadingRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 4,
    marginBottom: 10,
  },
  accentIndigo: {
    width: 4,
    height: 28,
    borderRadius: 4,
    backgroundColor: Theme.buttonPrimary,
  },
  accentEmerald: {
    width: 4,
    height: 28,
    borderRadius: 4,
    backgroundColor: Theme.positive,
  },
  accentAmber: {
    width: 4,
    height: 28,
    borderRadius: 4,
    backgroundColor: Theme.warning,
  },
  sectionHeading: {
    fontSize: 11,
    fontWeight: "900",
    color: Theme.textMuted,
    textTransform: "uppercase",
    letterSpacing: 2,
  },
  registryCard: {
    backgroundColor: Theme.cardWhite,
    borderRadius: 32,
    padding: 18,
    borderWidth: 1,
    borderColor: Theme.surfaceBorder,
    gap: 14,
  },
  registryRow: { flexDirection: "row", alignItems: "center", gap: 14 },
  registryIconWrap: {
    width: 56,
    height: 56,
    borderRadius: 20,
    backgroundColor: Theme.surfaceGray,
    alignItems: "center",
    justifyContent: "center",
  },
  registryLabel: {
    fontSize: 10,
    fontWeight: "900",
    color: Theme.textSection,
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: 4,
  },
  registryValue: {
    fontSize: 16,
    fontWeight: "700",
    color: Theme.textPrimary,
  },
  taxLabel: {
    fontSize: 10,
    fontWeight: "900",
    color: Theme.textSection,
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: 6,
  },
  taxGst: {
    fontSize: 20,
    fontWeight: "900",
    color: Theme.textPrimaryDark,
    textTransform: "uppercase",
  },
  taxPan: { fontSize: 16, fontWeight: "800", color: Theme.textPrimary },
  taxBilling: {
    fontSize: 14,
    fontWeight: "700",
    fontStyle: "italic",
    color: Theme.textSecondary,
    lineHeight: 20,
  },
  blockSpaced: { marginBottom: 22 },
  blockHeadingRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
    paddingHorizontal: 2,
    gap: 8,
  },
  linkCta: {
    fontSize: 10,
    fontWeight: "900",
    color: Theme.primary,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  hubGrid: { flexDirection: "row", flexWrap: "wrap", gap: 12 },
  hubGridStack: { flexDirection: "column" },
  hubCard: {
    flexGrow: 1,
    minWidth: 140,
    flexBasis: "47%",
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    backgroundColor: Theme.cardWhite,
    borderRadius: 28,
    padding: 16,
    borderWidth: 1,
    borderColor: Theme.surfaceBorder,
  },
  hubIcon: {
    width: 52,
    height: 52,
    borderRadius: 16,
    backgroundColor: Theme.surfaceGray,
    alignItems: "center",
    justifyContent: "center",
  },
  hubName: {
    fontSize: 15,
    fontWeight: "900",
    fontStyle: "italic",
    color: Theme.textPrimaryDark,
  },
  hubAddr: {
    marginTop: 4,
    fontSize: 10,
    fontWeight: "700",
    color: Theme.textMuted,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  ratingScoreRow: {
    flexDirection: "row",
    alignItems: "baseline",
    gap: 6,
    flexWrap: "wrap",
  },
  ratingScoreMain: {
    fontSize: 16,
    fontWeight: "900",
    color: Theme.textPrimaryDark,
  },
  ratingScoreMax: {
    fontSize: 11,
    fontWeight: "600",
    color: Theme.textMuted,
  },
  ratingDate: {
    fontSize: 9,
    fontWeight: "700",
    color: Theme.textMuted,
    marginTop: 4,
  },
  compThreeCol: {
    flexDirection: "row",
    alignItems: "stretch",
    gap: 8,
    marginBottom: 22,
  },
  compCell: {
    flex: 1,
    minWidth: 0,
    borderRadius: 28,
    paddingVertical: 14,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: Theme.surfaceBorder,
    backgroundColor: Theme.cardWhite,
  },
  compMissingNote: {
    fontSize: 11,
    lineHeight: 16,
    color: "rgb(217,119,6)",
    marginBottom: 10,
  },
  compCellLabel: {
    fontSize: 9,
    fontWeight: "900",
    color: Theme.textMuted,
    letterSpacing: 0.4,
    textTransform: "uppercase",
    marginBottom: 8,
    lineHeight: 12,
  },
  compCellValue: {
    fontSize: 12,
    fontWeight: "900",
    color: Theme.textPrimaryDark,
    lineHeight: 16,
  },
  badge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 10,
    borderWidth: 1,
  },
  badgeText: {
    fontSize: 10,
    fontWeight: "900",
    textTransform: "uppercase",
    letterSpacing: -0.2,
  },
  emptyMuted: {
    fontSize: 13,
    color: Theme.textMuted,
    fontWeight: "600",
  },
  /** CounterpartyProfileSystemCard view-tab chip bar (shared party chrome). */
  viewTabBar: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 14,
    paddingTop: 8,
    paddingBottom: 6,
    backgroundColor: Theme.cardWhite,
    borderBottomWidth: 1,
    borderBottomColor: Theme.borderInput,
  },
  viewTabChip: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: Theme.borderInput,
    backgroundColor: Theme.surfaceGray,
    minHeight: 30,
    justifyContent: "center",
  },
  viewTabChipActive: {
    backgroundColor: Theme.textPrimaryDark,
    borderColor: Theme.textPrimaryDark,
  },
  viewTabChipText: {
    fontSize: 9,
    fontWeight: "700",
    color: Theme.textRouteCard,
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  viewTabChipTextActive: {
    color: Theme.textOnPrimary,
  },
  hubBody: {
    paddingHorizontal: 14,
    paddingTop: 12,
  },
});
