// Auto-generated Phase 2 registry — org experience
import type { PolicyRecord } from '@/lib/navigationPolicy/types';

export const ORG_POLICIES: readonly PolicyRecord[] = [
  {
    id: 'org.trips',
    pattern: '/trips',
    experience: 'org',
    anonymousAccess: 'require_auth',
    driverAccess: 'deny',
    priority: 100,
    grants: { anyOf: ['dispatch', 'dispatch_for_own_fleet'] },
    onDeny: { type: 'sign_in' },
    softDeny: true,
  },
  {
    id: 'org.finance',
    pattern: '/finance',
    experience: 'org',
    anonymousAccess: 'require_auth',
    driverAccess: 'deny',
    priority: 100,
    grants: { anyOf: ['finance_view', 'finance_manage'] },
    onDeny: { type: 'path', path: '/trips' },
    softDeny: true,
  },
  {
    id: 'org.resources',
    pattern: '/resources',
    experience: 'org',
    anonymousAccess: 'require_auth',
    driverAccess: 'deny',
    priority: 100,
    grants: { anyOf: ['fleet_management'] },
    onDeny: { type: 'path', path: '/trips' },
    softDeny: true,
  },
  {
    id: 'org.clients',
    pattern: '/clients',
    experience: 'org',
    anonymousAccess: 'require_auth',
    driverAccess: 'deny',
    priority: 100,
    grants: { anyOf: ['dispatch', 'dispatch_for_own_fleet'] },
    onDeny: { type: 'path', path: '/trips' },
    softDeny: true,
  },
  {
    id: 'org.network',
    pattern: '/network',
    experience: 'org',
    anonymousAccess: 'require_auth',
    driverAccess: 'deny',
    priority: 100,
    onDeny: { type: 'sign_in' },
  },
  {
    id: 'org.network-hub',
    pattern: '/network/hub',
    experience: 'org',
    anonymousAccess: 'require_auth',
    driverAccess: 'deny',
    priority: 100,
    onDeny: { type: 'sign_in' },
  },
  {
    id: 'org.profile',
    pattern: '/profile',
    experience: 'org',
    anonymousAccess: 'require_auth',
    driverAccess: 'deny',
    priority: 100,
    onDeny: { type: 'sign_in' },
  },
  {
    id: 'org.payment-detail',
    pattern: '/payment-detail',
    experience: 'org',
    anonymousAccess: 'require_auth',
    driverAccess: 'deny',
    priority: 100,
    grants: { anyOf: ['finance_view', 'finance_manage'] },
    onDeny: { type: 'path', path: '/trips' },
    softDeny: true,
  },
  {
    id: 'org.report',
    pattern: '/report',
    experience: 'org',
    anonymousAccess: 'require_auth',
    driverAccess: 'deny',
    priority: 100,
    grants: { anyOf: ['finance_view', 'finance_manage'] },
    onDeny: { type: 'path', path: '/trips' },
    softDeny: true,
  },
  {
    id: 'org.indents-alias',
    pattern: '/indents',
    experience: 'org',
    anonymousAccess: 'require_auth',
    driverAccess: 'deny',
    priority: 100,
    grants: { anyOf: ['dispatch', 'dispatch_for_own_fleet'] },
    onDeny: { type: 'path', path: '/pulse-loads' },
    softDeny: true,
  },
  {
    id: 'org.pulse-loads',
    pattern: '/pulse-loads',
    experience: 'org',
    anonymousAccess: 'require_auth',
    driverAccess: 'legacy_open',
    priority: 100,
    grants: { anyOf: ['dispatch', 'dispatch_for_own_fleet'] },
    onDeny: { type: 'sign_in' },
    softDeny: true,
  },
  {
    id: 'org.create-indent',
    pattern: '/create-indent',
    experience: 'org',
    anonymousAccess: 'legacy_open',
    driverAccess: 'legacy_open',
    priority: 100,
    grants: { anyOf: ['dispatch', 'dispatch_for_own_fleet'] },
    onDeny: { type: 'sign_in' },
    softDeny: true,
  },
  {
    id: 'org.load-board',
    pattern: '/load-board',
    experience: 'org',
    anonymousAccess: 'legacy_open',
    driverAccess: 'legacy_open',
    priority: 100,
    grants: { anyOf: ['dispatch', 'dispatch_for_own_fleet'] },
    onDeny: { type: 'sign_in' },
    softDeny: true,
  },
  {
    id: 'org.from-clients',
    pattern: '/from-clients',
    experience: 'org',
    anonymousAccess: 'legacy_open',
    driverAccess: 'legacy_open',
    priority: 100,
    grants: { anyOf: ['dispatch', 'dispatch_for_own_fleet'] },
    onDeny: { type: 'sign_in' },
    softDeny: true,
  },
  {
    id: 'org.add-trip',
    pattern: '/add-trip',
    experience: 'org',
    anonymousAccess: 'legacy_open',
    driverAccess: 'legacy_open',
    priority: 100,
    grants: { anyOf: ['dispatch', 'dispatch_for_own_fleet'] },
    onDeny: { type: 'sign_in' },
    softDeny: true,
  },
  {
    id: 'org.indent',
    pattern: '/indent/:id',
    experience: 'org',
    anonymousAccess: 'legacy_open',
    driverAccess: 'legacy_open',
    priority: 80,
    grants: { anyOf: ['dispatch', 'dispatch_for_own_fleet'] },
    onDeny: { type: 'sign_in' },
    softDeny: true,
  },
  {
    id: 'org.indent-allocation',
    pattern: '/indent/:id/allocation',
    experience: 'org',
    anonymousAccess: 'legacy_open',
    driverAccess: 'legacy_open',
    priority: 90,
    grants: { anyOf: ['dispatch', 'dispatch_for_own_fleet'] },
    onDeny: { type: 'sign_in' },
    softDeny: true,
  },
  {
    id: 'org.client',
    pattern: '/client/:id',
    experience: 'org',
    anonymousAccess: 'legacy_open',
    driverAccess: 'legacy_open',
    priority: 80,
    grants: { anyOf: ['dispatch', 'dispatch_for_own_fleet'] },
    onDeny: { type: 'sign_in' },
    softDeny: true,
  },
  {
    id: 'org.client-analytics',
    pattern: '/client/:id/analytics',
    experience: 'org',
    anonymousAccess: 'legacy_open',
    driverAccess: 'legacy_open',
    priority: 90,
    grants: { anyOf: ['dispatch', 'dispatch_for_own_fleet'] },
    onDeny: { type: 'sign_in' },
    softDeny: true,
  },
  {
    id: 'org.client-profile',
    pattern: '/client/:id/profile',
    experience: 'org',
    anonymousAccess: 'legacy_open',
    driverAccess: 'legacy_open',
    priority: 90,
    grants: { anyOf: ['dispatch', 'dispatch_for_own_fleet'] },
    onDeny: { type: 'sign_in' },
    softDeny: true,
  },
  {
    id: 'org.supplier',
    pattern: '/supplier/:id',
    experience: 'org',
    anonymousAccess: 'legacy_open',
    driverAccess: 'legacy_open',
    priority: 80,
    grants: { anyOf: ['dispatch', 'dispatch_for_own_fleet'] },
    onDeny: { type: 'sign_in' },
    softDeny: true,
  },
  {
    id: 'org.supplier-analytics',
    pattern: '/supplier/:id/analytics',
    experience: 'org',
    anonymousAccess: 'legacy_open',
    driverAccess: 'legacy_open',
    priority: 90,
    grants: { anyOf: ['dispatch', 'dispatch_for_own_fleet'] },
    onDeny: { type: 'sign_in' },
    softDeny: true,
  },
  {
    id: 'org.supplier-profile',
    pattern: '/supplier/:id/profile',
    experience: 'org',
    anonymousAccess: 'legacy_open',
    driverAccess: 'legacy_open',
    priority: 90,
    grants: { anyOf: ['dispatch', 'dispatch_for_own_fleet'] },
    onDeny: { type: 'sign_in' },
    softDeny: true,
  },
  {
    id: 'org.party-customers-id',
    pattern: '/party/customers/:id',
    experience: 'org',
    anonymousAccess: 'legacy_open',
    driverAccess: 'legacy_open',
    priority: 95,
    grants: { anyOf: ['dispatch', 'dispatch_for_own_fleet'] },
    onDeny: { type: 'sign_in' },
    softDeny: true,
  },
  {
    id: 'org.party-kind',
    pattern: '/party/:kind',
    experience: 'org',
    anonymousAccess: 'legacy_open',
    driverAccess: 'legacy_open',
    priority: 70,
    onDeny: { type: 'sign_in' },
    softDeny: true,
  },
  {
    id: 'org.driver-entity',
    pattern: '/driver/:id',
    experience: 'org',
    anonymousAccess: 'legacy_open',
    driverAccess: 'legacy_open',
    priority: 80,
    grants: { anyOf: ['fleet_management'] },
    onDeny: { type: 'path', path: '/resources' },
    softDeny: true,
  },
  {
    id: 'org.driver-analytics',
    pattern: '/driver/:id/analytics',
    experience: 'org',
    anonymousAccess: 'legacy_open',
    driverAccess: 'legacy_open',
    priority: 90,
    grants: { anyOf: ['fleet_management'] },
    onDeny: { type: 'path', path: '/resources' },
    softDeny: true,
  },
  {
    id: 'org.driver-profile',
    pattern: '/driver/:id/profile',
    experience: 'org',
    anonymousAccess: 'legacy_open',
    driverAccess: 'legacy_open',
    priority: 90,
    grants: { anyOf: ['fleet_management'] },
    onDeny: { type: 'path', path: '/resources' },
    softDeny: true,
  },
  {
    id: 'org.vehicle',
    pattern: '/vehicle/:id',
    experience: 'org',
    anonymousAccess: 'legacy_open',
    driverAccess: 'legacy_open',
    priority: 80,
    grants: { anyOf: ['fleet_management'] },
    onDeny: { type: 'path', path: '/resources' },
    softDeny: true,
  },
  {
    id: 'org.vehicle-analytics',
    pattern: '/vehicle/:id/analytics',
    experience: 'org',
    anonymousAccess: 'legacy_open',
    driverAccess: 'legacy_open',
    priority: 90,
    grants: { anyOf: ['fleet_management'] },
    onDeny: { type: 'path', path: '/resources' },
    softDeny: true,
  },
  {
    id: 'org.vehicle-profile',
    pattern: '/vehicle/:id/profile',
    experience: 'org',
    anonymousAccess: 'legacy_open',
    driverAccess: 'legacy_open',
    priority: 90,
    grants: { anyOf: ['fleet_management'] },
    onDeny: { type: 'path', path: '/resources' },
    softDeny: true,
  },
  {
    id: 'org.trip',
    pattern: '/trip/:id',
    experience: 'org',
    anonymousAccess: 'legacy_open',
    driverAccess: 'legacy_open',
    priority: 70,
    grants: { anyOf: ['finance_view', 'finance_manage', 'dispatch', 'dispatch_for_own_fleet'] },
    onDeny: { type: 'sign_in' },
    softDeny: true,
  },
  {
    id: 'org.trip-assignment',
    pattern: '/trip/:id/assignment',
    experience: 'org',
    anonymousAccess: 'legacy_open',
    driverAccess: 'legacy_open',
    priority: 90,
    grants: { anyOf: ['dispatch', 'dispatch_for_own_fleet'] },
    onDeny: { type: 'sign_in' },
    softDeny: true,
  },
  {
    id: 'org.trip-verification',
    pattern: '/trip/:id/verification',
    experience: 'org',
    anonymousAccess: 'legacy_open',
    driverAccess: 'legacy_open',
    priority: 90,
    grants: { anyOf: ['dispatch', 'dispatch_for_own_fleet'] },
    onDeny: { type: 'sign_in' },
    softDeny: true,
  },
  {
    id: 'org.trip-ops-expenses',
    pattern: '/trip/:id/operations/expenses',
    experience: 'org',
    anonymousAccess: 'legacy_open',
    driverAccess: 'legacy_open',
    priority: 90,
    grants: { anyOf: ['finance_view', 'finance_manage', 'dispatch', 'dispatch_for_own_fleet'] },
    onDeny: { type: 'sign_in' },
    softDeny: true,
  },
  {
    id: 'org.trip-ops-fuel',
    pattern: '/trip/:id/operations/fuel',
    experience: 'org',
    anonymousAccess: 'legacy_open',
    driverAccess: 'legacy_open',
    priority: 90,
    grants: { anyOf: ['finance_view', 'finance_manage', 'dispatch', 'dispatch_for_own_fleet'] },
    onDeny: { type: 'sign_in' },
    softDeny: true,
  },
  {
    id: 'org.trip-ops-toll',
    pattern: '/trip/:id/operations/toll',
    experience: 'org',
    anonymousAccess: 'legacy_open',
    driverAccess: 'legacy_open',
    priority: 90,
    grants: { anyOf: ['finance_view', 'finance_manage', 'dispatch', 'dispatch_for_own_fleet'] },
    onDeny: { type: 'sign_in' },
    softDeny: true,
  },
  {
    id: 'org.trip-ops-other',
    pattern: '/trip/:id/operations/other',
    experience: 'org',
    anonymousAccess: 'legacy_open',
    driverAccess: 'legacy_open',
    priority: 90,
    grants: { anyOf: ['finance_view', 'finance_manage', 'dispatch', 'dispatch_for_own_fleet'] },
    onDeny: { type: 'sign_in' },
    softDeny: true,
  },
  {
    id: 'org.trip-ops-launcher',
    pattern: '/trip/:id/operations/launcher',
    experience: 'org',
    anonymousAccess: 'legacy_open',
    driverAccess: 'legacy_open',
    priority: 90,
    grants: { anyOf: ['finance_view', 'finance_manage', 'dispatch', 'dispatch_for_own_fleet'] },
    onDeny: { type: 'sign_in' },
    softDeny: true,
  },
  {
    id: 'org.finance-entry',
    pattern: '/finance-entry/:id',
    experience: 'org',
    anonymousAccess: 'legacy_open',
    driverAccess: 'legacy_open',
    priority: 80,
    grants: { anyOf: ['finance_view', 'finance_manage'] },
    onDeny: { type: 'path', path: '/trips' },
    softDeny: true,
  },
  {
    id: 'org.trip-ledger',
    pattern: '/trip-ledger/:id',
    experience: 'org',
    anonymousAccess: 'legacy_open',
    driverAccess: 'legacy_open',
    priority: 80,
    grants: { anyOf: ['finance_view', 'finance_manage'] },
    onDeny: { type: 'path', path: '/trips' },
    softDeny: true,
  },
  {
    id: 'org.invoicing-pdf',
    pattern: '/invoicing/pdf-preview',
    experience: 'org',
    anonymousAccess: 'legacy_open',
    driverAccess: 'legacy_open',
    priority: 100,
    grants: { anyOf: ['finance_view', 'finance_manage', 'dispatch', 'dispatch_for_own_fleet'] },
    onDeny: { type: 'path', path: '/trips' },
    softDeny: true,
  },
  {
    id: 'org.invoicing-execute',
    pattern: '/invoicing-execute',
    experience: 'org',
    anonymousAccess: 'legacy_open',
    driverAccess: 'legacy_open',
    priority: 100,
    grants: { anyOf: ['finance_view', 'finance_manage'] },
    onDeny: { type: 'path', path: '/trips' },
    softDeny: true,
  },
  {
    id: 'org.business-pulse',
    pattern: '/business-pulse',
    experience: 'org',
    anonymousAccess: 'legacy_open',
    driverAccess: 'legacy_open',
    priority: 100,
    grants: { anyOf: ['finance_view', 'finance_manage'] },
    onDeny: { type: 'path', path: '/trips' },
    softDeny: true,
  },
  {
    id: 'org.ledger-sync',
    pattern: '/ledger-sync',
    experience: 'org',
    anonymousAccess: 'legacy_open',
    driverAccess: 'legacy_open',
    priority: 100,
    grants: { anyOf: ['finance_view', 'finance_manage'] },
    onDeny: { type: 'path', path: '/trips' },
    softDeny: true,
  },
  {
    id: 'org.workspace',
    pattern: '/workspace',
    experience: 'org',
    anonymousAccess: 'legacy_open',
    driverAccess: 'legacy_open',
    priority: 100,
    onDeny: { type: 'sign_in' },
  },
  {
    id: 'org.documents-center',
    pattern: '/documents-center',
    experience: 'org',
    anonymousAccess: 'legacy_open',
    driverAccess: 'legacy_open',
    priority: 100,
    onDeny: { type: 'sign_in' },
  },
  {
    id: 'org.notifications',
    pattern: '/notifications',
    experience: 'org',
    anonymousAccess: 'legacy_open',
    driverAccess: 'legacy_open',
    priority: 100,
    onDeny: { type: 'sign_in' },
  },
  {
    id: 'org.chat',
    pattern: '/chat',
    experience: 'org',
    anonymousAccess: 'legacy_open',
    driverAccess: 'legacy_open',
    priority: 100,
    onDeny: { type: 'sign_in' },
  },
  {
    id: 'org.alert-detail',
    pattern: '/alert-detail',
    experience: 'org',
    anonymousAccess: 'legacy_open',
    driverAccess: 'legacy_open',
    priority: 100,
    onDeny: { type: 'sign_in' },
  },
  {
    id: 'org.milestone',
    pattern: '/milestone',
    experience: 'org',
    anonymousAccess: 'legacy_open',
    driverAccess: 'legacy_open',
    priority: 100,
    onDeny: { type: 'sign_in' },
  },
  {
    id: 'org.network-user',
    pattern: '/network-user',
    experience: 'org',
    anonymousAccess: 'legacy_open',
    driverAccess: 'legacy_open',
    priority: 100,
    onDeny: { type: 'sign_in' },
  },
  {
    id: 'org.pod-reconciliation',
    pattern: '/pod-reconciliation',
    experience: 'org',
    anonymousAccess: 'legacy_open',
    driverAccess: 'legacy_open',
    priority: 100,
    onDeny: { type: 'sign_in' },
  },
  {
    id: 'org.log-incoming-pods',
    pattern: '/log-incoming-pods',
    experience: 'org',
    anonymousAccess: 'legacy_open',
    driverAccess: 'legacy_open',
    priority: 100,
    onDeny: { type: 'sign_in' },
  },
  {
    id: 'org.add-commodity-type',
    pattern: '/add-commodity-type',
    experience: 'org',
    anonymousAccess: 'legacy_open',
    driverAccess: 'legacy_open',
    priority: 100,
    onDeny: { type: 'sign_in' },
  },
  {
    id: 'org.modal',
    pattern: '/modal',
    experience: 'org',
    anonymousAccess: 'legacy_open',
    driverAccess: 'legacy_open',
    priority: 100,
    onDeny: { type: 'sign_in' },
  },
  {
    id: 'org.audit',
    pattern: '/audit',
    experience: 'org',
    anonymousAccess: 'legacy_open',
    driverAccess: 'legacy_open',
    priority: 100,
    onDeny: { type: 'sign_in' },
  },
  {
    id: 'org.audit-log',
    pattern: '/audit-log',
    experience: 'org',
    anonymousAccess: 'legacy_open',
    driverAccess: 'legacy_open',
    priority: 100,
    onDeny: { type: 'sign_in' },
  },
  {
    id: 'org.modal-add-client',
    pattern: '/add-client',
    experience: 'org',
    anonymousAccess: 'legacy_open',
    driverAccess: 'legacy_open',
    priority: 100,
    grants: { anyOf: ['dispatch', 'dispatch_for_own_fleet'] },
    onDeny: { type: 'sign_in' },
    softDeny: true,
  },
  {
    id: 'org.modal-edit-client',
    pattern: '/edit-client',
    experience: 'org',
    anonymousAccess: 'legacy_open',
    driverAccess: 'legacy_open',
    priority: 100,
    grants: { anyOf: ['dispatch', 'dispatch_for_own_fleet'] },
    onDeny: { type: 'sign_in' },
    softDeny: true,
  },
  {
    id: 'org.modal-add-supplier',
    pattern: '/add-supplier',
    experience: 'org',
    anonymousAccess: 'legacy_open',
    driverAccess: 'legacy_open',
    priority: 100,
    grants: { anyOf: ['dispatch', 'dispatch_for_own_fleet'] },
    onDeny: { type: 'sign_in' },
    softDeny: true,
  },
  {
    id: 'org.modal-attribution',
    pattern: '/attribution-trip-create',
    experience: 'org',
    anonymousAccess: 'legacy_open',
    driverAccess: 'legacy_open',
    priority: 100,
    grants: { anyOf: ['dispatch', 'dispatch_for_own_fleet'] },
    onDeny: { type: 'sign_in' },
    softDeny: true,
  },
  {
    id: 'org.modal-add-driver',
    pattern: '/add-driver',
    experience: 'org',
    anonymousAccess: 'legacy_open',
    driverAccess: 'legacy_open',
    priority: 100,
    grants: { anyOf: ['fleet_management'] },
    onDeny: { type: 'path', path: '/resources' },
    softDeny: true,
  },
  {
    id: 'org.modal-add-vehicle',
    pattern: '/add-vehicle',
    experience: 'org',
    anonymousAccess: 'legacy_open',
    driverAccess: 'legacy_open',
    priority: 100,
    grants: { anyOf: ['fleet_management'] },
    onDeny: { type: 'path', path: '/resources' },
    softDeny: true,
  },
  {
    id: 'org.modal-team',
    pattern: '/team',
    experience: 'org',
    anonymousAccess: 'legacy_open',
    driverAccess: 'legacy_open',
    priority: 100,
    onDeny: { type: 'sign_in' },
  },
  {
    id: 'org.modal-invite',
    pattern: '/invite-member',
    experience: 'org',
    anonymousAccess: 'legacy_open',
    driverAccess: 'legacy_open',
    priority: 100,
    onDeny: { type: 'sign_in' },
  },
  {
    id: 'org.modal-language',
    pattern: '/language-settings',
    experience: 'org',
    anonymousAccess: 'legacy_open',
    driverAccess: 'legacy_open',
    priority: 100,
    onDeny: { type: 'sign_in' },
  },
  {
    id: 'org.modal-create-post',
    pattern: '/create-post',
    experience: 'org',
    anonymousAccess: 'legacy_open',
    driverAccess: 'legacy_open',
    priority: 100,
    onDeny: { type: 'sign_in' },
  },
  {
    id: 'org.modal-post-detail',
    pattern: '/post-detail',
    experience: 'org',
    anonymousAccess: 'legacy_open',
    driverAccess: 'legacy_open',
    priority: 100,
    onDeny: { type: 'sign_in' },
  },
  {
    id: 'org.modal-story-detail',
    pattern: '/story-detail',
    experience: 'org',
    anonymousAccess: 'legacy_open',
    driverAccess: 'legacy_open',
    priority: 100,
    onDeny: { type: 'sign_in' },
  },
  {
    id: 'org.modal-sms-otp',
    pattern: '/sms-otp-parsing',
    experience: 'org',
    anonymousAccess: 'legacy_open',
    driverAccess: 'legacy_open',
    priority: 100,
    onDeny: { type: 'sign_in' },
  },
];
