import { Platform, StyleSheet } from "react-native";

import Layout from "@/constants/Layout";
import Theme from "@/constants/Theme";

const padX = Layout.screenPaddingHorizontal;

export const partyMobileWizardStyles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: Theme.screenBackground,
  },
  shellColumn: {
    flex: 1,
    minHeight: 0,
  },
  /** Carded desktop/tablet: size to content instead of filling a fixed height. */
  rootFit: {
    flexGrow: 0,
    flexShrink: 1,
    backgroundColor: Theme.screenBackground,
  },
  shellColumnFit: {
    flexGrow: 0,
    flexShrink: 1,
  },
  topBar: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: padX,
    paddingBottom: 4,
  },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: Theme.surfaceForm,
    alignItems: "center",
    justifyContent: "center",
  },
  backBtnSpacer: {
    width: 36,
  },
  progressRow: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "center",
    gap: 6,
  },
  progressDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: Theme.borderLight,
  },
  progressDotActive: {
    backgroundColor: Theme.positive,
    width: 18,
  },
  hero: {
    paddingHorizontal: padX,
    paddingBottom: 6,
  },
  titleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  liveDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: Theme.positive,
  },
  entityTitle: {
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 1.2,
    color: Theme.positive,
    textTransform: "uppercase",
  },
  subtitle: {
    marginTop: 3,
    fontSize: 12,
    lineHeight: 16,
    color: Theme.textMuted,
  },
  errorBar: {
    marginHorizontal: padX,
    marginBottom: 6,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 10,
    backgroundColor: Theme.negativeMuted,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "#fecaca",
  },
  errorText: {
    fontSize: 12,
    fontWeight: "600",
    color: Theme.negative,
  },
  body: {
    paddingHorizontal: padX,
    paddingTop: 2,
  },
  bodyFields: {
    flex: 1,
  },
  bodyFieldsFit: {
    flexGrow: 0,
    flexShrink: 0,
  },
  bodyKeypad: {
    flex: 1,
    minHeight: 0,
    paddingBottom: 0,
    paddingHorizontal: 0,
  },
  bodyKeypadFit: {
    flexGrow: 0,
    flexShrink: 0,
    paddingBottom: 0,
    paddingHorizontal: 0,
  },
  bodyKeypadHeader: {
    paddingHorizontal: padX,
    paddingBottom: 4,
  },
  bodyKeypadContent: {
    flex: 1,
    minHeight: 0,
    width: "100%",
  },
  bodyKeypadContentFit: {
    width: "100%",
    // Carded desktop/tablet: inset the input + keypad to match the padded header
    // (the full-screen mobile layout intentionally bleeds them to the edges).
    paddingHorizontal: padX,
  },
  bodySource: {
    flexGrow: 0,
    flexShrink: 0,
  },
  stepTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: Theme.textPrimaryDark,
    letterSpacing: -0.3,
    lineHeight: 26,
  },
  stepTitleCompact: {
    fontSize: 17,
    lineHeight: 22,
  },
  stepHint: {
    marginTop: 4,
    marginBottom: 12,
    fontSize: 13,
    lineHeight: 18,
    color: Theme.textMuted,
  },
  stepHintKeypad: {
    marginTop: 4,
    marginBottom: 8,
    fontSize: 13,
    lineHeight: 18,
    color: Theme.textMuted,
  },
  sourceCard: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    backgroundColor: Theme.surfaceForm,
    overflow: "hidden",
  },
  sourceBlock: {
    gap: 0,
  },
  importPrimary: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: Theme.buttonPrimary,
    paddingVertical: 13,
    paddingHorizontal: 16,
    minHeight: Layout.minTouchTargetSize,
  },
  importPrimaryDim: {
    opacity: 0.65,
  },
  importPrimaryText: {
    fontSize: 13,
    fontWeight: "700",
    color: Theme.buttonPrimaryText,
    letterSpacing: 0.3,
  },
  importError: {
    fontSize: 11,
    color: Theme.negative,
    fontWeight: "600",
    paddingHorizontal: 14,
    paddingTop: 8,
  },
  importHint: {
    fontSize: 11,
    color: Theme.textMuted,
    lineHeight: 16,
    paddingHorizontal: 14,
    paddingTop: 8,
    paddingBottom: 4,
  },
  sourceDivider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: Theme.borderLight,
  },
  manualLink: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    paddingVertical: 12,
    minHeight: Layout.minTouchTargetSize,
  },
  manualLinkText: {
    fontSize: 13,
    fontWeight: "600",
    color: Theme.primary,
  },
  fieldBlock: {
    gap: 8,
  },
  labelRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  fieldLabel: {
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.8,
    color: Theme.textMuted,
  },
  optionalPill: {
    fontSize: 9,
    fontWeight: "700",
    color: Theme.textMuted,
    letterSpacing: 0.4,
  },
  input: {
    borderWidth: 1,
    borderColor: Theme.borderLight,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: Platform.OS === "web" ? 11 : 12,
    fontSize: 16,
    fontWeight: "600",
    color: Theme.textPrimaryDark,
    backgroundColor: Theme.surfaceForm,
    minHeight: Layout.minTouchTargetSize,
    ...Platform.select({
      web: { outlineStyle: "none" } as object,
    }),
  },
  skipLink: {
    alignSelf: "flex-start",
    paddingVertical: 4,
    minHeight: Layout.minTouchTargetSize,
    justifyContent: "center",
  },
  skipLinkText: {
    fontSize: 12,
    fontWeight: "600",
    color: Theme.textMuted,
  },
  phoneRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    borderRadius: 12,
    paddingHorizontal: 12,
    backgroundColor: Theme.surfaceForm,
    minHeight: Layout.minTouchTargetSize,
  },
  phoneCc: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingRight: 8,
    borderRightWidth: StyleSheet.hairlineWidth,
    borderRightColor: Theme.borderLight,
  },
  phoneCcText: {
    fontSize: 15,
    fontWeight: "700",
    color: Theme.textPrimaryDark,
  },
  phoneInput: {
    flex: 1,
    borderWidth: 0,
    backgroundColor: "transparent",
    paddingHorizontal: 0,
    minHeight: undefined,
  },
  presetPress: {
    justifyContent: "center",
    minHeight: Layout.minTouchTargetSize,
  },
  presetValue: {
    fontSize: 16,
    fontWeight: "600",
    color: Theme.textPrimaryDark,
  },
  presetPlaceholder: {
    fontSize: 15,
    fontWeight: "600",
    color: Theme.textMuted,
  },
  chipGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  chip: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    backgroundColor: Theme.surfaceForm,
    maxWidth: "48%",
  },
  chipActive: {
    borderColor: Theme.primary,
    backgroundColor: "rgba(99,102,241,0.1)",
  },
  chipText: {
    fontSize: 12,
    fontWeight: "600",
    color: Theme.textMuted,
    textAlign: "center",
  },
  chipTextActive: {
    color: Theme.primary,
  },
  specHint: {
    fontSize: 11,
    color: Theme.textMuted,
    marginTop: 2,
  },
  footer: {
    alignItems: "flex-end",
    paddingHorizontal: padX,
    paddingTop: 6,
    gap: 6,
  },
  fab: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: Theme.textPrimaryDark,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: Theme.shadow,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 4,
  },
  fabDisabled: {
    opacity: 0.4,
  },
  footerHint: {
    fontSize: 9,
    fontWeight: "700",
    color: Theme.textMuted,
    textTransform: "uppercase",
    letterSpacing: 0.6,
    marginRight: 2,
  },
  reviewOverlay: {
    flex: 1,
    backgroundColor: Theme.overlayBackdrop,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 20,
  },
  reviewCard: {
    width: "100%",
    maxWidth: 400,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    backgroundColor: Theme.screenBackground,
    paddingHorizontal: 22,
    paddingTop: 24,
    paddingBottom: 18,
    alignItems: "center",
    gap: 8,
    ...Platform.select({
      web: {
        boxShadow:
          "0 40px 90px -30px rgba(15,23,42,0.28), 0 2px 8px rgba(15,23,42,0.06)",
      } as object,
      default: {
        shadowColor: Theme.shadow,
        shadowOffset: { width: 0, height: 16 },
        shadowOpacity: 0.16,
        shadowRadius: 26,
        elevation: 14,
      },
    }),
  },
  reviewAnimationWrap: {
    width: 84,
    height: 84,
    borderRadius: 42,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#eef4ff",
    borderWidth: 1,
    borderColor: "#dbe7fb",
    marginBottom: 2,
  },
  reviewAnimation: {
    width: 58,
    height: 58,
  },
  reviewCardTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: Theme.textPrimaryDark,
    textAlign: "center",
    letterSpacing: -0.3,
  },
  reviewCardMessage: {
    fontSize: 13,
    lineHeight: 18,
    color: Theme.textSecondary,
    textAlign: "center",
    paddingHorizontal: 6,
  },
  reviewSummaryScroll: {
    width: "100%",
    marginTop: 4,
  },
  reviewSummaryScrollContent: {
    paddingBottom: 4,
    gap: 8,
  },
  reviewFooterExtra: {
    width: "100%",
  },
  reviewConfirmBtn: {
    marginTop: 6,
    minWidth: 120,
    width: "100%",
    minHeight: 44,
    borderRadius: 12,
    paddingHorizontal: 22,
    paddingVertical: 11,
    backgroundColor: Theme.buttonPrimary,
    borderWidth: Theme.buttonPrimaryBorderWidth,
    borderColor: Theme.buttonPrimaryBorder,
    alignItems: "center",
    justifyContent: "center",
  },
  reviewConfirmBtnDisabled: {
    opacity: 0.45,
  },
  reviewConfirmBtnText: {
    fontSize: 13,
    fontWeight: "800",
    color: Theme.buttonPrimaryText,
    letterSpacing: 0.4,
  },
  reviewEditLink: {
    minHeight: Layout.minTouchTargetSize,
    justifyContent: "center",
    paddingVertical: 4,
  },
  reviewEditLinkText: {
    fontSize: 13,
    fontWeight: "700",
    color: Theme.textMuted,
  },
});
