import { Platform, StyleSheet } from "react-native";

import Theme from "@/constants/Theme";

export const partyMobileWizardStyles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: "#fff",
  },
  topBar: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingBottom: 8,
  },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: "#f1f5f9",
    alignItems: "center",
    justifyContent: "center",
  },
  backBtnSpacer: {
    width: 40,
  },
  progressRow: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "center",
    gap: 8,
  },
  progressDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#e2e8f0",
  },
  progressDotActive: {
    backgroundColor: Theme.positive,
    width: 24,
  },
  hero: {
    paddingHorizontal: 24,
    paddingBottom: 12,
  },
  titleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  liveDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: Theme.positive,
  },
  entityTitle: {
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 2,
    color: Theme.positive,
    textTransform: "uppercase",
  },
  subtitle: {
    marginTop: 6,
    fontSize: 13,
    fontStyle: "italic",
    color: Theme.textMuted,
  },
  errorBar: {
    marginHorizontal: 20,
    marginBottom: 8,
    padding: 12,
    borderRadius: 12,
    backgroundColor: "#fef2f2",
    borderWidth: 1,
    borderColor: "#fecaca",
  },
  errorText: {
    fontSize: 13,
    fontWeight: "600",
    color: Theme.negative,
  },
  body: {
    flex: 1,
    paddingHorizontal: 24,
    paddingTop: 8,
  },
  stepTitle: {
    fontSize: 28,
    fontWeight: "800",
    color: "#0f172a",
    letterSpacing: -0.5,
  },
  stepHint: {
    marginTop: 8,
    marginBottom: 24,
    fontSize: 14,
    lineHeight: 20,
    color: Theme.textMuted,
  },
  sourceBlock: {
    gap: 16,
  },
  importPrimary: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    backgroundColor: Theme.primary,
    borderRadius: 16,
    paddingVertical: 18,
    paddingHorizontal: 20,
  },
  importPrimaryDim: {
    opacity: 0.65,
  },
  importPrimaryText: {
    fontSize: 14,
    fontWeight: "800",
    color: "#fff",
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  importError: {
    fontSize: 12,
    color: Theme.negative,
    fontWeight: "600",
  },
  importHint: {
    fontSize: 12,
    color: Theme.textMuted,
    lineHeight: 18,
  },
  manualLink: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 14,
  },
  manualLinkText: {
    fontSize: 14,
    fontWeight: "700",
    color: Theme.primary,
  },
  fieldBlock: {
    gap: 10,
  },
  labelRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  fieldLabel: {
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 1,
    color: Theme.textMuted,
  },
  optionalPill: {
    fontSize: 9,
    fontWeight: "800",
    color: Theme.textMuted,
    letterSpacing: 0.6,
  },
  input: {
    borderWidth: 1,
    borderColor: "#e2e8f0",
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: Platform.OS === "web" ? 14 : 16,
    fontSize: 18,
    fontWeight: "600",
    color: "#0f172a",
    backgroundColor: "#f8fafc",
    ...Platform.select({
      web: { outlineStyle: "none" } as object,
    }),
  },
  skipLink: {
    alignSelf: "flex-start",
    paddingVertical: 8,
  },
  skipLinkText: {
    fontSize: 13,
    fontWeight: "700",
    color: Theme.textMuted,
  },
  phoneRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    borderRadius: 14,
    paddingHorizontal: 12,
    backgroundColor: "#f8fafc",
  },
  phoneCc: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingRight: 8,
    borderRightWidth: 1,
    borderRightColor: "#e2e8f0",
  },
  phoneCcText: {
    fontSize: 16,
    fontWeight: "700",
    color: "#0f172a",
  },
  phoneInput: {
    flex: 1,
    borderWidth: 0,
    backgroundColor: "transparent",
    paddingHorizontal: 0,
  },
  presetPress: {
    justifyContent: "center",
    minHeight: 52,
  },
  presetValue: {
    fontSize: 18,
    fontWeight: "600",
    color: "#0f172a",
  },
  presetPlaceholder: {
    fontSize: 16,
    fontWeight: "600",
    color: Theme.textMuted,
  },
  chipGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  chip: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    backgroundColor: "#f8fafc",
    maxWidth: "48%",
  },
  chipActive: {
    borderColor: Theme.primary,
    backgroundColor: "rgba(99,102,241,0.1)",
  },
  chipText: {
    fontSize: 12,
    fontWeight: "700",
    color: Theme.textMuted,
    textAlign: "center",
  },
  chipTextActive: {
    color: Theme.primary,
  },
  specHint: {
    fontSize: 12,
    color: Theme.textMuted,
    fontStyle: "italic",
    marginTop: 4,
  },
  footer: {
    alignItems: "flex-end",
    paddingHorizontal: 24,
    paddingTop: 8,
    gap: 8,
  },
  fab: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: "#0f172a",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 6,
  },
  fabDisabled: {
    opacity: 0.4,
  },
  footerHint: {
    fontSize: 10,
    fontWeight: "700",
    color: Theme.textMuted,
    textTransform: "uppercase",
    letterSpacing: 0.8,
    marginRight: 4,
  },
  reviewRoot: {
    flex: 1,
    backgroundColor: "#fff",
  },
  reviewHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingBottom: 8,
  },
  reviewTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: "#0f172a",
  },
  reviewScroll: {
    paddingHorizontal: 20,
    paddingBottom: 24,
  },
  reviewFooter: {
    paddingHorizontal: 20,
    paddingTop: 12,
    gap: 10,
    borderTopWidth: 1,
    borderTopColor: "#e2e8f0",
  },
});
