import Theme from '@/constants/Theme';
import { Platform, StyleSheet } from 'react-native';

export const reassignStyles = StyleSheet.create({
  reviewRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
    paddingVertical: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Theme.border,
  },
  reviewLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: Theme.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    width: 72,
  },
  reviewValue: {
    flex: 1,
    fontSize: 15,
    fontWeight: '700',
    color: Theme.textPrimary,
    textAlign: 'right',
  },
  section: {
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.8,
    color: Theme.textMuted,
    textTransform: 'uppercase',
    marginBottom: 8,
  },
  currentCard: {
    backgroundColor: Theme.cardWhite,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: Theme.border,
    padding: 14,
    marginBottom: 12,
  },
  currentName: {
    fontSize: 16,
    fontWeight: '700',
    color: Theme.textPrimary,
  },
  currentMeta: {
    fontSize: 13,
    color: Theme.textSecondary,
    marginTop: 4,
  },
  segmentRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 12,
  },
  segmentPill: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: Theme.borderMedium,
    backgroundColor: Theme.surface,
  },
  segmentPillActive: {
    borderColor: Theme.primary,
    backgroundColor: Theme.primary,
  },
  segmentText: {
    fontSize: 13,
    fontWeight: '600',
    color: Theme.textSecondary,
  },
  segmentTextActive: {
    color: Theme.textOnPrimary,
  },
  list: {
    maxHeight: 280,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Theme.border,
    backgroundColor: Theme.cardWhite,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Theme.border,
    gap: 12,
  },
  rowSelected: {
    backgroundColor: Theme.surface,
  },
  rowBusy: {
    opacity: 0.55,
  },
  rowTitleMuted: {
    color: Theme.textMuted,
  },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: Theme.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: {
    color: Theme.textOnPrimary,
    fontWeight: '700',
    fontSize: 14,
  },
  rowTitle: {
    flex: 1,
    minWidth: 0,
    fontSize: 15,
    fontWeight: '600',
    color: Theme.textPrimary,
  },
  rowSub: {
    fontSize: 12,
    color: Theme.textSecondary,
    marginTop: 2,
  },
  empty: {
    padding: 24,
    alignItems: 'center',
  },
  emptyText: {
    fontSize: 14,
    color: Theme.textMuted,
    textAlign: 'center',
  },
  emptyCta: {
    marginTop: 12,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 10,
    backgroundColor: Theme.primary,
  },
  emptyCtaText: {
    color: Theme.textOnPrimary,
    fontWeight: '700',
    fontSize: 14,
  },
  form: {
    gap: 12,
    padding: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Theme.border,
    backgroundColor: Theme.cardWhite,
  },
  label: {
    fontSize: 12,
    fontWeight: '600',
    color: Theme.textSecondary,
    marginBottom: 4,
  },
  input: {
    borderWidth: 1,
    borderColor: Theme.borderMedium,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: Platform.OS === 'web' ? 10 : 12,
    fontSize: 15,
    color: Theme.textPrimary,
    backgroundColor: Theme.cardWhite,
  },
  typeChipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  typeChip: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: Theme.borderMedium,
    backgroundColor: Theme.surface,
  },
  typeChipActive: {
    borderColor: Theme.primary,
    backgroundColor: Theme.primary,
  },
  typeChipText: {
    fontSize: 12,
    fontWeight: '600',
    color: Theme.textSecondary,
  },
  typeChipTextActive: {
    color: Theme.textOnPrimary,
  },
  primaryBtn: {
    marginTop: 8,
    backgroundColor: Theme.primary,
    borderRadius: 10,
    paddingVertical: 12,
    alignItems: 'center',
  },
  primaryBtnDisabled: {
    opacity: 0.45,
  },
  primaryBtnText: {
    color: Theme.textOnPrimary,
    fontWeight: '700',
    fontSize: 15,
  },
  footer: {
    borderTopWidth: 1,
    borderTopColor: Theme.border,
    paddingHorizontal: 16,
    paddingTop: 12,
    backgroundColor: Theme.cardWhite,
    gap: 10,
  },
  footerSummary: {
    fontSize: 13,
    color: Theme.textSecondary,
  },
  footerSummaryStrong: {
    color: Theme.textPrimary,
    fontWeight: '600',
  },
  confirmBtn: {
    backgroundColor: Theme.buttonPrimary,
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
  },
  confirmBtnDisabled: {
    opacity: 0.5,
  },
  confirmBtnText: {
    color: Theme.textOnPrimary,
    fontWeight: '700',
    fontSize: 16,
  },
  inlineError: {
    fontSize: 13,
    color: Theme.negative,
    marginTop: 4,
  },
  warningBanner: {
    backgroundColor: Theme.warningMuted,
    borderWidth: 1,
    borderColor: Theme.warning,
    borderRadius: 12,
    padding: 12,
    marginBottom: 12,
  },
  warningBannerText: {
    fontSize: 13,
    color: Theme.textPrimary,
    lineHeight: 18,
  },
  partialBanner: {
    backgroundColor: Theme.surface,
    borderWidth: 1,
    borderColor: Theme.borderMedium,
    borderRadius: 12,
    padding: 12,
    marginBottom: 12,
    gap: 10,
  },
  partialBannerText: {
    fontSize: 14,
    color: Theme.textPrimary,
    lineHeight: 20,
  },
  retryBtn: {
    alignSelf: 'flex-start',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: Theme.primary,
  },
  retryBtnText: {
    color: Theme.textOnPrimary,
    fontWeight: '700',
    fontSize: 14,
  },
  otpSuccessCard: {
    backgroundColor: Theme.cardWhite,
    borderWidth: 1,
    borderColor: Theme.primary,
    borderRadius: 14,
    padding: 20,
    alignItems: 'center',
    marginVertical: 8,
  },
  otpSuccessTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: Theme.textPrimary,
    marginTop: 8,
  },
  otpSuccessCode: {
    fontSize: 32,
    fontWeight: '800',
    letterSpacing: 4,
    color: Theme.primary,
    marginVertical: 12,
  },
  otpSuccessHint: {
    fontSize: 13,
    color: Theme.textSecondary,
    textAlign: 'center',
    lineHeight: 18,
  },
  otpDismissBtn: {
    marginTop: 16,
    paddingVertical: 10,
    paddingHorizontal: 20,
  },
  otpDismissText: {
    fontSize: 14,
    fontWeight: '600',
    color: Theme.primary,
  },
  searchClear: {
    padding: 8,
  },
});
