/**
 * Supplier profile hub styles — extends the Metronic network tokens
 * and client profile atoms with supplier-specific layout primitives.
 */
import Theme from "@/constants/Theme";
import { METRONIC } from "@/features/network/components/desktop/networkDesktopHub.styles";
import { StyleSheet } from "react-native";

export { METRONIC } from "@/features/network/components/desktop/networkDesktopHub.styles";
export { networkDesktopHubStyles as hubStyles } from "@/features/network/components/desktop/networkDesktopHub.styles";
export { clientProfileStyles as spStyles } from "@/features/clients/components/desktop/clientProfileHub.styles";

/** Additional atoms not in the client profile styles — merged into spStyles override. */
export const supplierStyles = StyleSheet.create({
  // Hero stats strip
  heroStatsRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 0,
    marginTop: 16,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: "rgba(255,255,255,0.85)",
    overflow: "hidden",
  },
  heroStatItem: {
    flex: 1,
    alignItems: "center",
    paddingVertical: 10,
    paddingHorizontal: 8,
  },
  heroStatValue: {
    fontSize: 15,
    fontWeight: "600",
    color: METRONIC.text,
    letterSpacing: -0.2,
  },
  heroStatLabel: {
    fontSize: 9,
    fontWeight: "600",
    color: METRONIC.muted,
    letterSpacing: 0.4,
    marginTop: 2,
    textTransform: "uppercase",
  },
  heroStatDivider: {
    width: StyleSheet.hairlineWidth,
    alignSelf: "stretch",
    backgroundColor: METRONIC.border,
  },

  // Two-column overview
  overviewGrid: {
    flexDirection: "row",
    gap: 16,
    alignItems: "flex-start",
  },
  overviewLeft: {
    flex: 3,
    minWidth: 0,
    gap: 0,
  },
  overviewRight: {
    flex: 2,
    minWidth: 0,
    gap: 0,
  },
  overviewStack: {
    flexDirection: "column",
    width: "100%",
    alignSelf: "stretch",
    gap: 8,
  },
  overviewSection: {
    width: "100%",
    minWidth: 0,
    gap: 8,
  },

  // KPI cards
  kpiGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    marginBottom: 0,
  },
  kpiGridCompact: {
    gap: 8,
    width: "100%",
  },
  kpiCard: {
    minWidth: 140,
    flexGrow: 1,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
    padding: 14,
    gap: 4,
    alignItems: "center",
  },
  kpiCardCompact: {
    width: "48%",
    minWidth: 0,
    flexGrow: 0,
    flexShrink: 0,
    flexBasis: "48%",
    padding: 12,
  },
  kpiIcon: {
    width: 40,
    height: 40,
    borderRadius: 10,
    backgroundColor: "#F5F8FA",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 6,
    overflow: "hidden",
  },
  kpiValue: {
    fontSize: 16,
    fontWeight: "600",
    color: METRONIC.text,
    letterSpacing: -0.2,
  },
  kpiValueCompact: {
    fontSize: 16,
    fontWeight: "500",
  },
  kpiLabel: {
    fontSize: 11,
    fontWeight: "500",
    color: METRONIC.muted,
    textAlign: "center",
    lineHeight: 15,
  },

  // Data card wrapper
  dataCard: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
    padding: 16,
  },
  dataCardCompact: {
    padding: 12,
    borderRadius: 10,
    width: "100%",
    alignSelf: "stretch",
  },
  scorecardBodyCompact: {
    width: "100%",
    alignItems: "center",
    gap: 10,
  },
  importBtnCompact: {
    alignSelf: "stretch",
    justifyContent: "center",
  },

  // Info rows (label: value pairs)
  infoRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    paddingVertical: 7,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: METRONIC.border,
    gap: 16,
  },
  infoLabel: {
    fontSize: 12,
    fontWeight: "500",
    color: METRONIC.subtle,
    width: 120,
    flexShrink: 0,
  },
  infoValue: {
    flex: 1,
    fontSize: 12,
    fontWeight: "400",
    color: METRONIC.text,
    textAlign: "right",
    flexWrap: "wrap",
  },

  detailGridCompact: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    width: "100%",
  },
  detailCellCompact: {
    width: "48%",
    flexGrow: 0,
    flexShrink: 0,
    flexBasis: "48%",
    minWidth: 0,
    gap: 2,
    paddingVertical: 2,
  },
  detailLabelCompact: {
    fontSize: 10,
    fontWeight: "600",
    color: METRONIC.muted,
    textTransform: "uppercase",
    letterSpacing: 0.35,
    lineHeight: 13,
  },
  detailValueCompact: {
    fontSize: 12,
    fontWeight: "400",
    color: METRONIC.text,
    lineHeight: 17,
  },

  // Contracts
  contractsHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  contractCard: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
    padding: 16,
    marginBottom: 12,
    gap: 10,
  },
  contractCardHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  contractCardLeft: {
    flex: 1,
    minWidth: 0,
    gap: 3,
  },
  contractCardTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: METRONIC.text,
  },
  contractCardMeta: {
    fontSize: 12,
    fontWeight: "500",
    color: METRONIC.subtle,
  },
  contractStatusPill: {
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 3,
    flexShrink: 0,
  },
  contractSubTitle: {
    fontSize: 11,
    fontWeight: "700",
    color: METRONIC.muted,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginTop: 4,
    marginBottom: 6,
  },
  contractRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingVertical: 8,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: METRONIC.border,
  },
  contractName: {
    flex: 1,
    fontSize: 13,
    fontWeight: "600",
    color: METRONIC.text,
  },
  contractExpiry: {
    fontSize: 11,
    fontWeight: "500",
    color: METRONIC.muted,
  },

  // SLA badges
  slaBadgeRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  slaChip: {
    borderRadius: 6,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: "#F9FAFB",
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  slaChipText: {
    fontSize: 11,
    fontWeight: "600",
    color: METRONIC.subtle,
  },

  // Compliance health
  complianceHealthRow: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 20,
  },
  complianceHealthCard: {
    flex: 1,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
    padding: 16,
    alignItems: "center",
    gap: 6,
  },
  complianceHealthDot: {
    width: 24,
    height: 24,
    borderRadius: 12,
  },
  complianceHealthCount: {
    fontSize: 24,
    fontWeight: "800",
    color: METRONIC.text,
    letterSpacing: -0.5,
  },
  complianceHealthLabel: {
    fontSize: 11,
    fontWeight: "600",
    color: METRONIC.subtle,
  },

  // Alert config
  alertConfigRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    alignItems: "center",
    marginTop: 10,
    padding: 14,
    borderRadius: 10,
    backgroundColor: "#F9FAFB",
    borderWidth: 1,
    borderColor: METRONIC.border,
  },
  alertConfigChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: "#EEF6FF",
    backgroundColor: "#EEF6FF",
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  alertConfigText: {
    fontSize: 11,
    fontWeight: "700",
    color: METRONIC.link,
  },
  alertConfigHint: {
    fontSize: 11,
    fontWeight: "500",
    color: METRONIC.muted,
    flex: 1,
    minWidth: 200,
  },

  // Empty action card
  emptyActionCard: {
    padding: 48,
    alignItems: "center",
    gap: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: METRONIC.border,
    borderStyle: "dashed",
    backgroundColor: "#FAFAFA",
  },
  emptyActionTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: METRONIC.text,
    marginTop: 8,
  },
  emptyActionSub: {
    fontSize: 13,
    fontWeight: "500",
    color: METRONIC.subtle,
    textAlign: "center",
    maxWidth: 400,
    lineHeight: 20,
  },

  // Add button
  addBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: METRONIC.text,
  },
  addBtnText: {
    fontSize: 12,
    fontWeight: "700",
    color: Theme.buttonDarkText,
    letterSpacing: 0.2,
  },

  // Warehouse
  warehouseGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  warehouseCard: {
    width: "47%",
    minWidth: 280,
    flexGrow: 1,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
    padding: 16,
    gap: 2,
  },
  warehouseCardHead: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 10,
  },
  warehouseCardName: {
    flex: 1,
    fontSize: 14,
    fontWeight: "700",
    color: METRONIC.text,
  },
  warehouseCardCode: {
    fontSize: 10,
    fontWeight: "700",
    color: METRONIC.muted,
    letterSpacing: 0.5,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: METRONIC.border,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },

  // Performance
  performanceHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 20,
    padding: 20,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
    marginBottom: 20,
  },
  performanceHeaderMeta: {
    flex: 1,
    gap: 6,
  },
  performanceGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginTop: 12,
  },
  performanceMetricCard: {
    width: "18%",
    minWidth: 130,
    flexGrow: 1,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
    padding: 14,
    alignItems: "center",
    gap: 6,
  },
  performanceMetricIcon: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: "#F9FAFB",
    alignItems: "center",
    justifyContent: "center",
  },
  performanceMetricValue: {
    fontSize: 16,
    fontWeight: "800",
    color: METRONIC.text,
  },
  performanceMetricLabel: {
    fontSize: 10,
    fontWeight: "600",
    color: METRONIC.subtle,
    textAlign: "center",
    lineHeight: 14,
  },

  // Scorecard ring
  scorecardRing: {
    width: 80,
    height: 80,
    borderRadius: 40,
    borderWidth: 4,
    borderColor: "#50CD89",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#E8FFF3",
    gap: 0,
    flexShrink: 0,
  },
  scorecardScore: {
    fontSize: 20,
    fontWeight: "600",
    color: "#50CD89",
    letterSpacing: -0.3,
  },
  scorecardGrade: {
    fontSize: 11,
    fontWeight: "700",
    color: "#50CD89",
    marginTop: -2,
  },

  // Grade chips
  gradeChip: {
    width: 28,
    height: 28,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: METRONIC.border,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F9FAFB",
  },
  gradeChipText: {
    fontSize: 10,
    fontWeight: "700",
    color: METRONIC.subtle,
  },

  // Finance
  financeKpiRow: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 20,
    flexWrap: "wrap",
  },
  agingRow: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 20,
    flexWrap: "wrap",
  },
  agingCard: {
    flex: 1,
    minWidth: 120,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: METRONIC.border,
    borderTopWidth: 3,
    backgroundColor: Theme.cardWhite,
    padding: 14,
    alignItems: "center",
    gap: 4,
  },
  agingValue: {
    fontSize: 18,
    fontWeight: "800",
    letterSpacing: -0.3,
  },
  agingLabel: {
    fontSize: 11,
    fontWeight: "600",
    color: METRONIC.subtle,
  },

  // Timeline
  timelineNote: {
    fontSize: 12,
    fontWeight: "500",
    color: METRONIC.muted,
    marginBottom: 16,
    paddingHorizontal: 2,
  },
  timeline: {
    gap: 0,
  },
  timelineItem: {
    flexDirection: "row",
    gap: 12,
  },
  timelineLeft: {
    alignItems: "center",
    width: 28,
  },
  timelineIconCircle: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  timelineLine: {
    width: 2,
    flex: 1,
    backgroundColor: METRONIC.border,
    marginTop: 4,
    marginBottom: 4,
    minHeight: 24,
  },
  timelineContent: {
    flex: 1,
    paddingBottom: 20,
    paddingTop: 4,
    minWidth: 0,
    gap: 4,
  },
  timelineTitle: {
    fontSize: 13,
    fontWeight: "600",
    color: METRONIC.text,
    lineHeight: 19,
  },
  timelineMeta: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  timelineDate: {
    fontSize: 11,
    fontWeight: "500",
    color: METRONIC.muted,
  },

  // Activity feed — Metronic notifications / activity log pattern
  activityFeed: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
    overflow: "hidden",
  },
  activityFeedItem: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
  },
  activityFeedItemLast: {
    borderBottomWidth: 0,
  },
  activityFeedIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#F5F8FA",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    overflow: "hidden",
  },
  activityFeedBody: {
    flex: 1,
    minWidth: 0,
    gap: 3,
  },
  activityFeedHeadline: {
    fontSize: 13,
    lineHeight: 19,
    color: METRONIC.text,
  },
  activityFeedActor: {
    fontWeight: "600",
    color: METRONIC.text,
  },
  activityFeedAction: {
    fontWeight: "400",
    color: METRONIC.text,
  },
  activityFeedMeta: {
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "500",
    color: METRONIC.muted,
  },
  activityFeedDetail: {
    marginTop: 4,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 6,
    backgroundColor: "#F5F8FA",
    gap: 2,
  },
  activityFeedDetailText: {
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "500",
    color: "#78829D",
  },
  statLottieWrap: {
    marginBottom: 4,
    alignItems: "center",
    justifyContent: "center",
  },

  // Data table alt row
  dataTableRowAlt: {
    backgroundColor: "#FAFAFA",
  },

  // heroTagRow (also in client profile, included here for convenience)
  heroTagRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginTop: 8,
  },
  backBar: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: Theme.cardWhite,
    borderBottomWidth: 1,
    borderBottomColor: METRONIC.border,
  },
  backBarText: {
    fontSize: 14,
    fontWeight: "600",
    color: METRONIC.text,
  },
  hubChromeTitle: {
    flex: 1,
    fontSize: 16,
    fontWeight: "800",
    color: METRONIC.text,
    letterSpacing: -0.2,
  },
  hubChromePills: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    marginTop: 4,
  },
  hubChromePill: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    backgroundColor: "#F1F1F4",
  },
  hubChromePillText: {
    fontSize: 10,
    fontWeight: "700",
    color: METRONIC.subtle,
    letterSpacing: 0.3,
  },
  onboardingInput: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: "#FAFAFA",
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 13,
    fontWeight: "500",
    color: METRONIC.text,
    minHeight: 40,
  },
  onboardingCancelBtn: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: "#FAFAFA",
    alignItems: "center",
  },
  onboardingCancelText: {
    fontSize: 12,
    fontWeight: "700",
    color: METRONIC.subtle,
  },

  // ── Two-column desktop body layout ─────────────────────────────────────────
  hubBodyRow: {
    flexDirection: "row",
    flex: 1,
    minHeight: 400,
  },
  hubSidebarCol: {
    width: 280,
    borderRightWidth: 1,
    borderRightColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
  },
  hubMainCol: {
    flex: 1,
    minWidth: 0,
  },

  // ── Sidebar atoms ───────────────────────────────────────────────────────────
  sidebarCard: {
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: METRONIC.border,
  },
  sidebarCardTitle: {
    fontSize: 11,
    fontWeight: "700",
    color: METRONIC.muted,
    letterSpacing: 0.8,
    marginBottom: 12,
    textTransform: "uppercase",
  },
  sidebarRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 8,
  },
  sidebarRowText: {
    fontSize: 13,
    color: METRONIC.text,
    fontWeight: "500",
    flex: 1,
    minWidth: 0,
  },
  sidebarActionBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: Theme.cardWhite,
    marginBottom: 8,
  },
  sidebarActionBtnPrimary: {
    backgroundColor: METRONIC.text,
    borderColor: METRONIC.text,
  },
  sidebarActionBtnText: {
    fontSize: 12,
    fontWeight: "700",
    color: METRONIC.text,
    letterSpacing: 0.2,
  },
  sidebarActionBtnTextPrimary: {
    color: Theme.buttonPrimaryText,
  },
  sidebarBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
  },
  sidebarBadgeText: {
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.3,
  },
  sidebarKvRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 7,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: METRONIC.border,
    gap: 8,
  },
  sidebarKvLabel: {
    fontSize: 12,
    fontWeight: "500",
    color: METRONIC.muted,
    flexShrink: 0,
    minWidth: 72,
  },
  sidebarKvValue: {
    fontSize: 12,
    fontWeight: "600",
    color: METRONIC.text,
    textAlign: "right",
    flex: 1,
  },

  // ── Inline panel forms ──────────────────────────────────────────────────────
  inlineFormCard: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: "#FAFAFA",
    padding: 16,
    marginBottom: 16,
    gap: 12,
  },
  inlineFormTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: METRONIC.text,
    marginBottom: 4,
  },
  formGrid: { flexDirection: "row", flexWrap: "wrap", gap: 12 },
  fieldGroup: { minWidth: 200, flexGrow: 1, flexShrink: 1, gap: 5 },
  fieldLabel: {
    fontSize: 10,
    fontWeight: "700",
    color: METRONIC.muted,
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  fieldInput: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: "#fff",
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 13,
    fontWeight: "500",
    color: METRONIC.text,
    minHeight: 40,
  },
  selectBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: "#fff",
    paddingHorizontal: 12,
    paddingVertical: 10,
    minHeight: 40,
  },
  selectBtnText: { fontSize: 13, fontWeight: "500", color: METRONIC.text },
  selectDropdown: {
    position: "absolute",
    top: 68,
    left: 0,
    right: 0,
    zIndex: 100,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: "#fff",
    shadowColor: "#181C32",
    shadowOpacity: 0.08,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 8,
  },
  selectOption: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  selectOptionActive: { backgroundColor: "#EEF6FF" },
  selectOptionText: { fontSize: 13, fontWeight: "500", color: METRONIC.text },
  selectOptionTextActive: { color: METRONIC.link, fontWeight: "700" },
  inlineFormError: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#FFF1F2",
    borderRadius: 8,
    padding: 10,
    borderWidth: 1,
    borderColor: "#FECDD3",
  },
  inlineFormErrorText: { fontSize: 12, fontWeight: "600", color: "#F1416C", flex: 1 },
  inlineFormActions: { flexDirection: "row", gap: 10, marginTop: 4 },
  inlineCancelBtn: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: METRONIC.border,
    backgroundColor: "#FAFAFA",
    alignItems: "center",
  },
  inlineCancelBtnText: { fontSize: 12, fontWeight: "700", color: METRONIC.subtle },
  inlineSaveBtn: {
    flex: 2,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 10,
    borderRadius: 8,
    backgroundColor: METRONIC.text,
  },
  inlineSaveBtnText: { fontSize: 12, fontWeight: "700", color: "#fff" },
});
