import Theme from "@/constants/Theme";
import { Platform, StyleSheet } from "react-native";

export const aws = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: Theme.assignmentPageBg,
  },
  header: {
    backgroundColor: Theme.cardWhite,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Theme.networkCardBorder,
    zIndex: 30,
    ...Platform.select({
      web: { position: "sticky" as unknown as undefined, top: 0 },
      default: {},
    }),
  },
  headerInner: {
    maxWidth: 1280,
    width: "100%",
    alignSelf: "center",
    paddingHorizontal: 16,
    minHeight: 64,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  headerLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    flexShrink: 1,
    minWidth: 0,
  },
  iconBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: Theme.surface,
    borderWidth: 1,
    borderColor: Theme.networkCardBorder,
    alignItems: "center",
    justifyContent: "center",
  },
  eyebrow: {
    fontSize: 10,
    fontWeight: "800",
    color: Theme.textMuted,
    letterSpacing: 1.2,
    textTransform: "uppercase",
    fontFamily: Platform.select({ ios: "Menlo", android: "monospace", default: "monospace" }),
  },
  tripTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flexWrap: "wrap",
  },
  tripCode: {
    fontSize: 16,
    fontWeight: "800",
    color: Theme.textPrimaryDark,
    letterSpacing: -0.3,
    fontFamily: Platform.select({ ios: "Menlo", android: "monospace", default: "monospace" }),
  },
  statusPill: {
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 999,
    backgroundColor: Theme.networkHubListCardConnectedBg,
    borderWidth: 1,
    borderColor: Theme.networkHubListCardConnectedBorder,
  },
  statusPillText: {
    fontSize: 10,
    fontWeight: "700",
    color: Theme.networkHubListCardConnectedText,
    letterSpacing: 0.6,
    textTransform: "uppercase",
  },
  headerRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flexShrink: 0,
  },
  phoneChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: Theme.surface,
    borderWidth: 1,
    borderColor: Theme.networkCardBorder,
  },
  phoneChipText: {
    fontSize: 12,
    fontWeight: "600",
    color: Theme.textPrimary,
    fontFamily: Platform.select({ ios: "Menlo", android: "monospace", default: "monospace" }),
  },
  activityBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: Theme.surface,
    borderWidth: 1,
    borderColor: Theme.networkCardBorder,
  },
  activityBtnText: {
    fontSize: 11,
    fontWeight: "700",
    color: Theme.textPrimary,
    letterSpacing: 0.6,
    textTransform: "uppercase",
  },
  main: {
    flex: 1,
    maxWidth: 1280,
    width: "100%",
    alignSelf: "center",
    paddingHorizontal: 16,
    paddingVertical: 20,
    gap: 20,
  },
  hero: {
    backgroundColor: Theme.assignmentHeroBg,
    borderRadius: 24,
    padding: 24,
    overflow: "hidden",
    position: "relative",
  },
  heroRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
    zIndex: 1,
    minWidth: 0,
  },
  heroMetaRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 16,
    marginBottom: 14,
  },
  heroMetaItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  heroMetaIcon: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "rgba(255,255,255,0.08)",
    alignItems: "center",
    justifyContent: "center",
  },
  heroMetaLabel: {
    fontSize: 11,
    color: Theme.textMuted,
    fontFamily: Platform.select({ ios: "Menlo", android: "monospace", default: "monospace" }),
  },
  heroMetaValue: {
    fontSize: 12,
    fontWeight: "700",
    color: Theme.cardWhite,
  },
  routeRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    width: "100%",
    minWidth: 0,
  },
  routeRowMobile: {
    gap: 10,
  },
  routeEndpoint: {
    flex: 1,
    minWidth: 0,
    maxWidth: "40%",
  },
  routeEndpointEnd: {
    alignItems: "flex-end",
  },
  routeEndpointMobile: {
    maxWidth: "46%",
    flexBasis: "auto",
  },
  routeCity: {
    fontSize: 22,
    fontWeight: "900",
    color: Theme.cardWhite,
    letterSpacing: 0.4,
    fontFamily: Platform.select({ ios: "Menlo", android: "monospace", default: "monospace" }),
  },
  routeCityEnd: {
    textAlign: "right",
  },
  routeSub: {
    fontSize: 11,
    color: Theme.textMuted,
    marginTop: 2,
  },
  routeSubEnd: {
    textAlign: "right",
  },
  routeCenter: {
    width: 96,
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 4,
  },
  routeArrowMobile: {
    flexShrink: 0,
    paddingHorizontal: 4,
  },
  routeCenterLabels: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 4,
  },
  routeCenterLabel: {
    fontSize: 10,
    color: Theme.textMuted,
    fontFamily: Platform.select({ ios: "Menlo", android: "monospace", default: "monospace" }),
  },
  routeLine: {
    width: "100%",
    height: 28,
    justifyContent: "center",
    alignItems: "center",
  },
  routeLineFill: {
    position: "absolute",
    left: 0,
    right: 0,
    height: 2,
    backgroundColor: Theme.primaryLight,
    opacity: 0.85,
    borderRadius: 1,
  },
  routeDot: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: Theme.driverPrimary,
    borderWidth: 2,
    borderColor: Theme.networkHubListCardOnlineDot,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2,
  },
  routeDotText: {
    fontSize: 11,
    fontWeight: "800",
    color: Theme.cardWhite,
  },
  metricsBox: {
    flexDirection: "row",
    flexShrink: 0,
    backgroundColor: "rgba(15,23,42,0.9)",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(51,65,85,0.8)",
    paddingVertical: 8,
  },
  metricCell: {
    paddingHorizontal: 16,
    paddingVertical: 6,
    alignItems: "center",
    borderRightWidth: StyleSheet.hairlineWidth,
    borderRightColor: "rgba(51,65,85,0.9)",
  },
  metricCellLast: {
    borderRightWidth: 0,
  },
  metricLabel: {
    fontSize: 10,
    fontWeight: "700",
    color: Theme.textMuted,
    letterSpacing: 0.5,
    textTransform: "uppercase",
    marginBottom: 2,
    fontFamily: Platform.select({ ios: "Menlo", android: "monospace", default: "monospace" }),
  },
  metricValue: {
    fontSize: 13,
    fontWeight: "800",
    color: Theme.cardWhite,
    fontFamily: Platform.select({ ios: "Menlo", android: "monospace", default: "monospace" }),
  },
  metricValueWarn: {
    fontSize: 12,
    fontWeight: "700",
    color: Theme.feedbackModalStarActive,
    letterSpacing: 0.5,
    textTransform: "uppercase",
    fontFamily: Platform.select({ ios: "Menlo", android: "monospace", default: "monospace" }),
  },
  toolbarRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  tabBar: {
    flexDirection: "row",
    flexWrap: "wrap",
    backgroundColor: Theme.cardWhite,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: Theme.networkCardBorder,
    padding: 6,
    gap: 4,
  },
  tab: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 12,
  },
  tabActive: {
    backgroundColor: Theme.assignmentHeroBg,
  },
  tabText: {
    fontSize: 11,
    fontWeight: "800",
    color: Theme.textSecondary,
    letterSpacing: 0.3,
  },
  tabTextActive: {
    color: Theme.cardWhite,
  },
  modeBar: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: Theme.cardWhite,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: Theme.networkCardBorder,
    padding: 6,
  },
  modeLabel: {
    fontSize: 11,
    fontWeight: "800",
    color: Theme.textMuted,
    letterSpacing: 0.6,
    textTransform: "uppercase",
    paddingLeft: 10,
  },
  modeToggle: {
    flexDirection: "row",
    backgroundColor: Theme.surface,
    borderRadius: 12,
    padding: 4,
  },
  modeBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 8,
  },
  modeBtnAsset: {
    backgroundColor: "#2563eb",
  },
  modeBtnMarket: {
    backgroundColor: "#4f46e5",
  },
  modeBtnText: {
    fontSize: 11,
    fontWeight: "700",
    color: Theme.textSecondary,
  },
  modeBtnTextActive: {
    color: Theme.cardWhite,
  },
  infoBanner: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    backgroundColor: Theme.assignmentInfoBannerBg,
    borderWidth: 1,
    borderColor: Theme.assignmentInfoBannerBorder,
    borderRadius: 16,
    padding: 14,
  },
  infoBannerLeft: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    flex: 1,
    minWidth: 0,
  },
  infoIcon: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: "#2563eb",
    alignItems: "center",
    justifyContent: "center",
  },
  infoTitle: {
    fontSize: 11,
    fontWeight: "800",
    color: Theme.assignmentInfoBannerText,
    letterSpacing: 0.6,
    textTransform: "uppercase",
  },
  infoBody: {
    fontSize: 11,
    color: "rgba(30, 58, 138, 0.9)",
    marginTop: 2,
    lineHeight: 16,
  },
  verifyChip: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: "rgba(37, 99, 235, 0.12)",
    borderWidth: 1,
    borderColor: Theme.assignmentInfoBannerBorder,
  },
  verifyChipText: {
    fontSize: 10,
    fontWeight: "700",
    color: Theme.assignmentInfoBannerText,
    fontFamily: Platform.select({ ios: "Menlo", android: "monospace", default: "monospace" }),
  },
  dualGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 20,
    alignItems: "stretch",
    ...Platform.select({
      web: {
        display: "grid" as unknown as undefined,
        gridTemplateColumns: "repeat(2, minmax(0, 1fr))" as unknown as undefined,
      },
      default: {},
    }),
  },
  panel: {
    flex: 1,
    minWidth: 300,
    backgroundColor: Theme.cardWhite,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: Theme.networkCardBorder,
    // Clip only rounded corners on the header; body lists need to scroll.
    overflow: "visible",
    alignSelf: "stretch",
    flexDirection: "column",
    ...Platform.select({
      web: {
        minWidth: 0,
        width: "100%",
        height: "100%",
        // Keep card chrome rounded without clipping the list scrollport.
        overflow: "hidden",
        boxShadow: `0 8px 24px -6px ${Theme.assignmentCardShadow}`,
      },
      default: {
        overflow: "hidden",
        shadowColor: Theme.networkHubListCardShadow,
        shadowOpacity: 0.06,
        shadowRadius: 16,
        shadowOffset: { width: 0, height: 8 },
        elevation: 2,
      },
    }),
  },
  panelHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    paddingHorizontal: 18,
    paddingVertical: 14,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Theme.surfaceBorder,
    backgroundColor: Theme.surface,
    flexWrap: "wrap",
    minHeight: 72,
  },
  panelHeaderLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flex: 1,
    minWidth: 160,
  },
  panelIconDriver: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: Theme.networkHubListCardConnectedBg,
    borderWidth: 1,
    borderColor: Theme.networkHubListCardConnectedBorder,
    alignItems: "center",
    justifyContent: "center",
  },
  panelIconVehicle: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: Theme.assignmentVehicleAccentSoft,
    borderWidth: 1,
    borderColor: Theme.assignmentVehicleAccentBorder,
    alignItems: "center",
    justifyContent: "center",
  },
  panelTitle: {
    fontSize: 12,
    fontWeight: "800",
    color: Theme.textPrimaryDark,
    letterSpacing: 0.6,
    textTransform: "uppercase",
  },
  panelSub: {
    fontSize: 11,
    color: Theme.textMuted,
    marginTop: 2,
    lineHeight: 15,
  },
  actionToggle: {
    flexDirection: "row",
    backgroundColor: Theme.surfaceBorder,
    borderRadius: 12,
    padding: 3,
    flexShrink: 0,
    alignSelf: "center",
  },
  actionBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 9,
    minHeight: 34,
  },
  actionBtnActive: {
    backgroundColor: Theme.cardWhite,
    ...Platform.select({
      web: { boxShadow: "0 1px 3px rgba(15,23,42,0.08)" },
      default: {
        shadowColor: "#000",
        shadowOpacity: 0.06,
        shadowRadius: 3,
        shadowOffset: { width: 0, height: 1 },
        elevation: 1,
      },
    }),
  },
  actionBtnSwapDriver: {
    backgroundColor: Theme.driverPrimary,
  },
  actionBtnSwapVehicle: {
    backgroundColor: Theme.assignmentVehicleAccent,
  },
  actionBtnText: {
    fontSize: 11,
    fontWeight: "700",
    color: Theme.textSecondary,
  },
  actionBtnTextActive: {
    color: Theme.textPrimaryDark,
  },
  actionBtnTextOnDark: {
    color: Theme.cardWhite,
  },
  panelBody: {
    padding: 18,
    gap: 14,
    flexGrow: 1,
    flex: 1,
  },
  fieldsArea: {
    flexGrow: 1,
    gap: 12,
    minHeight: 148,
    // Allow nested roster lists to own their scroll (do not clip children).
    overflow: "visible",
  },
  snapshot: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    backgroundColor: Theme.surface,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: Theme.networkCardBorder,
    padding: 14,
    minHeight: 76,
  },
  snapshotLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flex: 1,
    minWidth: 0,
  },
  snapshotAvatarDriver: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: Theme.driverPrimary,
    alignItems: "center",
    justifyContent: "center",
  },
  snapshotAvatarVehicle: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: Theme.assignmentVehicleAccent,
    alignItems: "center",
    justifyContent: "center",
  },
  snapshotAvatarText: {
    fontSize: 18,
    fontWeight: "800",
    color: Theme.cardWhite,
  },
  snapshotEyebrow: {
    fontSize: 11,
    fontWeight: "700",
    color: Theme.textMuted,
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  snapshotName: {
    fontSize: 15,
    fontWeight: "800",
    color: Theme.textPrimaryDark,
    letterSpacing: -0.2,
  },
  snapshotMeta: {
    fontSize: 12,
    fontWeight: "500",
    color: Theme.textSecondary,
    marginTop: 2,
    fontFamily: Platform.select({ ios: "Menlo", android: "monospace", default: "monospace" }),
  },
  badgeOk: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: Theme.networkHubListCardConnectedBg,
    borderWidth: 1,
    borderColor: Theme.networkHubListCardConnectedBorder,
  },
  badgeOkText: {
    fontSize: 10,
    fontWeight: "700",
    color: Theme.networkHubListCardConnectedText,
    letterSpacing: 0.4,
    textTransform: "uppercase",
    fontFamily: Platform.select({ ios: "Menlo", android: "monospace", default: "monospace" }),
  },
  badgeBlue: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: Theme.assignmentVehicleAccentSoft,
    borderWidth: 1,
    borderColor: Theme.assignmentVehicleAccentBorder,
  },
  badgeBlueText: {
    fontSize: 10,
    fontWeight: "700",
    color: Theme.assignmentVehicleAccentText,
    letterSpacing: 0.4,
    textTransform: "uppercase",
    fontFamily: Platform.select({ ios: "Menlo", android: "monospace", default: "monospace" }),
  },
  fieldLabel: {
    fontSize: 11,
    fontWeight: "700",
    color: Theme.textSecondary,
    marginBottom: 6,
  },
  input: {
    width: "100%",
    paddingHorizontal: 14,
    paddingVertical: Platform.OS === "web" ? 12 : 13,
    borderRadius: 14,
    backgroundColor: Theme.surface,
    borderWidth: 1,
    borderColor: Theme.networkCardBorder,
    fontSize: 14,
    fontWeight: "600",
    color: Theme.textPrimaryDark,
    ...Platform.select({
      web: {
        outlineStyle: "none" as unknown as undefined,
        boxShadow: "inset 0 1px 2px rgba(15,23,42,0.04)",
      },
      default: {},
    }),
  },
  fieldsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  fieldHalf: {
    flexGrow: 1,
    flexBasis: "45%",
    minWidth: 140,
  },
  fieldFull: {
    flexGrow: 1,
    flexBasis: "100%",
    minWidth: 0,
    width: "100%",
  },
  panelHeaderMobile: {
    flexDirection: "column",
    alignItems: "stretch",
  },
  actionToggleMobile: {
    alignSelf: "stretch",
    justifyContent: "space-between",
  },
  actionBtnMobile: {
    flex: 1,
    justifyContent: "center",
  },
  snapshotMobile: {
    flexDirection: "column",
    alignItems: "flex-start",
    gap: 10,
  },
  panelBodyMobile: {
    padding: 14,
    gap: 12,
  },
  dualGridMobile: {
    gap: 14,
    ...Platform.select({
      web: {
        display: "flex" as unknown as undefined,
        flexDirection: "column",
      },
      default: {
        flexDirection: "column",
      },
    }),
  },
  panelMobile: {
    minWidth: 0,
    width: "100%",
    borderRadius: 18,
    ...Platform.select({
      web: { height: "auto" },
      default: {},
    }),
  },
  mainMobile: {
    paddingHorizontal: 12,
    paddingVertical: 12,
    gap: 14,
  },
  heroMobile: {
    padding: 16,
    borderRadius: 18,
  },
  routeCityMobile: {
    fontSize: 18,
  },
  metricsBoxMobile: {
    flexWrap: "wrap",
    alignSelf: "stretch",
    justifyContent: "space-between",
  },
  sectionHintRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 2,
    gap: 8,
  },
  sectionHint: {
    fontSize: 11,
    fontWeight: "700",
    color: Theme.textMuted,
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  kycHint: {
    fontSize: 10,
    fontWeight: "700",
    color: Theme.networkHubListCardConnectedText,
    fontFamily: Platform.select({ ios: "Menlo", android: "monospace", default: "monospace" }),
  },
  kycHintVehicle: {
    fontSize: 10,
    fontWeight: "700",
    color: Theme.assignmentVehicleAccent,
    fontFamily: Platform.select({ ios: "Menlo", android: "monospace", default: "monospace" }),
  },
  auditCard: {
    backgroundColor: Theme.cardWhite,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: Theme.networkCardBorder,
    padding: 20,
    gap: 16,
    ...Platform.select({
      web: {
        boxShadow: `0 8px 24px -6px ${Theme.assignmentCardShadow}`,
      },
      default: {},
    }),
  },
  auditHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Theme.surfaceBorder,
    paddingBottom: 12,
    gap: 12,
    flexWrap: "wrap",
  },
  auditTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  auditTitle: {
    fontSize: 11,
    fontWeight: "800",
    color: Theme.textPrimaryDark,
    letterSpacing: 0.6,
    textTransform: "uppercase",
  },
  auditId: {
    fontSize: 11,
    fontWeight: "600",
    color: Theme.textMuted,
    fontFamily: Platform.select({ ios: "Menlo", android: "monospace", default: "monospace" }),
  },
  auditGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 14,
    alignItems: "flex-end",
  },
  auditReason: {
    flexGrow: 1,
    flexBasis: 220,
    minWidth: 180,
  },
  auditRemarks: {
    flexGrow: 2,
    flexBasis: 260,
    minWidth: 180,
  },
  auditSubmitWrap: {
    flexGrow: 1,
    flexBasis: 180,
    minWidth: 160,
  },
  confirmBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 14,
    paddingHorizontal: 18,
    borderRadius: 14,
    backgroundColor: Theme.assignmentHeroBg,
    minHeight: 48,
  },
  confirmBtnDisabled: {
    opacity: 0.45,
  },
  confirmBtnText: {
    fontSize: 11,
    fontWeight: "800",
    color: Theme.cardWhite,
    letterSpacing: 0.6,
    textTransform: "uppercase",
  },
  placeholderTab: {
    backgroundColor: Theme.cardWhite,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: Theme.networkCardBorder,
    padding: 40,
    alignItems: "center",
  },
  placeholderText: {
    fontSize: 13,
    color: Theme.textMuted,
    textAlign: "center",
  },
  toast: {
    position: "absolute",
    right: 24,
    bottom: 24,
    zIndex: 50,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 18,
    paddingVertical: 14,
    borderRadius: 16,
    backgroundColor: Theme.textPrimaryDark,
    borderWidth: 1,
    borderColor: "rgba(16, 185, 129, 0.5)",
    maxWidth: 420,
  },
  toastText: {
    flex: 1,
    fontSize: 12,
    fontWeight: "700",
    color: Theme.cardWhite,
  },
  drawerBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(15, 23, 42, 0.5)",
    zIndex: 60,
    flexDirection: "row",
    justifyContent: "flex-end",
  },
  drawer: {
    width: "100%",
    maxWidth: 400,
    backgroundColor: Theme.cardWhite,
    height: "100%",
    padding: 20,
    justifyContent: "space-between",
  },
  drawerHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Theme.surfaceBorder,
    paddingBottom: 14,
    marginBottom: 20,
  },
  drawerTitle: {
    fontSize: 13,
    fontWeight: "800",
    color: Theme.textPrimaryDark,
    textTransform: "uppercase",
  },
  drawerSub: {
    fontSize: 11,
    color: Theme.textMuted,
    fontFamily: Platform.select({ ios: "Menlo", android: "monospace", default: "monospace" }),
  },
  timeline: {
    borderLeftWidth: 2,
    borderLeftColor: Theme.surfaceBorder,
    paddingLeft: 16,
    marginLeft: 8,
    gap: 22,
  },
  timelineDot: {
    position: "absolute",
    left: -23,
    top: 2,
    width: 12,
    height: 12,
    borderRadius: 6,
    borderWidth: 3,
    borderColor: Theme.cardWhite,
  },
  timelineTime: {
    fontSize: 10,
    color: Theme.textMuted,
    fontFamily: Platform.select({ ios: "Menlo", android: "monospace", default: "monospace" }),
  },
  timelineTitle: {
    fontSize: 12,
    fontWeight: "700",
    color: Theme.textPrimaryDark,
    marginTop: 2,
  },
  timelineBody: {
    fontSize: 11,
    color: Theme.textMuted,
    marginTop: 2,
    lineHeight: 16,
  },
  drawerClose: {
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: Theme.surface,
    alignItems: "center",
  },
  drawerCloseText: {
    fontSize: 11,
    fontWeight: "700",
    color: Theme.textPrimary,
    textTransform: "uppercase",
  },
  hint: {
    fontSize: 12,
    color: Theme.destructive,
    marginTop: 4,
  },
  selectLike: {
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 14,
    backgroundColor: Theme.surface,
    borderWidth: 1,
    borderColor: Theme.networkCardBorder,
  },
  selectLikeText: {
    fontSize: 13,
    fontWeight: "500",
    color: Theme.textPrimaryDark,
  },
  reasonChips: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    marginTop: 8,
  },
  reasonChip: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: Theme.surface,
    borderWidth: 1,
    borderColor: Theme.networkCardBorder,
  },
  reasonChipActive: {
    backgroundColor: Theme.assignmentHeroBg,
    borderColor: Theme.assignmentHeroBg,
  },
  reasonChipText: {
    fontSize: 10,
    fontWeight: "600",
    color: Theme.textSecondary,
  },
  reasonChipTextActive: {
    color: Theme.cardWhite,
  },
});
