import Theme from "@/constants/Theme";
import { Platform, StyleSheet } from "react-native";

/** Shared content rail — header / body / footer share this width + padding. */
export const CREATE_TRIP_DESKTOP_RAIL = {
  maxWidth: 1320,
  paddingHorizontal: 28,
} as const;

/** Desktop create-trip overlay — solid surfaces, aligned workspace rail. */
export const createTripDesktopStyles = StyleSheet.create({
  root: {
    flex: 1,
    width: "100%",
    backgroundColor: Theme.cardWhite,
    overflow: "hidden",
  },
  rail: {
    width: "100%",
    maxWidth: CREATE_TRIP_DESKTOP_RAIL.maxWidth,
    alignSelf: "center",
    paddingHorizontal: CREATE_TRIP_DESKTOP_RAIL.paddingHorizontal,
  },
  header: {
    borderBottomWidth: 1,
    borderBottomColor: Theme.borderLight,
    backgroundColor: Theme.cardWhite,
    zIndex: 20,
    flexShrink: 0,
  },
  headerInner: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 14,
    gap: 16,
  },
  headerLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 20,
    minWidth: 0,
    flex: 1,
  },
  closeBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingVertical: 4,
    ...Platform.select({ web: { cursor: "pointer" as const }, default: {} }),
  },
  closeBtnText: {
    fontSize: 14,
    fontWeight: "700",
    color: Theme.textSecondary,
  },
  headerDivider: {
    width: 1,
    height: 22,
    backgroundColor: Theme.borderLight,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: Theme.textPrimaryDark,
    letterSpacing: -0.35,
  },
  headerStep: {
    fontSize: 12,
    fontWeight: "700",
    color: Theme.textSecondary,
    letterSpacing: 0.2,
    flexShrink: 0,
  },
  content: {
    flex: 1,
    backgroundColor: Theme.cardWhite,
  },
  contentInner: {
    width: "100%",
    maxWidth: CREATE_TRIP_DESKTOP_RAIL.maxWidth,
    alignSelf: "center",
    paddingTop: 20,
    paddingHorizontal: CREATE_TRIP_DESKTOP_RAIL.paddingHorizontal,
    paddingBottom: 20,
  },
  stepSurface: {
    width: "100%",
    backgroundColor: Theme.cardWhite,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    overflow: "hidden",
  },
  stepSurfaceFill: {
    flex: 1,
    minHeight: 0,
  },
  stepSurfaceHeader: {
    paddingHorizontal: 24,
    paddingTop: 18,
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: Theme.borderLight,
    backgroundColor: Theme.cardWhite,
    gap: 12,
  },
  stepSurfaceBody: {
    paddingHorizontal: 24,
    paddingTop: 20,
    paddingBottom: 24,
    gap: 0,
    backgroundColor: Theme.cardWhite,
  },
  stepSurfaceBodyFill: {
    flex: 1,
    minHeight: 0,
    paddingVertical: 16,
  },
  stepSurfaceBodyScroll: {
    flex: 1,
    minHeight: 0,
    width: "100%",
  },
  stepSurfaceBodyScrollContent: {
    paddingHorizontal: 24,
    paddingTop: 20,
    paddingBottom: 32,
    flexGrow: 1,
  },
  stepSubtitle: {
    fontSize: 13,
    fontWeight: "500",
    color: Theme.textSecondary,
    lineHeight: 18,
  },
  stepBody: {
    width: "100%",
    gap: 20,
  },
  footer: {
    borderTopWidth: 1,
    borderTopColor: Theme.borderLight,
    backgroundColor: Theme.cardWhite,
    zIndex: 30,
    flexShrink: 0,
  },
  footerInner: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    paddingVertical: 14,
    gap: 16,
  },
  footerInnerWithBack: {
    justifyContent: "space-between",
  },
  footerBackBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingVertical: 8,
    paddingHorizontal: 2,
    minWidth: 72,
    ...Platform.select({ web: { cursor: "pointer" as const }, default: {} }),
  },
  footerBackBtnText: {
    fontSize: 13,
    fontWeight: "600",
    color: Theme.textSecondary,
  },
  footerSecondary: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    minWidth: 80,
    ...Platform.select({ web: { cursor: "pointer" as const }, default: {} }),
  },
  footerSecondaryText: {
    fontSize: 14,
    fontWeight: "700",
    color: Theme.textSecondary,
  },
  footerPrimaryWrap: {
    maxWidth: 280,
    minWidth: 180,
    flexShrink: 0,
    alignItems: "stretch",
  },
  footerPrimaryBtn: {
    width: "100%",
    paddingVertical: 12,
    borderRadius: 10,
    backgroundColor: Theme.primary,
    alignItems: "center",
    justifyContent: "center",
    minHeight: 44,
    ...Platform.select({ web: { cursor: "pointer" as const }, default: {} }),
  },
  footerPrimaryBtnDisabled: {
    opacity: 0.38,
    backgroundColor: Theme.borderMedium,
  },
  footerPrimaryBtnText: {
    fontSize: 14,
    fontWeight: "700",
    color: Theme.textOnPrimary,
  },
  footerSpacer: {
    width: 72,
  },
  footerHint: {
    marginTop: 6,
    textAlign: "right",
    fontSize: 11,
    color: Theme.textMuted,
    fontWeight: "500",
  },
  stepperWrap: {
    width: "100%",
    position: "relative",
  },
  stepperTrack: {
    position: "absolute",
    left: "8%",
    right: "8%",
    top: 18,
    height: 1,
    backgroundColor: Theme.borderLight,
    zIndex: 0,
  },
  stepperRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    zIndex: 1,
  },
  stepperItem: {
    flex: 1,
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 4,
    backgroundColor: Theme.cardWhite,
    minWidth: 0,
  },
  stepperCircle: {
    width: 36,
    height: 36,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Theme.surface,
    borderWidth: 1,
    borderColor: Theme.borderLight,
  },
  stepperCircleActive: {
    backgroundColor: Theme.primary,
    borderColor: Theme.primary,
  },
  stepperCircleDone: {
    backgroundColor: Theme.positiveMuted,
    borderColor: Theme.positiveMuted,
  },
  stepperCircleText: {
    fontSize: 13,
    fontWeight: "700",
    color: Theme.textMuted,
  },
  stepperCircleTextActive: {
    color: Theme.textOnPrimary,
  },
  stepperCircleTextDone: {
    color: Theme.darkGreen,
  },
  stepperLabel: {
    fontSize: 10,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    color: Theme.textMuted,
    textAlign: "center",
  },
  stepperLabelActive: {
    color: Theme.textPrimaryDark,
  },
  stepGrid: Platform.select({
    web: {
      flexDirection: "row",
      alignItems: "stretch",
      gap: 24,
      width: "100%",
    } as const,
    default: {
      flexDirection: "column",
      gap: 20,
      width: "100%",
    },
  }),
  stepGridMain: {
    flex: 1.35,
    minWidth: 0,
    gap: 16,
  },
  stepGridAside: Platform.select({
    web: {
      flex: 0.9,
      minWidth: 240,
      maxWidth: 340,
      flexShrink: 0,
      gap: 16,
      justifyContent: "flex-start",
    } as const,
    default: {
      width: "100%",
      gap: 16,
    },
  }),
  allocationColumns: Platform.select({
    web: {
      flexDirection: "row",
      alignItems: "stretch",
      gap: 20,
      width: "100%",
      flex: 1,
      minHeight: 0,
    } as const,
    default: {
      gap: 20,
      width: "100%",
    },
  }),
  allocationColumn: {
    flex: 1,
    minWidth: 0,
    gap: 10,
    minHeight: 0,
  },
  allocationStepBody: {
    width: "100%",
    flex: 1,
    minHeight: 0,
    gap: 16,
  },
  allocationToolbar: {
    width: "100%",
    gap: 12,
    flexGrow: 0,
    flexShrink: 0,
  },
  allocationFleetPanel: {
    width: "100%",
    flex: 1,
    minHeight: 0,
    gap: 12,
  },
  allocationWarnCompact: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    backgroundColor: Theme.warningMuted,
    borderWidth: 1,
    borderColor: Theme.borderLight,
  },
  allocationWarnCompactText: {
    flex: 1,
    fontSize: 10,
    fontWeight: "500",
    color: Theme.warning,
    lineHeight: 14,
  },
  fieldSection: {
    width: "100%",
    gap: 10,
    flexGrow: 0,
    flexShrink: 0,
  },
  /** Single allocation form — equal columns, no flex-overlap on stacks. */
  allocationForm: {
    width: "100%",
    gap: 16,
    flexGrow: 0,
    flexShrink: 0,
  },
  allocationFormRow: Platform.select({
    web: {
      flexDirection: "row",
      alignItems: "flex-start",
      gap: 24,
      width: "100%",
    } as const,
    default: {
      flexDirection: "column",
      gap: 16,
      width: "100%",
    },
  }),
  allocationFormRowTop: {
    alignItems: "flex-start",
  },
  allocationFormCol: {
    flex: 1,
    minWidth: 0,
    gap: 12,
  },
  allocationFieldBlock: {
    width: "100%",
    gap: 8,
    flexGrow: 0,
    flexShrink: 0,
  },
  allocationFieldBlockFull: {
    width: "100%",
    gap: 8,
    flexGrow: 0,
    flexShrink: 0,
    marginTop: 4,
  },
  sectionHeading: {
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.8,
    color: Theme.textMuted,
    marginBottom: 4,
  },
  routeGrid: Platform.select({
    web: {
      flexDirection: "row",
      alignItems: "stretch",
      gap: 24,
      width: "100%",
    } as const,
    default: {
      flexDirection: "column",
      gap: 20,
      width: "100%",
    },
  }),
  routeGridMain: {
    flex: 1.35,
    minWidth: 0,
    gap: 16,
  },
  routeGridAside: Platform.select({
    web: {
      flex: 0.9,
      minWidth: 240,
      maxWidth: 340,
      flexShrink: 0,
      gap: 16,
    } as const,
    default: {
      width: "100%",
      gap: 16,
    },
  }),
  routeFieldsStack: {
    gap: 16,
    position: "relative",
  },
  routeConnector: {
    position: "absolute",
    left: 23,
    top: 52,
    bottom: 52,
    width: 2,
    borderLeftWidth: 2,
    borderStyle: "dashed",
    borderColor: Theme.borderLight,
    zIndex: 0,
  },
  routeFieldBlock: {
    gap: 8,
    zIndex: 1,
  },
  routeFieldLabel: {
    fontSize: 10,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 1.2,
    color: Theme.textMuted,
  },
  routeFieldLabelPickup: {
    color: Theme.textSecondary,
  },
  routeFieldLabelDrop: {
    color: Theme.textSecondary,
  },
  routeInputShell: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Theme.cardWhite,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    gap: 12,
    minHeight: 48,
    ...Platform.select({
      web: {
        boxShadow: "0 1px 2px rgba(15, 23, 42, 0.04)",
      },
      default: {},
    }),
  },
  routeInputShellError: {
    borderColor: Theme.destructive,
  },
  routeInputFlex: {
    flex: 1,
    minWidth: 0,
  },
  routeDateSection: {
    gap: 12,
  },
  quickDateRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  quickDateChip: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    backgroundColor: Theme.cardWhite,
    ...Platform.select({ web: { cursor: "pointer" as const }, default: {} }),
  },
  quickDateChipActive: {
    borderColor: Theme.textPrimaryDark,
    backgroundColor: Theme.cardWhite,
    ...Platform.select({
      web: { boxShadow: "0 1px 3px rgba(15, 23, 42, 0.08)" },
      default: {},
    }),
  },
  quickDateChipText: {
    fontSize: 12,
    fontWeight: "600",
    color: Theme.textSecondary,
  },
  quickDateChipTextActive: {
    color: Theme.textPrimaryDark,
  },
  dateInput: {
    width: "100%",
    backgroundColor: Theme.cardWhite,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 14,
    fontWeight: "600",
    color: Theme.textPrimaryDark,
    ...Platform.select({
      web: { outlineStyle: "none" } as object,
    }),
  },
  infoBanner: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    padding: 14,
    backgroundColor: Theme.surface,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    borderRadius: 10,
  },
  infoBannerIcon: {
    width: 40,
    height: 40,
    borderRadius: 10,
    backgroundColor: Theme.surfaceForm,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  infoBannerCopy: {
    flex: 1,
    minWidth: 0,
    gap: 4,
  },
  infoBannerTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  infoBannerTitle: {
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.4,
    color: Theme.textPrimaryDark,
  },
  infoBannerBody: {
    fontSize: 13,
    fontWeight: "500",
    color: Theme.textSecondary,
    lineHeight: 18,
  },
  routeSummary: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    backgroundColor: Theme.surface,
    overflow: "hidden",
  },
  routeSummaryHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: Theme.borderLight,
  },
  routeSummaryTitle: {
    flex: 1,
    fontSize: 14,
    fontWeight: "700",
    color: Theme.textPrimaryDark,
    lineHeight: 20,
  },
  routeSummaryArrow: {
    color: Theme.textMuted,
    opacity: 0.85,
  },
  routeSummaryMetrics: {
    flexDirection: "row",
    padding: 16,
    backgroundColor: Theme.cardWhite,
  },
  routeSummaryMetric: {
    flex: 1,
    paddingHorizontal: 8,
  },
  routeSummaryMetricBorder: {
    borderRightWidth: 1,
    borderRightColor: Theme.borderLight,
  },
  routeSummaryMetricLabel: {
    fontSize: 10,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 1,
    color: Theme.textMuted,
    marginBottom: 4,
  },
  routeSummaryMetricValue: {
    fontSize: 14,
    fontWeight: "600",
    fontStyle: "italic",
    color: Theme.textPrimaryDark,
  },
  nonRouteStepWrap: {
    width: "100%",
    gap: 16,
  },
});
