import { StyleSheet } from "react-native";
import Theme from "@/constants/Theme";

/** Purple accent — matches attribution wizard & Theme.primary. */
export const WIZARD_ACCENT = Theme.primary;
export const WIZARD_ACCENT_SOFT = "rgba(79, 70, 229, 0.08)";
export const WIZARD_ACCENT_BORDER = "rgba(99, 102, 241, 0.35)";
export const WIZARD_ACCENT_MUTED = "rgba(238, 242, 255, 0.9)";

/** Shared light full-page wizard chrome (attribution / create trip / load / allocation). */
export const fullPageWizardStyles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: Theme.screenBackground,
  },
  pageRoot: {
    flex: 1,
    minHeight: 0,
    paddingHorizontal: 16,
    gap: 12,
  },
  pageRootKeypad: {
    gap: 8,
  },
  pageHeaderBlock: {
    gap: 4,
    flexShrink: 0,
  },
  pageHeaderBlockKeypad: {
    gap: 2,
  },
  headerBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    minHeight: 28,
  },
  headerBackBtn: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    backgroundColor: Theme.cardWhite,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  headerBackBtnText: {
    color: Theme.textPrimaryDark,
    fontSize: 12,
    fontWeight: "700",
  },
  headerStepText: {
    color: Theme.textMuted,
    fontSize: 11,
    fontWeight: "700",
  },
  title: {
    color: Theme.textPrimaryDark,
    fontSize: 22,
    fontWeight: "800",
  },
  titleKeypad: {
    fontSize: 20,
    lineHeight: 26,
  },
  subtitle: {
    color: Theme.textSecondary,
    fontSize: 13,
    lineHeight: 19,
  },
  subtitleKeypad: {
    fontSize: 12,
    lineHeight: 17,
  },
  wizardStepRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  wizardStepItem: {
    flex: 1,
    alignItems: "center",
    gap: 4,
    minWidth: 0,
  },
  wizardStepCircle: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    backgroundColor: Theme.cardWhite,
    alignItems: "center",
    justifyContent: "center",
  },
  wizardStepCircleActive: {
    borderColor: Theme.primary,
    backgroundColor: Theme.primary,
  },
  wizardStepCircleDone: {
    borderColor: Theme.primary,
    backgroundColor: Theme.primary,
  },
  wizardStepCircleText: {
    fontSize: 11,
    fontWeight: "700",
    color: Theme.textMuted,
  },
  wizardStepCircleTextActive: {
    color: Theme.textOnPrimary,
  },
  wizardStepText: {
    fontSize: 10,
    color: Theme.textMuted,
    fontWeight: "600",
    textAlign: "center",
  },
  wizardStepTextActive: {
    color: Theme.textPrimaryDark,
    fontWeight: "700",
  },
  bodyScroll: {
    flex: 1,
    minHeight: 0,
  },
  bodyScrollContent: {
    gap: 12,
    paddingBottom: 8,
  },
  bodyFill: {
    flex: 1,
    minHeight: 0,
    gap: 12,
  },
  bodyWide: {
    width: "100%",
    maxWidth: 860,
    alignSelf: "center",
  },
  partyRow: {
    flexDirection: "row",
    gap: 10,
  },
  partyRowStack: {
    flexDirection: "column",
  },
  partyCard: {
    flex: 1,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    backgroundColor: Theme.cardWhite,
    padding: 10,
  },
  partyTextWrap: {
    flex: 1,
    minWidth: 0,
  },
  partyLabel: {
    color: Theme.textMuted,
    fontSize: 10,
    textTransform: "uppercase",
    letterSpacing: 0.4,
    fontWeight: "700",
  },
  partyName: {
    color: Theme.textPrimaryDark,
    fontSize: 12,
    fontWeight: "700",
  },
  block: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    backgroundColor: Theme.cardWhite,
    padding: 12,
    gap: 8,
  },
  blockTitle: {
    color: Theme.textPrimaryDark,
    fontSize: 14,
    fontWeight: "700",
  },
  blockLine: {
    color: Theme.textPrimaryDark,
    fontSize: 13,
    fontWeight: "600",
  },
  blockMeta: {
    color: Theme.textSecondary,
    fontSize: 12,
  },
  modeRow: {
    flexDirection: "row",
    gap: 8,
  },
  modeChip: {
    flex: 1,
    minWidth: 0,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    backgroundColor: Theme.screenBackground,
    paddingHorizontal: 10,
    paddingVertical: 8,
    alignItems: "center",
  },
  modeChipActive: {
    borderColor: WIZARD_ACCENT,
    backgroundColor: WIZARD_ACCENT_SOFT,
  },
  modeChipText: {
    fontSize: 11,
    color: Theme.textSecondary,
    fontWeight: "700",
  },
  modeChipTextActive: {
    color: WIZARD_ACCENT,
  },
  footerBar: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 10,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: Theme.borderLight,
    paddingTop: 10,
  },
  footerSummary: {
    fontSize: 11,
    fontWeight: "600",
    color: Theme.textMuted,
    textAlign: "center",
    lineHeight: 15,
    marginBottom: 4,
  },
  cancelBtn: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    backgroundColor: Theme.cardWhite,
    paddingHorizontal: 14,
    paddingVertical: 10,
    minWidth: 88,
    alignItems: "center",
  },
  cancelBtnText: {
    color: Theme.textSecondary,
    fontSize: 12,
    fontWeight: "700",
  },
  submitBtn: {
    flex: 1,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Theme.primary,
    backgroundColor: Theme.primary,
    paddingHorizontal: 14,
    paddingVertical: 10,
    alignItems: "center",
    justifyContent: "center",
    minHeight: 42,
  },
  submitBtnDisabled: {
    opacity: 0.55,
  },
  submitBtnText: {
    color: Theme.textOnPrimary,
    fontSize: 12,
    fontWeight: "800",
  },
  footerHint: {
    color: Theme.textMuted,
    fontSize: 11,
    lineHeight: 15,
    textAlign: "center",
    marginTop: 6,
  },
  /** Form section card — matches wizard block styling inside step bodies. */
  formSectionCard: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    backgroundColor: Theme.cardWhite,
    paddingHorizontal: 14,
    paddingVertical: 14,
    gap: 8,
  },
  formSectionTitle: {
    color: Theme.textPrimaryDark,
    fontSize: 14,
    fontWeight: "700",
  },
  formSectionSubtitle: {
    color: Theme.textSecondary,
    fontSize: 12,
    lineHeight: 17,
  },
  formLabel: {
    color: Theme.textMuted,
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.35,
    textTransform: "uppercase",
  },
  formInput: {
    borderWidth: 1,
    borderColor: Theme.borderLight,
    borderRadius: 10,
    backgroundColor: Theme.screenBackground,
    color: Theme.textPrimaryDark,
    fontSize: 14,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  clientListWrap: {
    borderWidth: 1,
    borderColor: Theme.borderLight,
    borderRadius: 10,
    backgroundColor: Theme.screenBackground,
    overflow: "hidden",
  },
  clientLoadingWrap: {
    paddingVertical: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  clientRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 10,
    paddingVertical: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Theme.borderLight,
  },
  clientRowSelected: {
    backgroundColor: WIZARD_ACCENT_SOFT,
    borderLeftWidth: 2,
    borderLeftColor: WIZARD_ACCENT,
  },
  /** Horizontal shipper / client row — attribution picker style. */
  shipperMarkCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    backgroundColor: Theme.screenBackground,
    padding: 10,
  },
  shipperWarningCard: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: WIZARD_ACCENT_BORDER,
    backgroundColor: WIZARD_ACCENT_MUTED,
    padding: 10,
    gap: 8,
  },
  shipperWarningText: {
    color: "#4338ca",
    fontSize: 11,
    lineHeight: 16,
    fontWeight: "600",
  },
  addClientBtn: {
    alignSelf: "flex-start",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    backgroundColor: Theme.surface,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  addClientBtnText: {
    color: WIZARD_ACCENT,
    fontSize: 11,
    fontWeight: "700",
  },
  /** Wizard step field label — matches attribution block titles. */
  wizardFieldLabel: {
    color: Theme.textMuted,
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.35,
    textTransform: "uppercase",
    marginBottom: 6,
  },
  /** Wizard step text input — 14px black body (not dense 9–10px form). */
  wizardFieldInput: {
    borderWidth: 1,
    borderColor: Theme.borderLight,
    borderRadius: 10,
    backgroundColor: Theme.screenBackground,
    color: Theme.textPrimaryDark,
    fontSize: 14,
    fontWeight: "600",
    fontStyle: "normal",
    paddingHorizontal: 12,
    paddingVertical: 10,
    minHeight: 44,
    marginBottom: 8,
  },
  wizardStepBody: {
    width: "100%",
    gap: 12,
    paddingBottom: 4,
  },
  wizardFieldBlock: {
    width: "100%",
    gap: 6,
  },
  /** Flat list block — no outer card when parent already uses formSectionCard. */
  blockFlat: {
    width: "100%",
    gap: 8,
  },
  wizardPickerBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    borderRadius: 10,
    backgroundColor: Theme.screenBackground,
    paddingHorizontal: 12,
    paddingVertical: 10,
    minHeight: 44,
  },
  wizardPickerBtnEmpty: {
    borderStyle: "dashed",
  },
  wizardPickerBtnText: {
    flex: 1,
    minWidth: 0,
    fontSize: 14,
    fontWeight: "600",
    color: Theme.textPrimaryDark,
    lineHeight: 20,
  },
  wizardPickerBtnPlaceholder: {
    color: Theme.textMuted,
    fontWeight: "500",
  },
  wizardDateTouchable: {
    minHeight: 44,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    backgroundColor: Theme.screenBackground,
    paddingHorizontal: 12,
    justifyContent: "center",
  },
  wizardDateText: {
    fontSize: 14,
    fontWeight: "600",
    color: Theme.textPrimaryDark,
  },
  wizardDatePlaceholder: {
    fontSize: 14,
    fontWeight: "500",
    color: Theme.textMuted,
  },
  quickDateRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  quickDateChip: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: Theme.borderLight,
    backgroundColor: Theme.screenBackground,
  },
  quickDateChipActive: {
    borderColor: WIZARD_ACCENT,
    backgroundColor: WIZARD_ACCENT_SOFT,
  },
  quickDateChipText: {
    fontSize: 11,
    fontWeight: "600",
    color: Theme.textMuted,
  },
  quickDateChipTextActive: {
    color: WIZARD_ACCENT,
    fontWeight: "800",
  },
});
